// Deterministic orthographic CPU mesh preflight. No live-game acceptance claim.
import fs from 'node:fs';import zlib from 'node:zlib';
import {MeshoptDecoder} from 'meshoptimizer';
await MeshoptDecoder.ready;
import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import * as T from 'three';
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}),W=960,H=720,root='artifacts/jan-evertsen-pilot/previews';
const ids=process.argv.length>2?process.argv.slice(2):['vondeltuin','pllek','treehouse-ndsm','straat-museum','nieuw-dakota','de-gooyer'];
function crc(buf){let n=0xffffffff;for(const b of buf){n^=b;for(let k=0;k<8;k++)n=(n>>>1)^((n&1)?0xedb88320:0);}return(n^0xffffffff)>>>0;}
function chunk(type,data){const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length,0);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;}
function png(file,rgba){const header=Buffer.alloc(13);header.writeUInt32BE(W,0);header.writeUInt32BE(H,4);header[8]=8;header[9]=6;const scan=Buffer.alloc(H*(W*4+1));for(let y=0;y<H;y++)Buffer.from(rgba.buffer,y*W*4,W*4).copy(scan,y*(W*4+1)+1);fs.writeFileSync(file,Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',zlib.deflateSync(scan)),chunk('IEND',Buffer.alloc(0))]));}
function srgb(v){return Math.round(255*(v<=.0031308?12.92*v:1.055*Math.pow(v,1/2.4)-.055));}
for(const id of ids){const doc=await io.read(`artifacts/jan-evertsen-pilot/models/${id}.glb`),tris=[],bounds=new T.Box3();
 for(const node of doc.getRoot().listNodes()){const mesh=node.getMesh();if(!mesh)continue;const matrix=new T.Matrix4().fromArray(node.getWorldMatrix());for(const prim of mesh.listPrimitives()){const accessor=prim.getAttribute('POSITION'),pos=accessor.getArray(),ix=prim.getIndices()?.getArray(),rgb=prim.getMaterial().getBaseColorFactor();for(let i=0;i<(ix?.length??pos.length/3);i+=3){const points=[0,1,2].map(k=>{const j=(ix?ix[i+k]:i+k)*3;const values=accessor.getElement(j/3,[]);const p=new T.Vector3(...values).applyMatrix4(matrix);bounds.expandByPoint(p);return p;});tris.push({points,rgb});}}}
 const focus=process.env.LANDMARK_CPU_FOCUS?JSON.parse(process.env.LANDMARK_CPU_FOCUS):null;
 const center=focus?new T.Vector3(...focus.slice(0,3)):bounds.getCenter(new T.Vector3());
 for(const [angle,name] of (process.env.LANDMARK_CPU_VIEWS?JSON.parse(process.env.LANDMARK_CPU_VIEWS):[[.6,'front'],[Math.PI+.6,'opposite']])){const eye=new T.Vector3(Math.sin(angle),Number(process.env.LANDMARK_CPU_ELEVATION??.65),Math.cos(angle)).normalize(),right=new T.Vector3(0,1,0).cross(eye).normalize(),up=eye.clone().cross(right).normalize(),project=p=>{const q=p.clone().sub(center);return[q.dot(right),q.dot(up),q.dot(eye)];};const projected=tris.map(t=>({...t,q:t.points.map(project)}));let xmin=Infinity,xmax=-Infinity,ymin=Infinity,ymax=-Infinity;for(const t of projected)for(const p of t.q){xmin=Math.min(xmin,p[0]);xmax=Math.max(xmax,p[0]);ymin=Math.min(ymin,p[1]);ymax=Math.max(ymax,p[1]);}if(focus){xmin=ymin=-focus[3]/2;xmax=ymax=focus[3]/2;}const scale=.8*Math.min(W/(xmax-xmin),H/(ymax-ymin)),rgba=new Uint8Array(W*H*4),depth=new Float64Array(W*H).fill(-Infinity);for(let i=0;i<W*H;i++)rgba.set([232,229,217,255],i*4);
  for(const t of projected){const q=t.q.map(p=>[W/2+p[0]*scale,H/2-p[1]*scale,p[2]]),[a,b,c]=q,area=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(area)<1e-9)continue;const x0=Math.max(0,Math.floor(Math.min(...q.map(p=>p[0])))),x1=Math.min(W-1,Math.ceil(Math.max(...q.map(p=>p[0])))),y0=Math.max(0,Math.floor(Math.min(...q.map(p=>p[1])))),y1=Math.min(H-1,Math.ceil(Math.max(...q.map(p=>p[1]))));const n=t.points[1].clone().sub(t.points[0]).cross(t.points[2].clone().sub(t.points[0])).normalize();if(n.dot(eye)<0)n.negate();const shade=.7+.3*Math.max(0,n.dot(new T.Vector3(-.5,.9,.6).normalize())),color=t.rgb.slice(0,3).map(v=>srgb(Math.max(0,Math.min(1,v*shade))));for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const px=x+.5,py=y+.5,u=((b[1]-c[1])*(px-c[0])+(c[0]-b[0])*(py-c[1]))/area,v=((c[1]-a[1])*(px-c[0])+(a[0]-c[0])*(py-c[1]))/area,w=1-u-v;if(u<0||v<0||w<0)continue;const z=u*a[2]+v*b[2]+w*c[2],j=y*W+x;if(z>depth[j]+1e-8){depth[j]=z;rgba.set([...color,255],j*4);}}}
  png(`${root}/${id}-cpu-${name}.png`,rgba);
 }
 console.log(JSON.stringify({id,triangles:tris.length,scope:'CPU geometry preflight only; exact input mesh, no context or game acceptance'}));
}
