/**
 * Collect the walls of every storefront reference into src/canalRecall/storefrontWalls.generated.ts
 * (slug -> pand, wall ends, length, pin position along it). Run after build-refs.sh.
 *   npx tsx scripts/storefronts/emit-walls.ts tmp/storefronts/refs [more dirs...]
 */
import fs from 'node:fs';
import path from 'node:path';
const out: Record<string, unknown> = {};
const target = 'src/canalRecall/storefrontWalls.generated.ts';
const prior = fs.existsSync(target) ? JSON.parse(fs.readFileSync(target, 'utf8').split('= ')[1].replace(/;\s*$/, '')) : {};
Object.assign(out, prior);
for (const dir of process.argv.slice(2)) for (const f of fs.readdirSync(dir).filter(f => f.endsWith('.json'))) {
  const m = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')), w = m.wall;
  const r = (v: number) => Math.round(v * 1e7) / 1e7;
  out[m.name] = { pand: m.buildingIds[0], start: w.startLngLat.map(r), end: w.endLngLat.map(r), lengthM: Math.round(w.lengthM * 100) / 100, alongM: m.nearAlongM ?? w.lengthM / 2 };
}
fs.writeFileSync(target, `// Generated by scripts/storefronts/emit-walls.ts from panorama references. Do not edit.\nimport type { StorefrontWall } from './storefronts.js';\nexport const STOREFRONT_WALLS: Record<string, StorefrontWall> = ${JSON.stringify(out)};\n`);
console.log(`${Object.keys(out).length} storefront walls -> ${target}`);
