"""Add auditable assertions and raw-pack manifest without promoting geometry."""
import pathlib,json,hashlib,datetime,gzip,re
ROOT=pathlib.Path(__file__).resolve().parents[2];PACK=ROOT.parent/'map-recall2-source-data/streets/canalhouse-recipes-pilot';p=ROOT/'docs/references/canalhouse-recipes/pilot-inventory.json';I=json.load(open(p));now=datetime.datetime.now(datetime.timezone.utc).isoformat()
features={405:[('crown','straight cornice')],407:[('crown','straight cornice')],409:[('crown','small neck gable'),('groundEntrance','Empire door, transom and decorative fanlight rail')],411:[('crown','small neck gable'),('groundEntrance','Empire door/transom/fanlight rail; eighteenth-century stoop rail')],413:[('crown','straight cornice')],415:[('crown','stepped gable with six steps, diagonal masonry crown'),('roof','tiled saddle roof'),('windowGroups','three tall hall windows at first upper level; three sash windows above'),('groundEntrance','main right entrance with recessed stoop/portico; left double-door entry; central divided window'),('material','light brown brick with natural stone plinth and accents'),('windowHeads','flattened arches with masonry inset fields and stone springing/keystones')],417:[('crown','bell gable'),('ornament','Empire balusters')],419:[('crown','straight cornice')],421:[('crown','pointed gable')],423:[('crown','straight cornice'),('groundEntrance','decorated stoop; Empire fanlight railing')],425:[('crown','straight cornice with triglyphs and consoles'),('frontage','central projecting bay'),('groundEntrance','door surround circa1800')],427:[('crown','neck gable'),('groundEntrance','decorated stoop')]}
for h in I['houses']:
 n=int(h['address'].split()[-1]);h['assertions']=[dict(feature=f,value=v,sourceUrl=h['register']['rceUrl'],supportingPassage=h['register']['descriptions'][0]['text'],buildingPart='principal Herengracht facade' if f!='roof' else 'principal roof',sourceDate='register text undated; cached2026-10-05',confidence='high for register statement, pending exact present-state facade confirmation',measurement='prose architectural assertion; no invented dimensions')for f,v in features[n]]
 h['beeldbank']['accessState']='bounded address+bouwtekening response archived; JavaScript search shell; no catalogue item or drawing inspected'
 h['sourceGaps']=['Historical elevation/drawing not retrieved from Beeldbank shell','Bouwdossiers1905–2010 not separately opened; no dossier sheets inspected','Precise current pane/ornament counts require source-photo annotation','Front facade body/eaves height requires semantic partition review; global max not usable as body height']
I['selection']['reason']='Ranked by cached complete official description+Pand-link coverage and presence of five facade/entrance feature terms, then selected compact12-house run. Current municipal photos subsequently acquired and inspected as row views; partial tree/vehicle occlusion remains.'
D=json.load(gzip.open(ROOT.parent/'map-recall2-source-data/datasets/amsterdam-monument-register/2026-10-05T06-10-55-572Z-83107/normalized/records.json.gz'));R={r['monumentNumber']:r for r in D['rce']};runs=[]
for street in ['Herengracht','Keizersgracht','Prinsengracht']:
 M={int(m[1]):r for r in D['municipal'] if (m:=re.fullmatch(street+r' (\d+)',r['metadata'].get('adressering','')or'')) and r['bagPandIds'] and r['bagPandIds'][0].startswith('0363')}
 for start in M:
  row=[M.get(i)for i in range(start,start+24,2)]
  if not all(row):continue
  ds=[r['descriptions']or R.get(r['monumentNumber'],{}).get('descriptions',[])for r in row];text=' '.join(str(x)for x in ds).lower();runs.append(dict(street=street,start=start,end=start+22,descriptions=sum(bool(x)for x in ds),traitTerms=[x for x in ['halsgevel','klokgevel','trapgevel','lijst','tuitgevel','deur','pui']if x in text]))
runs.sort(key=lambda r:(r['descriptions'],len(r['traitTerms'])),reverse=True);I['selection']['candidateRanking']=runs[:20];I['selection']['rankingLimits']='Register evidence ranking only. Current municipal panorama availability/occlusion is assessed for selected row, not exhaustively for every run. Number sequences alone do not prove physical contiguity; ordered native footprints/current row context establish selected same-side row.'
p.write_text(json.dumps(I,indent=2)+'\n');records=[]
for f in sorted((PACK/'raw').glob('*.provenance.json')):
 m=json.load(open(f));rp=PACK/m['rawPath'];assert hashlib.sha256(rp.read_bytes()).hexdigest()==m['sha256'];records.append(m)
(PACK/'source-pack-manifest.json').write_text(json.dumps(dict(version=1,canonicalScope=I['id'],created=now,rawSources=records,existingRawRegisterSource=json.load(open(PACK/'register-source-link.json')),processed=[str(x.relative_to(PACK))for x in sorted((PACK/'processed').glob('*'))],rights='Municipal panoramas CC BY4.0; archive item rights unknown because only search shells obtained. No photo pixels enter generated assets.',gaps='No downloaded archive drawing or dossier sheets; exact photo facade annotation and root visual/game acceptance remain.'),indent=2)+'\n')
print('raw verified',len(records),'bytes',sum(r['bytes']for r in records))
