/** Exact-row actual-game check with frozen bundles/assets. Candidate evidence, never acceptance. */
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {chromium} from 'playwright';
import {gameReviewSelection} from './game-review-selection.mjs';
const opt=(n,d)=>process.argv.find(a=>a.startsWith(`--${n}=`))?.slice(n.length+3)??d;
const base=opt('base-url','http://127.0.0.1:5196'),row=opt('row','pilot');
const manifestFile=opt('manifest','public/canal-drive/models/canalhouse-recipes/pilot.json');
if(manifestFile!=='public/canal-drive/models/canalhouse-recipes/pilot.json'&&row==='pilot')throw Error('A custom manifest requires its explicit --row review identifier');
const devices=opt('devices','desktop,touch').split(','),rounds=Number(opt('rounds','3'));
if(!devices.length||new Set(devices).size!==devices.length||devices.some(d=>!['desktop','touch'].includes(d))||!Number.isInteger(rounds)||rounds<0||rounds>10)throw Error('Use desktop/touch devices and 0–10 measurement rounds');
const manifestBytes=await fs.readFile(manifestFile),sourceManifest=JSON.parse(manifestBytes.toString());
const selection=gameReviewSelection(sourceManifest,{row,position:opt('position','')?opt('position','').split(',').map(Number):undefined,angle:Number(opt('angle','-.7'))});
const manifest={...sourceManifest,entries:selection.entries,reviewRows:(sourceManifest.reviewRows??[]).filter(r=>r.id===row)},hashes={},modelRoutes=new Map();
const out=opt('output',`artifacts/canalhouse-recipes/${row}-game-${Date.now()}`);
try{await fs.access(out);throw Error('Review output already exists; preserve prior evidence and choose a new directory');}catch(e){if(e.code!=='ENOENT')throw e;}
await fs.mkdir(path.join(out,'bundles'),{recursive:true});await fs.mkdir(path.join(out,'models'),{recursive:true});
for(const n of (await fs.readdir('public/canal-drive/js')).filter(n=>n.endsWith('.js'))){const b=await fs.readFile(`public/canal-drive/js/${n}`);hashes['js/'+n]=crypto.createHash('sha256').update(b).digest('hex');await fs.writeFile(path.join(out,'bundles',n),b);}
for(const asset of selection.assets){const b=await fs.readFile(asset.file),sha=crypto.createHash('sha256').update(b).digest('hex');if(asset.fingerprint&&sha.slice(0,asset.fingerprint.length)!==asset.fingerprint)throw Error('Stale candidate fingerprint: '+asset.id);const frozen=path.join(out,'models',asset.id+'.glb');await fs.writeFile(frozen,b);hashes[asset.pathname]=sha;modelRoutes.set(asset.pathname,{file:frozen,fingerprint:asset.fingerprint});}
await fs.writeFile(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2));
const configuration={row,station:selection.station,angle:selection.angle,devices,rounds,owners:selection.owners,modelUrls:selection.entries.map(e=>e.modelUrl),assetIds:selection.entries.map(e=>e.id)};
const report={version:2,generatedAt:new Date().toISOString(),status:'prepared-not-run',sourceManifest:{path:manifestFile,sha256:crypto.createHash('sha256').update(manifestBytes).digest('hex')},configuration,immutableHashes:hashes,manifestStatus:manifest.status,acceptance:false,runs:[],limits:['Stationary rider is relocated in a running actual game: this does not establish route reachability.','Candidate on/off use separate pages with identical frozen JS/model bytes; all other signature models remain enabled.','Candidate loaded assets are matched by fingerprinted model URL, retaining genuine POI identities when the renderer merges an asset.','GPU query wraps full MapLibre frame; unsupported or disjoint query results cannot establish GPU budgets.','Headless local Chrome measurements are bounded to this browser/hardware and viewport.','Screenshots and identity diagnostics need human visual review; no automatic claim of facade recognition or blank-wall absence.','Preparation only is not browser/game/GPU/performance evidence.']};
await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));
if(process.argv.includes('--prepare-only')){console.log(JSON.stringify({output:out,row,assets:selection.assets.length,status:report.status,acceptance:false}));process.exit(0);}
let browser;
try{browser=await chromium.launch({headless:true,executablePath:opt('chrome','/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')});report.status='running';}catch(e){report.status='browser-launch-failed';report.launchFailure=e.stack;await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));throw e;}
const diagnostic=page=>page.evaluate(configuration=>{const g=window.canalRecallGame,v=g.vectorMap,t=v._threeBuildings,s=v._signatureLandmarks;const candidateUrls=new Set(configuration.modelUrls),ids=new Set(configuration.owners);const features=[...new Map([...t.chunks.values()].flatMap(c=>c.source??[]).map(f=>[String(f.properties?.id),f])).values()];const nearby=features.filter(f=>{const coords=f.geometry?.coordinates?.flat(f.geometry.type==='MultiPolygon'?2:1)??[];const pts=coords.filter(Array.isArray);return pts.some(p=>Math.abs(p[0]-configuration.station[0])<.0015&&Math.abs(p[1]-configuration.station[1])<.0015)});return{state:g.state,travelMode:g.travelMode,player:v.worldToLngLat(g.player.x,g.player.y,g.osmLoader),speed:g.player.speed,camera:{center:v.map.getCenter().toArray(),zoom:v.map.getZoom(),pitch:v.map.getPitch(),bearing:v.map.getBearing(),detached:g.camera.detached},loadedPilot:(s?._entries??[]).filter(e=>candidateUrls.has(e.spec.modelUrl)).map(e=>({id:e.spec.id,url:e.spec.modelUrl,ids:e.spec.suppressOsmIds,visible:e.group.visible,spatialSuppression:e.spec.spatialSuppression})),failed:[...(s?._failed??[])],pending:[...(s?._pending?.keys()??[])],signatureSuppression:v._signatureSuppressOsmIds(),threeSignatureSuppression:[...(t.hiddenBy.get('signature')??[])],threeHidden:[...t.hidden],roofHidden:v._pyramidalRoofs?[...v._pyramidalRoofs._hiddenIds??[]]:null,chunks:t.chunks.size,pendingChunks:t.pending.length,inflightChunks:t.inflight.size,city:v._completeCity?.status?.(),nearbySourceIdentities:nearby.map(f=>({id:f.properties.id,osmId:f.properties.osmId,hidden:t.hidden.has(String(f.properties.id)),pilot:ids.has(String(f.properties.id))})),rendererInfo:t.renderer.info.render};},configuration);
const timing=page=>page.evaluate(async()=>{const v=window.canalRecallGame.vectorMap,map=v.map,gl=v._threeBuildings.renderer.getContext(),ext=gl.getExtension('EXT_disjoint_timer_query_webgl2'),original=map._render,pending=[],gpu=[],cpu=[],frames=[];let warm=30,count=0,prev=null,disjoint=false;
if(typeof original!=='function')return{unsupported:'MapLibre _render unavailable'};
await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{map._render=original;reject(Error('Frame timing timeout'))},30000);map._render=function(...args){const query=ext&&!gl.getQuery(ext.TIME_ELAPSED_EXT,gl.CURRENT_QUERY)?gl.createQuery():null;if(query)gl.beginQuery(ext.TIME_ELAPSED_EXT,query);const start=performance.now();let result;try{result=original.apply(this,args)}finally{if(query){gl.endQuery(ext.TIME_ELAPSED_EXT);pending.push({query,keep:warm<=0})}const end=performance.now();if(warm>0)warm--;else{cpu.push(end-start);if(prev!==null)frames.push(start-prev);prev=start;count++;}if(ext&&gl.getParameter(ext.GPU_DISJOINT_EXT))disjoint=true;while(pending.length&&gl.getQueryParameter(pending[0].query,gl.QUERY_RESULT_AVAILABLE)){const q=pending.shift();if(q.keep)gpu.push(gl.getQueryParameter(q.query,gl.QUERY_RESULT)/1e6);gl.deleteQuery(q.query)}if(count>=90){clearTimeout(timeout);map._render=original;resolve()}else map.triggerRepaint()}return result};map.triggerRepaint()});
if(ext){await new Promise(r=>setTimeout(r,50));for(const q of pending){if(gl.getQueryParameter(q.query,gl.QUERY_RESULT_AVAILABLE)&&q.keep)gpu.push(gl.getQueryParameter(q.query,gl.QUERY_RESULT)/1e6);gl.deleteQuery(q.query)}}const stats=a=>{a.sort((a,b)=>a-b);return{count:a.length,median:a[Math.floor(a.length*.5)]??null,p95:a[Math.floor(a.length*.95)]??null}};const debug=gl.getExtension('WEBGL_debug_renderer_info');return{renderer:debug?gl.getParameter(debug.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),gpuExtension:!!ext,gpuDisjoint:disjoint,fullMapGpuMs:stats(gpu),fullMapCpuSubmissionMs:stats(cpu),frameIntervalsMs:stats(frames),method:'30 warmup + 90 measured full MapLibre _render frames, shared context EXT_disjoint_timer_query_webgl2; no gl.finish proxy.'}});
try{for(const device of devices)for(const pilot of [true,false]){
const context=await browser.newContext(device==='touch'?{viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1}:{viewport:{width:1440,height:1000},deviceScaleFactor:1});await context.addInitScript(()=>localStorage.setItem('canalRecall.preferences.v1',JSON.stringify({travelMode:'car',viewMode:'chase',buildingLook:'photo',reducedMotion:false})));
const page=await context.newPage(),run={device,pilot,errors:[],timings:[],screenshots:[]};report.runs.push(run);page.on('pageerror',e=>run.errors.push(e.message));
await page.route('**/canal-drive/js/*.js*',async r=>{const n=new URL(r.request().url()).pathname.split('/').at(-1);await r.fulfill({contentType:'application/javascript',path:path.join(out,'bundles',n)})});
await page.route('**/models/**/*.glb*',async r=>{const url=new URL(r.request().url()),asset=modelRoutes.get(url.pathname);if(!asset)return r.continue();if(url.searchParams.get('asset')!==asset.fingerprint){run.errors.push('Candidate request fingerprint differs from frozen asset: '+url.pathname);return r.abort();}return r.fulfill({contentType:'model/gltf-binary',path:asset.file});});
const ready=async()=>{await page.waitForFunction(()=>{const g=window.canalRecallGame,t=g?.vectorMap?._threeBuildings;return g?.state===4&&t?.ready&&t.chunks.size&&!t.pending.length&&!t.inflight.size&&!t.pumping&&!g.vectorMap._signatureLandmarks?._pending?.size&&Number.isFinite(g.vectorMap._clearancePitch)&&Math.abs(g.vectorMap._pitchSmoothed-48)<.001&&Math.abs(g.vectorMap.map.getPitch()-Math.min(g.vectorMap._pitchSmoothed,g.vectorMap._clearancePitch))<.001},null,{timeout:120000});await page.waitForTimeout(1200)};
try{await page.goto(`${base}/canal-drive/${pilot?'?canalhouseRecipes='+encodeURIComponent(row):''}#race=52.3735,4.8954,52.3608814,4.8687372,52.3713544,4.8979412`);await page.waitForFunction(()=>window.canalRecallGame?.state===4&&window.canalRecallGame?.player,null,{timeout:120000});await page.evaluate(({station,angle})=>{const g=window.canalRecallGame;g._overlay.store.setSetupOpen(false);const l=g.osmLoader,[lng,lat]=station,x=l._lastOffsetX+(lng-l._lastCenterLng)*111320*Math.cos(l._lastCenterLat*Math.PI/180)*3,y=l._lastOffsetY-(lat-l._lastCenterLat)*111320*3;g.player.x=x;g.player.y=y;g._intro=null;g.player.speed=0;g.player.vx=0;g.player.vy=0;g.player.angle=angle;g.camera.x=x;g.camera.y=y;g.camera.targetX=x;g.camera.targetY=y;g.camera.resetPan()},{station:selection.station,angle:selection.angle});await ready();
run.stationarySetup=await page.evaluate(()=>{const g=window.canalRecallGame,v=g.vectorMap,before=v.worldToLngLat(g.player.x,g.player.y,g.osmLoader),road=g.track.getNearestRoad(g.player.x,g.player.y,g.player.angle);if(!road||!Number.isFinite(road.x)||!Number.isFinite(road.y))throw Error('No valid road projection for stationary rider');g.player.x=road.x;g.player.y=road.y;g.player.speed=0;g.player.vx=0;g.player.vy=0;g.camera.x=road.x;g.camera.y=road.y;g.camera.targetX=road.x;g.camera.targetY=road.y;g.camera.resetPan();return{requestedPosition:before,projectedPosition:v.worldToLngLat(road.x,road.y,g.osmLoader),road:{x:road.x,y:road.y,width:road.width,angle:road.angle,dist:road.dist},method:'Project stationary rider to nearest actual car/bike-network road center; clear speed/vx/vy, keep normal game physics.'}});await ready();await page.waitForTimeout(1000);await page.evaluate(()=>{const p=window.canalRecallGame.player;p.speed=0;p.vx=0;p.vy=0});await page.waitForTimeout(1000);
if(pilot)await page.waitForFunction(urls=>urls.every(url=>window.canalRecallGame.vectorMap._signatureLandmarks._entries.some(e=>e.spec.modelUrl===url)),configuration.modelUrls,{timeout:60000});run.initial=await diagnostic(page);console.log('ready',device,pilot,run.initial.loadedPilot.length);
const prefix=`${device}-${pilot?'pilot':'baseline'}`;await page.screenshot({path:path.join(out,`${prefix}-rider.png`)});run.screenshots.push(`${prefix}-rider.png`);
for(let round=0;round<rounds;round++){run.timings.push(await timing(page));console.log('timing',device,pilot,round,JSON.stringify(run.timings.at(-1)))}
if(pilot){const box=await page.locator('#gameCanvas').boundingBox(),start={x:box.x+box.width*.65,y:box.y+box.height*.45},end={x:box.x+box.width*.15,y:box.y+box.height*.25};if(device==='touch'){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/12,y:start.y+(end.y-start.y)*i/12}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:12});await page.mouse.up()}await ready();run.panAway=await diagnostic(page);await page.screenshot({path:path.join(out,`${prefix}-pan-away.png`)});run.screenshots.push(`${prefix}-pan-away.png`);await page.keyboard.press('r');await ready();run.panBack=await diagnostic(page);await page.screenshot({path:path.join(out,`${prefix}-pan-back.png`)});run.screenshots.push(`${prefix}-pan-back.png`);run.stationaryCheck=stationaryCheck(run);run.stationaryAcrossPan=run.stationaryCheck.maxDisplacementM<=.01;run.realGestureDetached=run.panAway.camera.detached;run.recentered=!run.panBack.camera.detached;}
}catch(e){run.failure=e.stack;run.failurePageState=await page.evaluate(()=>({state:window.canalRecallGame?.state,travelMode:window.canalRecallGame?.travelMode,loadingMessage:window.canalRecallGame?.loadingMessage,text:document.body.innerText.slice(0,5000)}));console.log('failure',device,pilot,e.message);try{run.failedDiagnostic=await diagnostic(page);}catch{}await page.screenshot({path:path.join(out,`${device}-${pilot}-failure.png`)}).catch(()=>{})}
await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));await context.close();}
}finally{await browser.close();report.status=report.runs.some(r=>r.failure)?'runs-with-failures':'runs-recorded-not-visually-accepted';await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2))}
await summarize(report);console.log('report',path.join(out,'report.json'));
function stationaryCheck(run){const initial=run.initial.player;const distance=p=>Math.hypot((p[0]-initial[0])*111320*Math.cos(initial[1]*Math.PI/180),(p[1]-initial[1])*111320);return{maxDisplacementM:Math.max(distance(run.panAway.player),distance(run.panBack.player)),toleranceM:.01,method:'Measured geodetic displacement; centimetre tolerance permits physics floating-point/road-contact jitter.'}}
async function summarize(report){
const median=a=>a.length?a.toSorted((a,b)=>a-b)[Math.floor(a.length/2)]:null;report.comparisons=[];const expected=manifest.entries.flatMap(e=>e.suppressOsmIds).sort();
for(const device of ['desktop','touch']){const on=report.runs.find(r=>r.device===device&&r.pilot),off=report.runs.find(r=>r.device===device&&!r.pilot);if(!on?.initial||!off?.initial)continue;if(on.panAway&&on.panBack){on.stationaryCheck=stationaryCheck(on);on.stationaryAcrossPan=on.stationaryCheck.maxDisplacementM<=.01;}const suppression={};for(const key of ['signatureSuppression','threeSignatureSuppression','roofHidden']){if(!Array.isArray(on.initial[key])||!Array.isArray(off.initial[key])){suppression[key]={supported:false,added:[],removed:[],exactExpectedDelta:false};continue;}const added=on.initial[key].filter(id=>!off.initial[key].includes(id)).sort();suppression[key]={supported:true,added,removed:off.initial[key].filter(id=>!on.initial[key].includes(id)),exactExpectedDelta:JSON.stringify(added)===JSON.stringify(expected)};}const gpum=t=>median(t.filter(x=>x.gpuExtension&&!x.gpuDisjoint&&x.fullMapGpuMs?.count>0&&Number.isFinite(x.fullMapGpuMs.median)).map(x=>x.fullMapGpuMs.median));report.comparisons.push({device,suppression,pilotGpuMedianOfRoundMediansMs:gpum(on.timings),baselineGpuMedianOfRoundMediansMs:gpum(off.timings),gpuRatio:gpum(on.timings)!==null&&gpum(off.timings)>0?gpum(on.timings)/gpum(off.timings):null,globalSignatureSetsComparable:Object.values(suppression).every(s=>s.exactExpectedDelta&&s.removed.length===0),scopedPilotIdsHiddenInAllLayers:expected.every(id=>['signatureSuppression','threeSignatureSuppression','roofHidden'].every(key=>on.initial[key]?.includes(id)&&off.initial[key]!==null&&!off.initial[key]?.includes(id))),neighborSuppressionChanged:on.initial.nearbySourceIdentities.filter(f=>!f.pilot&&off.initial.nearbySourceIdentities.some(b=>b.id===f.id&&b.hidden!==f.hidden)),performanceConclusion:`${on.timings.length} sequential measured round(s) per page are descriptive; variability and page-order confounding prevent a stable causal overhead/budget claim.`});}
await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));await fs.writeFile(path.join(out,'index.html'),`<!doctype html><meta charset="utf-8"><title>Canalhouse actual game evidence</title><style>body{font:16px sans-serif;background:#eee;padding:20px}img{max-width:100%;display:block}figure{background:white;padding:12px}pre{white-space:pre-wrap}</style><h1>Actual game evidence · candidate only</h1><p>All visual recognition/heldout acceptance remains pending. Prior failed harness evidence remains in its original cycle directories. Unrelated global loaded-model inventories can differ between pages; inspect comparison limits. <a href="report.json">Full measured report</a>.</p>${report.runs.map(r=>`<h2>${r.device} · ${r.pilot?'pilot':'baseline'}</h2>${(r.screenshots??[]).map(f=>`<figure><figcaption>${f}</figcaption><img src="${f}"></figure>`).join('')}`).join('')}<h2>Comparisons and limits</h2><pre>${JSON.stringify({comparisons:report.comparisons,limits:report.limits},null,2)}</pre>`);}

