import assert from 'node:assert/strict';
import { acceptedWallColours, promoteWallColour, validatedWallRenderCalibrations, wallColourForBuilding, wallRenderColourForBuilding, type WallGrade, type WallMeasurement, type WallRenderCalibrationSet } from './wallColourPublication.js';

const H = 'a'.repeat(64), M = 'b'.repeat(64);
const measurements: WallMeasurement[] = [{ id: 'obs-1', buildingId: '123', sourceSha256: H, status: 'measured', dominant: { hex: '#654321' } }];
const grade: WallGrade = { observationId: 'obs-1', buildingId: '123', sourceSha256: H, verdict: 'accept', gradedAt: '2026-09-26T00:00:00Z', grader: 'owner', reviewOrigin: 'human-visual-review' };
const set = promoteWallColour(measurements, { 'obs-1': grade }, M);
assert.deepEqual(set.accepted.map(item => item.hex), ['#654321']);
const accepted = acceptedWallColours(set, measurements, M);
assert.deepEqual(wallColourForBuilding('123', '#eeeeee', accepted), { sideColour: '#654321', sideColourSource: 'measured-accepted', sideColourObservationId: 'obs-1', sideColourSourceSha256: H, sideColourReviewOrigin: 'human-visual-review', sideColourReviewer: 'owner' });
assert.deepEqual(wallColourForBuilding('456', '#eeeeee', accepted), { sideColour: '#eeeeee', sideColourSource: 'procedural-prior-not-measured' });
assert.throws(() => promoteWallColour(measurements, { 'obs-1': { ...grade, sourceSha256: 'c'.repeat(64) } }, M), /Stale/);
assert.throws(() => promoteWallColour(measurements, { 'obs-1': { ...grade, buildingId: '456' } }, M), /identity/);
assert.throws(() => promoteWallColour(measurements, { 'obs-2': { ...grade, observationId: 'obs-2' } }, M), /identity/);
assert.throws(() => acceptedWallColours(set, measurements, 'c'.repeat(64)), /current measurements/);
assert.throws(() => acceptedWallColours(set, [{ ...measurements[0], sourceSha256: 'c'.repeat(64) }], M), /Invalid accepted/);
assert.throws(() => acceptedWallColours(set, [{ ...measurements[0], buildingId: '456' }], M), /Invalid accepted/);
assert.throws(() => acceptedWallColours({ ...set, accepted: [{ ...set.accepted[0], hex: '#ff0000', observationId: 'invented' }] }, measurements, M), /Invalid accepted/);
assert.throws(() => acceptedWallColours({ ...set, accepted: [...set.accepted, { ...set.accepted[0], observationId: 'obs-2' }] }, [...measurements, { ...measurements[0], id: 'obs-2' }], M), /Multiple accepted walls/);
const corrected = promoteWallColour(measurements, { 'obs-1': { ...grade, correctedHex: '#abcdef' } }, M);
assert.equal(corrected.accepted[0].hex, '#abcdef');
assert.deepEqual(promoteWallColour(measurements, { 'obs-1': { ...grade, verdict: 'unusable' } }, M).accepted, []);
const model = promoteWallColour(measurements, { 'obs-1': { ...grade, reviewOrigin: 'model-visual-review', grader: 'gpt-6-sol', verdict: 'adjust', correctedHex: '#abcdef' } }, M);
assert.equal(model.accepted[0].reviewOrigin, 'model-visual-review');
assert.equal(model.accepted[0].reviewer, 'gpt-6-sol');
assert.equal(wallColourForBuilding('123', '#eeeeee', acceptedWallColours(model, measurements, M)).sideColourSource, 'measured-accepted');
assert.throws(() => promoteWallColour(measurements, { 'obs-1': { ...grade, reviewOrigin: undefined as any } }, M), /provenance/);
const R='c'.repeat(64), C='d'.repeat(64);
const calibration:WallRenderCalibrationSet={version:1,baselineReleaseId:R,calibrations:[{buildingId:'123',observationId:'obs-1',sourceSha256:H,referenceSha256:H,gameCaptureSha256:C,renderSideColour:'#a48770',reviewer:'gpt-6-sol',reviewOrigin:'model-visual-review',gradedAt:'2026-09-26T10:00:00Z',reason:'Rendered wall was darker than the same exposed wall in the source crop.'}]};
const validated=validatedWallRenderCalibrations(calibration,accepted,R);
assert.equal(wallColourForBuilding('123','#eeeeee',accepted).sideColour,'#654321');
assert.deepEqual(wallRenderColourForBuilding('123',validated),{renderSideColour:'#a48770',renderSideColourCalibration:{baselineReleaseId:R,observationId:'obs-1',referenceSha256:H,gameCaptureSha256:C,reviewer:'gpt-6-sol',reviewOrigin:'model-visual-review',gradedAt:'2026-09-26T10:00:00Z',reason:calibration.calibrations[0].reason}});
assert.deepEqual(wallRenderColourForBuilding('456',validated),{});
assert.throws(()=>validatedWallRenderCalibrations(calibration,accepted,C),/baseline release/);
assert.throws(()=>validatedWallRenderCalibrations({...calibration,calibrations:[{...calibration.calibrations[0],sourceSha256:C}]},accepted,R),/Invalid or stale/);
assert.throws(()=>validatedWallRenderCalibrations({...calibration,calibrations:[{...calibration.calibrations[0],observationId:'other'}]},accepted,R),/Invalid or stale/);
assert.throws(()=>validatedWallRenderCalibrations({...calibration,calibrations:[...calibration.calibrations,calibration.calibrations[0]]},accepted,R),/Invalid or stale/);
console.log('wallColourPublication: source and render calibration assertions passed');
