import assert from 'node:assert/strict';
import { acceptedWallColours, promoteWallColour, wallColourForBuilding, type WallGrade, type WallMeasurement } from './wallColourPublication.js';

const H = 'a'.repeat(64), M = 'b'.repeat(64);
const measurements: WallMeasurement[] = [{ id: 'obs-1', buildingId: '123', sourceSha256: H, status: 'measured', dominant: { hex: '#654321' } }];
const grade: WallGrade = { observationId: 'obs-1', buildingId: '123', sourceSha256: H, verdict: 'accept', gradedAt: '2026-09-26T00:00:00Z', grader: 'owner' };
const set = promoteWallColour(measurements, { 'obs-1': grade }, M);
assert.deepEqual(set.accepted.map(item => item.hex), ['#654321']);
const accepted = acceptedWallColours(set, measurements, M);
assert.deepEqual(wallColourForBuilding('123', '#eeeeee', accepted), { sideColour: '#654321', sideColourSource: 'measured-accepted', sideColourObservationId: 'obs-1', sideColourSourceSha256: H });
assert.deepEqual(wallColourForBuilding('456', '#eeeeee', accepted), { sideColour: '#eeeeee', sideColourSource: 'procedural-prior-not-measured' });
assert.throws(() => promoteWallColour(measurements, { 'obs-1': { ...grade, sourceSha256: 'c'.repeat(64) } }, M), /Stale/);
assert.throws(() => promoteWallColour(measurements, { 'obs-1': { ...grade, buildingId: '456' } }, M), /identity/);
assert.throws(() => promoteWallColour(measurements, { 'obs-2': { ...grade, observationId: 'obs-2' } }, M), /identity/);
assert.throws(() => acceptedWallColours(set, measurements, 'c'.repeat(64)), /current measurements/);
assert.throws(() => acceptedWallColours(set, [{ ...measurements[0], sourceSha256: 'c'.repeat(64) }], M), /Invalid accepted/);
assert.throws(() => acceptedWallColours(set, [{ ...measurements[0], buildingId: '456' }], M), /Invalid accepted/);
assert.throws(() => acceptedWallColours({ ...set, accepted: [{ ...set.accepted[0], hex: '#ff0000', observationId: 'invented' }] }, measurements, M), /Invalid accepted/);
assert.throws(() => acceptedWallColours({ ...set, accepted: [...set.accepted, { ...set.accepted[0], observationId: 'obs-2' }] }, [...measurements, { ...measurements[0], id: 'obs-2' }], M), /Multiple accepted walls/);
const corrected = promoteWallColour(measurements, { 'obs-1': { ...grade, correctedHex: '#abcdef' } }, M);
assert.equal(corrected.accepted[0].hex, '#abcdef');
assert.deepEqual(promoteWallColour(measurements, { 'obs-1': { ...grade, verdict: 'unusable' } }, M).accepted, []);
console.log('wallColourPublication: 13 assertions passed');
