/** Cache-only alternatives for five obscured intervals; no active inputs modified. */
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import jpeg from 'jpeg-js';
import sharp from 'sharp';
import {AMSTERDAM_WORLD_ALIGNED,rectifyFacade,worldToEquirectangularPixel} from '../../src/canalRecall/facade/rectify.ts';
import {lngLatToRd} from '../../src/canalRecall/facade/rdNew.ts';
import {sha,lensFor,footprintOcclusion,VISIBILITY_VERSION} from './neighbourhood-core.ts';
const out=path.resolve('.cache/da-costa-ground-bays-temporal-2026-09-09'),active=path.resolve('.cache/da-costa-neighbourhood');
assert.ok(!out.startsWith(active));await fs.mkdir(out+'/images',{recursive:true});
const read=async(p:string)=>JSON.parse(await fs.readFile(p,'utf8'));
const previousBytes=await fs.readFile('.cache/da-costa-ground-bays/manifest.json'),previous=JSON.parse(previousBytes.toString());
const activeBytes=await fs.readFile(active+'/manifest.json'),manifest=JSON.parse(activeBytes.toString());
const block=await read('public/data/da-costa-block/block.json'),bag=await read('.cache/da-costa-block/bag.json'),all=await read('.cache/da-costa-block/panoramas.json');
const cached=new Set((await fs.readdir(active+'/panoramas')).filter(n=>n.endsWith('.jpg')).map(n=>n.slice(0,-4)));
const registry=new Map(bag.map((b:any)=>[b.properties.identificatie,b])),local=(p:any)=>[p.x-block.origin.x,block.origin.y-p.y];
const occluders=block.buildings.map((b:any)=>{const source:any=registry.get(b.id);const polygons=source?(source.geometry.type==='Polygon'?[source.geometry.coordinates]:source.geometry.coordinates).map((p:any)=>p.map((r:any)=>r.map((v:any)=>local(lngLatToRd(v))))):(b.footprint.type==='Polygon'?[b.footprint.coordinates]:b.footprint.coordinates);const pts=polygons.flat(2);return{id:b.id,polygons,bounds:[Math.min(...pts.map((p:any)=>p[0])),Math.min(...pts.map((p:any)=>p[1])),Math.max(...pts.map((p:any)=>p[0])),Math.max(...pts.map((p:any)=>p[1]))]};});
const blockers=(a:number[],b:number[])=>occluders.filter((o:any)=>!(Math.max(a[0],b[0])<o.bounds[0]||Math.min(a[0],b[0])>o.bounds[2]||Math.max(a[1],b[1])<o.bounds[1]||Math.min(a[1],b[1])>o.bounds[3])&&footprintOcclusion(a,b,o.polygons).blocked).map((o:any)=>o.id);
const cameras=all.filter((p:any)=>cached.has(p.pano_id)&&p.surface_type==='L').flatMap((p:any)=>{const from=local(lngLatToRd(p.geometry.coordinates));const nearest=block.buildings.filter((b:any)=>Number.isFinite(b.groundNAP)).sort((a:any,b:any)=>Math.hypot(a.center[0]-from[0],a.center[1]-from[1])-Math.hypot(b.center[0]-from[0],b.center[1]-from[1]))[0];const lens=lensFor(p,nearest?.groundNAP);return lens?[{p,lens}]:[];});
const decoded=new Map<string,any>();async function source(id:string){if(decoded.has(id))return decoded.get(id);const file=active+'/panoramas/'+id+'.jpg',bytes=await fs.readFile(file),s={file,bytes,sha256:sha(bytes),image:jpeg.decode(bytes,{useTArray:true,formatAsRGBA:true})};decoded.set(id,s);if(decoded.size>2)decoded.delete(decoded.keys().next().value!);return s;}
const records:any[]=[];
for(const old of previous.records.filter((r:any)=>r.parentId==='0363100012077314_e_14o9326'&&[0,1,2,4,5].includes(r.interval.index))){
  const parent=manifest.records.find((r:any)=>r.id===old.parentId);assert.equal(parent.derivationKey,old.parentDerivationKey);
  const {start,end,normal}=old.wall,mid={x:(start.x+end.x)/2,y:(start.y+end.y)/2},baseZ=old.images['same-source'].plane.baseZ,topZ=old.images['same-source'].plane.topZ;
  const ranked=cameras.filter((c:any)=>c.p.pano_id!==old.images['best-cached'].panoramaId&&c.p.pano_id!==old.images['same-source'].panoramaId).map((c:any)=>{const pose=c.lens.pose,dx=pose.x-mid.x,dy=pose.y-mid.y,distance=Math.hypot(dx,dy),standoff=dx*normal.x+dy*normal.y,obliquity=Math.acos(Math.max(-1,Math.min(1,standoff/distance)))*180/Math.PI;const rayBlockers=[.15,.5,.85].map(t=>blockers(local(pose),local({x:start.x+(end.x-start.x)*t,y:start.y+(end.y-start.y)*t}))),hiddenFraction=rayBlockers.filter((r:any)=>r.length).length/3;const u=[start,end].map(p=>worldToEquirectangularPixel({...p,z:(baseZ+topZ)/2},pose,{width:8000,height:4000},AMSTERDAM_WORLD_ALIGNED)[0]);const nativeAngularWidthPx=Math.abs(((u[1]-u[0]+12000)%8000)-4000);return {...c,year:c.p.timestamp.slice(0,4),visibility:{version:VISIBILITY_VERSION,distance,standoff,obliquity,hiddenFraction,rayBlockers,geometryEligible:distance<=52&&standoff>=3&&obliquity<=48&&hiddenFraction<=.34},nativeAngularWidthPx};}).filter((c:any)=>c.visibility.geometryEligible).sort((a:any,b:any)=>b.nativeAngularWidthPx-a.nativeAngularWidthPx);
  // At most three unique capture years, oldest eligible year first. Failed
  // alternatives stay in the output; selection has no pixel-visibility oracle.
  const years=[...new Set(ranked.map((c:any)=>c.year))].sort(),chosen=years.slice(0,3).map(year=>ranked.find((c:any)=>c.year===year));
  const images:any[]=[];
  for(let n=0;n<chosen.length;n++){
    const c:any=chosen[n],s=await source(c.p.pano_id),prefix=old.id+'-alt-'+String(n+1).padStart(2,'0'),pose=c.lens.pose;
    const point=(m:number)=>({x:parent.wall.start.x+(parent.wall.end.x-parent.wall.start.x)*m/parent.wallWidthM,y:parent.wall.start.y+(parent.wall.end.y-parent.wall.start.y)*m/parent.wallWidthM});
    const variants=[{kind:'ground',plane:{start,end,baseZ,topZ}},{kind:'context',plane:{start:point(Math.max(0,old.interval.startM-1.5)),end:point(Math.min(parent.wallWidthM,old.interval.endM+1.5)),baseZ,topZ:parent.groundNAP+7}}];
    const crops:any={};for(const v of variants){const rect=rectifyFacade(s.image,pose,v.plane,{camera:AMSTERDAM_WORLD_ALIGNED,pixelsPerMetre:110,maxPixels:1600000}),bytes=jpeg.encode({width:rect.width,height:rect.height,data:Buffer.from(rect.data)},92).data,file=prefix+'-'+v.kind+'.jpg';await fs.writeFile(out+'/images/'+file,bytes);const rawQuad=[v.plane.start,v.plane.end].flatMap(p=>[worldToEquirectangularPixel({...p,z:v.plane.baseZ},pose,s.image,AMSTERDAM_WORLD_ALIGNED),worldToEquirectangularPixel({...p,z:v.plane.topZ},pose,s.image,AMSTERDAM_WORLD_ALIGNED)]);crops[v.kind]={file,sha256:sha(bytes),width:rect.width,height:rect.height,plane:v.plane,rawQuad};}
    const q=crops.context.rawQuad,xx=q.map((p:any)=>p[0]),yy=q.map((p:any)=>p[1]);const left=Math.max(0,Math.floor(Math.min(...xx)-220)),right=Math.min(s.image.width,Math.ceil(Math.max(...xx)+220)),top=Math.max(0,Math.floor(Math.min(...yy)-220)),bottom=Math.min(s.image.height,Math.ceil(Math.max(...yy)+220));
    assert.ok(right-left<s.image.width*.8,'Seam-crossing context needs explicit wrap handling');
    const crop={left,top,width:right-left,height:bottom-top},raw=await sharp(s.bytes).extract(crop).jpeg({quality:94}).toBuffer(),rawFile=prefix+'-original-context.jpg';await fs.writeFile(out+'/images/'+rawFile,raw);
    crops.originalContext={file:rawFile,sha256:sha(raw),sourcePixelCrop:crop,note:'Unrectified original pixel region with 220px context padding; no generated details. Location is evidence context, not bay-wide business text.'};
    images.push({alternative:n+1,panoramaId:c.p.pano_id,panoramaFile:s.file,panoramaSha256:s.sha256,date:c.p.timestamp,url:c.p._links.equirectangular_full.href,pose,datum:c.lens.datum,visibility:c.visibility,nativeAngularWidthPx:c.nativeAngularWidthPx,sourceDimensions:[s.image.width,s.image.height],crops});
  }
  const tileW=600,rowH=550,parts:any[]=[];for(let n=0;n<images.length;n++){const v=images[n],label=`${old.id.slice(-6)} alt ${v.alternative}: ${v.date.slice(0,10)} | ${v.visibility.distance.toFixed(1)}m, ${v.visibility.obliquity.toFixed(1)}deg | native angular width ${v.nativeAngularWidthPx.toFixed(0)}px`;parts.push({input:Buffer.from(`<svg width="1800" height="48"><rect width="100%" height="100%" fill="#faf9f3"/><text x="12" y="30" font-size="21" font-family="sans-serif">${label}</text></svg>`),left:0,top:n*rowH});for(const [i,key]of ['ground','context','originalContext'].entries()){const buf=await sharp(out+'/images/'+v.crops[key].file).resize(tileW,rowH-48,{fit:'contain',background:'#d8ddd2'}).jpeg().toBuffer();parts.push({input:buf,left:i*tileW,top:n*rowH+48});}}
  const sheet=old.id+'-temporal-sheet.jpg';if(images.length){await sharp({create:{width:1800,height:rowH*images.length,channels:3,background:'#d8ddd2'}}).composite(parts).jpeg({quality:93}).toFile(out+'/'+sheet);}
  records.push({id:old.id,parentId:old.parentId,parentBuildingId:old.parentBuildingId,parentElevationId:old.parentElevationId,parentDerivationKey:old.parentDerivationKey,parentIntervalDerivationKey:old.derivationKey,interval:old.interval,wall:old.wall,previousImages:old.images,candidateCount:ranked.length,availableYears:years,alternatives:images,sheet,appearanceEligible:false,policy:'Diagnostic local interval only; never promote to whole-wall appearance or tenant identity.',derivationKey:sha(JSON.stringify({parent:old.derivationKey,images}))});console.log(JSON.stringify({bay:old.interval.index+1,candidates:ranked.length,chosen:images.map((v:any)=>({date:v.date,pano:v.panoramaId,nativeWidth:Math.round(v.nativeAngularWidthPx)}))}));
}
assert.equal(sha(await fs.readFile(active+'/manifest.json')),sha(activeBytes),'Active manifest changed during experiment');
const result={version:1,createdAt:new Date().toISOString(),sourceManifestSha256:sha(previousBytes),activeManifestSha256:sha(activeBytes),selection:'Five previously obscured bays 01,02,03,05,06; at most one best-native-angular-width eligible cached camera per capture year, up to three oldest available years; previous same/best cameras excluded.',method:'Same parent intervals and projection convention; exact original metric endpoints preserved. Each alternative includes ground, clamped 1.5m context and unrectified original panorama region. No pixel quality assumed from geometry.',summary:{bays:records.length,alternatives:records.reduce((n,r)=>n+r.alternatives.length,0),downloads:0,costUsd:0},records};await fs.writeFile(out+'/manifest.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result.summary));
