/** Native original circular-segment roof mesh; recipe owns observed scope and profile. No imported geometry. */
export function barrelVault({frame,radius,centerAcross,centerHeight,angleStart,angleEnd,longStart,longEnd,arcSegments=40,lengthSegments=4,uv,material}){
 if(![radius,centerAcross,centerHeight,angleStart,angleEnd,longStart,longEnd,arcSegments,lengthSegments].every(Number.isFinite)||radius<=0||angleStart>=angleEnd||longStart>=longEnd||!Number.isInteger(arcSegments)||!Number.isInteger(lengthSegments)||arcSegments<3||lengthSegments<1||typeof frame?.point!=='function'||typeof uv!=='function'||!material)throw Error('Invalid bounded barrel vault');
 const at=(angle,v)=>frame.point(centerAcross+radius*Math.sin(angle),centerHeight+radius*Math.cos(angle),v),quads=[];
 for(let i=0;i<arcSegments;i++)for(let j=0;j<lengthSegments;j++){const t=i/arcSegments,u=(i+1)/arcSegments,v=j/lengthSegments,w=(j+1)/lengthSegments,a=angleStart+(angleEnd-angleStart)*t,b=angleStart+(angleEnd-angleStart)*u,c=longStart+(longEnd-longStart)*v,d=longStart+(longEnd-longStart)*w;quads.push({material,points:[at(a,c),at(b,c),at(b,d),at(a,d)],uvs:[uv(t,v),uv(u,v),uv(u,w),uv(t,w)],outward:frame.normal((a+b)/2)});}return{quads,at,profile:angle=>({across:centerAcross+radius*Math.sin(angle),height:centerHeight+radius*Math.cos(angle)}),arcLength:radius*(angleEnd-angleStart)};
}
/** Procedural diamond cassettes. Glass aperture physically shrinks toward opaque circular crest. */
export function diamondCassetteSVG({width=1024,height=1024,arcLength,longLength,angleStart,angleEnd,diamondAcross=2.1,diamondAlong=2.2,silver='#aaaead',seam='#858e8c',glass='#547d80',opaqueCrestAngle=.25}){
 if(![width,height,arcLength,longLength,angleStart,angleEnd,diamondAcross,diamondAlong,opaqueCrestAngle].every(Number.isFinite)||arcLength<=0||longLength<=0||diamondAcross<=0||diamondAlong<=0)throw Error('Invalid cassette atlas');
 const sx=(width-32)/arcLength,sy=height/longLength,path=(cx,cy,rx,ry)=>`${cx-rx},${cy} ${cx},${cy-ry} ${cx+rx},${cy} ${cx},${cy+ry}`;let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" shape-rendering="crispEdges"><rect width="${width}" height="${height}" fill="${silver}"/>`,panels=[];
 for(let i=-1;i<Math.ceil(arcLength/(diamondAcross/2))+1;i++)for(let j=-1;j<Math.ceil(longLength/(diamondAlong/2))+1;j++){if((i+j)%2)continue;const s=i*diamondAcross/2,v=j*diamondAlong/2,cx=32+s*sx,cy=v*sy,angle=angleStart+(angleEnd-angleStart)*s/arcLength,ratio=Math.max(0,Math.min(.79,(Math.abs(angle)-opaqueCrestAngle)/.85));svg+=`<polygon points="${path(cx,cy,diamondAcross*sx/2,diamondAlong*sy/2)}" fill="${silver}" stroke="${seam}" stroke-width="1.2"/>`;if(ratio>.08)svg+=`<polygon points="${path(cx,cy,diamondAcross*sx/2*ratio,diamondAlong*sy/2*ratio)}" fill="${glass}" stroke="#465b5d" stroke-width="1.1"/>`;if(s>0&&s<arcLength&&v>0&&v<longLength)panels.push({s,v,angle,glassRatio:ratio});}
 // Flat decks and louvered endwalls have explicit swatches, never photograph pixels.
 svg+=`<rect x="0" y="0" width="16" height="${height}" fill="#626d69"/><rect x="16" y="0" width="16" height="${height}" fill="#979e9a"/>`;for(let y=0;y<height;y+=7)svg+=`<rect x="16" y="${y}" width="16" height="2" fill="#68736d"/>`;return{svg:svg+'</svg>',panels};
}
