import fs from 'node:fs/promises';import * as T from 'three';import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {MeshoptDecoder} from 'meshoptimizer';import spec from './brouwers1-spec.json';
await MeshoptDecoder.ready;
const out='artifacts/ordinary-buildings/brouwers1',file=`${out}/${spec.digits}.glb`,doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(file),scene=new T.Scene();const palette={brick:'#4c403b',warehouseBrick:'#97725a',white:'#e0ded2',stone:'#a59f8e',glass:'#45616a',frame:'#343b37',door:'#28312e',iron:'#313330',roof:'#62625c',tile:'#686a65',chamber:'#435650',reveal:'#b2b3a9',joint:'#888377'};let finite=true,degenerate=0,downwardRoofs=0,roofTriangles=0,triangles=0;
const colour=(rgb:number[])=>Object.entries(palette).map(([k,v])=>({k,d:new T.Color(v).toArray().reduce((s,c,i)=>s+(c-rgb[i])**2,0)})).sort((a,b)=>a.d-b.d)[0].k;
for(const mesh of doc.getRoot().listMeshes())for(const p of mesh.listPrimitives()){const g=new T.BufferGeometry();for(const [src,dst]of[['POSITION','position'],['NORMAL','normal'],['COLOR_0','color']])g.setAttribute(dst,new T.BufferAttribute(p.getAttribute(src)!.getArray() as Float32Array,3));if(p.getIndices())g.setIndex(new T.BufferAttribute(p.getIndices()!.getArray() as Uint32Array,1));const pos=g.getAttribute('position'),col=g.getAttribute('color'),ix=g.index,count=ix?.count??pos.count;finite&&=[...pos.array,...g.getAttribute('normal').array].every(Number.isFinite);for(let i=0;i<count;i+=3){const ids=[0,1,2].map(j=>ix?ix.getX(i+j):i+j),vs=ids.map(j=>new T.Vector3().fromBufferAttribute(pos,j)),n=vs[1].clone().sub(vs[0]).cross(vs[2].clone().sub(vs[0]));triangles++;if(n.length()<1e-7)degenerate++;const c=colour([col.getX(ids[0]),col.getY(ids[0]),col.getZ(ids[0])]);if(['roof','tile','chamber'].includes(c)){roofTriangles++;if(n.y<=0)downwardRoofs++;}}scene.add(new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide})));}scene.updateMatrixWorld(true);
const cast=(point:number[],normal:number[],distance=3)=>{const n=new T.Vector3(...normal as[number,number,number]),ray=new T.Raycaster(new T.Vector3(...point as[number,number,number]).addScaledVector(n,distance),n.clone().negate(),0,distance+1);return ray.intersectObjects(scene.children)[0];};
const hitColour=(h:T.Intersection|undefined)=>{if(!h)return undefined;const c=(h.object as T.Mesh).geometry.getAttribute('color'),i=h.face!.a;return colour([c.getX(i),c.getY(i),c.getZ(i)]);};
const probes=JSON.parse(await fs.readFile(`${out}/opening-probes.json`,'utf8')),openingResults=probes.map((p:any)=>{const hit=cast(p.point,p.normal);return {label:p.label,expected:p.kind,first:hitColour(hit),pass:hitColour(hit)===p.kind,distance:hit?.distance};});
const inside=(p:number[],poly:number[][])=>{let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;};
const gardenResults:any[]=[];for(const g of (spec as any).gardenOpenings){let best:number[]|undefined;for(let x=Math.min(...g.ring.map((p:number[])=>p[0]));x<Math.max(...g.ring.map((p:number[])=>p[0]));x+=.6)for(let z=Math.min(...g.ring.map((p:number[])=>p[1]));z<Math.max(...g.ring.map((p:number[])=>p[1]));z+=.6){if(!inside([x,z],g.ring)||g.holes.some((h:number[][])=>inside([x,z],h)))continue;const hit=new T.Raycaster(new T.Vector3(x,25,z),new T.Vector3(0,-1,0),0,25).intersectObjects(scene.children)[0];gardenResults.push({point:[x,z],pass:!hit,first:hitColour(hit),height:hit?.point.y});}}
// Roof-center vertical probes use the actual prepared source ownership polygons.
const roofResults:any[]=[];for(const r of spec.roofs.filter(r=>r.role==='survey-roof-owner'&&r.areaMetres2>8)){let sample:number[]|undefined;for(let x=Math.min(...r.ring.map(p=>p[0]))+.25;!sample&&x<Math.max(...r.ring.map(p=>p[0]));x+=.4)for(let z=Math.min(...r.ring.map(p=>p[1]))+.25;z<Math.max(...r.ring.map(p=>p[1]));z+=.4){if(inside([x,z],r.ring)&&!r.holes.some(h=>inside([x,z],h))){sample=[x,z];break;}}if(!sample)continue;const y=r.plane[0]*sample[0]+r.plane[1]*sample[1]+r.plane[2],hit=cast([sample[0],y,sample[1]],[0,1,0],.15);roofResults.push({surface:r.surface,pass:!!hit&&Math.abs(hit.point.y-y)<.035,expected:y,actual:hit?.point.y});}
const supportResults=(spec as any).supports.filter((s:any)=>s.upper!==246).map((s:any)=>{const points=s.points.map((p:number[])=>new T.Vector3(...p as[number,number,number])),mid=points.reduce((a:T.Vector3,p:T.Vector3)=>a.add(p),new T.Vector3()).multiplyScalar(.25),n=points[1].clone().sub(points[0]).cross(points[2].clone().sub(points[0])).normalize(),hit=cast(mid.toArray(),n.toArray(),.15);return {upper:s.upper,lower:s.lower,pass:!!hit&&hit.point.distanceTo(mid)<.02&&hitColour(hit)===(s.upper===244?"white":"brick"),expected:s.upper===244?"white":"brick",actualDistance:hit?.point.distanceTo(mid),first:hitColour(hit)};});
const nativeEnvelope=JSON.parse(await fs.readFile(`${out}/native-envelope.json`,'utf8')).nativeEnvelope,lowTipExterior=nativeEnvelope.filter((r:any)=>r.nativeEdge===10),lowTipPass=lowTipExterior.length>0&&lowTipExterior.every((r:any)=>r.upperRegion===245&&Math.max(...r.upperRoofMetres)<3.45);
const omitted246=spec.roofs.find(r=>r.surface===246&&r.role==='survey-roof-owner')!,sample246=omitted246.ring.reduce((a,p)=>[a[0]+p[0]/omitted246.ring.length,a[1]+p[1]/omitted246.ring.length],[0,0]),low245=spec.roofs.find(r=>r.surface===245&&r.role==='survey-roof-owner')!,lowAt246=low245.plane[0]*sample246[0]+low245.plane[1]*sample246[1]+low245.plane[2],hit246=cast([sample246[0],lowAt246,sample246[1]],[0,1,0],22),omitted246Pass=!!hit246&&Math.abs(hit246.point.y-lowAt246)<.025;
const report={finite,triangles,degenerate,roofTriangles,downwardRoofs,materials:doc.getRoot().listMaterials().length,textures:doc.getRoot().listTextures().length,scale:spec.scale,exactSuppression:spec.suppress,retainNeighbors:spec.retain,openingResults,gardenResults,roofResults,supportResults,lowTipExterior,lowTipPass,omitted246Pass,omitted246Sample:{point:sample246,expectedLow:lowAt246,actual:hit246?.point.y},acceptance:'Decoded CPU geometric evidence only; no source/render/game acceptance'};await fs.writeFile(`${out}/geometry-check.json`,JSON.stringify(report,null,2));const failed=openingResults.filter((p:any)=>!p.pass),badGarden=gardenResults.filter(p=>!p.pass),badRoof=roofResults.filter(p=>!p.pass);console.log(JSON.stringify({finite,triangles,degenerate,roofTriangles,downwardRoofs,openings:openingResults.length,failed,badGarden,gardenRays:gardenResults.length,badRoof,roofRays:roofResults.length,lowTipPass,omitted246Pass,supportRays:supportResults.length,badSupport:supportResults.filter((p:any)=>!p.pass)}));if(!finite||degenerate||downwardRoofs||failed.length||badGarden.length||badRoof.length||!lowTipPass||!omitted246Pass||supportResults.some((p:any)=>!p.pass))process.exitCode=1;
