/** Source-informed native ordinary building batch. Original atlas pixels; no photo texture imports. */
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import * as T from 'three';
import sharp from 'sharp';
import {Document,NodeIO} from '@gltf-transform/core';
import {openTopPrism,upwardRoofPlane} from '../landmarks/house-geometry.js';
const data=process.env.ORDINARY_DATA_ROOT||'public/canal-drive/ordinary-buildings-data', output=process.env.ORDINARY_OUTPUT_ROOT||'public/canal-drive/models/ordinary-buildings';
await fs.mkdir(output,{recursive:true});
const recipes=JSON.parse(await fs.readFile(`${data}/recipes.json`,'utf8')).recipes;
const sourceRoot=process.env.ORDINARY_SOURCE_ROOT||'/Users/blackmad/Code/map-recall2-source-data';
const rgba=(hex:string):[number,number,number,number]=>{const c=new T.Color(hex);return [c.r,c.g,c.b,1]};
const rect=(x:number,y:number,w:number,h:number,c:string)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${c}"/>`;
/** All dimensions in physical metres, source recipes own face roles and parameters. */
function facadeConfig(r:any,edge:number){const f={...r.facade,...r.facade?.edges?.[String(edge)]};
 for(const group of [...f.windowTiers||[],...f.balconyGroups||[],...f.canopyGroups||[],...f.projectionGroups||[]])for(const key of ['pitchMetres','barPitchMetres'])if(group[key]!==undefined&&!(Number.isFinite(group[key])&&group[key]>0))throw Error(`Invalid ${key} on edge ${edge}`);
 for(const entry of f.groundEntries||[])if(entry.jointPitchMetres!==undefined&&!(entry.jointPitchMetres>0))throw Error(`Invalid entry joint pitch on edge ${edge}`);
 return f;}

function face(r:any,len:number,edge:number,height:number){
 const f=facadeConfig(r,edge),W=512,H=256,sx=W/len,sy=H/height;
 const wall=f.wallColor||r.wall,frame=f.frameColor||r.palette.frames,glass=f.glassColor||r.palette.glass;
 let svg=rect(0,0,W,H,wall);
 const draw=(x:number,bottom:number,w:number,h:number,c:string)=>{if(w>0&&h>0)svg+=rect(x*sx,(height-bottom-h)*sy,w*sx,h*sy,c);};
 if(f.plinthHeightMetres)draw(0,0,len,f.plinthHeightMetres,f.plinthColor||'#858b86');
 for(const band of f.bands||[])draw(band.xMetres??0,band.bottomMetres,band.widthMetres??len,band.heightMetres,band.color);
 const panes=f.panes??2,fw=f.frameWidthMetres??.09;
 function win(x:number,y:number,w:number,h:number,num=panes){draw(x,y,w,h,frame);for(let j=0;j<num;j++)draw(x+fw+j*(w-2*fw)/num,y+fw,(w-2*fw)/num-fw*.6,h-2*fw,glass);}
 // New assemblies are opt-in. Opening heads are real curved SVG outlines; no photo pixels.
 function opening(x:number,y:number,w:number,h:number,o:any={}){
  const frameColor=o.frameColor||frame,glassColor=o.glassColor||glass,border=o.frameWidthMetres??fw;
  const rise=Math.min(o.crownRiseMetres??0,h*.45),paneCount=o.panes??panes;
  if(!(w>2*border&&h>2*border)||paneCount<1)throw Error(`Invalid facade opening on edge ${edge}`);
  const outline=(px:number,py:number,pw:number,ph:number,pr:number)=>{const left=px*sx,top=(height-py-ph)*sy,right=(px+pw)*sx,bottom=(height-py)*sy;return `M ${left} ${bottom} L ${left} ${top+pr*sy} ${o.head==='round'?`A ${pw*sx/2} ${pr*sy} 0 0 1 ${right} ${top+pr*sy}`:`Q ${(left+right)/2} ${top-pr*sy} ${right} ${top+pr*sy}`} L ${right} ${bottom} Z`;};
  if(!rise){draw(x,y,w,h,frameColor);draw(x+border,y+border,w-2*border,h-2*border,glassColor);if(o.lowerSpandrelHeightMetres)draw(x+border,y+border,w-2*border,o.lowerSpandrelHeightMetres,o.lowerSpandrelColor||frameColor);}
  else{svg+=`<path d="${outline(x,y,w,h,rise)}" fill="${frameColor}"/><path d="${outline(x+border,y+border,w-2*border,h-2*border,Math.max(0,rise-border))}" fill="${glassColor}"/>`;}
  // Mullions terminate below the crown so they do not paint over curved wall corners.
  for(let j=1;j<paneCount;j++)draw(x+border+j*(w-2*border)/paneCount-border*.3,y+border,border*.6,h-2*border-rise);
  for(const transom of o.transomHeightsMetres||[])if(transom>border&&transom<h-rise-border)draw(x+border,y+transom,w-2*border,border*.65,frameColor);
  const grille=o.grille;if(grille){for(const key of ['verticalPitchMetres','horizontalPitchMetres'])if(grille[key]!==undefined&&!(Number.isFinite(grille[key])&&grille[key]>0))throw Error(`Invalid grille pitch on edge ${edge}`);const color=grille.color||frameColor,thick=grille.barWidthMetres??.025;for(let gx=x+border;gx<x+w-border;gx+=grille.verticalPitchMetres??.3)draw(gx,y+border,thick,h-2*border-rise,color);if(grille.horizontalPitchMetres)for(let gy=y+border;gy<y+h-rise-border;gy+=grille.horizontalPitchMetres)draw(x+border,gy,w-2*border,thick,color);}
  if(o.shutters&&!(f.shutterGroups?.length&&y>=3)){const shutter=o.shutters,width=shutter.widthMetres??w*.3,gap=shutter.gapMetres??.05;for(const side of shutter.sides||['left','right']){const left=side==='left'?x-gap-width:x+w+gap;draw(left,y,width,h-rise,shutter.color);for(let yy=y+.22;yy<y+h-rise;yy+=.22)draw(left,yy,width,.025,shutter.jointColor||'#573238');}}
  if(o.brickArch)arch(x,y+h,w,rise,{head:o.head,...o.brickArch});
 }
 function arch(x:number,crown:number,w:number,rise:number,a:any){
  const band=a.bandHeightMetres??.16,arcRise=a.riseMetres??rise,color=a.color||'#a57751',joint=a.jointColor||'#80684e';
  const left=x*sx,top=(height-crown)*sy;
  svg+=`<path d="M ${left} ${top+arcRise*sy} ${a.head==='round'?`A ${w*sx/2} ${arcRise*sy} 0 0 1 ${(x+w)*sx} ${top+arcRise*sy}`:`Q ${(x+w/2)*sx} ${top-arcRise*sy} ${(x+w)*sx} ${top+arcRise*sy}`}" fill="none" stroke="${color}" stroke-width="${band*sy}"/>`;
  const bricks=Math.max(2,Math.min(80,Math.round(w/(a.brickPitchMetres??.2))));
  for(let j=1;j<bricks;j++){const t=j/bricks,theta=Math.PI*(1-t),round=a.head==='round',px=round?x+w/2+w/2*Math.cos(theta):x+w*t,py=round?crown-arcRise+arcRise*Math.sin(theta):crown-arcRise*(1-4*t*(1-t)),slope=(8*arcRise*t-4*arcRise)/w,rx=round?Math.cos(theta)/(w/2):-slope,ry=round?Math.sin(theta)/Math.max(.001,arcRise):1,nx=rx/Math.hypot(rx,ry),ny=ry/Math.hypot(rx,ry);svg+=`<path d="M ${(px-nx*band/2)*sx} ${(height-py-ny*band/2)*sy} L ${(px+nx*band/2)*sx} ${(height-py+ny*band/2)*sy}" stroke="${joint}" stroke-width="${(a.jointWidthMetres??.018)*sx}"/>`;}
 }
 if(f.kind==='corrugated'||f.kind==='industrial-office')for(let x=.3;x<len;x+=f.corrugationPitchMetres??.4)draw(x,f.plinthHeightMetres??0,.035,height-(f.plinthHeightMetres??0),f.corrugationColor||'#909895');
 const ground=f.groundExceptionalBandHeightMetres??3,levels=f.levels??r.levels,pitch=f.floorPitchMetres??((height-ground)/Math.max(1,levels-1));
 if(!f.windowTiers&&!['blank','corrugated','sparse'].includes(f.kind))for(let row=0;row<levels;row++){
 if(f.kind==='commercial-upper'&&row===0)continue;
 const base=f.firstSillMetres!==undefined?f.firstSillMetres+row*pitch:row===0?(f.groundSillMetres??.15):ground+(row-1)*pitch+(f.sillHeightMetres??.5);
 const wh=row===0?(f.groundGroupHeightMetres??Math.min(ground-.3,f.groupHeightMetres??1.8)):(f.groupHeightMetres??1.8),ww=f.groupWidthMetres??2;
 const bay=f.bayPitchMetres??3,start=f.firstBayMetres??.5;
 for(let x=start,b=0;x+ww<len-(f.endMarginMetres??.35);x+=bay,b++){
 if(f.skipEveryNthBay&&((b+1)%f.skipEveryNthBay===0))continue;
 const group=f.alternatingGroups?.[b%f.alternatingGroups.length];win(x,base,group?.widthMetres??ww,group?.heightMetres??wh,group?.panes??panes);
 }
 if(f.floorBands)draw(0,Math.max(0,base-(f.sillHeightMetres??.5)),len,f.floorBandHeightMetres??.2,f.floorBandColor||frame);
 }
 for(const c of f.circularOpenings||[]){const cx=(c.xMetres+c.diameterMetres/2)*sx,cy=(height-c.sillMetres-c.diameterMetres/2)*sy,rx=c.diameterMetres*sx/2,ry=c.diameterMetres*sy/2,b=c.frameWidthMetres??.09;svg+=`<ellipse cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}" fill="${c.frameColor||frame}"/><ellipse cx="${cx}" cy="${cy}" rx="${rx-b*sx}" ry="${ry-b*sy}" fill="${c.glassColor||glass}"/>`;draw(c.xMetres+c.diameterMetres/2-.025,c.sillMetres+.08,.05,c.diameterMetres-.16,frame);draw(c.xMetres+.08,c.sillMetres+c.diameterMetres/2,c.diameterMetres-.16,.045,frame);}
 // Each tier owns its observed cluster rhythm; a cluster may contain separate narrow windows.
 for(const tier of f.windowTiers||[]){let renderedClusters=0;const clusters=tier.clusters||[{widthMetres:tier.widthMetres,openings:[{offsetMetres:0,widthMetres:tier.widthMetres}]}];const pitch=tier.pitchMetres;if(!(pitch>0))throw Error(`windowTiers need positive pitchMetres on edge ${edge}`);for(let x=tier.startMetres??.5,bay=0;x<len-(tier.endMarginMetres??.35)&&bay<(tier.count??1000);x+=pitch,bay++){const cluster=clusters[bay%clusters.length];if(x+cluster.widthMetres>len-(tier.endMarginMetres??.35))break;renderedClusters++;for(const item of cluster.openings||[])opening(x+(item.offsetMetres??0),tier.sillMetres+(item.sillOffsetMetres??0),item.widthMetres,item.heightMetres??tier.heightMetres,{...tier,...item});if(cluster.relievingArch)arch(x,tier.sillMetres+tier.heightMetres+(cluster.relievingArch.crownOffsetMetres??.25),cluster.widthMetres,0,cluster.relievingArch);}if(tier.requiredClusterCount!==undefined&&renderedClusters!==tier.requiredClusterCount)throw Error(`${r.digits} edge ${edge} tier ${tier.sillMetres}m: source requires ${tier.requiredClusterCount} window clusters, but ${renderedClusters} fit; check widths, pitch and end margin`);}
 if(f.sparseWindows)for(const w of f.sparseWindows)win(w.xMetres,w.sillMetres,w.widthMetres,w.heightMetres,w.panes??1);
 for(const door of f.doors||[]){let x=door.xMetres??1,p=door.pitchMetres??len+1;for(;x+(door.widthMetres??1.2)<len;x+=p){const dw=door.widthMetres??1.2,dh=door.heightMetres??ground-.2;draw(x,door.bottomMetres??.1,dw,dh,door.color||'#394447');if(door.kind==='glazed')win(x+.08,.18,dw-.16,dh-.16,door.panes??2);if(door.kind==='loading')for(let y=.4;y<dh;y+=.35)draw(x,y,dw,.025,frame);}}
 for(const assembly of f.glazedAssemblies||[]){win(assembly.xMetres,assembly.sillMetres,assembly.widthMetres,assembly.heightMetres,assembly.panes??2);if(assembly.crossbarMetres)draw(assembly.xMetres,assembly.crossbarMetres,assembly.widthMetres,fw,frame);if(assembly.pierWidthMetres){draw(assembly.xMetres-assembly.pierWidthMetres,0,assembly.pierWidthMetres,height,frame);draw(assembly.xMetres+assembly.widthMetres,0,assembly.pierWidthMetres,height,frame);}}
 for(const entry of f.groundEntries||[]){const y=entry.bottomMetres??.1,w=entry.widthMetres,h=entry.heightMetres,x=entry.xMetres;draw(x,y,w,h,entry.color||frame);if(entry.kind==='glazed'||entry.kind==='screened')opening(x,y,w,h,{...entry,glassColor:entry.kind==='screened'?(entry.glassColor||'#344339'):entry.glassColor});if(entry.kind==='loading')for(let yy=y+.3;yy<y+h;yy+=entry.jointPitchMetres??.35)draw(x,yy,w,.025,entry.jointColor||frame);}
 for(const balcony of f.balconyGroups||[]){const pitch=balcony.pitchMetres??len+1;for(let x=balcony.xMetres??.5,bay=0;x+balcony.widthMetres<=len&&bay<(balcony.count??1000);x+=pitch,bay++){const bottom=balcony.bottomMetres,rail=balcony.railHeightMetres??.9,color=balcony.railColor||frame,bar=balcony.barWidthMetres??.025;draw(x,bottom+rail,balcony.widthMetres,bar,color);for(let xx=x;xx<=x+balcony.widthMetres;xx+=balcony.barPitchMetres??.22)draw(xx,bottom,bar,rail,color);}}
 if(f.topBandHeightMetres)draw(0,height-f.topBandHeightMetres,len,f.topBandHeightMetres,f.topBandColor||frame);
 if(f.horizontalJointPitchMetres)for(let y=f.plinthHeightMetres??0;y<height;y+=f.horizontalJointPitchMetres)draw(0,y,len,.035,f.jointColor||'#b8c0bc');
 if(f.baseVents)for(let x=1;x<len;x+=f.baseVents.pitchMetres)draw(x,f.baseVents.sillMetres,f.baseVents.widthMetres,f.baseVents.heightMetres,f.baseVents.color||'#555d5e');
 if(f.panelSeamPitchMetres)for(let x=f.panelSeamPitchMetres;x<len;x+=f.panelSeamPitchMetres)draw(x,0,.10,height,f.panelSeamColor||'#434b4c');
 for(const band of f.flutedBands||[]){for(let x=band.xMetres??0;x<(band.widthSpanMetres??len);x+=band.pitchMetres??.1)draw(x,band.bottomMetres,band.widthMetres??.025,band.heightMetres,band.color||frame);}
 for(const stripe of f.stripes||[])draw(len*stripe.fraction,stripe.bottomMetres??f.plinthHeightMetres??0,stripe.widthMetres,height-(stripe.bottomMetres??f.plinthHeightMetres??0),stripe.color);
 if(f.lintelBand)draw(0,f.lintelBand.bottomMetres,len,f.lintelBand.heightMetres,f.lintelBand.color||frame);
 // Only source-supported defining real signage is admitted; approximate native sans family is recorded.
 const sign=f.signage||(r.signage?.panelEdge===edge?r.signage:undefined);if(sign){const x=sign.panelStartMetres,w=sign.panelWidthMetres,bottom=sign.bottomMetres,h=sign.heightMetres;draw(x,bottom,w,h,sign.panelColor||wall);const letters=[...sign.text],pitch=sign.letterPitchMetres??1.1,lh=sign.letterHeightMetres??.65,lw=sign.letterWidthMetres??.55,span=(letters.length-1)*pitch+lh,top=bottom+h-(h-span)/2;for(let j=0;j<letters.length;j++){const y=(height-(top-j*pitch))*sy;svg+=`<text x="0" y="0" transform="translate(${(x+w/2)*sx},${y+lh*sy}) scale(${lw*sx/(lh*sy*.75)},1)" text-anchor="middle" fill="${sign.color}" font-family="Arial Narrow, Helvetica Neue, sans-serif" font-weight="400" font-size="${lh*sy}">${letters[j]}</text>`;}}
 return svg;
}
function shape(rings:number[][][]){const s=new T.Shape(rings[0].map(v=>new T.Vector2(v[0],v[1])));for(const hole of rings.slice(1))s.holes.push(new T.Path(hole.map(v=>new T.Vector2(v[0],v[1]))));return s;}
function push(groups:T.BufferGeometry[],g:T.BufferGeometry){groups.push(g.index?g.toNonIndexed():g);}
function inside(point:number[],poly:number[][]){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
function distance(point:number[],poly:number[][]){let best=Infinity;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((point[0]-a[0])*dx+(point[1]-a[1])*dy)/(dx*dx+dy*dy)));best=Math.min(best,Math.hypot(point[0]-a[0]-t*dx,point[1]-a[1]-t*dy));}return best;}
function regions(r:any){return (r.officialRegions||[]).map((reg:any)=>{const ring=reg.ring,poly=ring.map((v:number[])=>[v[0],v[2]]);let normal=new T.Vector3(),best=0;const a=new T.Vector3(...ring[0]);for(let i=1;i<ring.length;i++)for(let j=i+1;j<ring.length;j++){const n=new T.Vector3(...ring[i]).sub(a).cross(new T.Vector3(...ring[j]).sub(a));if(Math.abs(n.y)>best){normal=n;best=Math.abs(n.y);}}if(best<1e-7)throw Error('Degenerate surveyed roof region');const at=(p:number[])=>a.y-(normal.x*(p[0]-a.x)+normal.z*(p[1]-a.z))/normal.y;const interpretation=r.roofInterpretation?.regionOverrides?.find((q:any)=>q.officialRegionIndex===(reg.sourceRegionIndex??(r.officialRegions||[]).indexOf(reg)));if(interpretation?.renderAs==='raised-terrace-deck'&&(!(interpretation.deckThicknessMetres>0)||!(interpretation.lowerEnvelopeMetres>=0)))throw Error('Invalid raised terrace deck dimensions');return{poly,holes:(reg.holes||[]).map((ring:any)=>ring.map((v:any)=>[v[0],v[2]])),at,sourceRegionIndex:reg.sourceRegionIndex,sourceArea:reg.sourceArea,interpretation};});}
function intersectTriangle(poly:number[][],triangle:number[][]){let clipped=poly;const orient=(triangle[1][0]-triangle[0][0])*(triangle[2][1]-triangle[0][1])-(triangle[1][1]-triangle[0][1])*(triangle[2][0]-triangle[0][0]);for(let edge=0;edge<3;edge++){const a=triangle[edge],b=triangle[(edge+1)%3],side=(p:number[])=>Math.sign(orient)*((b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]));let out:number[][]=[];for(let i=0;i<clipped.length;i++){let p=clipped[i],q=clipped[(i+1)%clipped.length],dp=side(p),dq=side(q);if(dp>=-1e-7)out.push(p);if((dp>0)!==(dq>0)){const t=dp/(dp-dq);out.push([p[0]+t*(q[0]-p[0]),p[1]+t*(q[1]-p[1])]);}}clipped=out;if(clipped.length<3)return[];}return clipped;}
const manifest:any={version:1,models:[]};
for(const r of recipes){const start=Date.now(),doc=new Document(),buffer=doc.createBuffer(),scene=doc.createScene(),mesh=doc.createMesh();scene.addChild(doc.createNode(r.digits).setMesh(mesh));
 const polys=(r.footprint.type==='Polygon'?[r.footprint.coordinates]:r.footprint.coordinates).map((poly:any)=>poly.map((ring:any)=>ring.slice(0,-1).map(([lng,lat]:number[])=>[(lng-r.anchor[0])*111320*Math.cos(r.anchor[1]*Math.PI/180),-(lat-r.anchor[1])*111320])));
 let main=r.mainHeight??r.sourceHeight,h=main,wallBase=r.wallBaseHeight??main;const sourceRegions=regions(r);const roofAt=(p:number[])=>{const found=sourceRegions.filter((reg:any)=>inside(p,reg.poly));if(found.length)return Math.max(...found.map((reg:any)=>reg.interpretation?.renderAs==='raised-terrace-deck'?reg.interpretation.lowerEnvelopeMetres:reg.at(p)));if(!sourceRegions.length)return main;const nearest=sourceRegions.reduce((a:any,b:any)=>distance(p,a.poly)<distance(p,b.poly)?a:b);return nearest.interpretation?.renderAs==='raised-terrace-deck'?nearest.interpretation.lowerEnvelopeMetres:nearest.at(p);};const wall:T.BufferGeometry[]=[],roof:T.BufferGeometry[]=[],accent:T.BufferGeometry[]=[];const faces:any[]=[];
 for(const poly of polys){const s=shape(poly);for(let ri=0;ri<poly.length;ri++){let ring=poly[ri],area=ring.reduce((a:number,v:number[],i:number)=>a+v[0]*ring[(i+1)%ring.length][1]-v[1]*ring[(i+1)%ring.length][0],0);for(let i=0;i<ring.length;i++){let a=ring[i],b=ring[(i+1)%ring.length],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);if(len<.3)continue;let normal=[dz/len,-dx/len];if(area<0)normal=normal.map(v=>-v);if(ri>0)normal=normal.map(v=>-v);const index=faces.length;faces.push({a,b,len,normal,edge:i});const edgeRoofAt=(p:number[])=>facadeConfig(r,i).fixedFacadeTopMetres??roofAt(p);
 const g=new T.BufferGeometry(),eps=.018,col=index%4,row=Math.floor(index/4),vertices:number[]=[],uvs:number[]=[],segments=sourceRegions.length?Math.max(1,Math.ceil(len)):1;
 const recesses=facadeConfig(r,i).recessGroups||[];if(recesses.length){
 const stops=Array.from({length:segments+1},(_,j)=>j/segments);for(const c of recesses)stops.push(c.xMetres/len,(c.xMetres+c.widthMetres)/len);stops.sort((a,b)=>a-b);
 for(let segment=0;segment<stops.length-1;segment++){const t=stops[segment],u=stops[segment+1];if(u-t<1e-7)continue;const pa=[a[0]+dx*t,a[1]+dz*t],pb=[a[0]+dx*u,a[1]+dz*u],ha=edgeRoofAt(pa),hb=edgeRoofAt(pb),ys=[0,...recesses.flatMap((c:any)=>[c.bottomMetres,c.bottomMetres+c.heightMetres]),Math.max(ha,hb)].sort((a,b)=>a-b);
 for(let j=0;j<ys.length-1;j++){const low=ys[j],hi=ys[j+1];if(hi-low<1e-7||low>=Math.min(ha,hb))continue;const h0=Math.min(hi,ha),h1=Math.min(hi,hb),midX=(t+u)*len/2,midY=(low+Math.min(h0,h1))/2,c=recesses.find((c:any)=>midX>c.xMetres&&midX<c.xMetres+c.widthMetres&&midY>c.bottomMetres&&midY<c.bottomMetres+c.heightMetres),d=c?-c.depthMetres:eps;
 const points=[[pa[0]+normal[0]*d,low,pa[1]+normal[1]*d],[pb[0]+normal[0]*d,low,pb[1]+normal[1]*d],[pb[0]+normal[0]*d,h1,pb[1]+normal[1]*d],[pa[0]+normal[0]*d,h0,pa[1]+normal[1]*d]],tex=[[col/4+t/4,row+1-low/main],[col/4+u/4,row+1-low/main],[col/4+u/4,row+1-h1/main],[col/4+t/4,row+1-h0/main]];for(const v of area>0?[0,2,1,0,3,2]:[0,1,2,0,2,3]){vertices.push(...points[v]);uvs.push(...tex[v]);}}
 }
 }else{
 for(let segment=0;segment<segments;segment++){const t=segment/segments,u=(segment+1)/segments,pa=[a[0]+dx*t,a[1]+dz*t],pb=[a[0]+dx*u,a[1]+dz*u],ha=edgeRoofAt(pa),hb=edgeRoofAt(pb);const points=[[pa[0]+normal[0]*eps,0,pa[1]+normal[1]*eps],[pb[0]+normal[0]*eps,0,pb[1]+normal[1]*eps],[pb[0]+normal[0]*eps,hb,pb[1]+normal[1]*eps],[pa[0]+normal[0]*eps,ha,pa[1]+normal[1]*eps]],tex=[[col/4+t/4,row+1],[col/4+u/4,row+1],[col/4+u/4,row+1-Math.min(1,hb/main)],[col/4+t/4,row+1-Math.min(1,ha/main)]];for(const v of area>0?[0,2,1,0,3,2]:[0,1,2,0,2,3]){vertices.push(...points[v]);uvs.push(...tex[v]);}}
 }
 g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));g.computeVertexNormals();push(wall,g);
 const box=(x:number,y:number,width:number,thick:number,depth:number)=>{const geo=new T.BoxGeometry(width,thick,depth);geo.rotateY(-Math.atan2(dz,dx));geo.translate(a[0]+dx/len*x+normal[0]*depth*.5,y,a[1]+dz/len*x+normal[1]*depth*.5);push(accent,geo);};
 const f=facadeConfig(r,i);
 if(f.fins){const fin=f.fins;for(let x=fin.firstMetres??.2;x<len;x+=fin.pitchMetres??f.bayPitchMetres)box(x,(fin.bottomMetres??0)+(fin.heightMetres??main)/2,fin.widthMetres??.12,fin.heightMetres??main,fin.depthMetres??.3);}

 // Source-defined physical bands, curved revolving entries, and original low relief silhouettes.
 for(const c of f.physicalBands||[])box(len/2,c.bottomMetres+c.heightMetres/2,len,c.heightMetres,c.depthMetres);
 for(const c of f.revolvingEntries||[]){const v:number[]=[],tex:number[]=[];const point=(x:number,y:number,d:number)=>[a[0]+dx/len*x+normal[0]*d,y,a[1]+dz/len*x+normal[1]*d];for(let k=0;k<12;k++){const t=k/12,u=(k+1)/12,x0=c.xMetres+c.widthMetres*t,x1=c.xMetres+c.widthMetres*u,d0=.04+c.depthMetres*Math.sin(t*Math.PI),d1=.04+c.depthMetres*Math.sin(u*Math.PI),y0=c.bottomMetres,y1=y0+c.heightMetres;for(const [x,y,d]of [[x0,y0,d0],[x1,y0,d1],[x1,y1,d1],[x0,y0,d0],[x1,y1,d1],[x0,y1,d0]]){v.push(...point(x,y,d));tex.push(col/4+x/len/4,row+1-y/main);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setAttribute('uv',new T.Float32BufferAttribute(tex,2));g.computeVertexNormals();push(wall,g);}
 for(const c of f.sculpturalReliefs||[]){const silhouette=new T.Shape(c.outline.map(([x,y]:number[])=>new T.Vector2((c.mirror?1-x:x)*c.widthMetres,y*c.heightMetres))),geo=new T.ExtrudeGeometry(silhouette,{depth:c.depthMetres,bevelEnabled:false,steps:1});const tangent=new T.Vector3(dx/len,0,dz/len),up=new T.Vector3(0,1,0),out=new T.Vector3(normal[0],0,normal[1]);const matrix=new T.Matrix4().makeBasis(tangent,up,out);geo.applyMatrix4(matrix);geo.translate(a[0]+dx/len*c.xMetres+normal[0]*.04,c.bottomMetres,a[1]+dz/len*c.xMetres+normal[1]*.04);push(accent,geo);for(const [cx,cy,rx,ry]of c.carvedLobes||[]){const lobe=new T.SphereGeometry(1,7,4);lobe.scale(rx*c.widthMetres,ry*c.heightMetres,.09);lobe.applyMatrix4(matrix);lobe.translate(a[0]+dx/len*(c.xMetres+(c.mirror?1-cx:cx)*c.widthMetres)+normal[0]*(c.depthMetres+.06),c.bottomMetres+cy*c.heightMetres,a[1]+dz/len*(c.xMetres+(c.mirror?1-cx:cx)*c.widthMetres)+normal[1]*(c.depthMetres+.06));push(accent,lobe);}}
 if(f.canopy){const c=f.canopy;box(len/2,c.bottomMetres+c.heightMetres/2,len,c.heightMetres,c.depthMetres);}
 for(const c of f.canopyGroups||[]){const pitch=c.pitchMetres??len+1;for(let x=c.xMetres??0,bay=0;x+c.widthMetres<=len&&bay<(c.count??1000);x+=pitch,bay++)box(x+c.widthMetres/2,c.bottomMetres+c.heightMetres/2,c.widthMetres,c.heightMetres,c.depthMetres);}
 for(const c of f.balconyGroups||[]){const pitch=c.pitchMetres??len+1;for(let x=c.xMetres??.5,bay=0;x+c.widthMetres<=len&&bay<(c.count??1000);x+=pitch,bay++){const thick=c.slabHeightMetres??.12;box(x+c.widthMetres/2,c.bottomMetres-thick/2,c.widthMetres,thick,c.depthMetres??.35);}}
 // Opt-in physical open shutters use the original facade atlas color and horizontal plank marks.
 for(const c of f.shutterGroups||[]){for(const side of [-1,1]){const hinge=c.xMetres+(side>0?c.openingWidthMetres:0),angle=(c.openAngleDegrees??55)*Math.PI/180,w=c.widthMetres,uvx=(c.xMetres+(side<0?-w/2-.05:c.openingWidthMetres+w/2+.05))/len,point=(d:number,y:number,depth:number)=>[a[0]+dx/len*(hinge+side*d*Math.cos(angle))+normal[0]*depth,y,a[1]+dz/len*(hinge+side*d*Math.cos(angle))+normal[1]*depth],bottom=c.bottomMetres,top=bottom+c.heightMetres,vertices=[point(0,bottom,.04),point(w,bottom,w*Math.sin(angle)+.04),point(w,top,w*Math.sin(angle)+.04),point(0,top,.04)],g=new T.BufferGeometry(),positions:number[]=[],uv:number[]=[];for(const j of [0,1,2,0,2,3]){positions.push(...vertices[j]);uv.push(.5,Math.ceil(faces.length/4)+1-(j<2?bottom:top)/main);}g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.computeVertexNormals();push(wall,g);}}
 // Pale stone coping follows each fitted street gable rather than adding a full-depth roof.
 if(f.gableTrim){const segments=Math.max(1,Math.ceil(len/.25));for(let j=0;j<segments;j++){const x0=len*j/segments,x1=len*(j+1)/segments,p0=[a[0]+dx*x0/len,a[1]+dz*x0/len],p1=[a[0]+dx*x1/len,a[1]+dz*x1/len],y0=edgeRoofAt(p0),y1=edgeRoofAt(p1),length=Math.hypot(x1-x0,y1-y0),g=new T.BoxGeometry(length,.13,.17);const tangent=new T.Vector3(dx/len*(x1-x0),y1-y0,dz/len*(x1-x0)).normalize(),depth=new T.Vector3(normal[0],0,normal[1]),up=depth.clone().cross(tangent).normalize();if(up.y<0)up.negate();g.applyMatrix4(new T.Matrix4().makeBasis(tangent,up,depth));g.translate((p0[0]+p1[0])/2+normal[0]*.035,(y0+y1)/2+.06,(p0[1]+p1[1])/2+normal[1]*.035);push(accent,g);}}
 // Photographic dark rounded roof cap stays confined to the measured dominant low roof edges.
 if(f.roundedCap){const c=f.roundedCap,parts=Math.max(1,Math.ceil(len/.35));for(let j=0;j<parts;j++){const t=j/parts,u=(j+1)/parts,pa=[a[0]+dx*t,a[1]+dz*t],pb=[a[0]+dx*u,a[1]+dz*u],ha=edgeRoofAt(pa),hb=edgeRoofAt(pb);if(Math.min(ha,hb)<c.minTopMetres||Math.max(ha,hb)>c.maxTopMetres)continue;const points=(p:number[],h:number,k:number)=>{const theta=k/4*Math.PI/2;return[p[0]+normal[0]*(.03-c.depthMetres*(1-Math.cos(theta))),h-c.heightMetres*(1-Math.sin(theta)),p[1]+normal[1]*(.03-c.depthMetres*(1-Math.cos(theta)))];},g=new T.BufferGeometry(),v:number[]=[];for(let k=0;k<4;k++)for(const p of [points(pa,ha,k),points(pb,hb,k),points(pb,hb,k+1),points(pa,ha,k),points(pb,hb,k+1),points(pa,ha,k+1)])v.push(...p);g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.computeVertexNormals();push(roof,g);}}
 // Shallow source-supported bay stacks retain the facade atlas on their first-hit front.
 for(const c of f.projectionGroups||[]){const pitch=c.pitchMetres??len+1;for(let x=c.xMetres??0,bay=0;x+c.widthMetres<=len&&bay<(c.count??1000);x+=pitch,bay++){if(!(c.depthMetres>0&&c.heightMetres>0&&c.widthMetres>0&&c.bottomMetres>=0&&c.bottomMetres+c.heightMetres<=Math.min(edgeRoofAt(a),edgeRoofAt(b))))throw Error(`Invalid facade projection on edge ${i}`);box(x+c.widthMetres/2,c.bottomMetres+c.heightMetres/2,c.widthMetres,c.heightMetres,c.depthMetres);const point=(offset:number,y:number)=>[a[0]+dx/len*offset+normal[0]*(c.depthMetres+.02),y,a[1]+dz/len*offset+normal[1]*(c.depthMetres+.02)],v=[point(x,c.bottomMetres),point(x+c.widthMetres,c.bottomMetres),point(x+c.widthMetres,c.bottomMetres+c.heightMetres),point(x,c.bottomMetres+c.heightMetres)],tex=[[col/4+x/len/4,row+1-c.bottomMetres/main],[col/4+(x+c.widthMetres)/len/4,row+1-c.bottomMetres/main],[col/4+(x+c.widthMetres)/len/4,row+1-(c.bottomMetres+c.heightMetres)/main],[col/4+x/len/4,row+1-(c.bottomMetres+c.heightMetres)/main]],g=new T.BufferGeometry(),positions:number[]=[],uv:number[]=[];for(const j of (-dz*normal[0]+dx*normal[1]<0?[0,2,1,0,3,2]:[0,1,2,0,2,3])){positions.push(...v[j]);uv.push(...tex[j]);}g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.computeVertexNormals();push(wall,g);}}


 }}
 if(sourceRegions.length){
 // Triangulate simple native and survey polygons, intersect in plan, then apply each fitted roof plane.
 const native=upwardRoofPlane(s,0).toNonIndexed().getAttribute('position'),values:number[]=[];
 for(const region of sourceRegions){const surveyed=upwardRoofPlane(shape([region.poly,...region.holes]),0).toNonIndexed().getAttribute('position');for(let n=0;n<native.count;n+=3){const tri=[0,1,2].map(j=>[native.getX(n+j),native.getZ(n+j)]);for(let q=0;q<surveyed.count;q+=3){const from=[0,1,2].map(j=>[surveyed.getX(q+j),surveyed.getZ(q+j)]),hit=intersectTriangle(from,tri);for(let j=1;j<hit.length-1;j++)for(const p of [hit[0],hit[j],hit[j+1]])values.push(p[0],region.at(p),p[1]);}}}
 const roofGeo=new T.BufferGeometry();roofGeo.setAttribute('position',new T.Float32BufferAttribute(values,3));roofGeo.computeVertexNormals();push(roof,roofGeo);
 // Source region boundaries enclose real roof-height steps, including the tall box's low strip.
 for(const region of sourceRegions){if((r.roofObjectAssemblies||[]).some((g:any)=>g.recipeRegionIndices.includes(sourceRegions.indexOf(region))))continue;const side:number[]=[],sideUvs:number[]=[];for(let i=0;i<region.poly.length;i++){const a=region.poly[i],b=region.poly[(i+1)%region.poly.length],length=Math.hypot(b[0]-a[0],b[1]-a[1]),parts=Math.max(1,Math.ceil(length));for(let j=0;j<parts;j++){const t=j/parts,u=(j+1)/parts,pa=[a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])],pb=[a[0]+u*(b[0]-a[0]),a[1]+u*(b[1]-a[1])],mid=[(pa[0]+pb[0])/2,(pa[1]+pb[1])/2];if(!inside(mid,poly[0])||distance(mid,poly[0])<.4||poly.slice(1).some((hole:number[][])=>inside(mid,hole)))continue;const ha=region.at(pa),hb=region.at(pb);let ba=wallBase,bb=wallBase;if(region.interpretation?.renderAs==='raised-terrace-deck'){ba=ha-region.interpretation.deckThicknessMetres;bb=hb-region.interpretation.deckThicknessMetres;}else if(r.exposedRoofSteps){const area=region.poly.reduce((sum:number,p:number[],k:number)=>sum+p[0]*region.poly[(k+1)%region.poly.length][1]-p[1]*region.poly[(k+1)%region.poly.length][0],0),sign=area>0?1:-1,dx=b[0]-a[0],dz=b[1]-a[1],outside=[mid[0]+sign*dz/length*.04,mid[1]-sign*dx/length*.04],neighbor=sourceRegions.filter((q:any)=>q!==region&&inside(outside,q.poly));if(neighbor.length){ba=Math.max(...neighbor.map((q:any)=>q.interpretation?.renderAs==='raised-terrace-deck'?q.interpretation.lowerEnvelopeMetres:q.at(pa)));bb=Math.max(...neighbor.map((q:any)=>q.interpretation?.renderAs==='raised-terrace-deck'?q.interpretation.lowerEnvelopeMetres:q.at(pb)));}if((ha+hb-ba-bb)/2<.15)continue;ba=Math.min(ba,ha);bb=Math.min(bb,hb);}side.push(pa[0],ba,pa[1],pb[0],bb,pb[1],pb[0],hb,pb[1],pa[0],ba,pa[1],pb[0],hb,pb[1],pa[0],ha,pa[1]);if(r.roofStepGlazing){const corner=r.roofStepGlazing.lowerCornerAssembly,cornerSupported=corner&&corner.regionIndices.includes(region.sourceRegionIndex)&&mid[0]>=corner.boundsXZ[0]&&mid[0]<=corner.boundsXZ[2]&&mid[1]>=corner.boundsXZ[1]&&mid[1]<=corner.boundsXZ[3],glazed=r.roofStepGlazing.regionIndices.includes(region.sourceRegionIndex)||cornerSupported,technical=(r.roofStepGlazing.darkTechnicalRegionIndices||[]).includes(region.sourceRegionIndex),swatchRow=Math.ceil(faces.length/4);for(const [x,y]of [[t*length,ba],[u*length,bb],[u*length,hb],[t*length,ba],[u*length,hb],[t*length,ha]])sideUvs.push(glazed?Math.min(.9,x/16):technical?.98:0,glazed?swatchRow+1-y/main:technical?swatchRow+.5:0);}}}if(side.length){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(side,3));if(r.roofStepGlazing)g.setAttribute('uv',new T.Float32BufferAttribute(sideUvs,2));g.computeVertexNormals();push(wall,g);}}

 // Opt-in source-curated thin decks retain surveyed tops without invented opaque support boxes.
 for(const region of sourceRegions.filter((q:any)=>q.interpretation?.renderAs==='raised-terrace-deck')){const c=region.interpretation,deckShape=shape([region.poly]);push(roof,upwardRoofPlane(deckShape,c.lowerEnvelopeMetres));const bottom=upwardRoofPlane(deckShape,0).toNonIndexed(),bp=bottom.getAttribute('position');for(let j=0;j<bp.count;j++)bp.setY(j,region.at([bp.getX(j),bp.getZ(j)])-c.deckThicknessMetres);const undersideValues:number[]=[];for(let j=0;j<bp.count;j+=3)for(const k of [0,2,1])undersideValues.push(bp.getX(j+k),bp.getY(j+k),bp.getZ(j+k));const underside=new T.BufferGeometry();underside.setAttribute('position',new T.Float32BufferAttribute(undersideValues,3));underside.computeVertexNormals();push(accent,underside);
 if(c.railingHeightMetres){for(let j=0;j<region.poly.length;j++){const a=region.poly[j],b=region.poly[(j+1)%region.poly.length],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz),mid=[(a[0]+b[0])/2,(a[1]+b[1])/2];if((r.regionFacadeAssemblies||[]).some((f:any)=>f.segmentsXZ.some(([u,v]:number[][])=>{const vx=v[0]-u[0],vz=v[1]-u[1],t=Math.max(0,Math.min(1,((mid[0]-u[0])*vx+(mid[1]-u[1])*vz)/(vx*vx+vz*vz)));return Math.hypot(mid[0]-u[0]-t*vx,mid[1]-u[1]-t*vz)<.3;})))continue;const box=(x:number,y:number,w:number,h:number)=>{const g=new T.BoxGeometry(w,h,.035);g.rotateY(-Math.atan2(dz,dx));g.translate(a[0]+dx*x/len,y,a[1]+dz*x/len);push(accent,g);};for(let k=0;k<Math.ceil(len/.5);k++){const x0=len*k/Math.ceil(len/.5),x1=len*(k+1)/Math.ceil(len/.5),x=(x0+x1)/2,top=region.at([a[0]+dx*x/len,a[1]+dz*x/len]);box(x,top+c.railingHeightMetres,x1-x0,.035);for(const h of [.33,.66])box(x,top+h,x1-x0,.018);}for(let x=.1;x<len;x+=2)box(x,region.at([a[0]+dx*x/len,a[1]+dz*x/len])+c.railingHeightMetres/2,.04,c.railingHeightMetres);}}
 }
 // Thin survey/native perimeter disagreement is covered by a dark low roof layer, below all supported planes.
 push(roof,upwardRoofPlane(s,wallBase-.015));
 }else if(r.roofProfile?.type==='gable'){
 const ring=poly[0],profile=r.roofProfile;let length=0,axis=new T.Vector2();for(let j=0;j<ring.length;j++){const a=ring[j],b=ring[(j+1)%ring.length],len=Math.hypot(b[0]-a[0],b[1]-a[1]);if(len>length){length=len;axis.set(-(b[1]-a[1])/len,(b[0]-a[0])/len);}}
 const vals=ring.map((v:number[])=>v[0]*axis.x+v[1]*axis.y),low=Math.min(...vals),high=Math.max(...vals),mid=(low+high)/2;
 const alt=(v:number[])=>main+(profile.ridgeHeightMetres-main)*(1-Math.abs((v[0]*axis.x+v[1]*axis.y-mid)/(high-low)*2));
 function clipHalf(polygon:number[][],sign:number){let out:number[][]=[];for(let j=0;j<polygon.length;j++){const a=polygon[j],b=polygon[(j+1)%polygon.length],da=sign*(a[0]*axis.x+a[1]*axis.y-mid),db=sign*(b[0]*axis.x+b[1]*axis.y-mid);if(da>=-1e-6)out.push(a);if((da>0)!==(db>0)){let t=da/(da-db);out.push([a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])]);}}return out;}
 for(const sign of [-1,1]){const half=clipHalf(ring,sign),geo=upwardRoofPlane(shape([half]),0).toNonIndexed(),p=geo.getAttribute('position');for(let j=0;j<p.count;j++)p.setY(j,alt([p.getX(j),p.getZ(j)]));geo.computeVertexNormals();push(roof,geo);}
 // Native perimeter gables fill above the eaves; roof owns its top.
 for(let j=0;j<ring.length;j++){const a=ring[j],b=ring[(j+1)%ring.length],da=a[0]*axis.x+a[1]*axis.y-mid,db=b[0]*axis.x+b[1]*axis.y-mid,stops=[0,1];if(da*db<0)stops.push(da/(da-db));stops.sort((a,b)=>a-b);let values:number[]=[];for(let q=0;q<stops.length-1;q++){const at=(t:number)=>[a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])],p=at(stops[q]),c=at(stops[q+1]);values.push(p[0],main,p[1],c[0],main,c[1],c[0],alt(c),c[1],p[0],main,p[1],c[0],alt(c),c[1],p[0],alt(p),p[1]);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(values,3));geo.computeVertexNormals();push(wall,geo);}
 h=profile.ridgeHeightMetres;
 }else push(roof,upwardRoofPlane(s,main));
 if(r.roofPanelGrid){const grid=r.roofPanelGrid,a=poly[0][0],b=poly[0][1],d=poly[0][3],at=(u:number,v:number)=>[a[0]+u*(b[0]-a[0])+v*(d[0]-a[0]),a[1]+u*(b[1]-a[1])+v*(d[1]-a[1])];for(let i=0;i<grid.columns;i++)for(let j=0;j<grid.rows;j++){const panelShape=shape([[at((i+.06)/grid.columns,(j+.06)/grid.rows),at((i+.94)/grid.columns,(j+.06)/grid.rows),at((i+.94)/grid.columns,(j+.94)/grid.rows),at((i+.06)/grid.columns,(j+.94)/grid.rows)]]),sides=openTopPrism(panelShape,main,main+grid.reliefMetres),sp=sides.getAttribute('position'),sn=sides.getAttribute('normal'),kept:number[]=[];for(let k=0;k<sp.count;k+=3){if(sn.getY(k)<-.9)continue;for(let t=0;t<3;t++)kept.push(sp.getX(k+t),sp.getY(k+t),sp.getZ(k+t));}const sideGeo=new T.BufferGeometry();sideGeo.setAttribute('position',new T.Float32BufferAttribute(kept,3));sideGeo.computeVertexNormals();push(roof,sideGeo);push(roof,upwardRoofPlane(panelShape,main+grid.reliefMetres));}}

 }

 // Explicit source-faced interior roof-step assemblies. The surveyed step owns its wall;
 // this outward overlay supplies original facade pixels only on admitted source segments.
 for(const assembly of r.regionFacadeAssemblies||[])for(const [a,b]of assembly.segmentsXZ){const dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz),normal=[-dz/len,dx/len],region=sourceRegions[assembly.officialRegionIndex];if(!region)throw Error('Missing source region for interior facade');const topA=region.at(a),topB=region.at(b),bottom=assembly.bottomMetres??Math.min(...assembly.approximateTierSillsMetres)-.6,index=faces.length,col=index%4,row=Math.floor(index/4),f={kind:assembly.kind,levels:0,wallColor:assembly.wallColor,frameColor:assembly.frameColor,glassColor:assembly.glassColor,frameWidthMetres:.08,windowTiers:assembly.approximateTierSillsMetres.map((sill:number)=>({sillMetres:sill,heightMetres:assembly.openingHeightMetres,startMetres:.12,pitchMetres:assembly.bayPitchMetres,widthMetres:assembly.openingWidthMetres,panes:1,endMarginMetres:.05})),flutedBands:assembly.approximateTierSillsMetres.map((sill:number)=>({bottomMetres:sill+assembly.openingHeightMetres,heightMetres:assembly.spandrelTopHeightMetres,pitchMetres:.09,widthMetres:.025,color:'#8e8a7c'}))};faces.push({a,b,len,normal,edge:index,customFacade:f});const point=(x:number,y:number)=>[a[0]+dx*x/len+normal[0]*.055,y,a[1]+dz*x/len+normal[1]*.055],g=new T.BufferGeometry(),verts=[point(0,bottom),point(len,bottom),point(len,topB),point(0,topA)],v:number[]=[],uv:number[]=[];for(const j of [0,1,2,0,2,3]){v.push(...verts[j]);uv.push(col/4+(j===1||j===2?1:0)/4,row+1-verts[j][1]/main);}g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.computeVertexNormals();push(wall,g);
 const rail=assembly.balconyOrTerraceRailing;if(rail){const box=(x:number,y:number,width:number,height:number,depth:number,offset=.5)=>{const geo=new T.BoxGeometry(width,height,depth);geo.rotateY(-Math.atan2(dz,dx));geo.translate(a[0]+dx*x/len+normal[0]*offset,y,a[1]+dz*x/len+normal[1]*offset);push(accent,geo);};box(len/2,rail.bottomMetres+rail.heightMetres,len,.045,.045);for(let y=.33;y<rail.heightMetres;y+=.33)box(len/2,rail.bottomMetres+y,len,.018,.018);for(let x=.12;x<len;x+=rail.postsPitchMetres)box(x,rail.bottomMetres+rail.heightMetres/2,.045,rail.heightMetres,.045);}
 }
 const hasPhysicalShutters=faces.some(f=>(facadeConfig(r,f.edge).shutterGroups||[]).length),rows=Math.ceil(faces.length/4)+(hasPhysicalShutters||r.roofStepGlazing?1:0),atlasParts=faces.map((f,i)=>({input:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="256">${face(f.customFacade?{...r,facade:f.customFacade}:r,f.len,f.edge,main)}</svg>`),left:i%4*512,top:Math.floor(i/4)*256}));if(hasPhysicalShutters){let shutterSvg=rect(0,0,2048,256,r.sourceColors?.shutters||'#713e43');for(let y=0;y<main;y+=.22)shutterSvg+=rect(0,(main-y)/main*256,2048,.025/main*256,'#573238');atlasParts.push({input:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="2048" height="256">${shutterSvg}</svg>`),left:0,top:(rows-1)*256});}if(r.roofStepGlazing){const W=2048,H=256,sx=W/16,sy=H/main;let stepSvg=rect(0,0,W,H,r.wall);for(let x=.3;x<14;x+=2.3){const bottom=r.roofStepGlazing.bottomMetres,h=r.roofStepGlazing.heightMetres,width=1.65,fw=.11;stepSvg+=rect(x*sx,(main-bottom-h)*sy,width*sx,h*sy,r.palette.frames);for(let pane=0;pane<2;pane++)stepSvg+=rect((x+fw+pane*(width-2*fw)/2)*sx,(main-bottom-h+fw)*sy,((width-2*fw)/2-.035)*sx,(h-2*fw)*sy,r.palette.glass);}const corner=r.roofStepGlazing.lowerCornerAssembly;if(corner){for(let x=.3;x<14;x+=2.3){const bottom=corner.bottomMetres,h=corner.heightMetres,width=1.65,fw=.11;stepSvg+=rect(x*sx,(main-bottom-h)*sy,width*sx,h*sy,r.palette.frames);for(let pane=0;pane<2;pane++)stepSvg+=rect((x+fw+pane*(width-2*fw)/2)*sx,(main-bottom-h+fw)*sy,((width-2*fw)/2-.035)*sx,(h-2*fw)*sy,r.palette.glass);}stepSvg+=rect(0,(main-corner.capBottomMetres-corner.capHeightMetres)*sy,W,corner.capHeightMetres*sy,'#454e50');}stepSvg+=rect(W*.95,0,W*.05,H,'#454e50');atlasParts.push({input:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="2048" height="256">${stepSvg}</svg>`),left:0,top:(rows-1)*256});}const png=await sharp({create:{width:2048,height:rows*256,channels:4,background:r.wall}}).composite(atlasParts).png().toBuffer();const texture=doc.createTexture('original-source-informed-facade-atlas').setImage(png).setMimeType('image/png');
 const material=doc.createMaterial('facade').setMetallicFactor(0).setBaseColorTexture(texture).setRoughnessFactor(.9).setDoubleSided(true),roofmat=doc.createMaterial('roof').setMetallicFactor(0).setBaseColorFactor(rgba(r.roof)).setRoughnessFactor(1),accentmat=doc.createMaterial('slabs-fins').setMetallicFactor(0).setBaseColorFactor(rgba(r.palette.balcony||r.palette.frames)).setRoughnessFactor(.9);let triangles=0,bmin=[Infinity,Infinity,Infinity],bmax=[-Infinity,-Infinity,-Infinity];
 for(const [geos,mat] of [[wall,material],[roof,roofmat],[accent,accentmat]] as const){if(!geos.length)continue;let positions:number[]=[],normals:number[]=[],uv:number[]=[];for(const g of geos){let p=g.getAttribute('position'),n=g.getAttribute('normal'),tex=g.getAttribute('uv');for(let i=0;i<p.count;i++){let xyz=[p.getX(i),p.getY(i),p.getZ(i)];positions.push(...xyz);normals.push(n.getX(i),n.getY(i),n.getZ(i));for(let j=0;j<3;j++){bmin[j]=Math.min(bmin[j],xyz[j]);bmax[j]=Math.max(bmax[j],xyz[j]);} // shell invisible behind atlas: use a wall-color pixel at atlas border
 uv.push(tex?tex.getX(i):0,tex?(geos===wall?tex.getY(i)/rows:Math.max(0,Math.min(1,tex.getY(i)))):0);}}
 const primitive=doc.createPrimitive().setAttribute('POSITION',doc.createAccessor().setType('VEC3').setArray(new Float32Array(positions)).setBuffer(buffer)).setAttribute('NORMAL',doc.createAccessor().setType('VEC3').setArray(new Float32Array(normals)).setBuffer(buffer)).setMaterial(mat);if(geos===wall)primitive.setAttribute('TEXCOORD_0',doc.createAccessor().setType('VEC2').setArray(new Float32Array(uv)).setBuffer(buffer));mesh.addPrimitive(primitive);triangles+=positions.length/9;}
 const bytes=await new NodeIO().writeBinary(doc);await fs.writeFile(`${output}/${r.digits}.glb`,bytes);const refDir=`${data}/references/${r.digits}`;await fs.mkdir(refDir,{recursive:true});const referenceImages=[];for(const name of r.references.slice(0,4)){await fs.copyFile(path.join(sourceRoot,r.sourcePack,'processed',name),`${refDir}/${name}`);referenceImages.push(`./ordinary-buildings-data/references/${r.digits}/${name}`);}
 const simplifications=r.simplifications||['Original procedural atlas replaces physical small mullions; source-specific physical group dimensions and face exceptions retained.','Tiny signs, interiors, rail bars and rooftop equipment omitted.'];
 manifest.models.push({id:`ordinary-${r.digits}`,category:'ordinary',buildingId:r.id,name:r.label,anchor:r.anchor,cameraBearing:r.cameraBearing,footprint:r.footprint,height:bmax[1],modelUrl:`./models/ordinary-buildings/${r.digits}.glb`,bounds:{min:bmin,max:bmax},triangles,bytes:bytes.length,materials:mesh.listPrimitives().length,hash:crypto.createHash('sha256').update(bytes).digest('hex'),referenceImages,sourcePack:r.sourcePack,sourceUrls:r.sourceUrls??[],traits:r.traits,simplifications,sourceTiming:r.timing,heightEvidence:r.heightEvidence,facadeRecipe:r.facade,official3D:r.official3D,...(r.galleryFrontage?{galleryFrontage:r.galleryFrontage}:{}),...(r.gallerySecondary?{gallerySecondary:r.gallerySecondary}:{}),generationMilliseconds:Date.now()-start,reviewState:'pending independent gallery/live-game visual review'});await fs.writeFile(`${data}/catalogue.json`,JSON.stringify(manifest,null,2));console.log(r.digits,bytes.length,triangles);
}
