import {EXTMeshoptCompression,ALL_EXTENSIONS} from '@gltf-transform/extensions';import {MeshoptEncoder,MeshoptDecoder} from 'meshoptimizer';import fs from 'node:fs/promises';import crypto from 'node:crypto';import * as T from 'three';import {weld,dedup,prune} from '@gltf-transform/functions';import {Document,NodeIO} from '@gltf-transform/core';import {exactIndexDocument} from './exact-index.mjs';import type {BuildingTools} from '../landmarks/cultural-builders';import {buildNieuwespiegel555,probes} from './nieuwespiegel555-builder';import spec from './nieuwespiegel555-spec.json';
const out=process.env.ORDINARY_OUTPUT_ROOT||'artifacts/ordinary-buildings/nieuwespiegel555',palette:any={brick:'#824b41',historicBrick:'#69564d',insetBrick:'#825747',stone:'#b6b8a8',white:'#dbdfce',glass:'#547b87',frame:'#344c50',iron:'#3b4340',slate:'#626465',roof:'#6f7372',joint:'#92968e',floor:'#979b91',solar:'#45565e',solarFrame:'#a3aeb0'};
const parts:{g:T.BufferGeometry;c:string}[]=[];buildNieuwespiegel555(0,0,{add(g:T.BufferGeometry,c:string,x=0,y=0,z=0,a=0){g.rotateY(a);g.translate(x,y,z);parts.push({g,c});}} as BuildingTools);
console.log(Object.fromEntries([...new Set(parts.map(p=>p.c))].map(c=>[c,parts.filter(p=>p.c===c).reduce((s,p)=>s+(p.g.index?.count??p.g.attributes.position.count)/3,0)])));const doc=new Document(),buffer=doc.createBuffer(),scene=doc.createScene(spec.digits),mesh=doc.createMesh(spec.digits);scene.addChild(doc.createNode(spec.digits).setMesh(mesh));doc.getRoot().setDefaultScene(scene);
for(const group of['physical','glass']){const positions:number[]=[],normals:number[]=[],colors:number[]=[];for(const part of parts.filter(p=>(p.c==='glass')===(group==='glass'))){const g=part.g.index?part.g.toNonIndexed():part.g,p=g.getAttribute('position'),n=g.getAttribute('normal'),color=new T.Color(palette[part.c]);for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2);if(b.sub(a).cross(c.sub(a)).length()<1e-6)continue;if([0,1,2].every(j=>n.getY(i+j)<-.999)&&!['stone','slate','white'].includes(part.c))continue;for(let j=0;j<3;j++){positions.push(p.getX(i+j),p.getY(i+j),p.getZ(i+j));normals.push(...[n.getX(i+j),n.getY(i+j),n.getZ(i+j)].map(v=>Math.round(v*10000)/10000));colors.push(...color.toArray().map(v=>Math.round(v*255)));}}}
 const m=doc.createMaterial(group).setBaseColorFactor([1,1,1,1]).setMetallicFactor(0).setRoughnessFactor(group==='glass'?.45:.94).setDoubleSided(false),p=doc.createPrimitive().setMaterial(m);
 for(const[name,type,array,norm]of[['POSITION','VEC3',new Float32Array(positions),false],['NORMAL','VEC3',new Float32Array(normals),false],['COLOR_0','VEC3',new Uint8Array(colors),true]] as const)p.setAttribute(name,doc.createAccessor().setType(type).setArray(array).setNormalized(norm).setBuffer(buffer));mesh.addPrimitive(p);
}
const indexProof=exactIndexDocument(doc);await doc.transform(weld({tolerance:1e-5}),dedup(),prune());await MeshoptEncoder.ready;doc.createExtension(EXTMeshoptCompression).setRequired(true).setEncoderOptions({method:EXTMeshoptCompression.EncoderMethod.QUANTIZE});const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder,'meshopt.decoder':MeshoptDecoder}),bytes=await io.writeBinary(doc),hash=crypto.createHash('sha256').update(bytes).digest('hex');let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity],triangles=0;for(const p of mesh.listPrimitives()){triangles+=p.getIndices()!.getCount()/3;const v=p.getAttribute('POSITION')!.getArray()!;for(let i=0;i<v.length;i++){min[i%3]=Math.min(min[i%3],v[i]);max[i%3]=Math.max(max[i%3],v[i]);}}
const sourceCommit='087986cc828b344e55303764e680ef2d9d4101f8',sourcePath='experiments/canal-belt-continuation-20261007/next-large-box-source-26-followup/0363100012167897';
const references=['./ordinary-buildings-data/references/'+spec.digits+'/fullfront-0363100012167897-2025-00403-einitial.jpg','./ordinary-buildings-data/references/'+spec.digits+'/fullfront-0363100012167897-2025-00390-esouth.jpg','./ordinary-buildings-data/references/'+spec.digits+'/fullfront-0363100012167897-2025-00415-enorth.jpg'];const entry={name:'Nieuwe Spiegelstraat3–17 / Keizersgracht555 historic office and arcade wing',cameraBearing:297.758,referenceImages:references,traits:['Long red-brick lower street wing: white window surrounds, layered cornice, true recessed ground arcade and arched attic end projections.','Taller historic Keizers555: pale rusticated base, iron-grilled shallow arches, eighteen-pane historic sashes, fluted pilasters, portico/frontons and west balustrade.','Native irregular footprint, independent low/high source roof families, retained reentrant perimeter and neighboring Pand identities.'],simplifications:['Arcade depth2.2m inferred, backshop closures bounded; no through passage claimed.','Upper/red axis counts and historic17axes photo/register-guided; complete street rhythm source review pending.','Hidden rear windows unobserved; carvings simplified to shallow relief family. Architectural inscriptions/signs omitted pending native lettering proof.','Fitted survey roof surfaces retained; individual dormers simplified from register/current photos, not photographic mesh.'],galleryFrontage:{target:[4.890084,52.364897],distanceMetres:52,targetHeightMetres:7,referenceImages:[references[0],references[2]]},gallerySecondary:{target:[4.889967,52.364410],cameraBearing:192.55,distanceMetres:43,targetHeightMetres:12,referenceImages:[references[1]]},sourcePack:sourcePath,reviewState:'Author first-hit checks passed; source/gallery/independent/native-game/performance acceptance pending.',id:'ordinary-'+spec.digits,buildingId:spec.id,modelUrl:'/models/ordinary-buildings/'+spec.digits+'.glb',anchor:spec.anchor,bearing:0,scale:1,hash,bytes:bytes.length,materials:doc.getRoot().listMaterials().length,triangles,bounds:{min,max},height:max[1],footprint:spec.footprint,sourceCommit,sourcePath,sourceUrls:spec.sourceUrls,suppress:spec.suppress,retainedNeighbors:spec.retain,treatment:'full',status:'draft-pending-source-render-independent-native-game-performance'};
await fs.mkdir(out,{recursive:true});await fs.writeFile(out+'/'+spec.digits+'.glb',bytes);await fs.writeFile(out+'/runtime-entry.json',JSON.stringify(entry,null,2)+'\n');await fs.writeFile(out+'/export.json',JSON.stringify({...entry,indexProof,textures:0},null,2)+'\n');await fs.writeFile(out+'/opening-probes.json',JSON.stringify(probes,null,2)+'\n');console.log(JSON.stringify({hash,bytes:entry.bytes,triangles,materials:entry.materials,bounds:entry.bounds}));if(bytes.length>=500000||entry.materials>3||triangles>40000)throw Error('Strict budget failed; failed GLB retained');

const registrationRoot=process.env.ORDINARY_DATA_ROOT??'public/canal-drive/ordinary-buildings-data';
const registration=JSON.parse(await fs.readFile(`${registrationRoot}/catalogue.json`,'utf8'));
const registered=registration.models.find((m:{buildingId:string})=>m.buildingId===spec.id);
if(!registered||registered.id!==`ordinary-${spec.digits}`)throw Error('Exact native ordinary identity required');
Object.assign(registered,{hash:entry.hash,bytes:entry.bytes,triangles:entry.triangles,materials:entry.materials,bounds:entry.bounds,height:entry.bounds.max[1]});
await fs.writeFile(`${registrationRoot}/catalogue.json`,JSON.stringify(registration,null,2)+'\n');
