import * as T from 'three';import fs from 'node:fs/promises';import type {BuildingTools} from '../landmarks/cultural-builders';import {buildPrinsen485,openingProbes} from './prinsen485-builder';import spec from './prinsen485-spec.json';
const parts:{g:T.BufferGeometry;c:string}[]=[],b={add(g:T.BufferGeometry,c:string,x=0,y=0,z=0,a=0){g.rotateY(a);g.translate(x,y,z);parts.push({g,c});}} as BuildingTools;buildPrinsen485(0,0,b);const meshes=parts.map(p=>{const m=new T.Mesh(p.g,new T.MeshBasicMaterial({side:T.FrontSide}));m.userData.colour=p.c;m.updateMatrixWorld();return m;}),ray=new T.Raycaster(),failed:unknown[]=[];
for(const p of openingProbes){const n=new T.Vector3(...p.normal as[number,number,number]);ray.set(new T.Vector3(...p.point as[number,number,number]).addScaledVector(n,3),n.negate());const hit=ray.intersectObjects(meshes)[0];if(hit?.object.userData.colour!==p.kind)failed.push({label:p.label,wanted:p.kind,firstColour:hit?.object.userData.colour});}
let roofFaces=0,downwardRoofFaces=0;for(const p of parts.filter((_p,i)=>i>=1&&i<=spec.roofs.length*2&&i%2===1)){const g=p.g.index?p.g.toNonIndexed():p.g,v=g.getAttribute('position');for(let i=0;i<v.count;i+=3){const a=new T.Vector3().fromBufferAttribute(v,i),bb=new T.Vector3().fromBufferAttribute(v,i+1),c=new T.Vector3().fromBufferAttribute(v,i+2),n=bb.sub(a).cross(c.sub(a));if(Math.abs(n.y)>.000001){roofFaces++;if(n.y<0)downwardRoofFaces++;}}}
if(downwardRoofFaces)failed.push({label:'downward-source-owned-roof-faces',count:downwardRoofFaces});
// Count roof planes directly: unlike facade boxes each source surface must face up.
for(const r of spec.roofs){const tri=T.ShapeUtils.triangulateShape(r.ring.map(p=>new T.Vector2(...p as[number,number])),r.holes.map(h=>h.map(p=>new T.Vector2(...p as[number,number]))));if(!tri.length)failed.push({label:`roof${r.surface}-empty`});}
const inside=(x:number,z:number)=>{let yes=false;const r=spec.nativeRing;for(let i=0,j=r.length-1;i<r.length;j=i++){const p=r[i],q=r[j];if((p[1]>z)!==(q[1]>z)&&x<(q[0]-p[0])*(z-p[1])/(q[1]-p[1])+p[0])yes=!yes;}return yes;};
const distance=(x:number,z:number)=>Math.min(...spec.nativeRing.slice(1).map((q,i)=>{const p=spec.nativeRing[i],dx=q[0]-p[0],dz=q[1]-p[1],u=Math.max(0,Math.min(1,((x-p[0])*dx+(z-p[1])*dz)/(dx*dx+dz*dz)));return Math.hypot(x-p[0]-u*dx,z-p[1]-u*dz);}));let exteriorProbes=0;
for(let x=-24;x<24;x+=1.3)for(let z=-12;z<13;z+=1.3)if(!inside(x,z)&&distance(x,z)>.6){exteriorProbes++;ray.set(new T.Vector3(x,25,z),new T.Vector3(0,-1,0));if(ray.intersectObjects(meshes).length)failed.push({label:'outside-native',x,z});}
const low=spec.sourceRoofRings.find(r=>r.surface===77)!;const pt=low.ring.reduce((p,q)=>[p[0]+q[0]/low.ring.length,p[1]+q[1]/low.ring.length],[0,0]);ray.set(new T.Vector3(pt[0],25,pt[1]),new T.Vector3(0,-1,0));const hit=ray.intersectObjects(meshes)[0];if(!hit||hit.point.y>4)failed.push({label:'rear-low156m2-height',height:hit?.point.y});
const result={id:spec.id,firstHitProbes:openingProbes.length,exteriorProbes,rearLowRoofHeight:hit?.point.y,sourceRoofOwners:spec.sourceRoofRings.length,photoFrontRoofPieces:spec.roofs.filter(r=>r.photoAtticProfile).length,roofFaces,downwardRoofFaces,failed,retain:spec.retain,limitations:'CPU only; attic profile interpretation, native independent/gallery/live/performance pending.'};await fs.mkdir('artifacts/ordinary-buildings/prinsen485',{recursive:true});await fs.writeFile('artifacts/ordinary-buildings/prinsen485/geometry-check.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(failed.length)process.exitCode=1;
