import * as T from 'three';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {NodeIO} from '@gltf-transform/core';
import type {BuildingTools} from '../landmarks/cultural-builders';import {buildPrinsen215,openingProbes} from './prinsen215-builder';import spec from './prinsen215-spec.json';
const root=process.env.ORDINARY_REPORT_ROOT??'experiments/prinsen215-build53/report';const parts:{g:T.BufferGeometry;c:string}[]=[];
buildPrinsen215(0,0,{add(g:T.BufferGeometry,c:string,x=0,y=0,z=0,a=0){g.rotateY(a);g.translate(x,y,z);parts.push({g,c});}} as BuildingTools);
const meshes=parts.map(p=>{const m=new T.Mesh(p.g,new T.MeshBasicMaterial({side:T.DoubleSide}));m.userData.colour=p.c;m.updateMatrixWorld();return m;});const ray=new T.Raycaster(),failed:any[]=[];
for(const p of openingProbes){const n=new T.Vector3(...p.normal as[number,number,number]);ray.set(new T.Vector3(...p.point as[number,number,number]).addScaledVector(n,3),n.clone().negate());const h=ray.intersectObjects(meshes)[0];if(h?.object.userData.colour!==p.kind)failed.push({label:p.label,expected:p.kind,firstColour:h?.object.userData.colour,distance:h?.distance,point:p.point});}
let downwardRoofTriangles=0,roofTriangles=0;for(const p of parts.filter(p=>p.c==='slate')){const g=p.g.index?p.g.toNonIndexed():p.g,v=g.getAttribute('position');for(let i=0;i<v.count;i+=3){const a=new T.Vector3().fromBufferAttribute(v,i),b=new T.Vector3().fromBufferAttribute(v,i+1),c=new T.Vector3().fromBufferAttribute(v,i+2);const n=b.sub(a).cross(c.sub(a));roofTriangles++;if(n.y<-.0000001)downwardRoofTriangles++;}}
const native=new T.Shape(spec.nativeRing.map(p=>new T.Vector2(p[0],p[1])));assert.equal(native.holes.length,0);assert.equal(spec.suppress.length,1);assert.equal(spec.suppress[0],spec.id);assert.equal(spec.scale,1);
// This four-sided parent has no courtyard or exterior notch: exterior offset probes must be empty.
const exterior=[];for(let e=0;e<4;e++){const a=spec.nativeRing[e],b=spec.nativeRing[(e+1)%4],dx=b[0]-a[0],dz=b[1]-a[1],l=Math.hypot(dx,dz),x=(a[0]+b[0])/2-dz/l*1.5,z=(a[1]+b[1])/2+dx/l*1.5;ray.set(new T.Vector3(x,30,z),new T.Vector3(0,-1,0));exterior.push({edge:e,hits:ray.intersectObjects(meshes).length});}
const doc=await new NodeIO().read('public/canal-drive/models/ordinary-buildings/'+spec.digits+'.glb');const decoded=doc.getRoot().listMeshes()[0];let finite=true;for(const p of decoded.listPrimitives())for(const v of p.getAttribute('POSITION')!.getArray()!)finite&&=Number.isFinite(v);const bytes=(await fs.stat('public/canal-drive/models/ordinary-buildings/'+spec.digits+'.glb')).size;
const report={id:spec.id,probeCount:openingProbes.length,failedFirstHitProbes:failed,roofTriangles,downwardRoofTriangles,exteriorProbes:exterior,finite,bytes,materials:doc.getRoot().listMaterials().length,textures:doc.getRoot().listTextures().length,scale:1,suppress:spec.suppress,retainNeighbors:spec.retainNeighbors,notchTest:'Not applicable: native four-sided scope without holes/notches. Exterior probes included.',acceptance:'CPU checks only. Any exposed-pane failures require own source/render review; no inherited waiver.'};await fs.writeFile(root+'/geometry-check.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,failedFirstHitProbes:failed.map(p=>({label:p.label,firstColour:p.firstColour}))}));assert(finite&&bytes<500000&&report.materials<=3&&report.textures===0);assert.equal(downwardRoofTriangles,0);assert(exterior.every(p=>p.hits===0));if(failed.length)process.exitCode=1;
