import fs from 'node:fs/promises';import * as T from 'three';import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {MeshoptDecoder} from 'meshoptimizer';import {collect,palette} from './heren208-export';import {probes,roofOwnership} from './heren208-builder';import spec from './heren208-spec.json';
const out=process.env.ORDINARY_OUTPUT_ROOT??'artifacts/ordinary-buildings/heren208',parts=collect(),original=new T.Scene();for(const part of parts){const m=new T.Mesh(part.g,new T.MeshBasicMaterial({side:T.FrontSide}));m.userData.colour=part.c;original.add(m);}original.updateMatrixWorld(true);
await MeshoptDecoder.ready;const doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(`${out}/${spec.digits}.glb`),decoded=new T.Scene();let finite=true,degenerate=0,triangles=0;
const colour=(rgb:number[])=>Object.entries(palette).map(([k,v])=>({k,d:new T.Color(v).toArray().reduce((s,c,i)=>s+(c-rgb[i])**2,0)})).sort((a,b)=>a.d-b.d)[0].k;
for(const mesh of doc.getRoot().listMeshes())for(const p of mesh.listPrimitives()){const g=new T.BufferGeometry();for(const [src,dst]of[['POSITION','position'],['NORMAL','normal'],['COLOR_0','color']])g.setAttribute(dst,new T.BufferAttribute(p.getAttribute(src)!.getArray() as Float32Array,3));if(p.getIndices())g.setIndex(new T.BufferAttribute(p.getIndices()!.getArray() as Uint32Array,1));const pos=g.getAttribute('position'),ix=g.index,count=ix?.count??pos.count;finite&&=[...pos.array,...g.getAttribute('normal').array].every(Number.isFinite);for(let i=0;i<count;i+=3){const ids=[0,1,2].map(j=>ix?ix.getX(i+j):i+j),vs=ids.map(j=>new T.Vector3().fromBufferAttribute(pos,j)),n=vs[1].clone().sub(vs[0]).cross(vs[2].clone().sub(vs[0]));triangles++;if(n.length()<1e-7)degenerate++;}decoded.add(new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide})));}decoded.updateMatrixWorld(true);
function cast(scene:T.Scene,point:number[],normal:number[],distance=3){const n=new T.Vector3(...normal as[number,number,number]);return new T.Raycaster(new T.Vector3(...point as[number,number,number]).addScaledVector(n,distance),n.clone().negate(),0,distance+1).intersectObjects(scene.children)[0];}
function hitColour(h:T.Intersection|undefined){if(!h)return undefined;if(h.object.userData.colour)return h.object.userData.colour;const c=(h.object as T.Mesh).geometry.getAttribute('color'),i=h.face!.a;return colour([c.getX(i),c.getY(i),c.getZ(i)]);}
const openingResults=probes.map(p=>{const o=cast(original,p.point,p.normal,p.distance),d=cast(decoded,p.point,p.normal,p.distance);return {label:p.label,expected:p.colour,original:hitColour(o),decoded:hitColour(d),originalHit:o?.point.toArray(),decodedHit:d?.point.toArray(),pass:hitColour(o)===p.colour&&hitColour(d)===p.colour};});
const gardenResults=spec.gardenProbes.map(([x,z])=>{const o=cast(original,[x,0,z],[0,1,0],35),d=cast(decoded,[x,0,z],[0,1,0],35);return{point:[x,z],originalHeight:o?.point.y,decodedHeight:d?.point.y,pass:!o&&!d};});
const roofResults=spec.roofs.map(r=>{const [x,z]=r.sample,o=cast(original,[x,0,z],[0,1,0],35),d=cast(decoded,[x,0,z],[0,1,0],35),owner=spec.faces.find(f=>f.type==='RoofSurface'&&f.part===r.part&&f.face===r.face)!,sourceScene=new T.Scene();const sourceG=parts.find(p=>p.g.userData.source?.part===r.part&&p.g.userData.source?.face===r.face)!.g;sourceScene.add(new T.Mesh(sourceG,new T.MeshBasicMaterial()));sourceScene.updateMatrixWorld(true);const s=cast(sourceScene,[x,0,z],[0,1,0],35);return{part:r.part,semantic:r.semantic,sourceHeight:s?.point.y,originalHeight:o?.point.y,decodedHeight:d?.point.y,pass:!!s&&!!o&&!!d&&o.point.y>=s.point.y-.015&&Math.abs(o.point.y-d.point.y)<.025,upperAdornment:!!o&&!!s&&o.point.y-s.point.y>.10};});
const roofNormals=parts.filter(p=>p.g.userData.source?.type==='RoofSurface').map(p=>{const g=p.g.index?p.g.toNonIndexed():p.g,v=g.getAttribute('position');let downward=0,area=0;for(let i=0;i<v.count;i+=3){const a=new T.Vector3().fromBufferAttribute(v,i),b=new T.Vector3().fromBufferAttribute(v,i+1),c=new T.Vector3().fromBufferAttribute(v,i+2),n=b.sub(a).cross(c.sub(a));if(n.y<=0)downward++;area+=Math.abs(n.y)/2;}const rings=spec.faces.find(f=>f.part===p.g.userData.source.part&&f.face===p.g.userData.source.face)!.rings;const ringArea=(r:number[][])=>Math.abs(r.reduce((s,a,i)=>{const b=r[(i+1)%r.length];return s+a[0]*b[2]-b[0]*a[2]},0))/2,expected=ringArea(rings[0])-rings.slice(1).reduce((s,r)=>s+ringArea(r),0);return{...p.g.userData.source,downward,area,expected,pass:downward===0&&Math.abs(area-expected)<.001};});
const groundResults=parts.filter(p=>p.g.userData.source?.type==='GroundSurface').map(p=>{const g=p.g.index?p.g.toNonIndexed():p.g,v=g.getAttribute('position'),point=[0,1,2].map(i=>new T.Vector3().fromBufferAttribute(v,i)).reduce((s,v)=>s.add(v),new T.Vector3()).divideScalar(3),o=cast(original,point.toArray(),[0,-1,0],2),d=cast(decoded,point.toArray(),[0,-1,0],2);return{...p.g.userData.source,pass:!!o&&!!d&&Math.abs(o.point.y-d.point.y)<.025};});
const roof31=spec.faces.find(f=>f.type==='RoofSurface'&&f.semantic===31)!,raisedIslandResults=roof31.rings.slice(1).map(h=>{const p=h.reduce((s,v)=>[s[0]+v[0]/h.length,s[1]+v[2]/h.length],[0,0]),o=cast(original,[p[0],0,p[1]],[0,1,0],35),d=cast(decoded,[p[0],0,p[1]],[0,1,0],35);return{point:p,originalHeight:o?.point.y,decodedHeight:d?.point.y,pass:!!o&&!!d&&o.point.y>19&&o.point.y<20&&Math.abs(o.point.y-d.point.y)<.025};});
const report={finite,triangles,degenerate,scale:spec.scale,materials:doc.getRoot().listMaterials().length,textures:doc.getRoot().listTextures().length,openingResults,gardenResults,roofResults,roofNormals,groundResults,raisedIslandResults,sourceFaceCount:spec.faces.length,sourceRoofCount:spec.roofs.length,allRoofOwners:roofOwnership,exactSuppression:spec.suppress,retainNeighbors:spec.retain,acceptance:'Original and decoded CPU geometric evidence; root visual/game/performance review remains required.'};await fs.writeFile(`${out}/geometry-check.json`,JSON.stringify(report,null,2)+'\n');const failures=[...openingResults,...gardenResults,...roofResults,...roofNormals,...groundResults,...raisedIslandResults].filter(r=>!r.pass);console.log(JSON.stringify({finite,degenerate,triangles,probes:openingResults.length,gardenRays:gardenResults.length,roofRays:roofResults.length,roofOwners:roofOwnership.length,failures}));if(!finite||degenerate||failures.length)process.exitCode=1;
