/** Convert source roof plane survey polygons to native anchored metres, not imported mesh geometry. */
import fs from 'node:fs/promises';import proj4 from 'proj4';
const root=process.env.ORDINARY_SOURCE_ROOT||'/Users/blackmad/Code/map-recall2-source-data';
const rd='+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.4171,50.3319,465.5524,-0.398957,0.343988,-1.8774,4.0725 +units=m +no_defs';
const file='public/canal-drive/ordinary-buildings-data/recipes.json',data=JSON.parse(await fs.readFile(file,'utf8'));
for(const r of data.recipes){if(r.roofInterpretation){console.log(`${r.digits}: retained visual roof interpretation`);continue;}const rel=r.official3D?.summaryPath||(r.digits.endsWith('2242125')||r.digits.endsWith('2074248')?`experiments/3dbag-screen/${r.digits}/geometry-summary.json`:undefined);if(!rel)continue;const s=JSON.parse(await fs.readFile(`${root}/${rel}`,'utf8'));
 const major=s.roofSurfaces.filter((p:any)=>p.area>s.footprintArea*.008 && (!r.excludeRegionAboveHeightMetres || p.height<=r.excludeRegionAboveHeightMetres));r.officialRegions=major.map((p:any)=>({sourceArea:p.area,ring:p.coordinates.map(([x,y,z]:number[])=>{const [lng,lat]=proj4(rd,'EPSG:4326',[x,y]);return[(lng-r.anchor[0])*111320*Math.cos(r.anchor[1]*Math.PI/180),z-s.groundNAP,-(lat-r.anchor[1])*111320];})}));
 const ys=r.officialRegions.flatMap((p:any)=>p.ring.map((v:number[])=>v[1]));r.mainHeight=Math.max(...ys);r.wallBaseHeight=Math.min(...ys);delete r.roofProfile;r.official3D={...r.official3D,summaryPath:rel,groundNAP:s.groundNAP,rectangleFill:s.rectangleFill,courtyardArea:s.courtyardArea,dominantRoofPlaneCount:major.length};r.heightEvidence='Official fitted roof plane vertices minus b3_h_maaiveld; dominant regions clipped to native footprint, eaves and local roof slopes retained. Equipment planes below0.8% footprint area omitted.';r.simplifications=(r.simplifications||[]).filter((v:string)=>!v.startsWith('Flat dominant')).concat('Minor roof/equipment patches below0.8% footprint area omitted; main fitted roof planes retained.');}
await fs.writeFile(file,JSON.stringify(data,null,2));
