import fs from 'node:fs';import * as T from 'three';import type{BuildingTools}from '../landmarks/cultural-builders';import{buildKeizers73,probes,roofGeometries}from './keizers73-builder';import spec from './keizers73-spec.json';
const root=new T.Group(),tools={add(g:T.BufferGeometry,c:string,x=0,y=0,z=0,a=0){g.rotateY(a);g.translate(x,y,z);const mesh=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));mesh.userData.color=c;root.add(mesh);}}as BuildingTools;buildKeizers73(0,0,tools);root.updateMatrixWorld(true);let fail:any[]=[];const results:any[]=[];
for(const p of probes){const point=new T.Vector3(...p.point as[number,number,number]),n=new T.Vector3(...p.normal as[number,number,number]),ray=new T.Raycaster(point.clone().addScaledVector(n,2),n.clone().negate(),0,2.35),hit=ray.intersectObject(root,true)[0];const expected=p.kind==='masonry'?!!hit:p.kind===hit?.object.userData.color;const row={label:p.label,kind:p.kind,first:hit?.object.userData.color,depth:hit?2-hit.distance:null,pass:expected};results.push(row);if(!expected)fail.push(row);}
let downward=0;for(const g of roofGeometries){const n=g.getAttribute('normal');for(let i=0;i<n.count;i++)if(n.getY(i)<=0)downward++;}if(downward)fail.push({downwardRoofVertices:downward});
const edges=new Set(spec.nativeWalls.map(w=>w.edge));if(edges.size!==spec.nativeRing.length)fail.push({missingBoundaryEdges:true});
const roof21=spec.roofs.filter(r=>r.surface===21&&r.role==='survey-roof-owner');if(!roof21.length||roof21.some(r=>r.sourceHeightRange[1]>6.6))fail.push({lowMiddleLost:true});
const gapRays=spec.unresolvedRoofCoverage.filter(r=>r.areaMetres2>.25).map((r,i)=>{const x=r.ring.reduce((s,p)=>s+p[0],0)/r.ring.length,z=r.ring.reduce((s,p)=>s+p[1],0)/r.ring.length,hit=new T.Raycaster(new T.Vector3(x,30,z),new T.Vector3(0,-1,0),0,30).intersectObject(root,true)[0];return{label:'source-roof-gap-'+i,area:r.areaMetres2,point:[x,30,z],first:hit?.object.userData.color??null,hitY:hit?.point.y??null};});
const protectedHoleRays=spec.protectedSourceHoles.map((r,i)=>{const x=r.reduce((s,p)=>s+p[0],0)/r.length,z=r.reduce((s,p)=>s+p[1],0)/r.length,hit=new T.Raycaster(new T.Vector3(x,30,z),new T.Vector3(0,-1,0),0,30).intersectObject(root,true)[0];if(hit)fail.push({protectedSourceHoleCapped:i,hitY:hit.point.y});return{label:'raw-ground-hole-'+i,point:[x,30,z],first:hit?.object.userData.color??null,hitY:hit?.point.y??null};});
const output={protectedHoleRays,gapRays,id:spec.id,sourceCommit:spec.sourceCommit,nativeEdges:edges.size,masonryProbes:results.filter(r=>r.kind==='masonry').length,visibleFacadeProbes:results.filter(r=>r.kind!=='masonry').length,downwardRoofVertices:downward,unresolvedRoofArea:spec.unresolvedRoofCoverage.reduce((s,r)=>s+r.areaMetres2,0),results,failures:fail,acceptance:'Geometry evidence only; nativeGPU/gallery/game/neighbors/performance pending'};fs.mkdirSync('artifacts/ordinary-buildings/keizers73',{recursive:true});fs.writeFileSync('artifacts/ordinary-buildings/keizers73/geometry-check.json',JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify({...output,results:undefined}));if(fail.length)process.exitCode=1;
