import fs from 'node:fs/promises';import * as T from 'three';import{NodeIO}from '@gltf-transform/core';import{ALL_EXTENSIONS}from '@gltf-transform/extensions';import{MeshoptDecoder}from 'meshoptimizer';import type{BuildingTools}from '../landmarks/cultural-builders';import{buildKeizers575,probes,roofGeometries,roofAssemblyProbes,glassUndersideGeometries}from './keizers575-builder';import spec from './keizers575-spec.json';import actualRiskRays from './keizers575-camera-risk-rays.json';import rearRiskRays from './keizers575-rear-risk-rays.json';import undersideRiskRays from './keizers575-underside-risk-rays.json';
const palette={brick:'#805d52',insetBrick:'#694c45',stone:'#bcb9a7',relief:'#aaa795',white:'#e9ece4',glass:'#4a626b',roof:'#656c70',slate:'#505962',iron:'#303b3a',dark:'#293331',copper:'#648578'};
const parts:{g:T.BufferGeometry;c:string}[]=[],tools={add(g:T.BufferGeometry,c:string,x=0,y=0,z=0,a=0){g.rotateY(a);g.translate(x,y,z);parts.push({g,c});}}as BuildingTools;buildKeizers575(0,0,tools);
let roofFaces=0,downwardRoofFaces=0;for(const g of roofGeometries){const flat=g.index?g.toNonIndexed():g,p=flat.getAttribute('position');for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2),n=b.sub(a).cross(c.sub(a));roofFaces++;if(n.y< -1e-8)downwardRoofFaces++;}}
await MeshoptDecoder.ready;const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}),doc=await io.read('artifacts/ordinary-buildings/keizers575/0363100012176752.glb'),failed:any[]=[],meshes:T.Mesh[]=[],min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];let triangles=0;
for(const primitive of doc.getRoot().listMeshes()[0].listPrimitives()){const g=new T.BufferGeometry();for(const[name,label]of[['POSITION','position'],['NORMAL','normal'],['COLOR_0','color']]){const a=primitive.getAttribute(name)!;g.setAttribute(label,new T.BufferAttribute(a.getArray()!,a.getElementSize(),a.getNormalized()));for(const v of a.getArray()!)if(!Number.isFinite(v))failed.push({label:'decoded-nonfinite-'+name});}if(primitive.getIndices())g.setIndex(new T.BufferAttribute(primitive.getIndices()!.getArray()!,1));const p=g.getAttribute('position');for(let i=0;i<p.count;i++)for(let j=0;j<3;j++){const v=p.getComponent(i,j);min[j]=Math.min(min[j],v);max[j]=Math.max(max[j],v);}triangles+=(g.index?.count??p.count)/3;const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));m.updateMatrixWorld();meshes.push(m);}
const ray=new T.Raycaster(),colours=Object.entries(palette).map(([name,hex])=>({name,rgb:new T.Color(hex).toArray()})),firstColour=(hit:T.Intersection|undefined)=>{if(!hit)return null;const g=(hit.object as T.Mesh).geometry,c=g.getAttribute('color'),i=hit.face!.a,v=[c.getX(i),c.getY(i),c.getZ(i)];return colours.reduce((a,b)=>Math.hypot(...a.rgb.map((x,j)=>x-v[j]))<Math.hypot(...b.rgb.map((x,j)=>x-v[j]))?a:b).name;};
for(const p of probes){const n=new T.Vector3(...p.normal as[number,number,number]),origin=new T.Vector3(...p.point as[number,number,number]).addScaledVector(n,5);ray.set(origin,n.negate());const hit=ray.intersectObjects(meshes)[0],col=firstColour(hit);if(col!==p.kind)failed.push({label:p.label,wanted:p.kind,firstColour:col,point:hit?.point.toArray()});}
let intentionalGlassUndersideFaces=0,wrongUpwardGlassUndersideFaces=0;for(const g of glassUndersideGeometries){const flat=g.index?g.toNonIndexed():g,p=flat.getAttribute('position');for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2),normal=b.sub(a).cross(c.sub(a));intentionalGlassUndersideFaces++;if(normal.y>=-1e-8)wrongUpwardGlassUndersideFaces++;}}if(wrongUpwardGlassUndersideFaces)failed.push({label:'glass-undersides-must-face-down',wrongUpwardGlassUndersideFaces});
const actualUndersidePixelChecks:any[]=[];for(const p of undersideRiskRays.rays){ray.set(new T.Vector3(...p.camera as[number,number,number]),new T.Vector3(...p.direction as[number,number,number]));const hit=ray.intersectObjects(meshes)[0],colour=firstColour(hit),covered=!!hit&&colour===p.expectedColour&&hit.distance<=p.maximumFirstDistanceMetres;actualUndersidePixelChecks.push({pixel:p.pixel,covered,expected:p.expectedColour,firstColour:colour,distance:hit?.distance??null,v05FrontHit:p.v05FrontHit});if(!covered)failed.push({label:'actualv05-culled-pane-pixel',pixel:p.pixel,colour,distance:hit?.distance});}
const belowCanopyPaneChecks:any[]=[];for(const p of roofAssemblyProbes.filter(p=>p.label.startsWith('west-')&&p.kind==='glass')){const n=new T.Vector3(...p.normal as[number,number,number]);ray.set(new T.Vector3(...p.point as[number,number,number]).addScaledVector(n,-.5),n);const hit=ray.intersectObjects(meshes)[0],colour=firstColour(hit),covered=colour==='glass';belowCanopyPaneChecks.push({label:p.label,covered,firstColour:colour});if(!covered)failed.push({label:'observed-canopy-pane-underside-first-hit',probe:p.label,colour});}
const roofAssemblyChecks:any[]=[];for(const p of roofAssemblyProbes){const n=new T.Vector3(...p.normal as[number,number,number]);ray.set(new T.Vector3(...p.point as[number,number,number]).addScaledVector(n,3),n.clone().negate());const hit=ray.intersectObjects(meshes)[0],colour=firstColour(hit),covered=colour===p.kind;roofAssemblyChecks.push({label:p.label,expected:p.kind,firstColour:colour,covered});if(!covered)failed.push({label:'roof-glazing-assembly-first-hit',probe:p.label,expected:p.kind,firstColour:colour});}
const residualRearPixelChecks:any[]=[];for(const p of rearRiskRays.rays){ray.set(new T.Vector3(...p.camera as[number,number,number]),new T.Vector3(...p.direction as[number,number,number]));const hit=ray.intersectObjects(meshes)[0],colour=firstColour(hit),covered=!!hit&&colour===p.expectedColour&&hit.distance<=p.maximumFirstDistanceMetres;residualRearPixelChecks.push({pixel:p.pixel,rawWallIndex:p.rawWallIndex,covered,firstColour:colour,distance:hit?.distance??null});if(!covered)failed.push({label:'actualv04-rear-wedge-pixel',pixel:p.pixel,rawWallIndex:p.rawWallIndex,colour,distance:hit?.distance});}
if(downwardRoofFaces)failed.push({label:'downward-source-roof',downwardRoofFaces});if(max[1]>26||max[1]<25)failed.push({label:'unsupported-height-envelope',max:max[1]});
const sourceWallChecks:any[]=[];
for(const wall of spec.sourceInteriorWalls){const point=new T.Vector3(...wall.sourceSample as[number,number,number]),normal=new T.Vector3(...wall.normal as[number,number,number]);let found=false,closest=Infinity;for(const sign of[-1,1]){ray.set(point.clone().addScaledVector(normal,.15*sign),normal.clone().multiplyScalar(-sign));const hit=ray.intersectObjects(meshes)[0];if(hit&&hit.distance<=.30){found=true;closest=Math.min(closest,hit.distance);}}sourceWallChecks.push({rawWallIndex:wall.rawWallIndex,addedAreaMetres2:wall.addedAreaMetres2,covered:found,closestDistance:closest===Infinity?null:closest});if(!found&&wall.addedAreaMetres2>.04)failed.push({label:'selected-source-interior-wall-uncovered',rawWallIndex:wall.rawWallIndex,sample:wall.sourceSample});}
const nativeProfileChecks:any[]=[];for(const wall of spec.nativeSourceWallProfiles){const point=new T.Vector3(...wall.sample as[number,number,number]),n=new T.Vector3(...wall.normal as[number,number,number]);ray.set(point.clone().addScaledVector(n,1.5),n.clone().negate());const hit=ray.intersectObjects(meshes)[0],covered=!!hit&&hit.distance<=1.65;nativeProfileChecks.push({rawWallIndex:wall.rawWallIndex,nativeEdge:wall.nativeEdge,covered,distance:hit?.distance??null});if(!covered&&wall.addedAreaMetres2>.04)failed.push({label:'bounded-native-source-profile-uncovered',rawWallIndex:wall.rawWallIndex,nativeEdge:wall.nativeEdge});}
const failedRearCameraChecks:any[]=[];const rearCamera=new T.Vector3(13.007125705,41.238767853,-60.160339045);for(const y of[1,4,8,12,16])for(const dx of[-.005,0,.005,.02]){const p=spec.nativeRing[4],target=new T.Vector3(p[0]+dx,y,p[1]);ray.set(rearCamera,target.clone().sub(rearCamera).normalize());const hit=ray.intersectObjects(meshes)[0],colour=firstColour(hit),covered=!!hit&&(y===1?colour==='roof'&&hit.point.y<1.8:colour==='brick'&&hit.point.distanceTo(target)<.8);failedRearCameraChecks.push({corner:4,y,dx,covered,firstColour:colour,targetDistance:hit?.point.distanceTo(target)??null});if(!covered)failed.push({label:'actual-rear-camera-long-seam',corner:4,y,dx});}
// Root actuallower gallery: eye2.1m, east42m/west28m; OrbitControls70px
// rightward drag over610px rotates azimuth by2π70/610. Targets retain source
// facade locations; these rays seek the actualv03 street/front and west gaps.
const galleryTarget=(lng:number,lat:number)=>new T.Vector3((lng-spec.anchor[0])*111320*Math.cos(spec.anchor[1]*Math.PI/180),0,-(lat-spec.anchor[1])*111320);
const eastTarget=galleryTarget(4.891004546462495,52.36426969631949),westTarget=galleryTarget(4.8907375409187726,52.36430473045531),galleryCamera=(p:T.Vector3,bearing:number,d:number)=>new T.Vector3(p.x+Math.sin(bearing*Math.PI/180)*d,2.1,p.z-Math.cos(bearing*Math.PI/180)*d),eastCamera=galleryCamera(eastTarget,192.2,42),westCamera=galleryCamera(westTarget,191.7+360*70/610,28),failedOpeningCameraChecks:any[]=[];
for(const wall of spec.nativeSourceWallProfiles.filter(w=>w.rawWallIndex===36&&w.nativeEdge===12||w.rawWallIndex===19&&w.nativeEdge===6||w.rawWallIndex===115&&w.nativeEdge===5)){const camera=wall.rawWallIndex===36?eastCamera:westCamera,base=new T.Vector3(...wall.sample as[number,number,number]);for(const deltaY of[-.04,0,.04]){const target=base.clone();target.y+=deltaY;ray.set(camera,target.clone().sub(camera).normalize());const hit=ray.intersectObjects(meshes)[0],colour=firstColour(hit),covered=!!hit&&hit.distance<=camera.distanceTo(target)+.05&&['brick','slate','stone','roof','white','glass'].includes(colour??'');failedOpeningCameraChecks.push({rawWallIndex:wall.rawWallIndex,nativeEdge:wall.nativeEdge,camera:camera.toArray(),target:target.toArray(),deltaY,covered,firstColour:colour,targetDistance:hit?.point.distanceTo(target)??null});if(!covered)failed.push({label:'actual-failed-lower-camera-opening',rawWallIndex:wall.rawWallIndex,nativeEdge:wall.nativeEdge,deltaY});}}
const actualFailedPixelChecks:any[]=[];for(const p of actualRiskRays.rays){ray.set(new T.Vector3(...p.camera as[number,number,number]),new T.Vector3(...p.direction as[number,number,number]));const hit=ray.intersectObjects(meshes)[0],colour=firstColour(hit),covered=!!hit&&colour===p.expectedColour&&hit.distance<=p.maximumFirstDistanceMetres;actualFailedPixelChecks.push({view:p.name,pixel:p.pixel,covered,firstColour:colour,firstDistance:hit?.distance??null,maximumFirstDistance:p.maximumFirstDistanceMetres,v03:p.v03});if(!covered)failed.push({label:'actualv03-failed-pixel-regression',view:p.name,pixel:p.pixel,colour,distance:hit?.distance});}
const nativeCornerChecks:any[]=[];
for(const corner of[0,1,4,5,6,7,8,9,10,11,12,13]){const r=spec.nativeRing,p=r[corner],before=r[(corner+r.length-1)%r.length],after=r[(corner+1)%r.length],norm=(a:number[],b:number[])=>{const dx=b[0]-a[0],dz=b[1]-a[1],L=Math.hypot(dx,dz);return[-dz/L,dx/L];},n0=norm(before,p),n1=norm(p,after),n=new T.Vector3(n0[0]+n1[0],0,n0[1]+n1[1]).normalize(),point=new T.Vector3(p[0],.9,p[1]);for(const jitter of[-.0005,.0005]){const target=point.clone().add(new T.Vector3(-n.z,0,n.x).multiplyScalar(jitter));ray.set(target.addScaledVector(n,.3),n.clone().negate());const hit=ray.intersectObjects(meshes)[0],covered=!!hit&&hit.distance<.45;nativeCornerChecks.push({corner,jitterMetres:jitter,covered,firstDistance:hit?.distance??null});if(!covered)failed.push({label:'native-envelope-corner-seam',corner,jitterMetres:jitter});}}
const eastA=spec.nativeRing[8],eastB=spec.nativeRing[13],eastL=Math.hypot(eastB[0]-eastA[0],eastB[1]-eastA[1]),eastT=[(eastB[0]-eastA[0])/eastL,(eastB[1]-eastA[1])/eastL],eastN=[-eastT[1],eastT[0]],chimneyChecks:any[]=[];
for(const u of[.63,6.80,14.07,21.74])for(const du of[-.56,0,.56]){const point=new T.Vector3(eastA[0]+eastT[0]*(u+du)+eastN[0]*5,23.8,eastA[1]+eastT[1]*(u+du)+eastN[1]*5);ray.set(point,new T.Vector3(-eastN[0],0,-eastN[1]));const first=firstColour(ray.intersectObjects(meshes)[0]),expected=du===0?'brick':null;chimneyChecks.push({u,offset:du,y:23.8,firstColour:first,expected});if(first!==expected)failed.push({label:'photo-slender-chimney-separation',u,offset:du,firstColour:first,expected});}
const low=spec.roofs.find(r=>r.surface===233&&r.role==='survey-roof-owner')!,pt=low.ring.reduce((s,p)=>[s[0]+p[0]/low.ring.length,s[1]+p[1]/low.ring.length],[0,0]);ray.set(new T.Vector3(pt[0],30,pt[1]),new T.Vector3(0,-1,0));const lowHit=ray.intersectObjects(meshes)[0];if(!lowHit||lowHit.point.y>2)failed.push({label:'low-covered-patch-raised',y:lowHit?.point.y});
const gapChecks=spec.unresolvedRoofCoverage.map(g=>{const p=g.ring.reduce((s,q)=>[s[0]+q[0]/g.ring.length,s[1]+q[1]/g.ring.length],[0,0]);ray.set(new T.Vector3(p[0],30,p[1]),new T.Vector3(0,-1,0));return{area:g.areaMetres2,firstHeight:ray.intersectObjects(meshes)[0]?.point.y??null};});for(const gap of gapChecks)if(gap.firstHeight!==null)failed.push({label:'unobserved-gap-filled',...gap});
const inside=(p:number[])=>{let yes=false;for(let i=0,j=spec.nativeRing.length-1;i<spec.nativeRing.length;j=i++){const a=spec.nativeRing[i],b=spec.nativeRing[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;},dist=(p:number[])=>Math.min(...spec.nativeRing.map((a,i)=>{const b=spec.nativeRing[(i+1)%spec.nativeRing.length],dx=b[0]-a[0],dz=b[1]-a[1],f=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dz)/(dx*dx+dz*dz)));return Math.hypot(p[0]-a[0]-f*dx,p[1]-a[1]-f*dz);}));let outsideProbes=0;
for(let x=-25;x<24;x+=1.4)for(let z=-30;z<24;z+=1.4)if(!inside([x,z])&&dist([x,z])>1){outsideProbes++;ray.set(new T.Vector3(x,30,z),new T.Vector3(0,-1,0));if(ray.intersectObjects(meshes).length)failed.push({label:'outside-native-roof-hit',x,z});}
const report={id:spec.id,decodedGLB:true,triangles,bounds:{min,max},firstHitProbes:probes.length,roofAssemblyChecks,intentionalGlassUndersideFaces,wrongUpwardGlassUndersideFaces,actualUndersidePixelChecks,belowCanopyPaneChecks,residualRearPixelChecks,sourceWallChecks,nativeProfileChecks,failedRearCameraChecks,failedOpeningCameraChecks,actualFailedPixelChecks,nativeCornerChecks,chimneyChecks,stoneBackingProbes:probes.filter(p=>p.kind==='stone').length,roofFaces,downwardRoofFaces,lowCoveredPatchHeight:lowHit?.point.y,outsideProbes,gapChecks,unresolvedRearAreaMetres2:spec.unresolvedRoofCoverage.reduce((s,g)=>s+g.areaMetres2,0),failed,acceptance:'CPU geometry only. Unresolved roof coverage deliberately retained. Independent/gallery/live/suppression/neighbors/performance review pending.'};await fs.writeFile('artifacts/ordinary-buildings/keizers575/geometry-check.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(failed.length)process.exitCode=1;
