/** Actual normal bike-follow review, same-version profile ablation, full MapLibre frame GPU queries. */
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {chromium} from 'playwright';
const option=(n,d)=>process.argv.find(a=>a.startsWith(`--${n}=`))?.slice(n.length+3)??d;
const output=option('output','artifacts/street-appearance/retry/9/game'),base=option('base-url','http://127.0.0.1:5196');
await fs.mkdir(path.join(output,'bundles'),{recursive:true});
const names=['three-buildings.bundle.js','three-buildings-worker.bundle.js','vector-map.js','game-route.js'];const hashes={};
for(const n of names){const input=option('bundle-dir',null)?path.join(option('bundle-dir',null),n):`public/canal-drive/js/${n}`;const b=await fs.readFile(input);hashes[n]=crypto.createHash('sha256').update(b).digest('hex');await fs.writeFile(path.join(output,'bundles',n),b);}
const catalogBytes=await fs.readFile(option('catalog-path','public/data/street-appearance/profiles.json')),catalog=JSON.parse(catalogBytes);await fs.writeFile(path.join(output,'profiles.json'),catalogBytes);
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),ctx=await browser.newContext(option('device','desktop')==='phone'?{viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1}:{viewport:{width:1440,height:1000}});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await ctx.addInitScript(()=>localStorage.setItem('canalRecall.preferences.v1',JSON.stringify({travelMode:'car',viewMode:'chase',buildingLook:'photo',reducedMotion:false})));
for(const n of names)await page.route(`**/canal-drive/js/${n}*`,r=>r.fulfill({status:200,contentType:'application/javascript',path:path.join(output,'bundles',n)}));
await page.route('**/data/street-appearance/profiles.json*',r=>r.fulfill({status:200,contentType:'application/json',body:catalogBytes}));
const ready=async()=>{await page.waitForFunction(()=>{const v=window.canalRecallGame?.vectorMap,t=v?._threeBuildings,c=v?._completeCity?.status?.();return window.canalRecallGame.state===4&&t?.ready&&t.chunks.size&&!t.pending.length&&!t.inflight.size&&!t.pumping&&!c?.inFlight&&!c?.queued},null,{timeout:120000});await page.waitForTimeout(750)};
const diagnostic=()=>page.evaluate(()=>{const g=window.canalRecallGame,v=g.vectorMap,t=v._threeBuildings,ll=v.worldToLngLat(g.player.x,g.player.y,g.osmLoader),n=2**t.detailZoom,r=ll[1]*Math.PI/180,tile=`${Math.floor((ll[0]+180)/360*n)}/${Math.floor((1-Math.log(Math.tan(r)+1/Math.cos(r))/Math.PI)/2*n)}`;let digest=2166136261;const mix=a=>{if(!a)return;for(let i=0;i<a.length;i+=Math.max(1,Math.floor(a.length/2000)))digest=Math.imul(digest^(a[i]*997|0),16777619)};const geometryByMode={};let triangles=0;for(const [key,c]of t.chunks){if(!c.mesh)continue;const mode=key.startsWith('extras:')?'extras':key.startsWith('coarse:')?'coarse':key.startsWith('near:')?'near-walls':'other';const bucket=geometryByMode[mode]??(geometryByMode[mode]={triangles:0,chunks:0,features:0});bucket.triangles+=(c.mesh.geometry.index?.count??c.mesh.geometry.attributes.position.count)/3;bucket.chunks++;bucket.features+=c.source?.length??0;mix(c.mesh.geometry.attributes.position.array);if(c.mesh.geometry.attributes.tint)mix(c.mesh.geometry.attributes.tint.array);triangles+=(c.mesh.geometry.index?.count??c.mesh.geometry.attributes.position.count)/3;digest=Math.imul(digest^(c.mesh.geometry.index?.count??c.mesh.geometry.attributes.position.count),16777619);}return{revision:t.appearanceRevision,profiles:t.appearanceProfiles.length,look:t.look,requested:t.requestedLook,player:ll,subject:v.worldToLngLat(g.camera.targetX,g.camera.targetY,g.osmLoader),playerTile:tile,detailZoom:t.detailZoom,detailTiles:[...t.detailTiles],playerTileSelected:t.detailTiles.has(tile),camera:{center:v.map.getCenter().toArray(),zoom:v.map.getZoom(),pitch:v.map.getPitch(),bearing:v.map.getBearing(),detached:g.camera.detached},chunks:t.chunks.size,coarseChunks:[...t.chunks.values()].filter(c=>c.mesh.userData.coarse).length,triangles,geometryByMode,geometryCountDigest:(digest>>>0).toString(16),mismatches:[...t.chunks.values()].filter(c=>c.mesh.userData.appearanceRevision!==undefined&&(c.mesh.userData.installedLook!==t.look||c.mesh.userData.appearanceRevision!==t.appearanceRevision)).map(c=>c.mesh.userData)}});
const modes=[],timings=[],ablate=option('ablate','true')==='true',rounds=Number(option('rounds','3')),looks=option('looks','photo,storybook,cartoon,procedural').split(',');
try{
 await page.goto(`${base}/canal-drive/#race=${option('race','52.3735,4.8954,52.3608814,4.8687372,52.3713544,4.8979412')}`);await page.waitForFunction(()=>window.canalRecallGame?.player,null,{timeout:120000});await page.evaluate(()=>window.canalRecallGame._overlay.store.setSetupOpen(false));await ready();
 const reviewPosition=option('review-position',null);
 if(reviewPosition){
  const point=reviewPosition.split(',').map(Number);if(point.length!==2||!point.every(Number.isFinite))throw Error('Invalid review position');
  await page.evaluate(([lng,lat])=>{const g=window.canalRecallGame,l=g.osmLoader,x=l._lastOffsetX+(lng-l._lastCenterLng)*111320*Math.cos(l._lastCenterLat*Math.PI/180)*3,y=l._lastOffsetY-(lat-l._lastCenterLat)*111320*3;g.player.x=x;g.player.y=y;g.player.speed=0;g.camera.x=x;g.camera.y=y;g.camera.targetX=x;g.camera.targetY=y;g.camera.resetPan();},point);await ready();
 }
 for(const look of looks){await page.evaluate(async look=>{const v=window.canalRecallGame.vectorMap;v.setBuildingLook(look);await v.setBuildingsLook(look)},look);await page.waitForFunction(look=>window.canalRecallGame.vectorMap._threeBuildings.look===look&&window.canalRecallGame.vectorMap._threeBuildings.requestedLook===look,look,{timeout:120000});await ready();const d=await diagnostic();await fs.writeFile(path.join(output,`diagnostic-${look}.json`),JSON.stringify(d,null,2));console.log('mode diagnostic',JSON.stringify(d));if(!d.playerTileSelected||d.look!==look||d.requested!==look||d.revision!==catalog.revision||d.mismatches.length)throw Error('Normal gameplay mode/detail/revision regression');await page.screenshot({path:path.join(output,`overtoom-bike-${look}.png`)});modes.push(d);console.log('actual bike',look,d.revision,d.playerTileSelected);}
 await page.evaluate(async()=>{const v=window.canalRecallGame.vectorMap;v.setBuildingLook('photo');await v.setBuildingsLook('photo')});await page.waitForFunction(()=>window.canalRecallGame.vectorMap._threeBuildings.look==='photo',null,{timeout:120000});await ready();
 for(let round=0;round<rounds;round++)for(const on of ablate?(round%2?[false,true]:[true,false]):[true]){
  await page.evaluate(c=>window.canalRecallGame.vectorMap._threeBuildings.setStreetAppearance(c),on?catalog:{schemaVersion:1,revision:`review-empty-${round}`,profiles:[],streetFrontPaths:catalog.streetFrontPaths});await ready();const d=await diagnostic();
  const timing=await page.evaluate(async()=>{const v=window.canalRecallGame.vectorMap,map=v.map,gl=v._threeBuildings.renderer.getContext(),ext=gl.getExtension('EXT_disjoint_timer_query_webgl2'),original=map._render;const pending=[],gpu=[],cpu=[],frames=[];let warm=30,count=0,previous=null,disjoint=false;
   if(typeof original!=='function')return{unsupported:'MapLibre _render unavailable'};
   await new Promise(resolve=>{map._render=function(...args){const query=ext&&!gl.getQuery(ext.TIME_ELAPSED_EXT,gl.CURRENT_QUERY)?gl.createQuery():null;if(query)gl.beginQuery(ext.TIME_ELAPSED_EXT,query);const start=performance.now();let result;try{result=original.apply(this,args)}finally{if(query){gl.endQuery(ext.TIME_ELAPSED_EXT);pending.push({query,keep:warm<=0})}const end=performance.now();if(warm>0)warm--;else{cpu.push(end-start);if(previous!==null)frames.push(start-previous);previous=start;count++;}if(ext&&gl.getParameter(ext.GPU_DISJOINT_EXT))disjoint=true;while(pending.length&&gl.getQueryParameter(pending[0].query,gl.QUERY_RESULT_AVAILABLE)){const q=pending.shift();if(q.keep)gpu.push(gl.getQueryParameter(q.query,gl.QUERY_RESULT)/1e6);gl.deleteQuery(q.query);}if(count>=90){map._render=original;resolve();}else map.triggerRepaint();}return result};map.triggerRepaint();});
   if(ext){await new Promise(r=>setTimeout(r,50));for(const q of pending){if(gl.getQueryParameter(q.query,gl.QUERY_RESULT_AVAILABLE)&&q.keep)gpu.push(gl.getQueryParameter(q.query,gl.QUERY_RESULT)/1e6);gl.deleteQuery(q.query);}}
   const stats=a=>{a.sort((a,b)=>a-b);return{count:a.length,median:a[Math.floor(a.length*.5)]??null,p95:a[Math.floor(a.length*.95)]??null}};return{gpuRenderer:gl.getExtension('WEBGL_debug_renderer_info')?gl.getParameter(gl.getExtension('WEBGL_debug_renderer_info').UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),gpuExtension:!!ext,gpuDisjoint:disjoint,fullMapGpuMs:stats(gpu),fullMapCpuSubmissionMs:stats(cpu),frameIntervalsMs:stats(frames),method:'EXT_disjoint_timer_query_webgl2 around full MapLibre _render on shared context, all background/custom layers included. Steady actual bike follow;30warm then90measured frames. No gl.finish proxy.'};});timings.push({round,profilesOn:on,diagnostics:d,timing});console.log('fullframe',round,on,JSON.stringify(timing.fullMapGpuMs??timing));
 }
 await page.evaluate(c=>window.canalRecallGame.vectorMap._threeBuildings.setStreetAppearance(c),catalog);await ready();
 const beforePan=await diagnostic();await page.evaluate(()=>{const v=window.canalRecallGame.vectorMap;v.sync=()=>{};v.map.jumpTo({center:[4.86853,52.37534],zoom:18.3,pitch:58,bearing:-25});v._completeCity.followCamera()});await ready();const coarsePan=await diagnostic();await page.screenshot({path:path.join(output,'coarse-pan-revision.png')});
 const on=timings.filter(t=>t.profilesOn).map(t=>t.timing.fullMapGpuMs?.median).filter(Number.isFinite),off=timings.filter(t=>!t.profilesOn).map(t=>t.timing.fullMapGpuMs?.median).filter(Number.isFinite);const median=a=>a.sort((a,b)=>a-b)[Math.floor(a.length/2)];const gpuRatio=on.length===3&&off.length===3?median(on)/median(off):null;
 const report={version:1,device:option('device','desktop'),race:option('race','52.3735,4.8954,52.3608814,4.8687372,52.3713544,4.8979412'),reviewPosition,bundleDir:option('bundle-dir','production-snapshot'),profileAblation:ablate,catalogRevision:catalog.revision,immutableBundles:hashes,modes,timings,beforePan,coarsePan,coarseOwnershipUnchanged:JSON.stringify(beforePan.detailTiles)===JSON.stringify(coarsePan.detailTiles),geometryOnOffChanged:timings.some(t=>t.profilesOn&&timings.some(o=>!o.profilesOn&&o.diagnostics.geometryCountDigest!==t.diagnostics.geometryCountDigest)),fullMapGpuMedianRatio:gpuRatio,errors,limits:['Normal gameplay four modes use actual bike hash and camera sync; setup presentation overlay dismissed to reveal running ride.','Optional review-position moves the stationary rider in the running game for a scene test; this is not evidence of route reachability.','Coarse pan is separate fixed read-only camera regression after normal timing; rider detail ownership retained intentionally.','Profile ablation uses identical current bundles and street-front paths.','Headless local Chrome GPU timing is this hardware/browser only; report query support/disjoint and variability before asserting budget.','Partial assembly progress and runtime checks do not waive failed Overtoom block composition.']};await fs.writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log('complete',JSON.stringify({gpuRatio,errors,geometryOnOffChanged:report.geometryOnOffChanged}));
}finally{await browser.close()}
