import * as T from 'three';
import type {BuildingTools} from './cultural-builders';
import data from './canal-renaissance-footprints.json';
type Colour=Parameters<BuildingTools['add']>[1];
/** Measured Renaissance canal-house silhouettes with exact neighbor scope. */
export function buildCanalRenaissanceLandmark(id:string,_w:number,_d:number,b:BuildingTools){
 const {add,box,sign}=b,s=data.sites.find(s=>s.id===id)!,a=s.authorHeadingDegrees*Math.PI/180;
 const point=(p:number[])=>{const e=(p[0]-s.anchor[0])*111320*Math.cos(s.anchor[1]*Math.PI/180),n=(p[1]-s.anchor[1])*110540;return new T.Vector2(e*Math.sin(a)+n*Math.cos(a),e*Math.cos(a)-n*Math.sin(a));};
 const poly=s.buildings[0].geometry.coordinates[0].map(r=>r.slice(0,-1).map(point));
 function shell(r:T.Vector2[],h:number,c:Colour){const g=new T.ExtrudeGeometry(new T.Shape(r),{depth:h,bevelEnabled:false});g.rotateX(Math.PI/2);g.translate(0,h,0);add(g,c);}
 function clip(r:T.Vector2[],value:number,less:boolean,axis:'x'|'y'='x'){const out:T.Vector2[]=[];for(let i=0;i<r.length;i++){const p=r[i],q=r[(i+1)%r.length],pin=less?p[axis]<=value:p[axis]>=value,qin=less?q[axis]<=value:q[axis]>=value;if(pin)out.push(p);if(pin!==qin)out.push(p.clone().lerp(q,(value-p[axis])/(q[axis]-p[axis])));}return out;}
 function roof(r:T.Vector2[],y:number,rise:number){
  // Clip the actual outline at all four hip planes. No sampled triangle fan
  // or bounding rectangle can bridge a facade recess or the rounded bay.
  const xs=r.map(p=>p.x),zs=r.map(p=>p.y),xl=Math.min(...xs),xh=Math.max(...xs),zl=Math.min(...zs),zh=Math.max(...zs),cz=(zl+zh)/2,hz=Math.min((zh-zl)/2,(xh-xl)/2);
  const planes=[(p:T.Vector2)=>p.y-zl,(p:T.Vector2)=>zh-p.y,(p:T.Vector2)=>p.x-xl,(p:T.Vector2)=>xh-p.x];
  function half(r:T.Vector2[],f:(p:T.Vector2)=>number){const out:T.Vector2[]=[];for(let i=0;i<r.length;i++){const p=r[i],q=r[(i+1)%r.length],fp=f(p),fq=f(q);if(fp>=-1e-7)out.push(p);if((fp>=0)!==(fq>=0))out.push(p.clone().lerp(q,fp/(fp-fq)));}return out;}
  const vertices:number[]=[];for(let i=0;i<4;i++){let p=r;for(let j=0;j<4;j++)if(i!==j)p=half(p,q=>planes[j](q)-planes[i](q));if(p.length<3)continue;const triangulation=new T.ShapeGeometry(new T.Shape(p)),pos=triangulation.getAttribute('position'),indices=triangulation.index!;for(let k=0;k<indices.count;k++){const q=new T.Vector2(pos.getX(indices.getX(k)),pos.getY(indices.getX(k)));vertices.push(q.x,y+Math.max(0,Math.min(hz,planes[i](q)))*rise/hz,q.y);}triangulation.dispose();}
  for(let k=0;k<r.length;k++){const p=r[k],q=r[(k+1)%r.length],yp=y+Math.max(0,Math.min(hz,...planes.map(f=>f(p))))*rise/hz,yq=y+Math.max(0,Math.min(hz,...planes.map(f=>f(q))))*rise/hz;vertices.push(p.x,y,p.y,q.x,y,q.y,q.x,yq,q.y,p.x,y,p.y,q.x,yq,q.y,p.x,yp,p.y);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.computeVertexNormals();add(g,'slate');
 }
 function pane(x:number,y:number,z:number,w:number,h:number,angle=0,c:Colour='white'){
  const nx=Math.sin(angle),nz=Math.cos(angle);add(new T.PlaneGeometry(w+.24,h+.24),c,x,y+h/2,z,angle);add(new T.PlaneGeometry(w,h),'glass',x+nx*.035,y+h/2,z+nz*.035,angle);add(new T.PlaneGeometry(.075,h),'white',x+nx*.065,y+h/2,z+nz*.065,angle);for(let yy=.8;yy<h;yy+=1.2)add(new T.PlaneGeometry(w,.065),'white',x+nx*.07,y+yy,z+nz*.07,angle);box(x+nx*.08,y-.16,z+nz*.08,w+.4,.18,.35,c,angle);
 }
 function arch(x:number,y:number,z:number,w:number,h:number,angle=0){
  const nx=Math.sin(angle),nz=Math.cos(angle),tx=Math.cos(angle),tz=-Math.sin(angle),sh=new T.Shape();sh.moveTo(-w/2,0);sh.lineTo(w/2,0);sh.lineTo(w/2,h-w/2);sh.absarc(0,h-w/2,w/2,0,Math.PI,false);sh.closePath();add(new T.ShapeGeometry(sh,12),'glass',x,y,z,angle);add(new T.TorusGeometry(w/2+.13,.15,4,12,Math.PI),'white',x+nx*.06,y+h-w/2,z+nz*.06,angle);for(const u of [-w/2-.13,0,w/2+.13])box(x+u*tx+nx*.08,y,z+u*tz+nz*.08,u===0?.08:.25,h-w/2,.18,'white',angle);for(let yy=1.3;yy<h-w/2;yy+=1.3)box(x+nx*.1,y+yy,z+nz*.1,w,.07,.12,'white',angle);for(let k=1;k<6;k++){const t=k*Math.PI/6,dx=Math.cos(t)*w*.25,dy=Math.sin(t)*w*.25;const g=new T.PlaneGeometry(.065,w/2);g.rotateZ(t-Math.PI/2);add(g,'white',x+dx*tx+nx*.12,y+h-w/2+dy,z+dx*tz+nz*.12,angle);}box(x+nx*.08,y-.15,z+nz*.08,w+.45,.18,.35,'white',angle);
 }
 function pediment(x:number,y:number,z:number,w:number,h:number,angle=0){const sh=new T.Shape();sh.moveTo(-w/2,0);sh.lineTo(w/2,0);sh.lineTo(0,h);sh.closePath();add(new T.ShapeGeometry(sh),'brick',x,y,z,angle);const rim=new T.Shape();rim.moveTo(-w/2-.2,0);rim.lineTo(0,h+.2);rim.lineTo(w/2+.2,0);rim.lineTo(w/2-.12,0);rim.lineTo(0,h-.12);rim.lineTo(-w/2+.12,0);rim.closePath();add(new T.ShapeGeometry(rim),'stone',x,y,z+.02*Math.cos(angle),angle);box(x,y,z,w+.35,.2,.34,'stone',angle);}
 function band(r:T.Vector2[],y:number,h:number,c:Colour,depth=.25){for(let i=0;i<r.length;i++){const p=r[i],q=r[(i+1)%r.length],delta=q.clone().sub(p),len=delta.length(),mid=p.clone().add(q).multiplyScalar(.5),angle=-Math.atan2(delta.y,delta.x);box(mid.x,y,mid.y,len,h,depth,c,angle);}}
 function cornice(x:number,y:number,z:number,w:number,angle=0){for(const [dy,hh,dd]of [[0,.18,.28],[.18,.24,.48],[.42,.20,.64]])box(x,y+dy,z,w,hh,dd,'stone',angle);for(let u=-w/2+.2;u<w/2;u+=.45)box(x+u*Math.cos(angle),y-.24,z-u*Math.sin(angle),.15,.30,.3,'stone',angle);}
 function sideWindows(r:T.Vector2[],h:number,skipFront=false){let area=0;for(let k=0;k<r.length;k++)area+=r[k].x*r[(k+1)%r.length].y-r[(k+1)%r.length].x*r[k].y;for(let k=0;k<r.length;k++){const p=r[k],q=r[(k+1)%r.length],v=q.clone().sub(p),len=v.length();if(len<2.4)continue;const tangent=v.clone().normalize(),normal=new T.Vector2(tangent.y,-tangent.x).multiplyScalar(area>0?1:-1),angle=Math.atan2(normal.x,normal.y),count=Math.round(len/3.7);if(skipFront&&normal.y>.75)continue;for(let j=0;j<count;j++){const pt=p.clone().addScaledVector(tangent,len*(j+.5)/count).addScaledVector(normal,.05);for(let y of [1.0,5.0,9.0,13.0].filter(y=>y+2.4<h))pane(pt.x,y,pt.y,Math.min(1.4,len/count*.65),2.35,angle);}}}
 const r=poly[0];
 function gable(r:T.Vector2[],h:number,rise:number,c:Colour='slate',acrossZ=false){if(acrossZ)r=r.map(p=>new T.Vector2(p.y,p.x));const xs=r.map(p=>p.x),lo=Math.min(...xs),hi=Math.max(...xs),mid=(lo+hi)/2,half=(hi-lo)/2,verts:number[]=[];for(const left of [true,false]){const p=clip(r,mid,left);if(p.length<3)continue;const sh=new T.ShapeGeometry(new T.Shape(p)),pos=sh.getAttribute('position'),ix=sh.index!;for(let j=0;j<ix.count;j++){const x=pos.getX(ix.getX(j)),z=pos.getY(ix.getX(j));verts.push(x,h+rise*(1-Math.abs(x-mid)/half),z);}sh.dispose();}for(let j=0;j<r.length;j++){const p=r[j],q=r[(j+1)%r.length],hp=h+rise*(1-Math.abs(p.x-mid)/half),hq=h+rise*(1-Math.abs(q.x-mid)/half);verts.push(p.x,h,p.y,q.x,h,q.y,q.x,hq,q.y,p.x,h,p.y,q.x,hq,q.y,p.x,hp,p.y);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.computeVertexNormals();if(acrossZ){const pos=g.getAttribute('position');for(let i=0;i<pos.count;i++){const x=pos.getX(i);pos.setX(i,pos.getZ(i));pos.setZ(i,x);}g.computeVertexNormals();}add(g,c);}
 function stepped(x:number,y:number,z:number,w:number,h:number,angle=0){
  const pts:number[][]=[[-w/2,0],[w/2,0]];for(let k=0;k<5;k++){const yy=h*k/5,ww=w/2*(1-k/5);pts.push([ww,yy+h/5],[ww-w/10,yy+h/5]);}pts.push([0,h+.2]);for(let k=4;k>=0;k--){const yy=h*k/5,ww=w/2*(1-k/5);pts.push([-ww+w/10,yy+h/5],[-ww,yy+h/5]);}const shape=new T.Shape(pts.map(p=>new T.Vector2(p[0],p[1])));add(new T.ShapeGeometry(shape),'brick',x,y,z,angle);const tx=Math.cos(angle),tz=-Math.sin(angle),nx=Math.sin(angle),nz=Math.cos(angle);for(let i=1;i<pts.length-1;i++){const p=pts[i],q=pts[i+1];if(Math.abs(q[1]-p[1])>.01)continue;const mid=(p[0]+q[0])/2;box(x+mid*tx+nx*.06,y+p[1]-.02,z+mid*tz+nz*.06,Math.abs(q[0]-p[0])+.2,.16,.30,'stone',angle);}box(x,y+h,z,.25,.55,.28,'stone',angle);
 }
 function crossWindow(x:number,y:number,z:number,w:number,h:number,angle=0,shutters=false){pane(x,y,z,w,h,angle,'white');const nx=Math.sin(angle),nz=Math.cos(angle),tx=Math.cos(angle),tz=-Math.sin(angle);box(x+nx*.09,y+h*.43,z+nz*.09,w,.15,.15,'white',angle);if(shutters)for(const side of [-1,1]){const u=side*(w/2+.37);box(x+u*tx+nx*.10,y,z+u*tz+nz*.10,.59,h*.42,.13,'red',angle);for(const yy of [.22,h*.30])box(x+u*tx+nx*.18,y+yy,z+u*tz+nz*.18,.61,.075,.075,'dark',angle);}}
 function relief(x:number,y:number,z:number){add(new T.SphereGeometry(.20,6,4),'stone',x,y,z);box(x,y-.25,z,.12,.15,.12,'stone');}
 if(id==='huis-aan-drie-grachten'){
  shell(r,10.8,'brick');gable(r,10.8,4.5,'red',true);const cx=-.34,z=6.83,w=12.92;box(cx,.0,z,w,10.82,.22,'brick');
  for(const y of [0.6,4.7,9.3,10.65])box(cx,y,z+.11,w+.15,.14,.30,'stone');for(const x of [-6.4,5.72])for(let y=.8;y<10.7;y+=.55)box(x,y,z+.10,.30,.16,.28,'stone');
  for(let k=0;k<5;k++){const x=cx+(k-2)*2.35;crossWindow(x,.95,z+.20,1.65,3.25,0,k!==2);crossWindow(x,5.25,z+.20,1.65,2.62,0,true);add(new T.TorusGeometry(.87,.045,4,16,Math.PI),'stone',x,8.2,z+.24);add(new T.TorusGeometry(.87,.045,4,16,Math.PI),'stone',x,4.2,z+.24);if(k!==2)pane(x,-.02,z+.17,1.05,.46);}
  // Central entrance and central street-facing dormer gable, with crosswise
  // roof ridge and a stepped gable at each of the two canal-facing ends.
  box(cx,.3,z+.36,1.55,2.5,.16,'dark');add(new T.TorusGeometry(.65,.12,4,14,Math.PI),'stone',cx,2.43,z+.44);for(const x of [cx-.88,cx+.88])box(x,.15,z+.43,.25,2.65,.3,'stone');pediment(cx,2.94,z+.44,2.22,.55);for(let j=0;j<3;j++)box(cx,.06+j*.09,z+.66-j*.15,2.1,.1,.32,'stone');
  stepped(cx,10.4,z+.16,4.85,5.05);crossWindow(cx,11.1,z+.29,1.26,1.35,0,true);crossWindow(cx,13.13,z+.29,.82,1.08);gable(clip(clip(clip(r,cx-2.43,false),cx+2.43,true),-.35,false,'y'),10.8,4.5,'red');
  for(const k of [0,4]){const p=r[k],q=r[(k+1)%r.length],v=q.clone().sub(p),m=p.clone().add(q).multiplyScalar(.5),angle=-Math.atan2(v.y,v.x),nx=Math.sin(angle),nz=Math.cos(angle);stepped(m.x+nx*.10,10.7,m.y+nz*.10,v.length(),4.5,angle);crossWindow(m.x+nx*.22,1.8,m.y+nz*.22,1.38,2.62,angle,true);}
  // Brick chimneys and subtle parallel tile bands remain original geometry.
  for(const x of [-5.0,4.8]){box(x,13.5,-.38,.55,2.7,.7,'brick');box(x,16.1,-.38,.72,.22,.86,'stone');}for(let zt=-6.4;zt<6.7;zt+=.65){const xs:number[]=[];for(let i=0;i<r.length;i++){const p=r[i],q=r[(i+1)%r.length];if((p.y>zt)!==(q.y>zt))xs.push(p.x+(q.x-p.x)*(zt-p.y)/(q.y-p.y));}if(xs.length<2)continue;const lo=Math.min(...xs),hi=Math.max(...xs),y=10.8+4.5*(1-Math.abs(zt+.35)/7.05);box((lo+hi)/2,y+.025,zt,hi-lo,.028,.038,'brick');}
 }else{
  shell(r,12.35,'brick');sideWindows(r,12.35,true);const cx=.055,z=15.72,w=14.22;for(const [lo,hi]of [[-7.14,cx],[cx,7.14]])gable(clip(clip(r,lo,false),hi,true),12.35,4.15);
  box(cx,0,z,w,12.5,.26,'brick');for(const y of [.08,4.3,8.6,11.82])box(cx,y,z+.14,w+.18,.25,.34,'stone');for(const x of [cx-w/2+.13,cx+w/2-.13])for(let y=.3;y<12.3;y+=.62)box(x,y,z+.12,.45,.2,.35,'stone');
  for(let k=0;k<5;k++){const x=cx+(k-2)*2.62;crossWindow(x,.90,z+.22,1.60,3.1);crossWindow(x,5.07,z+.22,1.55,2.95);crossWindow(x,9.30,z+.22,1.65,2.1);for(const yy of [4.04,8.12,11.51]){add(new T.TorusGeometry(.83,.08,4,16,Math.PI),'stone',x,yy,z+.26);relief(x,yy+.55,z+.31);}}
  box(cx,.05,z+.42,1.25,2.8,.13,'dark');pane(cx,2.88,z+.46,1.28,.63);for(const x of [cx-.84,cx+.84])box(x,.05,z+.40,.25,3.42,.25,'stone');for(let j=0;j<3;j++)box(cx,.04+j*.13,z+.66-j*.2,1.95,.15,.30,'stone');
  // Both current restored facade tops stand within the same actual parent,
  // and Singel138 remains a separate neighboring building.
  for(const x of [cx-3.555,cx+3.555]){
   const outline=[[-3.55,0],[3.55,0],[2.9,1.1],[2.25,1.55],[1.65,2.5],[1.65,4.65],[1.82,4.65],[1.82,5.13],[.68,5.13],[.68,6.37],[0,6.67],[-.68,6.37],[-.68,5.13],[-1.82,5.13],[-1.82,4.65],[-1.65,4.65],[-1.65,2.5],[-2.25,1.55],[-2.9,1.1]];add(new T.ShapeGeometry(new T.Shape(outline.map(p=>new T.Vector2(p[0],p[1])))),'brick',x,12.2,z+.08);crossWindow(x,12.38,z+.28,2.45,1.68);for(const side of [-1,1]){box(x+side*1.45,12.20,z+.31,.22,2.07,.23,'stone');add(new T.TorusGeometry(.47,.16,4,12,Math.PI),'stone',x+side*2.4,13.38,z+.30);box(x+side*1.52,14.28,z+.26,.25,2.67,.20,'stone');}add(new T.TorusGeometry(.79,.15,4,16,Math.PI),'stone',x,15.0,z+.30);relief(x,15.48,z+.37);cornice(x,16.71,z+.22,3.78);box(x,17.40,z+.17,1.48,1.11,.26,'brick');pediment(x,18.55,z+.25,1.72,.49);for(const xx of [x-.63,x+.63])box(xx,17.41,z+.31,.20,1.08,.19,'stone');box(x,17.90,z+.34,.48,.24,.08,'stone');
  }
 }
}
