import * as T from 'three';
import {mergeGeometries} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import fs from 'node:fs/promises';
import {Document,NodeIO} from '@gltf-transform/core';
import {weld,dedup,prune,meshopt} from '@gltf-transform/functions';
import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
import {MeshoptEncoder} from 'meshoptimizer';
import {buildDorusTheusBrug} from './dorus-theus-brug-builder';
import spec from './dorus-theus-brug-spec.json';
import footprints from './dorus-theus-brug-footprints.json';
import type {BuildingTools} from './cultural-builders';
const doc=new Document(),buf=doc.createBuffer(),scene=doc.createScene(),groups=new Map<string,T.BufferGeometry[]>();
const b={add(g:T.BufferGeometry,c:string){const key=c+'|'+(g.userData.role??'detail');const a=groups.get(key)??[];a.push(g.index?g.toNonIndexed():g);groups.set(key,a)}} as BuildingTools;
buildDorusTheusBrug(0,0,b);let triangles=0;const roles:Record<string,number>={};
for(const [key,geometries]of groups){const[c,role]=key.split('|'),g=mergeGeometries(geometries)!;const material=doc.createMaterial(c).setBaseColorFactor([...new T.Color(spec.materialOverrides[c as keyof typeof spec.materialOverrides]).toArray(),1]).setRoughnessFactor(1).setMetallicFactor(0),p=g.getAttribute('position'),n=g.getAttribute('normal'),prim=doc.createPrimitive().setAttribute('POSITION',doc.createAccessor().setType('VEC3').setArray(new Float32Array(p.array)).setBuffer(buf)).setAttribute('NORMAL',doc.createAccessor().setType('VEC3').setArray(new Float32Array(n.array)).setBuffer(buf)).setMaterial(material).setExtras({role});scene.addChild(doc.createNode(role).setMesh(doc.createMesh(role).addPrimitive(prim)));triangles+=p.count/3;roles[role]=(roles[role]??0)+p.count/3;}
const out='artifacts/landmark-next-batch';await fs.mkdir(out,{recursive:true});await new NodeIO().write(`${out}/dorus-theus-brug-uncompressed.glb`,doc);await MeshoptEncoder.ready;await doc.transform(weld(),dedup(),prune(),meshopt({encoder:MeshoptEncoder,level:'medium'}));await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder}).write(`${out}/dorus-theus-brug.glb`,doc);const evidence={triangles,bytes:(await fs.stat(`${out}/dorus-theus-brug.glb`)).size,roles,materials:doc.getRoot().listMaterials().length,textures:doc.getRoot().listTextures().length};await fs.writeFile(`${out}/dorus-theus-brug-budget.json`,JSON.stringify(evidence,null,2)+'\n');console.log(evidence);
// Decode compressed geometry with its quantization node transforms before native open-water probes.
const {MeshoptDecoder}=await import('meshoptimizer');await MeshoptDecoder.ready;
const decoded=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(`${out}/dorus-theus-brug.glb`),group=new T.Group(),bounds=new T.Box3(),failures:string[]=[];let downwardTop=0;
for(const node of decoded.getRoot().listNodes())for(const p of node.getMesh()?.listPrimitives()??[]){const a=p.getAttribute('POSITION')!,normal=p.getAttribute('NORMAL')!,g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(Array.from({length:a.getCount()},(_,i)=>a.getElement(i,[])).flat(),3));g.setAttribute('normal',new T.Float32BufferAttribute(Array.from({length:normal.getCount()},(_,i)=>normal.getElement(i,[])).flat(),3));if(p.getIndices())g.setIndex(Array.from(p.getIndices()!.getArray()!));g.applyMatrix4(new T.Matrix4().fromArray(node.getWorldMatrix()));g.computeBoundingBox();bounds.union(g.boundingBox!);const mesh=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));mesh.userData.role=p.getExtras().role;group.add(mesh);if(['gabion-rim','filter-soil','pier-top'].includes(mesh.userData.role)){const pos=g.getAttribute('position'),ix=g.index;for(let i=0;i<(ix?.count??pos.count);i+=3){const v=[0,1,2].map(k=>new T.Vector3().fromBufferAttribute(pos,ix?ix.getX(i+k):i+k));if(v[1].clone().sub(v[0]).cross(v[2].clone().sub(v[0])).y<-.00001)downwardTop++}}}
group.updateMatrixWorld(true);const ray=(x:number,z:number)=>new T.Raycaster(new T.Vector3(x,4,z),new T.Vector3(0,-1,0)).intersectObjects(group.children).map(h=>({role:h.object.userData.role,y:h.point.y}));const probes:Record<string,ReturnType<typeof ray>>={middleWalk:ray(5,.45),northGapWater:ray(5,-1.2),southGapWater:ray(5,2.1),northWater:ray(-8,-6),southWater:ray(-8,7),southBridge:ray(22.65,7.7)};
if(probes.middleWalk[0]?.role!=='deck-plank')failures.push('Middle walking surface not first hit');if(probes.southBridge[0]?.role!=='deck-plank')failures.push('Southern bridge walking surface not first hit');for(const name of['northGapWater','southGapWater','northWater','southWater'])if(probes[name].length)failures.push(name+' wrongly covered');if(downwardTop)failures.push('Downward top faces');const broaderProbes:{category:string,x:number,z:number,firstRole:string|null,passed:boolean}[]=[];
const pointDistance=(p:number[],a:number[],q:number[])=>{const x=q[0]-a[0],z=q[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*x+(p[1]-a[1])*z)/(x*x+z*z)));return Math.hypot(p[0]-a[0]-t*x,p[1]-a[1]-t*z)};
const paths=footprints.selectedFeatures.filter(f=>f.tags.highway==='footway').map(f=>f.localEastSouthMetres);
const inside=(p:number[],ps:number[][])=>{let hit=false;for(let i=0,j=ps.length-1;i<ps.length;j=i++){const a=ps[i],q=ps[j];if((a[1]>p[1])!==(q[1]>p[1])&&p[0]<(q[0]-a[0])*(p[1]-a[1])/(q[1]-a[1])+a[0])hit=!hit}return hit};
const sourcePier=footprints.selectedFeatures.find(f=>f.id==='w626223371')!.localEastSouthMetres;
const nearestPath=(p:number[])=>Math.min(...paths.flatMap(ps=>ps.slice(1).map((q,i)=>pointDistance(p,ps[i],q))));
for(const ps of paths)for(let i=1;i<ps.length;i++){const a=ps[i-1],q=ps[i],length=Math.hypot(q[0]-a[0],q[1]-a[1]),nx=-(q[1]-a[1])/length,nz=(q[0]-a[0])/length;for(let u=.15;u<length-.1;u+=.7)for(const side of[-.35,0,.35]){const x=a[0]+(q[0]-a[0])*u/length+nx*side,z=a[1]+(q[1]-a[1])*u/length+nz*side,first=ray(x,z)[0];const exposedRoles=['deck-plank','pier-top','pier-seam'];const passed=exposedRoles.includes(first?.role??'')||[-.008,.008].some(offset=>exposedRoles.includes(ray(x+(q[0]-a[0])/length*offset,z+(q[1]-a[1])/length*offset)[0]?.role??''));broaderProbes.push({category:'fractional walking surface',x,z,firstRole:first?.role??null,passed});}}
for(const f of footprints.selectedFeatures.filter(f=>f.tags.landuse==='grass')){const ps=f.localEastSouthMetres.slice(0,-1),centre=ps.reduce((a,p)=>[a[0]+p[0]/ps.length,a[1]+p[1]/ps.length],[0,0]);for(let i=0;i<ps.length;i++){const a=ps[i],q=ps[(i+1)%ps.length];for(const t of[.2,.5,.8]){const x=a[0]+(q[0]-a[0])*t,z=a[1]+(q[1]-a[1])*t,d=Math.hypot(x-centre[0],z-centre[1]),dx=(x-centre[0])/d,dz=(z-centre[1])/d;const outside=[x+dx*.75,z+dz*.75];if(nearestPath(outside)>.75&&!inside(outside,sourcePier)){const first=ray(...outside as[number,number])[0];broaderProbes.push({category:'water outside exact gabion perimeter',x:outside[0],z:outside[1],firstRole:first?.role??null,passed:!first});}const rim=[x-dx*.09,z-dz*.09];if(nearestPath(rim)>.7){const first=ray(...rim as[number,number])[0];broaderProbes.push({category:'gabion rim top visible',x:rim[0],z:rim[1],firstRole:first?.role??null,passed:first?.role==='gabion-rim'});}}}}
const materialValues=decoded.getRoot().listMaterials().map(m=>({name:m.getName(),metallic:m.getMetallicFactor(),roughness:m.getRoughnessFactor()}));if(materialValues.some(m=>m.metallic!==0))failures.push('Nonzero metallic material');for(const p of broaderProbes)if(!p.passed)failures.push(p.category+' failed at '+p.x.toFixed(3)+','+p.z.toFixed(3));const {createHash}=await import('node:crypto');const geometryEvidence={sha256:createHash('sha256').update(await fs.readFile(`${out}/dorus-theus-brug.glb`)).digest('hex'),scope:'Decoded compressed draft CPU geometry; native gallery/live-game/route/pin/card/suppression/pan acceptance pending',bounds,downwardTop,probes,materialValues,broaderProbes,failures};await fs.writeFile(`${out}/dorus-theus-brug-geometry-check.json`,JSON.stringify(geometryEvidence,null,2)+'\n');console.log({...geometryEvidence,broaderProbes:{count:broaderProbes.length,failed:broaderProbes.filter(p=>!p.passed)}});if(failures.length)process.exitCode=1;
