import * as T from 'three';
import type {BuildingTools} from './cultural-builders';
import data from './dungeon-footprints.json';
/** Current venue scope is two actual parents, not the entire protected block. */
export function buildDungeonLandmark(_id:string,_w:number,_d:number,b:BuildingTools){
 const {add,box,sign}=b,s=data.sites[0],a=s.authorHeadingDegrees*Math.PI/180;
 const point=(p:number[])=>{const e=(p[0]-s.anchor[0])*111320*Math.cos(s.anchor[1]*Math.PI/180),n=(p[1]-s.anchor[1])*110540;return new T.Vector2(e*Math.sin(a)+n*Math.cos(a),e*Math.cos(a)-n*Math.sin(a));};
 const rings=s.buildings.map(f=>f.geometry.coordinates[0][0].slice(0,-1).map(point)),church=rings[0],front=rings[1];
 function clip(r:T.Vector2[],v:number,less:boolean,axis:'x'|'y'='x'){const out:T.Vector2[]=[];for(let i=0;i<r.length;i++){const p=r[i],q=r[(i+1)%r.length],pin=less?p[axis]<=v:p[axis]>=v,qin=less?q[axis]<=v:q[axis]>=v;if(pin)out.push(p);if(pin!==qin)out.push(p.clone().lerp(q,(v-p[axis])/(q[axis]-p[axis])));}return out;}
 function region(r:T.Vector2[],bounds:number[]){for(const [axis,v,less]of [['x',bounds[0],false],['x',bounds[1],true],['y',bounds[2],false],['y',bounds[3],true]]as const)r=clip(r,v,less,axis);return r;}
 function shell(r:T.Vector2[],h:number){if(r.length<3)return;const g=new T.ExtrudeGeometry(new T.Shape(r),{depth:h,bevelEnabled:false});g.rotateX(Math.PI/2);g.translate(0,h,0);add(g,'brick');}
 function roof(r:T.Vector2[],y:number,top:number,ridge:number,half:number){if(r.length<3)return;const verts:number[]=[],height=(p:T.Vector2)=>y+(top-y)*Math.max(0,1-Math.abs(p.x-ridge)/half);for(const left of [true,false]){const p=clip(r,ridge,left);if(p.length<3)continue;const g=new T.ShapeGeometry(new T.Shape(p)),pos=g.getAttribute('position'),ix=g.index!;for(let i=0;i<ix.count;i++){const q=new T.Vector2(pos.getX(ix.getX(i)),pos.getY(ix.getX(i)));verts.push(q.x,height(q),q.y);}g.dispose();}for(let i=0;i<r.length;i++){const p=r[i],q=r[(i+1)%r.length];verts.push(p.x,y,p.y,q.x,y,q.y,q.x,height(q),q.y,p.x,y,p.y,q.x,height(q),q.y,p.x,height(p),p.y);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.computeVertexNormals();add(g,'slate');}
 function wing(r:T.Vector2[],bounds:number[],h:number,top:number){const p=region(r,bounds);shell(p,h);const x=p.map(p=>p.x),lo=Math.min(...x),hi=Math.max(...x);roof(p,h,top,(lo+hi)/2,(hi-lo)/2);}
 // Low rooms and annexes follow the parent perimeter rather than a site box.
 shell(church,7.3);wing(church,[-30,-10,-30,3],11.55,15.72);wing(church,[10.6,30,-30,3],7.3,10.92);wing(church,[-30,30,-30,-14.35],7.3,10.47);
 const stem=region(church,[-4.05,1.12,2.55,30]);shell(stem,13.33);roof(stem,13.33,17.80,-1.46,2.6);shell(front,13.3);roof(front,13.3,17.78,4.03,3.09);
 // An original regular octagon lies entirely inside the actual central chapel.
 const cx=-1.52,cz=-6.52,radius=8.48,oct=Array.from({length:8},(_,i)=>new T.Vector2(cx+radius*Math.cos(Math.PI/8+i*Math.PI/4),cz+radius*Math.sin(Math.PI/8+i*Math.PI/4)));shell(oct,17.85);
 const roofVertices:number[]=[],topR=1.54;for(let i=0;i<8;i++){const p=oct[i],q=oct[(i+1)%8],u=p.clone().sub(new T.Vector2(cx,cz)).multiplyScalar(topR/radius).add(new T.Vector2(cx,cz)),v=q.clone().sub(new T.Vector2(cx,cz)).multiplyScalar(topR/radius).add(new T.Vector2(cx,cz));roofVertices.push(p.x,17.85,p.y,q.x,17.85,q.y,v.x,24.68,v.y,p.x,17.85,p.y,v.x,24.68,v.y,u.x,24.68,u.y);}
 const roofG=new T.BufferGeometry();roofG.setAttribute('position',new T.Float32BufferAttribute(roofVertices,3));roofG.computeVertexNormals();add(roofG,'slate');
 function pane(x:number,y:number,z:number,w:number,h:number,angle=0){const nx=Math.sin(angle),nz=Math.cos(angle);add(new T.PlaneGeometry(w+.23,h+.20),'stone',x,y+h/2,z,angle);add(new T.PlaneGeometry(w,h),'glass',x+nx*.03,y+h/2,z+nz*.03,angle);box(x+nx*.07,y,z+nz*.07,.07,h,.10,'white',angle);box(x+nx*.075,y+h*.7,z+nz*.075,w,.07,.10,'white',angle);box(x+nx*.07,y-.16,z+nz*.07,w+.38,.18,.32,'stone',angle);}
 function arch(x:number,y:number,z:number,w:number,h:number,angle=0){const nx=Math.sin(angle),nz=Math.cos(angle),shape=new T.Shape();shape.moveTo(-w/2,0);shape.lineTo(w/2,0);shape.lineTo(w/2,h-w/2);shape.absarc(0,h-w/2,w/2,0,Math.PI,false);shape.closePath();add(new T.ShapeGeometry(shape,12),'glass',x,y,z,angle);add(new T.TorusGeometry(w/2+.09,.10,4,14,Math.PI),'stone',x+nx*.06,y+h-w/2,z+nz*.06,angle);const tx=Math.cos(angle),tz=-Math.sin(angle);for(const u of [-w/2-.09,w/2+.09,0])box(x+u*tx+nx*.10,y,z+u*tz+nz*.10,u===0?.07:.18,h-w/2,.18,'stone',angle);box(x+nx*.12,y+h*.68,z+nz*.12,w,.08,.12,'white',angle);}
 function bands(p:T.Vector2[],ys:number[]){for(let i=0;i<p.length;i++){const u=p[i],v=p[(i+1)%p.length],d=v.clone().sub(u),m=u.clone().add(v).multiplyScalar(.5);for(const y of ys)box(m.x,y,m.y,d.length(),.16,.26,'stone',-Math.atan2(d.y,d.x));}}
 bands(oct,[.7,5.9,11.6,17.56]);for(let i=0;i<8;i++){const p=oct[i],q=oct[(i+1)%8],m=p.clone().add(q).multiplyScalar(.5),n=m.clone().sub(new T.Vector2(cx,cz)).normalize(),angle=Math.atan2(n.x,n.y);arch(m.x+n.x*.10,8.4,m.y+n.y*.10,3.42,6.6,angle);add(new T.TorusGeometry(.64,.10,4,12),'stone',m.x+n.x*.22,14.33,m.y+n.y*.22,angle);for(const u of [-1.06,1.06])box(m.x+u*Math.cos(angle)+n.x*.18,8.44,m.y-u*Math.sin(angle)+n.y*.18,.07,5.02,.08,'white',angle);}
 // Open-column lantern, rail and modest finial; no opaque central tower box.
 add(new T.CylinderGeometry(1.72,1.72,.25,8),'stone',cx,24.72,cz);for(let i=0;i<8;i++){const a=i*Math.PI/4+Math.PI/8,x=cx+1.40*Math.cos(a),z=cz+1.40*Math.sin(a);box(x,24.8,z,.18,2.15,.18,'stone');}add(new T.CylinderGeometry(1.65,1.65,.24,8),'stone',cx,26.99,cz);add(new T.CylinderGeometry(.92,1.68,.84,8),'slate',cx,27.53,cz);for(let i=0;i<8;i++){const a=i*Math.PI/4,x=cx+1.59*Math.cos(a),z=cz+1.59*Math.sin(a);box(x,27.05,z,.10,.40,.10,'stone');}add(new T.CylinderGeometry(.10,.90,.66,8),'slate',cx,28.28,cz);box(cx,28.61,cz,.08,.68,.08,'dark');
 // Both museum gabled frontage sections are actual parent geometry. The
 // neighboring corner dome and other protected shops remain separate.
 for(const [x,w,z]of [[-1.46,5.0,16.06],[5.72,2.96,16.15]]){box(x,.0,z,w,.90,.18,'stone');for(const y of [.90,5.17,9.60,13.24])box(x,y,z,w,.19,.29,'stone');for(let k=0;k<3;k++){const xx=x+(k-1)*w*.285;pane(xx,1.45,z+.13,w*.25,3.27);arch(xx,5.78,z+.14,w*.25,3.2);arch(xx,10.06,z+.14,w*.25,2.83);}const sh=new T.Shape([new T.Vector2(-w/2,0),new T.Vector2(w/2,0),new T.Vector2(0,4.60)]);add(new T.ShapeGeometry(sh),'brick',x,13.25,z);for(const side of [-1,1]){const v=new T.Vector3(side*w/2,-4.6,0),g=new T.BoxGeometry(.13,v.length(),.22);g.applyQuaternion(new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),v.normalize()));add(g,'stone',x+side*w/4,15.55,z+.12);}pane(x,14.42,z+.17,.62,1.46);box(x,17.63,z,.24,.62,.24,'stone');add(new T.SphereGeometry(.16,6,4),'stone',x,18.33,z);}
 // Mapped door is recessed at x3.61,z14.52, not a bounding-box entrance.
 const ex=3.61,ez=14.56;box(ex,.08,ez,1.40,3.2,.11,'dark');for(const x of [ex-.92,ex+.92])box(x,.0,ez+.08,.25,3.56,.33,'stone');add(new T.TorusGeometry(.86,.20,4,16,Math.PI),'stone',ex,3.2,ez+.21);const top=new T.Shape([new T.Vector2(-1.12,0),new T.Vector2(1.12,0),new T.Vector2(0,1.25)]);add(new T.ShapeGeometry(top),'stone',ex,4.32,ez+.09);box(ex,4.11,ez+.20,2.02,.20,.34,'stone');box(ex,5.27,ez+.11,.28,.39,.24,'stone');sign('DUNGEON',ex,4.48,ez+.26,.041,'red');for(let i=0;i<3;i++)box(ex,.06+i*.11,ez+.31-i*.16,1.76,.12,.30,'stone');
 bands(front,[.72,5.20,9.58,13.20]);bands(stem,[.72,5.20,9.58,13.20]);
 // Side-street rooms receive subdued openings at their actual lower heights.
 for(const r of [church]){let area=0;for(let i=0;i<r.length;i++)area+=r[i].x*r[(i+1)%r.length].y-r[(i+1)%r.length].x*r[i].y;for(let i=0;i<r.length;i++){const p=r[i],q=r[(i+1)%r.length],v=q.clone().sub(p),len=v.length();if(len<3.5||p.y>13&&q.y>13)continue;const t=v.clone().normalize(),n=new T.Vector2(t.y,-t.x).multiplyScalar(area>0?1:-1),angle=Math.atan2(n.x,n.y),count=Math.round(len/3.2);for(let j=0;j<count;j++){const pt=p.clone().addScaledVector(t,len*(j+.5)/count).addScaledVector(n,.06);pane(pt.x,1.05,pt.y,1.35,2.45,angle);if(Math.abs(pt.x)>10&&pt.x<0)pane(pt.x,5.1,pt.y,1.35,2.4,angle);}}}
}
