import * as T from 'three';
import type {BuildingTools} from './cultural-builders';
import data from './eastern-bank-museum-footprints.json';
type Colour=Parameters<BuildingTools['add']>[1];
/** Original museum buildings, retaining surveyed parent polygons and open courts. */
export function buildEasternBankMuseumLandmark(id:string,w:number,d:number,b:BuildingTools){
 const {add,box,sign,clock}=b,s=data.sites.find(s=>s.id===id)!,heading=s.authorHeadingDegrees*Math.PI/180;
 const point=(p:number[])=>{const e=(p[0]-s.anchor[0])*111320*Math.cos(s.anchor[1]*Math.PI/180),n=(p[1]-s.anchor[1])*110540;return new T.Vector2(e*Math.sin(heading)+n*Math.cos(heading),e*Math.cos(heading)-n*Math.sin(heading));};
 const polygons=(f:any):T.Vector2[][][]=>f.geometry.coordinates.map((poly:number[][][])=>poly.map(r=>r.slice(0,-1).map(point)));
 const parent=polygons(s.buildings[0]);
 function mesh(v:number[],c:Colour){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.computeVertexNormals();add(g,c);}
 function shell(poly:T.Vector2[][],h:number,c:Colour){const sh=new T.Shape(poly[0]);sh.holes=poly.slice(1).map(r=>new T.Path(r));const g=new T.ExtrudeGeometry(sh,{depth:h,bevelEnabled:false});g.rotateX(Math.PI/2);g.translate(0,h,0);add(g,c);}
 function pane(x:number,y:number,z:number,pw:number,ph:number,a=0,c:Colour='white',sash=true){const nx=Math.sin(a),nz=Math.cos(a);add(new T.PlaneGeometry(pw+.22,ph+.22),c,x,y+ph/2,z,a);add(new T.PlaneGeometry(pw,ph),'glass',x+nx*.03,y+ph/2,z+nz*.03,a);if(sash){add(new T.PlaneGeometry(.065,ph),'white',x+nx*.06,y+ph/2,z+nz*.06,a);for(let yy=.75;yy<ph;yy+=1.1)add(new T.PlaneGeometry(pw,.06),'white',x+nx*.065,y+yy,z+nz*.065,a);}box(x+nx*.08,y-.12,z+nz*.08,pw+.35,.15,.25,c,a);}
 function beam(a:T.Vector3,c:T.Vector3,r:number,col:Colour){let delta=c.clone().sub(a),g=new T.CylinderGeometry(r,r,delta.length(),5);g.applyQuaternion(new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize()));const mid=a.clone().add(c).multiplyScalar(.5);add(g,col,mid.x,mid.y,mid.z);}
 function clip(r:T.Vector2[],cut:number,left:boolean,axis:'x'|'y'='x'){const out:T.Vector2[]=[];for(let i=0;i<r.length;i++){const a=r[i],c=r[(i+1)%r.length],ain=left?a[axis]<=cut:a[axis]>=cut,cin=left?c[axis]<=cut:c[axis]>=cut;if(ain)out.push(a);if(ain!==cin){const t=(cut-a[axis])/(c[axis]-a[axis]);out.push(a.clone().lerp(c,t));}}return out;}
 function cap(poly:T.Vector2[][],y:number,rise:number,c:Colour='slate',pyramid=false,axisAngle=0,frustum=false){
  const u=(p:T.Vector2)=>p.x*Math.cos(axisAngle)+p.y*Math.sin(axisAngle),v=(p:T.Vector2)=>-p.x*Math.sin(axisAngle)+p.y*Math.cos(axisAngle),us=poly[0].map(u),vs=poly[0].map(v),lo=Math.min(...us),hi=Math.max(...us),vl=Math.min(...vs),vh=Math.max(...vs),cx=(lo+hi)/2,cz=(vl+vh)/2,half=(hi-lo)/2,hz=(vh-vl)/2;
  const roofHeight=(p:T.Vector2)=>y+.03+rise*(pyramid?Math.max(0,Math.min(1-Math.abs(u(p)-cx)/half,1-Math.abs(v(p)-cz)/hz)):Math.max(0,Math.min(1,(frustum?2:1)*(1-Math.abs(u(p)-cx)/half))));
  const shape=new T.Shape(poly[0]);shape.holes=poly.slice(1).map(r=>new T.Path(r));const g=new T.ShapeGeometry(shape),pos=g.getAttribute('position'),ix=g.index!,out:number[]=[];
  for(let i=0;i<ix.count;i+=3){let tri=[0,1,2].map(k=>new T.Vector2(pos.getX(ix.getX(i+k)),pos.getY(ix.getX(i+k))));if(pyramid){const centre=new T.Vector2(cx*Math.cos(axisAngle)-cz*Math.sin(axisAngle),cx*Math.sin(axisAngle)+cz*Math.cos(axisAngle));for(let k=0;k<3;k++){const a=tri[k],c=tri[(k+1)%3];out.push(a.x,roofHeight(a),a.y,c.x,roofHeight(c),c.y,centre.x,roofHeight(centre),centre.y);}}else{const local=tri.map(p=>new T.Vector2(u(p),v(p)));const cuts=frustum?[lo,lo+half*.5,cx,hi-half*.5,hi]:[lo,cx,hi];for(let ci=0;ci<cuts.length-1;ci++){const r=clip(clip(local,cuts[ci],false),cuts[ci+1],true);for(let k=1;k<r.length-1;k++)for(const p of [r[0],r[k],r[k+1]]){const q=new T.Vector2(p.x*Math.cos(axisAngle)-p.y*Math.sin(axisAngle),p.x*Math.sin(axisAngle)+p.y*Math.cos(axisAngle));out.push(q.x,roofHeight(q),q.y);}}}}
  // Pyramid footprints are rectangles in mapped KIT tower parts. Fan once
  // around their actual perimeter rather than overlapping each base triangle.
  if(pyramid){out.length=0;const mid=new T.Vector2(cx*Math.cos(axisAngle)-cz*Math.sin(axisAngle),cx*Math.sin(axisAngle)+cz*Math.cos(axisAngle));const r=poly[0];for(let i=0;i<r.length;i++){const a=r[i],c=r[(i+1)%r.length];out.push(a.x,y+.03,a.y,c.x,y+.03,c.y,mid.x,y+rise+.03,mid.y);}}
  mesh(out,c);
  if(!pyramid)for(const r of poly)for(let i=0;i<r.length;i++){const a=r[i],e=r[(i+1)%r.length],du=u(e)-u(a),ts=(frustum?[lo+half*.5,cx,hi-half*.5]:[cx]).map(cut=>(cut-u(a))/du).filter(t=>t>0&&t<1).sort((a,c)=>a-c),pts=[a,...ts.map(t=>a.clone().lerp(e,t)),e];for(let k=0;k<pts.length-1;k++){const a=pts[k],e=pts[k+1];mesh([a.x,y,a.y,e.x,y,e.y,e.x,roofHeight(e),e.y,a.x,y,a.y,e.x,roofHeight(e),e.y,a.x,roofHeight(a),a.y],id==='allard-pierson'?'stone':'brick');}}
 }
 function walls(poly:T.Vector2[][],h:number,spacing=4.5,col:Colour='stone'){for(const r of poly){let area=0;for(let i=0;i<r.length;i++)area+=r[i].x*r[(i+1)%r.length].y-r[(i+1)%r.length].x*r[i].y;for(let i=0;i<r.length;i++){const a=r[i],e=r[(i+1)%r.length],delta=e.clone().sub(a),len=delta.length();if(len<3.7)continue;const tangent=delta.clone().normalize(),normal=new T.Vector2(tangent.y,-tangent.x).multiplyScalar(area>0?1:-1),angle=Math.atan2(normal.x,normal.y),mid=a.clone().add(e).multiplyScalar(.5),count=Math.max(1,Math.round(len/spacing));box(mid.x+normal.x*.07,h-.22,mid.y+normal.y*.07,len,.28,.32,col,angle);for(const y of h>12?[2.1,7.0,12.2,17.5,22.7].filter(y=>y+3.2<h):[1.0])for(let k=0;k<count;k++){const p=a.clone().addScaledVector(tangent,len*(k+.5)/count).addScaledVector(normal,.1);pane(p.x,y,p.y,Math.min(1.85,len/count*.65),h>12?3.1:Math.min(2.0,h-1.5),angle);}}}}
 function pediment(x:number,y:number,z:number,width:number,height:number,col:Colour='stone'){const sh=new T.Shape();sh.moveTo(-width/2,0);sh.lineTo(width/2,0);sh.lineTo(0,height);sh.closePath();add(new T.ShapeGeometry(sh),col,x,y,z);box(x,y,z,width,.2,.35,col);beam(new T.Vector3(x-width/2,y,z+.08),new T.Vector3(x,y+height,z+.08),.11,'white');beam(new T.Vector3(x,y+height,z+.08),new T.Vector3(x+width/2,y,z+.08),.11,'white');}
 function arch(x:number,y:number,z:number,width:number,height:number){const sh=new T.Shape();sh.moveTo(-width/2,0);sh.lineTo(width/2,0);sh.lineTo(width/2,height-width/2);sh.absarc(0,height-width/2,width/2,0,Math.PI,false);sh.closePath();add(new T.ShapeGeometry(sh,12),'dark',x,y,z);add(new T.TorusGeometry(width/2+.12,.13,4,12,Math.PI),'stone',x,y+height-width/2,z+.03);box(x,y,z+.08,.08,height,.1,'frame');box(x,y+height-width/2,z+.08,width,.08,.1,'frame');}
 if(id==='wereldmuseum-amsterdam'){
  // All 38 mapped KIT portions: the museum light court is glass-roofed,
  // while the actual courtyard between museum and institute stays open.
  for(const f of s.parts){const pr=f.properties as any,top=Number(pr.height)||18,rise=Number(pr['roof:height'])|| (pr['roof:shape']==='fustrum'?4.5:0),eave=top-rise,poly=polygons(f);for(const p of poly){shell(p,eave,'brick');walls(p,eave,5.2);const roof=pr['roof:shape'],xs=p[0].map(p=>p.x),zs=p[0].map(p=>p.y),across=pr['roof:orientation']==='across';let angle=(Math.max(...xs)-Math.min(...xs) > Math.max(...zs)-Math.min(...zs)?Math.PI/2:0)+(across?Math.PI/2:0);cap(p,eave,rise,pr['roof:material']==='glass'?'glass':'slate',roof==='pyramidal',angle,roof==='fustrum');}}
  // Clock and small green metal lanterns mark the two entrance towers.
  for(const x of [-31.8,3.0]){box(x,28.1,77.2,11.9,.4,.48,'stone');box(x,32.0,76.0,3.6,3.7,2.4,'stone');pediment(x,35.7,77.3,3.8,1.3);if(x>0){add(new T.CircleGeometry(1.18,16),'dark',x,33.85,77.38);add(new T.TorusGeometry(1.2,.08,4,16),'gold',x,33.85,77.42);for(let k=0;k<12;k++){const a=k*Math.PI/6;box(x+.98*Math.sin(a),33.85+.98*Math.cos(a)-.05,77.46,.065,.13,.04,'gold',-a);}box(x,33.85,77.5,.07,.8,.045,'gold');box(x+.25,33.81,77.51,.6,.07,.045,'gold');}else pane(x,32.4,77.36,1.65,2.7,0,'stone',false);add(new T.CylinderGeometry(.65,1.45,1.8,8),'frame',x,40.9,70.7);add(new T.SphereGeometry(1,8,5),'frame',x,42.0,70.7);add(new T.ConeGeometry(.6,1.35,8),'gold',x,43.0,70.7);box(x,43.6,70.7,.06,1.0,.06,'dark');}
  // Sculpted central Renaissance gable, crossing stone bands and mullions.
  const gx=-14.0,z=80.4;pediment(gx,18.1,z,12.4,8.5,'brick');for(const yy of [18.2,20.2,22.0,23.8])box(gx,yy,z+.09,Math.max(2,12.4-(yy-18.1)*1.3),.24,.35,'stone');for(let u of [-3.6,0,3.6])pane(gx+u,17.3,z+.18,2.3,3.65);pane(gx,21.8,z+.18,2.2,2.3);add(new T.TorusGeometry(.65,.15,5,12),'stone',gx,24.7,z+.15);box(gx,1.0,z+.22,13.1,1.3,.5,'stone');arch(gx,1.2,z+.4,4.0,4.0);sign('WERELDMUSEUM',gx,2.0,z+.55,.21,'dark');
  for(let x=-34;x<=7;x+=4.6)for(let y of [5.4,10.5,16.0,21.3,27.0])box(x,y,78.0,.35,.35,.12,'stone');
 }else if(id==='dutch-resistance-museum'){
  for(const p of parent){shell(p,4.8,'brick');cap(p,4.8,.7);walls(p,4.8,4.8);const front=clip(p[0],20.9,false,'y');shell([front],15.7,'brick');cap([front],15.7,1.3);}
  const x=17.6,z=31.47;box(x,0,z,21.9,15.5,.26,'stone');for(let yy of [4.75,9.9,14.7,15.7])box(x,yy,z+.13,22.6,.25,.5,'stone');for(let u of [-8.5,-4.25,0,4.25,8.5]){pane(x+u,5.5,z+.2,2.2,3.9,0,'stone',false);pane(x+u,10.4,z+.2,2.2,3.6,0,'stone',false);add(new T.PlaneGeometry(.10,3.9),'dark',x+u,7.45,z+.28);add(new T.PlaneGeometry(.10,3.6),'dark',x+u,12.2,z+.28);box(x+u,7.6,z+.3,2.2,.1,.06,'dark');box(x+u,12.3,z+.3,2.2,.1,.06,'dark');pediment(x+u,9.55,z+.24,2.8,.6);}
  arch(x-6.2,0,z+.35,5.0,4.5);arch(x+6.2,0,z+.35,5.0,4.5);arch(x,0,z+.36,2.0,4.1);pediment(x,15.0,z+.34,12.0,2.8);sign('PLANCIUS',x,15.75,z+.46,.20,'dark');const star=new T.Shape();for(let i=0;i<12;i++){let a=Math.PI/2+i*Math.PI/6,r=i%2?.25:.5;i?star.lineTo(Math.cos(a)*r,Math.sin(a)*r):star.moveTo(Math.cos(a)*r,Math.sin(a)*r);}star.closePath();add(new T.ShapeGeometry(star),'dark',x,16.7,z+.49);sign('VERZETS',x+6.2,3.4,z+.52,.12,'white');sign('MUSEUM',x+6.2,2.8,z+.52,.12,'white');box(x+8.8,3.2,z+.5,1.0,2.7,.12,'red');
  for(let u=-10.4;u<=10.4;u+=1.0)box(x+u,15.05,z+.28,.18,.65,.4,'stone');
 }else{
  // Five measured cadastral sections distinguish the former bank front from
  // the connected UvA ranges; the irregular outside edge remains exact.
  const cuts=[-61,-28,0,27,39.6,46.4,56],heights=[15.8,16.5,16.7,17.2,18.9,18.9];
  for(const p of parent)for(let i=0;i<cuts.length-1;i++){let r=clip(clip(p[0],cuts[i],false,'y'),cuts[i+1],true,'y');if(i===4)r=clip(r,-8,true);if(r.length<3)continue;shell([r],heights[i],i>=4?'stone':'brick');cap([r],heights[i],i>=4?3.0:3.6);walls([r],heights[i],4.0);}
  const x=-15.3,z=54.96;box(x,0,z,24.1,5.0,.32,'stone');box(x,5.0,z,24.1,13.8,.30,'frame');for(let yy of [1.1,5.05,5.55,18.6,19.1])box(x,yy,z+.2,24.6,.26,.45,'stone');for(let u=-10.9;u<=10.9;u+=2.72){pane(x+u,1.6,z+.24,1.75,2.25,0,'stone',false);pane(x+u,7.1,z+.24,1.75,6.7,0,'stone',false);pane(x+u,15.4,z+.24,1.6,.85,0,'stone',false);box(x+u+1.16,5.7,z+.25,.24,12.6,.2,'stone');box(x+u,13.9,z+.29,2.2,.23,.3,'stone');pediment(x+u,14.25,z+.26,2.2,.7);}
  pediment(x,19.15,z+.4,10.2,3.5);for(let u of [-5.2,0,5.2])add(new T.IcosahedronGeometry(.5,0),'stone',x+u,22.8,z+.34);box(x-10.4,.1,z+.38,3.8,5.1,.15,'dark');box(x-10.4,5.1,z+.4,4.2,.45,.5,'stone');sign('ALLARD PIERSON',x-1.0,4.15,z+.5,.145,'dark');for(let yy=1;yy<5;yy+=.6)box(x+10.9,yy,z+.3,2.5,.06,.05,'frame');
  // Transparent PRO infill occupies the mapped notch behind the entrance;
  // its sloping roof and thin dark framing stay within the bank footprint.
  box(-5.8,0,43.0,4.4,5.0,6.8,'stone');box(-5.8,5.0,43.0,4.4,12.1,6.8,'glass');for(let u=-7.8;u<-3.5;u+=.85)box(u,5.0,46.46,.07,12.1,.10,'dark');for(let yy of [5.0,9.1,13.3,17.1])box(-5.8,yy,46.47,4.4,.08,.12,'dark');cap([[new T.Vector2(-8,39.6),new T.Vector2(-3.6,39.6),new T.Vector2(-3.6,46.4),new T.Vector2(-8,46.4)]],17.1,2.2,'glass');
 }
}
