import * as T from 'three';import assert from 'node:assert/strict';import {buildFireStationDirk} from './fire-station-dirk-builder';import type {BuildingTools} from './cultural-builders';import source from './fire-station-dirk-footprints.json';
const group=new T.Group(),panes:T.Mesh[]=[],roof:T.BufferGeometry[]=[],parts:T.BufferGeometry[]=[];
const add:BuildingTools['add']=(g,c,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));m.userData={...g.userData,colour:c};group.add(m);parts.push(g);if(g.userData.tag==='pane')panes.push(m);if(g.userData.tag==='roof')roof.push(g)};
const unused=()=>{throw Error('unused')};buildFireStationDirk(0,0,{add,box(x,y,z,w,h,d,c,a=0){add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a)},window:unused,clock:unused,sign:unused,hip:unused,prism:unused,gableRoof:unused});group.updateMatrixWorld(true);
const bounds=new T.Box3().setFromObject(group);assert(bounds.min.y>=-.01&&bounds.max.y<17,'finite native height bounds');for(const g of parts)for(const v of g.getAttribute('position').array)assert(Number.isFinite(v));
let faces=0;for(const g of roof){const p=g.getAttribute('position');for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2),n=b.sub(a).cross(c.sub(a));if(n.length()>1e-6){assert(n.y>0,'upward roof winding');faces++}}}
const ang=source.localRotationRadians,c=Math.cos(ang),s=Math.sin(ang),world=(x:number,z:number)=>new T.Vector2(c*x+s*z,-s*x+c*z);const ray=new T.Raycaster();const failures:string[]=[];let samples=0;
for(const pane of panes){const q=pane.userData.local;for(const fx of[.22,.78])for(const fy of[.2,.5,.83]){const dx=(fx-.5)*q.w,x=q.x+Math.cos(q.a)*dx,z=q.z-Math.sin(q.a)*dx,p=world(x,z),n=new T.Vector3(Math.sin(ang+q.a),0,Math.cos(ang+q.a)),target=new T.Vector3(p.x,q.y+fy*q.h,p.y),origin=target.clone().addScaledVector(n,.7);ray.set(origin,n.clone().negate());ray.far=1.5;const hit=ray.intersectObjects(group.children,false)[0];samples++;if(hit?.object!==pane)failures.push(`${q.x.toFixed(1)},${q.z.toFixed(1)}: ${hit?.object.userData.colour}`)}}
console.log(JSON.stringify({bounds:bounds.toJSON(),panes:panes.length,samples,upwardRoofFaces:faces,failures},null,2));assert.equal(failures.length,0,'first-hit aperture exposure');
