import * as T from 'three';import type{BuildingTools}from './cultural-builders';import{openTopPrism}from './house-geometry';import src from './fire-station-pieter-footprints.json';import lettering from './fire-station-pieter-lettering.json';
type C=Parameters<BuildingTools['add']>[1];
export function buildFireStationPieter(_w:number,_d:number,b:BuildingTools){
 for(const r of src.surveyRoofParts){const p=r.rings[0],top=p.reduce((s,v)=>s+v[1],0)/p.length,shape=new T.Shape(p.map(v=>new T.Vector2(v[0],v[2])));b.add(openTopPrism(shape,0,top),'brick');
 const xyz:number[]=[];for(const f of T.ShapeUtils.triangulateShape(p.map(v=>new T.Vector2(v[0],v[2])),[])){const v=f.map(i=>p[i]),n=new T.Vector3().fromArray(v[1]).sub(new T.Vector3().fromArray(v[0])).cross(new T.Vector3().fromArray(v[2]).sub(new T.Vector3().fromArray(v[0])));const longest=Math.max(new T.Vector3().fromArray(v[0]).distanceTo(new T.Vector3().fromArray(v[1])),new T.Vector3().fromArray(v[1]).distanceTo(new T.Vector3().fromArray(v[2])),new T.Vector3().fromArray(v[2]).distanceTo(new T.Vector3().fromArray(v[0])));if(Math.abs(n.y)/longest<.002)continue; // rounded survey boundary below2mm planaltitude reversed aftercompression; preserve failure report
 if(n.y<0)v.reverse();xyz.push(...v.flat());}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(xyz,3));g.computeVertexNormals();g.userData={tag:'roof'};b.add(g,'slate');
 }
 function facade(a:number[],z:number[]){const dx=z[0]-a[0],dz=z[1]-a[1],len=Math.hypot(dx,dz),tx=dx/len,tz=dz/len,nx=-tz,nz=tx,ang=Math.atan2(nx,nz);const pos=(u:number,v:number)=>[a[0]+tx*u+nx*v,a[1]+tz*u+nz*v];const box=(u:number,y:number,v:number,w:number,h:number,d:number,c:C)=>{const p=pos(u,v);b.box(p[0],y,p[1],w,h,d,c,ang)};
 const pane=(u:number,y:number,w:number,h:number,v=.12)=>{const p=pos(u,v),g=new T.BoxGeometry(w,h,.06);g.rotateY(ang);g.translate(p[0],y+h/2,p[1]);g.userData={tag:'pane',aperture:{x:p[0],z:p[1],y,w,h,a:ang}};b.add(g,'glass');for(const x of[-w/2,w/2])box(u+x,y,v+.045,.075,h,.08,'frame');for(const yy of[0,h])box(u,y+yy,v+.045,w,Math.min(.065,h*.10),.08,'frame');};return{pos,box,pane,len,ang};}
 const east=facade(src.nativeRing[4],src.nativeRing[6]),south=facade(src.nativeRing[16],src.nativeRing[21]);
 // Five observed east apparatus bays; slight setbacks remain in the surveyed perimeter.
 const bayStart=2.05,step=4.10,w=3.76;for(let i=0;i<5;i++){const u=bayStart+i*step;east.box(u,.05,.10,w,1.62,.12,'red');east.box(u,4.46,.10,w,.95,.12,'red');for(let j=0;j<4;j++){east.pane(u,1.67+j*.69,w,.62);east.box(u,1.65+j*.69,.21,w,.08,.1,'red');}for(const x of[-w/2,-w/6,w/6,w/2])east.box(u+x,1.65,.22,.085,2.83,.10,'red');east.box(u,.46,.18,.65,.08,.05,'stone');east.box(u+.9,.46,.18,.65,.08,.05,'stone');east.box(u+step/2,0,.10,.29,5.50,.21,'stone');}
 // White balcony-panel ribbon with narrow high slots, dark framed accommodation windows.
 east.box(east.len/2,5.46,.11,east.len,1.37,.24,'white');east.box(east.len/2,8.19,.13,east.len,.24,.28,'white');for(let u=.95;u<east.len-.6;u+=1.68){east.pane(u,6.99,1.57,1.05);east.pane(u,6.62,1.52,.20,.25);east.box(u+.83,5.46,.24,.025,1.13,.04,'stone');}
 // Setback top room along roof41, with grey lower panels and continuous glazing.
 const upper=facade([-.91,-3.77],[-1.1,-25.55]);for(let u=.75;u<upper.len-.3;u+=1.52){upper.box(u,11.48,.10,1.43,1.05,.13,'frame');upper.pane(u,12.61,1.41,1.49);upper.box(u+.74,11.47,.18,.055,2.69,.09,'white');}upper.box(upper.len/2,14.23,.15,upper.len,.15,.30,'frame');
 // South wall is a shared boundary with BAG0363100012088592 Reddingsbrigade Amsterdam.
 // The south panorama balcony, pedestrian door and two apparatus portals belong to that neighbour.
 // Surveyed small southeast projecting watch room with its observed window ribbon.
 const watch=facade(src.nativeRing[1],src.nativeRing[2]);watch.pane(2.82,2.0,2.95,1.1);watch.box(.64,.06,.12,.96,2.79,.10,'dark');watch.pane(.64,2.93,.85,.28);watch.box(.64,1.39,.23,.18,.11,.025,'white');watch.box(watch.len/2,3.59,.14,watch.len,.58,.28,'brick');
 // West windows face the neighbouring paved access, without inventing unseen ground equipment.
 const west=facade(src.nativeRing[12],src.nativeRing[14]);for(let u=3;u<west.len-1;u+=4.4){west.pane(u,2.5,2.9,1.1);west.pane(u,6.85,2.9,1.1);}const north=facade(src.nativeRing[8],src.nativeRing[10]);for(const u of[1.7,4.6,7.6]){north.pane(u,2.6,2.0,1.0);north.pane(u,8.7,2.0,1.4);}
 // Real source-visible operator sign only. Arial Bold is an approximate native sans match.
 const path=new T.ShapePath();for(const v of lettering.commands as any[]){if(v.type==='M')path.moveTo(v.x,-v.y);else if(v.type==='L')path.lineTo(v.x,-v.y);else if(v.type==='Q')path.quadraticCurveTo(v.x1,-v.y1,v.x,-v.y);else if(v.type==='C')path.bezierCurveTo(v.x1,-v.y1,v.x2,-v.y2,v.x,-v.y);else if(v.type==='Z')path.currentPath?.closePath();}const sign=new T.ExtrudeGeometry(path.toShapes(),{depth:.05,bevelEnabled:false,curveSegments:3});sign.computeBoundingBox();const bb=sign.boundingBox!,sz=bb.getSize(new T.Vector3());sign.translate(-(bb.min.x+bb.max.x)/2,-bb.min.y,0);sign.scale(5.35/sz.x,.54/sz.y,1);sign.rotateY(east.ang);const q=east.pos(10,.36);sign.translate(q[0],5.82,q[1]);b.add(sign,'red');
 const shield=new T.Shape();shield.moveTo(-.42,.6);shield.lineTo(.42,.6);shield.lineTo(.47,.08);shield.lineTo(0,-.42);shield.lineTo(-.47,.08);shield.closePath();const bg=new T.ExtrudeGeometry(shield,{depth:.08,bevelEnabled:false});bg.rotateY(east.ang);const badge=east.pos(6.55,.35);bg.translate(badge[0],6.05,badge[1]);b.add(bg,'red');const flame=new T.Shape();flame.moveTo(0,-.27);flame.lineTo(-.27,.10);flame.lineTo(-.16,.41);flame.lineTo(-.02,.70);flame.lineTo(.11,.32);flame.lineTo(.27,.19);flame.lineTo(.22,-.01);flame.closePath();const fg=new T.ExtrudeGeometry(flame,{depth:.025,bevelEnabled:false});fg.rotateY(east.ang);const fq=east.pos(6.55,.445);fg.translate(fq[0],6.05,fq[1]);b.add(fg,'bronze');
}
