import * as T from 'three';import assert from 'node:assert/strict';import {buildFireStationOsdorp} from './fire-station-osdorp-builder';import type {BuildingTools} from './cultural-builders';import src from './fire-station-osdorp-footprints.json';
const group=new T.Group(),panes:T.Mesh[]=[],roofs:T.BufferGeometry[]=[];
const add:BuildingTools['add']=(g,col,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));m.userData={...g.userData,col};group.add(m);if(g.userData.probe)panes.push(m);if(g.userData.tag==='roof')roofs.push(g)};const unused=()=>{throw Error('unused')};buildFireStationOsdorp(0,0,{add,box(x,y,z,w,h,d,c,a=0){add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a)},window:unused,clock:unused,sign:unused,hip:unused,prism:unused,gableRoof:unused});group.updateMatrixWorld(true);
const bounds=new T.Box3().setFromObject(group);assert(bounds.min.y>=-.01&&bounds.max.y<15);let faces=0;for(const g of roofs){const p=g.getAttribute('position');for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2),n=b.sub(a).cross(c.sub(a));assert(n.y>0,'upward wave roof');faces++;}}
const angle=src.localRotationRadians,c=Math.cos(angle),s=Math.sin(angle),ray=new T.Raycaster(),failures:any[]=[];
for(const pane of panes){const p=pane.userData.probe,target=new T.Vector3(c*p.x+s*p.z,p.y,-s*p.x+c*p.z),n=new T.Vector3(Math.sin(angle+p.a),0,Math.cos(angle+p.a));ray.set(target.clone().addScaledVector(n,.65),n.clone().negate());ray.far=1.3;const hit=ray.intersectObjects(group.children,false)[0];if(hit?.object!==pane)failures.push({probe:p,hit:hit?.object.userData.col});}
console.log(JSON.stringify({bounds:bounds.toJSON(),panes:panes.length,roofFaces:faces,failures},null,2));assert.equal(failures.length,0,'first-hit exposure');
// Terrace center must have open sky to the lowered floor, not a hidden main cap.
const x=10.5,z=10.6;ray.set(new T.Vector3(c*x+s*z,20,-s*x+c*z),new T.Vector3(0,-1,0));ray.far=25;const h=ray.intersectObjects(group.children,false)[0];assert(Math.abs(h.point.y-10.8)<.02,'terrace remains lowered and open');
