import * as T from 'three';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {buildFireStationOsdorp} from './fire-station-osdorp-builder';import type {BuildingTools} from './cultural-builders';import src from './fire-station-osdorp-footprints.json';
const group=new T.Group(),panes:T.Mesh[]=[];
const add:BuildingTools['add']=(g,col,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));m.userData={...g.userData,col};group.add(m);if(g.userData.probe)panes.push(m)};const unused=()=>{throw Error('unused')};buildFireStationOsdorp(0,0,{add,box(x,y,z,w,h,d,c,a=0){add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a)},window:unused,clock:unused,sign:unused,hip:unused,prism:unused,gableRoof:unused});group.updateMatrixWorld(true);
const ray=new T.Raycaster(),fractions=[.2,.5,.8],blocking:any[]=[],expectedFrameCoverage:any[]=[],assemblies:Record<string,{panes:number,samples:number,exposed:number,frameCovered:number}>={};let exposed=0,samples=0;
for(let index=0;index<panes.length;index++){
 const pane=panes[index],q=pane.userData.probe,angle=src.localRotationRadians+q.a,n=new T.Vector3(Math.sin(angle),0,Math.cos(angle)),t=new T.Vector3(Math.cos(angle),0,-Math.sin(angle)),verts=pane.geometry.getAttribute('position');
 let tmin=Infinity,tmax=-Infinity,ymin=Infinity,ymax=-Infinity,nmin=Infinity,nmax=-Infinity;for(let k=0;k<verts.count;k++){const p=new T.Vector3().fromBufferAttribute(verts,k);const u=p.dot(t),v=p.dot(n);tmin=Math.min(tmin,u);tmax=Math.max(tmax,u);ymin=Math.min(ymin,p.y);ymax=Math.max(ymax,p.y);nmin=Math.min(nmin,v);nmax=Math.max(nmax,v);}
 const assembly=pane.userData.tag==='window-pane'?'masonry-windows':q.x<-2.5?(Math.abs(q.a)>1?'hall-wave-side-curtain':'hall-end-vehicle-curtain'):'glazed-connector';const count=assemblies[assembly]??={panes:0,samples:0,exposed:0,frameCovered:0};count.panes++;
 for(const fx of fractions)for(const fy of fractions){const target=t.clone().multiplyScalar(tmin+(tmax-tmin)*fx).addScaledVector(n,nmax).add(new T.Vector3(0,ymin+(ymax-ymin)*fy,0));ray.set(target.clone().addScaledVector(n,.65),n.clone().negate());ray.far=1.3;const hit=ray.intersectObjects(group.children,false)[0];samples++;count.samples++;
  if(hit?.object===pane){exposed++;count.exposed++;continue;}
  const hitGeometry=(hit?.object as T.Mesh)?.geometry;let hitFaceWidth=Infinity,hitHeight=Infinity;if(hitGeometry){const hp=hitGeometry.getAttribute('position');let lo=Infinity,hi=-Infinity,yl=Infinity,yh=-Infinity;for(let k=0;k<hp.count;k++){const p=new T.Vector3().fromBufferAttribute(hp,k),u=p.dot(t);lo=Math.min(lo,u);hi=Math.max(hi,u);yl=Math.min(yl,p.y);yh=Math.max(yh,p.y);}hitFaceWidth=hi-lo;hitHeight=yh-yl;}
  const record={pane:index,assembly,local:q,fraction:[fx,fy],firstHit:hit?.object.userData.col??null,firstHitTag:hit?.object.userData.tag??null,distance:hit?.distance??null,hitFaceWidth,hitHeight};
  // Mullions, source roof beams and masonry opening surrounds legitimately cross the face.
  // Only thin named frame palettes qualify; actual masonry, soffit or roof occlusion is a failure.
  if(hit&&['white','frame','stone','bronze'].includes(hit.object.userData.col)&&(hitFaceWidth<=.3||hitHeight<=.45)){expectedFrameCoverage.push(record);count.frameCovered++;}else blocking.push(record);
 }
}
const glb='artifacts/fire-station-osdorp-draft/fire-station-osdorp.glb';const report={model:'fire-station-osdorp',inputSha256:crypto.createHash('sha256').update(fs.readFileSync(glb)).digest('hex'),method:'All actual authored pane vertices projected on tangent/outward normal;9sample fractions0.2/0.5/0.8 perface at3heights. Double-sided first-hitray records distinguish thin frames from wall/roofburial.',panes:panes.length,samples,exposed,assemblies,expectedFrameCoverage,blocking};fs.writeFileSync('artifacts/fire-station-osdorp-draft/aperture-fractions.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({panes:panes.length,samples,exposed,assemblies,expectedFrameCoverage:expectedFrameCoverage.length,blocking},null,2));assert.equal(blocking.length,0,'pane faces not buried by walls or roofs');
