import * as T from 'three';import assert from 'node:assert/strict';import {buildFireStationWeesp} from './fire-station-weesp-builder';import type {BuildingTools} from './cultural-builders';
const group=new T.Group(),panes:T.Mesh[]=[],roofs:T.BufferGeometry[]=[];
const add:BuildingTools['add']=(g,c,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));m.userData={...g.userData,colour:c};group.add(m);if(g.userData.tag==='pane' || g.userData.tag==='entrance-pane')panes.push(m);if(['roof','shoulder-roof','canopy-top'].includes(g.userData.tag))roofs.push(g)};
const unused=()=>{throw Error('unused')};buildFireStationWeesp(0,0,{add,box(x,y,z,w,h,d,c,a=0){add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a)},window:unused,clock:unused,sign:unused,hip:unused,prism:unused,gableRoof:unused});group.updateMatrixWorld(true);
const soffits=group.children.filter(o=>o.userData.tag==='canopy-soffit');assert.equal(soffits.length,4,'four continuous canopy strips');for(const o of soffits){const g=(o as T.Mesh).geometry,p=g.getAttribute('position');for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2);assert(b.sub(a).cross(c.sub(a)).y<0,'downward canopy soffit');}}assert.equal(group.children.filter(o=>o.userData.tag==='trapezoid-reveal').length,4,'four aperture reveals');assert.equal(group.children.find(o=>o.userData.tag==='trapezoid-pane')?.userData.recessMetres,.24,'actual glazing recess');
const bounds=new T.Box3().setFromObject(group);assert(bounds.min.y>=-.01&&bounds.max.y<26,'native heights');for(const o of group.children)for(const v of (o as T.Mesh).geometry.getAttribute('position').array)assert(Number.isFinite(v));
let upward=0;for(const g of roofs){const flat=g.index?g.toNonIndexed():g,p=flat.getAttribute('position');for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2);assert(b.sub(a).cross(c.sub(a)).y>0,'upwardroof');upward++}}
const ray=new T.Raycaster(),failures:any[]=[];let samples=0;for(const pane of panes){const q=pane.userData.probe;for(const fx of[.19,.81])for(const fy of[.31,.71]){const dx=(fx-.5)*q.w,target=new T.Vector3(q.x+Math.cos(q.a)*dx,q.y+fy*q.h,q.z-Math.sin(q.a)*dx),n=new T.Vector3(Math.sin(q.a),0,Math.cos(q.a));ray.set(target.clone().addScaledVector(n,.7),n.clone().negate());ray.far=1.5;const hit=ray.intersectObjects(group.children,false)[0];samples++;if(hit?.object!==pane)failures.push({sample:q,fx,fy,hit:hit?.object.userData.colour})}}
for(const pane of group.children.filter(o=>o.userData.tag==='trapezoid-pane')){const q=pane.userData.polyProbe;for(const fy of[.25,.75])for(const fx of[.27,.73]){const w=q.bottomWidth+(q.topWidth-q.bottomWidth)*fy,dx=(fx-.5)*w+q.bottomCenter+(q.topCenter-q.bottomCenter)*fy,target=new T.Vector3(q.x+Math.cos(q.a)*dx,4.2+4.49*fy,q.z-Math.sin(q.a)*dx),n=new T.Vector3(Math.sin(q.a),0,Math.cos(q.a));ray.set(target.clone().addScaledVector(n,.7),n.clone().negate());ray.far=1.5;const hit=ray.intersectObjects(group.children,false)[0];samples++;if(hit?.object!==pane)failures.push({tag:'trapezoid',fx,fy,hit:hit?.object.userData.colour});}}
let canopySamples=0;for(const mesh of group.children.filter(o=>['canopy-top','canopy-soffit'].includes(o.userData.tag))){const pos=(mesh as T.Mesh).geometry.getAttribute('position'),target=new T.Vector3();for(let i=0;i<3;i++)target.add(new T.Vector3().fromBufferAttribute(pos,i));target.multiplyScalar(1/3);const n=new T.Vector3(0,mesh.userData.tag==='canopy-top'?1:-1,0);ray.set(target.clone().addScaledVector(n,.08),n.clone().negate());ray.far=.2;assert.equal(ray.intersectObjects(group.children,false)[0]?.object,mesh,'actual canopy cover/soffit visibility');canopySamples++;}
console.log(JSON.stringify({bounds:bounds.toJSON(),panes:panes.length,samples,canopySamples,upwardRoofFaces:upward,failures},null,2));assert.equal(failures.length,0,'firsthit glazing');
