import * as T from 'three';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildFireStationHendrik} from './fire-station-hendrik-builder';
import type {BuildingTools} from './cultural-builders';
const meshes:T.Mesh[]=[];const glazing:{mesh:T.Mesh,w:number,h:number,center:T.Vector3,angle:number}[]=[];
const add=(g:T.BufferGeometry,c:string,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);const mesh=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));mesh.userData.colour=c;meshes.push(mesh);return mesh;};
const b={add,box(x:number,y:number,z:number,w:number,h:number,d:number,c:string,a=0){const mesh=add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a);if(c==='glass')glazing.push({mesh,w,h,center:new T.Vector3(x,y+h/2,z),angle:a});}} as BuildingTools;
buildFireStationHendrik(46,57.6,b);meshes.forEach(m=>m.updateMatrixWorld());
const bounds=new T.Box3();let triangles=0;for(const m of meshes){m.geometry.computeBoundingBox();bounds.union(m.geometry.boundingBox!);const p=m.geometry.attributes.position;for(let i=0;i<p.count;i++)assert(Number.isFinite(p.getX(i))&&Number.isFinite(p.getY(i))&&Number.isFinite(p.getZ(i)));triangles+=(m.geometry.index?.count??p.count)/3;}
const failures:any[]=[];let probes=0;for(const {mesh,w,h,center,angle} of glazing){const n=new T.Vector3(Math.sin(angle),0,Math.cos(angle)),u=new T.Vector3(Math.cos(angle),0,-Math.sin(angle));for(const fx of [-.38,-.17,.17,.38])for(const fy of [-.31,.31]){const target=center.clone().addScaledVector(u,w*fx).add(new T.Vector3(0,h*fy,0));const ray=new T.Raycaster(target.clone().addScaledVector(n,2),n.clone().negate(),0,2.2),hit=ray.intersectObjects(meshes)[0];probes++;if(hit?.object!==mesh){const colour=hit?.object.userData.colour; if(colour!=='white'&&colour!=='dark'&&colour!=='frame')failures.push({target:target.toArray(),colour,hit:hit?.point.toArray()});}}}
let roofs=0,downward=0;for(const m of meshes)if(m.geometry.userData.role==='source-roof'){roofs++;const g=m.geometry.index?m.geometry.toNonIndexed():m.geometry,p=g.attributes.position;for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2),normal=b.sub(a).cross(c.sub(a));if(normal.y<-1e-6)downward++;}}
const result={triangles,bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},roofParts:roofs,downwardRoofTriangles:downward,glassFaces:glazing.length,fractionalFirstHitProbes:probes,nonFrameOcclusions:failures};fs.mkdirSync('docs/references/fire-station-hendrik',{recursive:true});fs.writeFileSync('docs/references/fire-station-hendrik/geometry-check.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,nonFrameOcclusions:failures.length}));assert.equal(downward,0);assert.equal(failures.length,0,'Expose supported glazing; preserve failure report');assert(triangles<40000);
