import * as T from 'three';import assert from 'node:assert/strict';import {buildFireStationWillem} from './fire-station-willem-builder';import type {BuildingTools} from './cultural-builders';
const group=new T.Group(),panes:T.Mesh[]=[],roofs:T.BufferGeometry[]=[];
const add:BuildingTools['add']=(g,c,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));m.userData={...g.userData,colour:c};group.add(m);if(g.userData.tag==='pane')panes.push(m);if(g.userData.tag==='roof')roofs.push(g)};
const unused=()=>{throw Error('unused')};buildFireStationWillem(0,0,{add,box(x,y,z,w,h,d,c,a=0){add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a)},window:unused,clock:unused,sign:unused,hip:unused,prism:unused,gableRoof:unused});group.updateMatrixWorld(true);
const bounds=new T.Box3().setFromObject(group);assert(bounds.min.y>=-.01&&bounds.max.y<26,'native heights');for(const o of group.children)for(const v of (o as T.Mesh).geometry.getAttribute('position').array)assert(Number.isFinite(v));
let upward=0;for(const g of roofs){const flat=g.index?g.toNonIndexed():g,p=flat.getAttribute('position');for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2);assert(b.sub(a).cross(c.sub(a)).y>0,'upwardroof');upward++}}
const ray=new T.Raycaster(),failures:any[]=[];let samples=0;for(const pane of panes){const q=pane.userData.sample;for(const fx of[.22,.78])for(const fy of[.2,.75]){const dx=(fx-.5)*q.w,target=new T.Vector3(q.x+Math.cos(q.a)*dx,q.y+fy*q.h,q.z-Math.sin(q.a)*dx),n=new T.Vector3(Math.sin(q.a),0,Math.cos(q.a));ray.set(target.clone().addScaledVector(n,.7),n.clone().negate());ray.far=1.5;const hit=ray.intersectObjects(group.children,false)[0];samples++;if(hit?.object!==pane)failures.push({sample:q,fx,fy,hit:hit?.object.userData.colour})}}
console.log(JSON.stringify({bounds:bounds.toJSON(),panes:panes.length,samples,upwardRoofFaces:upward,failures},null,2));assert.equal(failures.length,0,'firsthit glazing');
const rooflightExposure:any[]=[],solarFailures:any[]=[],frames=group.children.filter(m=>m.userData.tag==='roof-frame');
for(const obj of group.children){const m=obj as T.Mesh;if(m.userData.rooflight===undefined)continue;const p=m.geometry.getAttribute('position'),report={part:m.userData.rooflight,samples:0,visible:0,blocked:[] as any[]};for(let i=0;i<p.count;i+=3){const vs=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,i+j));for(const weights of[[.6,.2,.2],[.2,.6,.2],[.2,.2,.6]]){const target=new T.Vector3();vs.forEach((v,j)=>target.addScaledVector(v,weights[j]));ray.set(new T.Vector3(target.x,30,target.z),new T.Vector3(0,-1,0));ray.far=40;const hit=ray.intersectObjects(group.children,false)[0];report.samples++;if(hit?.object===obj||hit?.object.userData.tag==='roof-frame')report.visible++;else report.blocked.push({target:target.toArray(),hit:hit?.object.userData});}}rooflightExposure.push(report);}
for(const obj of group.children){if(obj.userData.tag!=='solar')continue;const q=obj.userData.sample;for(const [x,z]of[[q.x,q.z],...q.corners.map(([x,z]:number[])=>[q.x+(x-q.x)*.85,q.z+(z-q.z)*.85])]){ray.set(new T.Vector3(x,30,z),new T.Vector3(0,-1,0));ray.far=40;const hit=ray.intersectObjects(group.children,false)[0];if(hit?.object!==obj)solarFailures.push({q,hit:hit?.object.userData});}}
console.log(JSON.stringify({rooflightExposure,solarPanels:group.children.filter(m=>m.userData.tag==='solar').length,solarFailures,roofFrames:frames.length},null,2));assert.equal(solarFailures.length,0,'solar firsthits');assert(rooflightExposure.every(r=>r.visible/r.samples>.8),'survey rooflights exposed');for(const obj of frames){const p=(obj as T.Mesh).geometry.getAttribute('position');for(let i=0;i<p.count;i+=3){const vs=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,i+j));assert(vs[1].sub(vs[0]).cross(vs[2].sub(vs[0])).y>0,'roofframe winding');}}
let solarSupportSamples=0;const unsupportedSolar:any[]=[];for(const obj of group.children){if(obj.userData.tag!=='solar')continue;const q=obj.userData.sample;for(const [x,z]of[[q.x,q.z],...q.corners.map(([x,z]:number[])=>[q.x+(x-q.x)*.85,q.z+(z-q.z)*.85])]){ray.set(new T.Vector3(x,17.97,z),new T.Vector3(0,-1,0));ray.far=.25;const hit=ray.intersectObjects(group.children,false)[0];solarSupportSamples++;if(hit?.object.userData.colour!=='slate'||hit.object.userData.tag!=='roof')unsupportedSolar.push({sample:[x,z],hit:hit?.object.userData});}}
const frameExposure={samples:0,visible:0};for(const obj of frames){const g=(obj as T.Mesh).geometry,p=g.getAttribute('position'),target=new T.Vector3();for(let i=0;i<p.count;i++)target.add(new T.Vector3().fromBufferAttribute(p,i));target.divideScalar(p.count);ray.set(new T.Vector3(target.x,30,target.z),new T.Vector3(0,-1,0));ray.far=40;const hit=ray.intersectObjects(group.children,false)[0];frameExposure.samples++;if(hit?.object.userData.tag==='roof-frame')frameExposure.visible++;}
console.log(JSON.stringify({solarSupportSamples,unsupportedSolar,frameExposure},null,2));assert.equal(unsupportedSolar.length,0,'solar flatroof supports');assert(frameExposure.visible/frameExposure.samples>.85,'roof frame visibility');
