import fs from 'node:fs';import crypto from 'node:crypto';import * as T from 'three';import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {MeshoptDecoder} from 'meshoptimizer';
await MeshoptDecoder.ready;const file=process.argv[2]??'artifacts/haparandaweg-13/haparandaweg-13.glb',doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(file),meshes:T.Mesh[]=[],panes:{points:T.Vector3[],normal:T.Vector3}[]=[],bounds=new T.Box3();let triangles=0,downward=0;
for(const node of doc.getRoot().listNodes()){const mesh=node.getMesh();if(!mesh)continue;for(const p of mesh.listPrimitives()){const pos=p.getAttribute('POSITION')!,ix=p.getIndices(),g=new T.BufferGeometry(),points=Array.from({length:pos.getCount()},(_,i)=>new T.Vector3(...pos.getElement(i,[])).applyMatrix4(new T.Matrix4().fromArray(node.getWorldMatrix())));g.setAttribute('position',new T.Float32BufferAttribute(points.flatMap(p=>p.toArray()),3));if(ix)g.setIndex(Array.from(ix.getArray()!));g.computeVertexNormals();const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));m.userData.material=p.getMaterial()!.getName();meshes.push(m);for(const v of points){if(!Number.isFinite(v.length()))throw Error('nonfinite');bounds.expandByPoint(v);}const indices=ix?Array.from(ix.getArray()!) as number[]:points.map((_,i)=>i);for(let i=0;i<indices.length;i+=3){const pts=indices.slice(i,i+3).map(j=>points[j]),n=pts[1].clone().sub(pts[0]).cross(pts[2].clone().sub(pts[0]));triangles++;if(['slate','green'].includes(m.userData.material)&&n.y<-.000001)downward++;if(m.userData.material==='glass'&&Math.abs(n.clone().normalize().y)<.1)panes.push({points:pts,normal:n.normalize()});}}}
const ray=new T.Raycaster(),failures:any[]=[],dense:any[]=[],unclassified:any[]=[];let checks=0;
function firstHit(q:T.Vector3,n:T.Vector3){ray.set(q.clone().addScaledVector(n,4),n.clone().negate());ray.far=4.2;const hit=ray.intersectObjects(meshes)[0];return {material:hit?.object.userData.material??null,distance:hit?.distance};}
for(const [i,p] of panes.entries()){
 for(const weights of [[.55,.25,.2],[.2,.55,.25],[.25,.2,.55]]){const q=p.points.reduce((s,v,k)=>s.addScaledVector(v,weights[k]),new T.Vector3()),hit=firstHit(q,p.normal);checks++;if(hit.material!=='glass')failures.push({pane:i,target:q.toArray(),normal:p.normal.toArray(),hit:hit.material,distance:hit.distance});}
 // Full dense scan includes triangles missed by the original 3-point lattice.
 const counts:Record<string,number>={},samples:any[]=[];for(let a=1;a<=8;a++)for(let b=1;b<=9-a;b++){const w=[a/10,b/10,(10-a-b)/10],q=p.points.reduce((s,v,k)=>s.addScaledVector(v,w[k]),new T.Vector3()),hit=firstHit(q,p.normal);counts[String(hit.material)]=(counts[String(hit.material)]??0)+1;if(hit.material!=='glass')samples.push({target:q.toArray(),...hit});}
 const bad=samples;const record={pane:i,checks:36,counts,samples,unclassified:bad.length};dense.push(record);if(bad.length)unclassified.push(record);
}
// The front recess and a point outside the surveyed parent must stay clear.
const openProbes:[[number,number,number],number][]=[[[8,1,7],12],[[-8,1,-6],12]];const open=[];for(const [p,len] of openProbes){ray.set(new T.Vector3(...p),new T.Vector3(0,1,0));ray.far=len;open.push({from:p,clear:ray.intersectObjects(meshes).length===0});}
// Barycentric interiors of decoded roof faces must first hit their own bounded top.
const roofSupportProbes:any[]=[];for(const m of meshes){if(m.userData.material!=='slate')continue;const g=m.geometry,pa=g.getAttribute('position'),ids=g.index?Array.from(g.index.array):Array.from({length:pa.count},(_,i)=>i);for(let i=0;i<ids.length;i+=3){const points=ids.slice(i,i+3).map(j=>new T.Vector3().fromBufferAttribute(pa,j)),q=points.reduce((a,p)=>a.add(p),new T.Vector3()).multiplyScalar(1/3);ray.set(new T.Vector3(q.x,12,q.z),new T.Vector3(0,-1,0));ray.far=15;const hit=ray.intersectObjects(meshes)[0];roofSupportProbes.push({point:q.toArray(),firstHit:hit?.object.userData.material,delta:hit?Math.abs(hit.point.y-q.y):null});}}
const summary={sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),triangles,bytes:fs.statSync(file).size,bounds:[bounds.min.toArray(),bounds.max.toArray()],downwardRoofFaces:downward,roofSupportProbes,firstHitGlazing:{checks,failures:failures.length,denseChecks:panes.length*36,unclassifiedTriangles:unclassified.length,denseFailureSamples:unclassified.map(v=>({pane:v.pane,bounds:v.bounds,counts:v.counts})),sampleFailures:failures.slice(0,16),failureGroups:Object.entries(failures.reduce((a,v)=>{const k=[v.hit,Math.round(v.target[0]/5)*5,Math.round(v.target[2]/5)*5].join(':');a[k]=(a[k]??0)+1;return a;},{} as Record<string,number>))},frontRecessAndNeighborOutsideScope:open,pending:'Independent/sourcecomparison/gallery/live neighbors/suppression/performance. CPU not acceptance.'};fs.mkdirSync('artifacts/haparandaweg-13',{recursive:true});fs.writeFileSync('artifacts/haparandaweg-13/geometry-review.json',JSON.stringify(summary,null,2));fs.writeFileSync('artifacts/haparandaweg-13/dense-glazing-probes.json',JSON.stringify({sha256:summary.sha256,originalFailures:failures,dense},null,2));console.log(JSON.stringify({...summary,firstHitGlazing:{...summary.firstHitGlazing,denseFailureSamples:summary.firstHitGlazing.denseFailureSamples.slice(0,12)}}));if(triangles>40000||summary.bytes>500000||downward||roofSupportProbes.some(v=>v.firstHit!=='slate'||v.delta>.005)||open.some(v=>!v.clear)||unclassified.length)process.exitCode=1;
