import json,math,pathlib
root=pathlib.Path('../map-recall2-source-data/models/huize-frankendael'); raw=root/'raw';dest=pathlib.Path('scripts/landmarks');anchor=[4.9335095,52.351162];h=316.086
bag=next(f for f in json.loads((raw/'bag.json').read_text())['features'] if f['properties']['identificatie']=='0363100012162192');osm=json.loads((raw/'osm.json').read_text())['elements'];subject=[e for e in osm if e['id'] in [44980011,1562613213,1562613214,1562613215]]
currentMap=json.loads((raw/'osm-small-map.json').read_text())['elements'];nodes={e['id']:e for e in currentMap if e['type']=='node'}
se=next(e for e in currentMap if e['id']==1562613216 and e['type']=='way');se=dict(se,geometry=[dict(lon=nodes[n]['lon'],lat=nodes[n]['lat']) for n in se['nodes']],sourceNote='Official OSM current small-map/full-way endpoint; absent from earlier Overpass response, which must not establish exhaustive parts')
subject.append(se)
def local(ll):
 e=(ll[0]-anchor[0])*111320*math.cos(math.radians(anchor[1]));n=(ll[1]-anchor[1])*110540;t=math.radians(h)
 return [round(e*math.sin(t)+n*math.cos(t),4),round(e*math.cos(t)-n*math.sin(t),4)]
address=json.loads((raw/'vbo-bounded.json').read_text())['features'][0]
refs=[dict(url=r['url'],cached=r['file'],access=r['access'],sha256=r.get('sha256')) for r in json.loads((root/'acquisition.json').read_text()) if r.get('status')==200]
source=dict(addressParent=address,modelId='huize-frankendael',retrievedOn='2026-10-08',bag=bag,osm=subject,geometry=bag['geometry'],localRing=[local(p) for p in bag['geometry']['coordinates'][0]],coordinateConvention='Local +X northwest bearing316.086; +Z northeast front bearing46.086, Y up, native metres. 111320cos(lat)/110540 geographic approximation.',anchor=anchor,retainedNeighbors=[dict(id='w278698882',bagId='NL.IMBAG.Pand.0363100012098251',name='De Bron southeast'),dict(id='w278699069',bagId='NL.IMBAG.Pand.0363100012214449',name='De Bron outbuilding southeast'),dict(id='w278613028',bagId='NL.IMBAG.Pand.0363100012152512',name='Middenweg opposite northeast')],heightNotes=dict(groundNap=-3.746,source='3DBAG AHN5 2023 and OSM parts current 2026-10-08',wingEaves=6.0,wingTruncatedHipTop=8.6,centralEaves=11.6,centralTruncatedHipTop=14.6,rearProjectionAttic=11.6,upperSilhouette=16.6,warning='3DBAG roof statistics in NAP. Front corner chimney planes are maxima, not full-building crest or walls. Dormers and balustrade dimensioned approximately from photos.'),publicEntrance=dict(position=[4.933559,52.351191],evidence='NO facade central door: RCE422420 and operator front photograph. Projected from central surveyed front edge; approximate threshold.',frontOutwardNormalEastNorth=[.7209,.6930],streetGapMetresApprox=None,streetGapEvidence="Front forecourt visible in photographs; no calibrated road-edge survey; do not infer a parcel suppression mask"),references=refs,openSpaces=['No courtyard hole in current BAG parent. Surrounding forecourt, rear garden and both end setbacks remain empty; gate/fountain detached and excluded.'],archiveSearch=dict(url='https://archief.amsterdam/beeldbank/?mode=gallery&view=horizontal&q=Frankendael%20Middenweg%2072',access='HTTP200 JavaScript mediabank shell, no drawing inspected'),uncertainties=['Current operator page photo upload2016 capture unknown; inspected clearer front2022-04-17. Rear2014-03-14 compared to current BAG and2023 roof survey.', 'Fine rococo ornament and pierced balusters simplified as original geometric relief. No calibrated facade drawing.', 'No exact public entrance OSM node returned; sourced NO door projected from BAG front edge.'])
(dest/'huize-frankendael-footprints.json').write_text(json.dumps(source,indent=2)+'\n')
spec=dict(id='huize-frankendael',name='Huize Frankendael',landmarkId='extract_landmarks_746892406',modelUrl='./models/huize-frankendael.glb',suppressOsmIds=['w44980011','NL.IMBAG.Pand.0363100012162192','w1562613213','w1562613214','w1562613215','w1562613216'],spatialSuppression=False,footprint=dict(centre=anchor,headingDegrees=h,lengthMetres=32.46,widthMetres=12.91),surveyed=dict(anchor=anchor,northOffsetDegrees=h-90,source='Current BAG0363100012162192 / OSM w44980011 and four exact mapped parts. Native original reconstruction; AHN5 2023 roof semantics and RCE422420.'),groundAltitudeMetres=0,facingOffsetDegrees=90,materialOverrides=dict(brick='#766a65',stone='#d8d1b8',white='#eee7d5',slate='#4a555b',glass='#465d62',frame='#292d28',dark='#23392c',concrete='#888980'),attribution=dict(title='Huize Frankendael',author='Map Recall',sourceUrl='https://monumentenregister.cultureelerfgoed.nl/monumenten/422420',licence='Original project asset',licenceUrl='./LICENSE',modifications='Original texture-free native BAG brick pavilion, coach-house wings, truncated grey hip roofs, rear polygonal projection, pale rococo surrounds, balustrade, dormers and entrance steps. No imported meshes or photo pixels.'))
(dest/'huize-frankendael-spec.json').write_text(json.dumps(spec,indent=2)+'\n')
poi=dict(modelId='huize-frankendael',id='extract_landmarks_746892406',name='Huize Frankendael',sourceUrl='https://huizefrankendael.nl/nl/over/geschiedenis-huize-frankendael/',description='Frankendael is the last surviving country estate in the Watergraafsmeer, where wealthy Amsterdammers once built many summer retreats. Izaak Balde gave the house its present central pavilion and lower coach-house wings around 1733. Restaurant Merkelbach occupies a former coach house, named for city architect Ben Merkelbach, who moved into the house in 1957.',sources=['https://huizefrankendael.nl/nl/over/geschiedenis-huize-frankendael/','https://monumentenregister.cultureelerfgoed.nl/monumenten/422420'],destinationRecommendation=dict(keepExistingId=True,existingLatLng=[52.351122,4.933403],publicEntranceLatLng=[52.351191,4.933559],reason='Existing center falls on rear bay; sourced public main entrance is northeast. Root should only relocate pin if routing requires or improves actual entrance.' ))
(dest/'huize-frankendael-poi.json').write_text(json.dumps(poi,indent=2)+'\n')
