import * as T from 'three';import type{BuildingTools}from './cultural-builders';import{openTopPrism}from './house-geometry';import source from './nieuw-dakota-footprints.json';
/** Original twin-gabled shared host; preserves neighboring tenant front and narrow rear extension. */
export function buildNieuwDakota(_w:number,_d:number,b:BuildingTools){
 const [lng0,lat0]=source.anchor;const ring=source.bag.geometry.coordinates[0].slice(0,-1).map(([lng,lat])=>new T.Vector2((lng-lng0)*111320*Math.cos(lat0*Math.PI/180),-(lat-lat0)*110540)),roofs=source.roofPlanes,sign=Math.sign(ring.reduce((v,p,i)=>{const q=ring[(i+1)%ring.length];return v+p.x*q.y-q.x*p.y;},0));
 const emit=(v:number[][],c:Parameters<BuildingTools['add']>[1])=>{const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v.flat(),3));g.computeVertexNormals();b.add(g,c);};
 b.add(openTopPrism(new T.Shape(ring),0,.12),'concrete');
 for(const roof of roofs){const r=roof.rings[0],xy=r.map(p=>new T.Vector2(p[0],p[2]));for(const t of T.ShapeUtils.triangulateShape(xy,[])){let pts=t.map(i=>r[i]);const n=new T.Vector3(...pts[1] as[number,number,number]).sub(new T.Vector3(...pts[0] as[number,number,number])).cross(new T.Vector3(...pts[2] as[number,number,number]).sub(new T.Vector3(...pts[0] as[number,number,number])));if(n.y<0)pts=[pts[0],pts[2],pts[1]];emit(pts,'frame');}}
 const heightAt=(p:T.Vector2)=>{let best=Infinity,h=4.1;for(const roof of roofs)for(const r of roof.rings)for(let i=0;i<r.length;i++){const a=r[i],q=r[(i+1)%r.length],delta=new T.Vector2(q[0]-a[0],q[2]-a[2]),u=T.MathUtils.clamp(p.clone().sub(new T.Vector2(a[0],a[2])).dot(delta)/delta.lengthSq(),0,1),projected=new T.Vector2(a[0]+delta.x*u,a[2]+delta.y*u),dist=p.distanceTo(projected);if(dist<best){best=dist;h=a[1]+(q[1]-a[1])*u;}}return h;};
 // Walls follow surveyed roof edge profile, including both west gables rather than a flat box.
 for(let i=0;i<ring.length;i++){const a=ring[i],q=ring[(i+1)%ring.length],delta=q.clone().sub(a),length=delta.length(),normal=new T.Vector2(delta.y,-delta.x).normalize().multiplyScalar(sign),angle=-Math.atan2(delta.y,delta.x),blue=i===6||i===7;const steps=Math.ceil(length/.3);for(let j=0;j<steps;j++){const p=a.clone().lerp(q,j/steps),s=a.clone().lerp(q,(j+1)/steps),hp=heightAt(p),hs=heightAt(s);const v=[[p.x,.12,p.y],[s.x,.12,s.y],[s.x,hs,s.y],[p.x,.12,p.y],[s.x,hs,s.y],[p.x,hp,p.y]];if(sign>0)for(let k=0;k<v.length;k+=3)[v[k+1],v[k+2]]=[v[k+2],v[k+1]];emit(v,blue?'blue':'white');}
  // Shallow corrugation stays bounded to each wall, following actual gable height.
  if(!blue)for(let u=.18;u<length;u+=.44){const p=a.clone().lerp(q,u/length).addScaledVector(normal,.034),h=heightAt(a.clone().lerp(q,u/length));b.box(p.x,.15,p.y,.025,h-.18,.07,'frame',angle);}
 }
 const facade=(a:T.Vector2,q:T.Vector2)=>{const delta=q.clone().sub(a),len=delta.length(),t=delta.clone().normalize(),n=new T.Vector2(t.y,-t.x).multiplyScalar(sign),angle=-Math.atan2(t.y,t.x);return{len,box:(u:number,y:number,w:number,h:number,c:Parameters<BuildingTools['box']>[6],offset=.15)=>{const p=a.clone().addScaledVector(t,u).addScaledVector(n,offset);b.box(p.x,y,p.y,w,h,.12,c,angle);}};};
 const south=facade(ring[7],ring[8]),north=facade(ring[3],ring[6]);
 function greenWindow(f:ReturnType<typeof facade>,u:number,y:number,w:number,h:number){f.box(u,y,w,h,'glass');for(const du of [-w/2,0,w/2])f.box(u+du,y,.13,h,'green',.24);for(const yy of [y,y+h])f.box(u,yy,w+.2,.14,'green',.24);}
 greenWindow(south,south.len*.51,4.45,4.1,1.85);greenWindow(south,2.25,.12,3.05,2.85);greenWindow(north,north.len*.55,3.65,5.1,2.15);greenWindow(north,north.len-1.75,.12,2.7,2.7);
 // Source-backed geometric mural on northern tenant face: original coarse cubes, no copied artwork pixels/words.
 for(const y of [.35,6.35])for(let u=.8;u<north.len-.5;u+=2.05){if(y>heightAt(ring[3].clone().lerp(ring[6],u/north.len))-1)continue;north.box(u,y,.65,.8,'blue',.14);north.box(u+.68,y+.3,.65,.55,'frame',.15);}
 // Pale translucent roof sheets are visible in current municipal context views. Positions are photographic estimates.
 const lightEdges=[[4,1,3,2],[0,3,1,2],[0,1,3,2],[2,1,5,0]];
 for(let k=0;k<4;k++){const r=roofs[k].rings[0],[la,lq,ha,hq]=lightEdges[k],at=(u:number,v:number)=>r[la].map((x,i)=>{const low=x+(r[lq][i]-x)*u,high=r[ha][i]+(r[hq][i]-r[ha][i])*u;return low+(high-low)*v+(i===1?.045:0);});for(const u of [.12,.43,.75]){const pts=[at(u,.27),at(u+.12,.27),at(u+.12,.73),at(u,.73)];for(const tri of [[0,1,2],[0,2,3]]){let v=tri.map(i=>pts[i]);const n=new T.Vector3(...v[1] as[number,number,number]).sub(new T.Vector3(...v[0] as[number,number,number])).cross(new T.Vector3(...v[2] as[number,number,number]).sub(new T.Vector3(...v[0] as[number,number,number])));if(n.y<0)v=[v[0],v[2],v[1]];emit(v,'stone');}}}
 // Exposed metal ridge seams.
 for(const roof of roofs){if(roof.semantic.b3_hellingshoek<20)continue;const r=roof.rings[0],high=[...r].sort((a,q)=>q[1]-a[1]).slice(0,2);if(high.length===2){const a=new T.Vector3(...high[0] as[number,number,number]),q=new T.Vector3(...high[1] as[number,number,number]),d=q.clone().sub(a),g=new T.BoxGeometry(.09,.09,d.length());g.applyQuaternion(new T.Quaternion().setFromUnitVectors(new T.Vector3(0,0,1),d.normalize()));const mid=a.add(q).multiplyScalar(.5);b.add(g,'white',mid.x,mid.y+.04,mid.z);}}
}
