import fs from 'node:fs';import assert from 'node:assert/strict';import * as T from 'three';import {buildOosterparkkerk} from './oosterparkkerk-builder';import type {BuildingTools} from './cultural-builders';import source from './oosterparkkerk-footprints.json';import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {MeshoptDecoder} from 'meshoptimizer';
const ms:T.Mesh[]=[];const add:BuildingTools['add']=(g,c,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));m.userData={...g.userData,colour:c};ms.push(m);};const box:BuildingTools['box']=(x,y,z,w,h,d,c,a=0)=>add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a);buildOosterparkkerk(0,0,{add,box} as BuildingTools);for(const m of ms)m.updateMatrixWorld();
const bound=new T.Box3();for(const m of ms)bound.expandByObject(m);assert(bound.min.y>=-.001);assert(bound.max.y>16&&bound.max.y<18);const ray=new T.Raycaster(),probes:any[]=[];
const probe=(name:string,p:T.Vector3,n:T.Vector3,colours:string[])=>{const eye=p.clone().addScaledVector(n,6);ray.set(eye,n.clone().negate());const hit=ray.intersectObjects(ms)[0];assert(hit,`No hit ${name}`);const c=hit.object.userData.colour;probes.push({name,colour:c,distance:hit.distance,target:p.toArray()});assert(colours.includes(c),`${name} first hit ${c}; expected ${colours}`);assert(Math.abs(hit.distance-6)<.60,`${name} buried/floating surface ${hit.distance}`);};
const point=(u:number,v:number,y:number)=>new T.Vector3(5.32-.423*u+.906*v,y,-6.09-.906*u-.423*v),n=new T.Vector3(.906,0,-.423);
for(const u of [-1.6,-.8,.5,1.4])probe('front-upper-pane '+u,point(u,.48,9.11),n,['glass','dark','ochre']);
for(const u of [-3.78,4.05])probe('front-slit '+u,point(u,.49,5.50),n,['glass','ochre','dark']);
for(const u of [-.9,.9])probe('entry-door '+u,point(u,2.035,1.50),n,['ochre','brick','dark']);
probe('caretaker-wing-door',point(-3.76,2.04,.70),n,['ochre','dark']);probe('north-wing-window',point(4.24,2.04,1.62),n,['glass','ochre','dark']);
for(const t of [.33,.51,.69]){const a=[-14.47,-4.62],z=[3.01,-11.03],dx=z[0]-a[0],dz=z[1]-a[1],L=Math.hypot(dx,dz),nn=new T.Vector3(dz/L,0,-dx/L);for(const y of [2.5,4.3,6.8])probe('north-hall '+t+' y'+y,new T.Vector3(a[0]+dx*t+nn.x*.10,y,a[1]+dz*t+nn.z*.10),nn,['glass','ochre','dark']);}
for(const y of [1.1,4.55])probe('caretaker-side y'+y,new T.Vector3(10.8896-.37965*.13,y,-3.062-.92513*.13),new T.Vector3(-.37965,0,-.92513),['glass','ochre','dark']);
// Independent rejection regression: all six actual caretaker apertures must
// expose shallow segment glass/relieved arches, and their high corners must not
// retain the former rectangular glazing. Check native true wall normals.
const caretakerRoles=['caretaker-segment-head-glass','caretaker-relief-arch','caretaker-arched-frame'];
for(const role of caretakerRoles)assert.equal(ms.filter(m=>m.userData.role===role).length,6,`six ${role} assemblies`);
const ka=source.outline[0][0],kb=source.outline[0][48],kl=Math.hypot(kb[0]-ka[0],kb[1]-ka[1]),kx=(kb[0]-ka[0])/kl,kz=(kb[1]-ka[1])/kl;
const windows:any[]=[];for(const y of [.55,4.01])for(const t of [.27,.69])windows.push({name:`front-${t}-${y}`,x:ka[0]+(kb[0]-ka[0])*t,z:ka[1]+(kb[1]-ka[1])*t,y,w:1.33,h:2.55,tx:-kx,tz:-kz,nx:kz,nz:-kx});
const cl=Math.hypot(-2.68,1.10);for(const y of [.55,4.01])windows.push({name:`side-${y}`,x:10.8896,z:-3.062,y,w:1.14,h:2.45,tx:-2.68/cl,tz:1.10/cl,nx:-1.10/cl,nz:-2.68/cl});
for(const w of windows){const normal=new T.Vector3(w.nx,0,w.nz),wp=(u:number,yy:number,o=.13)=>new T.Vector3(w.x+w.tx*u+w.nx*o,w.y+yy,w.z+w.tz*u+w.nz*o);probe('caretaker-pane '+w.name,wp(w.w*.19,1.03),normal,['glass']);probe('caretaker-segment-head '+w.name,wp(w.w*.19,w.h-.10),normal,['glass']);probe('caretaker-relieved-arch '+w.name,wp(w.w*.35,w.h+.045,.20),normal,['brick','stone']);probe('caretaker-nonrectangular-corner '+w.name,wp(w.w*.49,w.h-.02),normal,['brick','stone','ochre']);}
// Forecourt must remain outside source Pand/body. Points in front of building are
// tested upward below canopy; stair approach has its own bounded extent.
for(const u of [-4,4]){ray.set(point(u,4.0,.1),new T.Vector3(0,1,0));assert.equal(ray.intersectObjects(ms).length,0,'forecourt filled');}
let roofTriangles=0;for(const m of ms.filter(m=>m.userData.role==='explicit-roof')){const p=m.geometry.getAttribute('position'),ix=m.geometry.index;for(let k=0;k<(ix?.count??p.count);k+=3){const ids=[0,1,2].map(j=>ix?ix.getX(k+j):k+j),ps=ids.map(i=>new T.Vector3().fromBufferAttribute(p,i)),norm=new T.Vector3().crossVectors(ps[1].clone().sub(ps[0]),ps[2].clone().sub(ps[0]));assert(norm.y>0,'downward roof');const center=ps[0].clone().add(ps[1]).add(ps[2]).multiplyScalar(1/3);ray.set(center.clone().add(new T.Vector3(0,.25,0)),new T.Vector3(0,-1,0));const hit=ray.intersectObjects([m])[0];assert(hit&&Math.abs(hit.distance-.25)<.01,'roof self visibility');roofTriangles++;}}
await MeshoptDecoder.ready;const file='artifacts/oosterparkkerk/oosterparkkerk.glb',doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(file);let decodedRedRoofFaces=0;let triangles=0;for(const m of doc.getRoot().listMeshes())for(const p of m.listPrimitives()){triangles+=(p.getIndices()?.getCount()??p.getAttribute('POSITION')!.getCount())/3;const a=p.getAttribute('POSITION')!.getArray()!;assert([...a].every(Number.isFinite));if(p.getMaterial()?.getName()==='red'){const ix=p.getIndices()?.getArray();for(let j=0;j<(ix?.length??a.length/3);j+=3){const ps=[0,1,2].map(k=>{const i=ix?ix[j+k]:j+k;return new T.Vector3(a[i*3],a[i*3+1],a[i*3+2]);}),nn=new T.Vector3().crossVectors(ps[1].clone().sub(ps[0]),ps[2].clone().sub(ps[0]));assert(nn.y>0,'compressed red roof downward');decodedRedRoofFaces++;}}}for(const m of doc.getRoot().listMaterials()){assert.equal(m.getMetallicFactor(),0);assert.equal(m.getBaseColorTexture(),null);}assert(triangles<40000);assert(fs.statSync(file).size<300000);
// Decode the actual compressed mesh, then reproduce all eight independent
// missing-wing rays and the complete1471-sample native footprint top inventory.
const compressed:T.Mesh[]=[];for(const node of doc.getRoot().listNodes())for(const p of node.getMesh()?.listPrimitives()??[]){const g=new T.BufferGeometry(),pa=p.getAttribute('POSITION')!,v=new Float32Array(pa.getCount()*3);for(let i=0;i<pa.getCount();i++)v.set(pa.getElement(i,[]),i*3);g.setAttribute('position',new T.BufferAttribute(v,3));const ix=p.getIndices()?.getArray();if(ix)g.setIndex(new T.BufferAttribute(ix,1));g.applyMatrix4(new T.Matrix4().fromArray(node.getWorldMatrix()));const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));m.userData={colour:p.getMaterial()?.getName()};m.updateMatrixWorld();compressed.push(m);}
ms.splice(0,ms.length,...compressed);for(const w of windows){const normal=new T.Vector3(w.nx,0,w.nz),wp=(u:number,yy:number,o=.13)=>new T.Vector3(w.x+w.tx*u+w.nx*o,w.y+yy,w.z+w.tz*u+w.nz*o);probe('compressed-caretaker-pane '+w.name,wp(w.w*.19,1.03),normal,['glass']);probe('compressed-caretaker-segment-head '+w.name,wp(w.w*.19,w.h-.10),normal,['glass']);probe('compressed-caretaker-relieved-arch '+w.name,wp(w.w*.35,w.h+.045,.20),normal,['brick','stone']);probe('compressed-caretaker-nonrectangular-corner '+w.name,wp(w.w*.49,w.h-.02),normal,['brick','stone','ochre']);}
const wingTopProbes:any[]=[];for(const u of [-4,-3,3,4])for(const v of [.8,1.4]){ray.set(point(u,v,20),new T.Vector3(0,-1,0));const hit=ray.intersectObjects(compressed)[0];assert(hit&&Math.abs(hit.point.y-3.42)<.005,'compressed wing top missing/wrong height');assert.equal(hit.object.userData.colour,'stone');wingTopProbes.push({u,v,height:hit.point.y,colour:hit.object.userData.colour});}
const ring=source.outline[0],inside=(x:number,z:number)=>{let yes=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if(((a[1]>z)!==(b[1]>z))&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;};let topGridSamples=0;const topGridGaps:any[]=[];for(let x=-14.5;x<13;x+=.5)for(let z=-11;z<18;z+=.5)if(inside(x,z)){topGridSamples++;ray.set(new T.Vector3(x,30,z),new T.Vector3(0,-1,0));const hit=ray.intersectObjects(compressed)[0];if(!hit||hit.point.y<.1)topGridGaps.push([x,z,hit?.point.y??null]);}assert.equal(topGridSamples,1471);assert.equal(topGridGaps.length,0,'uncovered native roof inventory');
let decodedCopingTopFaces=0;for(const m of compressed.filter(m=>m.userData.colour==='stone')){const p=m.geometry.getAttribute('position'),ix=m.geometry.index;for(let i=0;i<(ix?.count??p.count);i+=3){const ps=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,ix?ix.getX(i+j):i+j));if(!ps.every(p=>Math.abs(p.y-3.42)<.002))continue;const normal=new T.Vector3().crossVectors(ps[1].clone().sub(ps[0]),ps[2].clone().sub(ps[0]));assert(normal.y>0,'decoded coping top downward');decodedCopingTopFaces++;}}assert(decodedCopingTopFaces>0);
const report={status:'CPU-only; root/source-independent gallery/native/game acceptance pending',bound:{min:bound.min.toArray(),max:bound.max.toArray()},triangles,bytes:fs.statSync(file).size,probes,roofTriangles,decodedRedRoofFaces,decodedCopingTopFaces,wingTopProbes,topGridSamples,topGridGaps,sourcePand:source.pandId,sourceOSM:source.osmId,limitations:['Source59 partywall correction is recorded visual inference; independent comparison required','Rear hall facade obscured by adjoining school; no speculative repeated rear windows','Actual game, compressed roof-normal samples and performance evidence remain root review work']};fs.writeFileSync('artifacts/oosterparkkerk/check.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({triangles,bytes:report.bytes,probes:probes.length,roofTriangles,decodedRedRoofFaces,decodedCopingTopFaces,topGridSamples,topGridGaps,wingTopProbes,bound:report.bound}));
