import fs from 'node:fs';
import proj4 from 'proj4';
import {perspectiveCrop} from '../street-appearance/perspective';
const dir='artifacts/podium-mozaiek-source';
if(process.argv.includes('--prepare-sources')){
proj4.defs('RD','+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.4171,50.3319,465.5524,-0.398957,0.343988,-1.8774,4.0725 +units=m +no_defs');
const anchor=proj4('RD','EPSG:4326',[118717.8,488158.5]);
const native=(p:number[])=>{const ll=proj4('RD','EPSG:4326',p);return [(ll[0]-anchor[0])*111320*Math.cos(anchor[1]*Math.PI/180),-(ll[1]-anchor[1])*111320];};
const pand=JSON.parse(fs.readFileSync(`${dir}/pand.raw`,'utf8')),bag=JSON.parse(fs.readFileSync(`${dir}/3dbag.raw`,'utf8')),transform=bag.metadata.transform;
const vertices=bag.feature.vertices.map((p:number[])=>{const rd=p.map((v,i)=>v*transform.scale[i]+transform.translate[i]);const local=native(rd.slice(0,2));return [local[0],rd[2]-.262,local[1]];});
const geometry=Object.values(bag.feature.CityObjects).flatMap((o:any)=>o.geometry).find((g:any)=>g.lod==='2.2');
const roofs=geometry.boundaries[0].flatMap((face:number[][],i:number)=>geometry.semantics.surfaces[geometry.semantics.values[0][i]].type==='RoofSurface'?[{semantic:geometry.semantics.values[0][i],rings:face}]:[]);
fs.writeFileSync('scripts/landmarks/podium-mozaiek-footprints.json',JSON.stringify({id:'podium-mozaiek',bagPand:'0363100012122803',bagVbo:'0363010001021419',anchor,localRing:pand.geometrie.coordinates[0].slice(0,-1).map(native),surveyVertices:vertices,surveyRoofs:roofs,sourceGroundNAP:.262,sourceNotes:'BAG actual boundary; native WGS east/south metres. Roof semantic6 represents erroneous closed fit over thin tower, omitted. Main hall photos show curved roof approximated with original segmented barrel. Survey towers identify square bases and steel belfries; do not use22m OSM height as wallheight.'},null,2));
const pano=JSON.parse(fs.readFileSync(`${dir}/selected-panorama.json`,'utf8')),ll=pano.geometry.coordinates,heading=Math.atan2((anchor[0]-ll[0])*Math.cos(anchor[1]*Math.PI/180),anchor[1]-ll[1])*180/Math.PI;
fs.writeFileSync(`${dir}/panorama-front.jpg`,perspectiveCrop(fs.readFileSync(`${dir}/panorama.jpg`),heading,1400,1000,85,15));console.log({anchor,heading,roofs:roofs.length});
}
import * as T from 'three';
import {Document,NodeIO} from '@gltf-transform/core';
import {weld,dedup,prune,meshopt,join,flatten} from '@gltf-transform/functions';
import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
import {MeshoptEncoder} from 'meshoptimizer';
import type {BuildingTools} from './cultural-builders';
import {buildPodiumMozaiek} from './podium-mozaiek-builder';
import spec from './podium-mozaiek-spec.json';
const doc=new Document(),buffer=doc.createBuffer(),scene=doc.createScene(),materials=new Map<string,ReturnType<Document['createMaterial']>>(),meshes:T.Mesh[]=[];let triangles=0;
const colours:Record<string,string>={white:'#e1e2d9',glass:'#63776e',slate:'#655348',frame:'#b8bcb2',dark:'#343b36'};
const tools={add(g:T.BufferGeometry,c:string){g.userData.colour=c;g.computeVertexNormals();const material=materials.get(c)??doc.createMaterial(c).setBaseColorFactor([...new T.Color(colours[c]).toArray(),1]).setRoughnessFactor(1).setMetallicFactor(0);materials.set(c,material);const p=g.getAttribute('position'),n=g.getAttribute('normal'),prim=doc.createPrimitive().setAttribute('POSITION',doc.createAccessor().setType('VEC3').setArray(new Float32Array(p.array)).setBuffer(buffer)).setAttribute('NORMAL',doc.createAccessor().setType('VEC3').setArray(new Float32Array(n.array)).setBuffer(buffer)).setMaterial(material).setExtras({role:g.userData.role??'detail'});if(g.index)prim.setIndices(doc.createAccessor().setType('SCALAR').setArray(new Uint32Array(g.index.array)).setBuffer(buffer));scene.addChild(doc.createNode(g.userData.role).setMesh(doc.createMesh().addPrimitive(prim)));triangles+=(g.index?.count??p.count)/3;meshes.push(new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide})));}} as BuildingTools;
buildPodiumMozaiek(0,0,tools);const out='artifacts/podium-mozaiek-cpu';fs.mkdirSync(out,{recursive:true});await new NodeIO().write(`${out}/podium-mozaiek.glb`,doc);await MeshoptEncoder.ready;await doc.transform(flatten(),join(),weld(),dedup(),prune(),meshopt({encoder:MeshoptEncoder,level:'medium'}));await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder}).write(`${out}/podium-mozaiek-compressed.glb`,doc);
const bounds=new T.Box3();let nonfinite=0,downwardRoofFaces=0;const raycaster=new T.Raycaster(),glassChecks:{role:string,visible:boolean,hit?:string,distance?:number}[]=[];
for(const m of meshes){m.geometry.computeBoundingBox();m.updateMatrixWorld();bounds.expandByObject(m);const p=m.geometry.getAttribute('position'),n=m.geometry.getAttribute('normal');for(let i=0;i<p.count;i++)if(![p.getX(i),p.getY(i),p.getZ(i)].every(Number.isFinite))nonfinite++;if(m.geometry.userData.role.includes('roof')&&!m.geometry.userData.role.includes('cross'))for(let i=0;i<n.count;i++)if(n.getY(i)<-.01)downwardRoofFaces++;
 if(m.geometry.userData.role==='exposed-diamond-glass'){m.geometry.computeBoundingBox();const centre=m.geometry.boundingBox!.getCenter(new T.Vector3()),fac=m.geometry.userData.facadeFacing;const direction=new T.Vector3(-fac[0],0,-fac[1]),origin=centre.clone().addScaledVector(direction,-5);raycaster.set(origin,direction);const hits=raycaster.intersectObjects(meshes,false);glassChecks.push({role:m.geometry.userData.role,visible:hits[0]?.object===m,hit:(hits[0]?.object as T.Mesh)?.geometry.userData.role,distance:hits[0]?.distance});}}
const f=JSON.parse(fs.readFileSync('scripts/landmarks/podium-mozaiek-footprints.json','utf8')),upper=[118,92,97,112,122,134].map(i=>new T.Vector2(f.surveyVertices[i][0],f.surveyVertices[i][2])),centre=upper.reduce((a,p)=>a.add(p),new T.Vector2()).multiplyScalar(1/upper.length),wallSupport=[];
for(let i=0;i<upper.length;i++){const a=upper[i],c=upper[(i+1)%upper.length],axis=c.clone().sub(a).normalize(),normal=new T.Vector2(-axis.y,axis.x);if(normal.dot(a.clone().lerp(c,.5).sub(centre))<0)normal.negate();for(const fraction of [.2,.5,.8]){const p=a.clone().lerp(c,fraction);raycaster.set(new T.Vector3(p.x+normal.x*3,10.3,p.y+normal.y*3),new T.Vector3(-normal.x,0,-normal.y));raycaster.far=3.2;const hit=raycaster.intersectObjects(meshes,false)[0];wallSupport.push({edge:i,fraction,hit:!!hit,firstRole:(hit?.object as T.Mesh)?.geometry.userData.role});}}
const belfryOpen=[];for(const ids of [[136,141,82,85,138],[127,123,109,113,115,125]]){const center=ids.reduce((sum,i)=>sum.add(new T.Vector3(f.surveyVertices[i][0],0,f.surveyVertices[i][2])),new T.Vector3()).multiplyScalar(1/ids.length);for(const yy of [18.45,18.95]){raycaster.set(center.clone().add(new T.Vector3(3,yy,0)),new T.Vector3(-1,0,0));raycaster.far=6;const hits=raycaster.intersectObjects(meshes,false);belfryOpen.push({tower:ids[0],height:yy,blockedBySolid:hits.some(h=>['tower-square-base','clerestory-wall','full-native-scope-wall','church-raised-wall'].includes((h.object as T.Mesh).geometry.userData.role))});}}
const report={triangles,bytes:fs.statSync(`${out}/podium-mozaiek-compressed.glb`).size,bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},nonfinite,downwardRoofFaces,diamondFirstHitVisible:glassChecks.filter(p=>p.visible).length,diamondFirstHitChecks:glassChecks.length,glassChecks,wallSupport,belfryOpen,status:'CPU evidence only; native gallery/reference/independent/game checks remain'};fs.writeFileSync(`${out}/cpu-report.json`,JSON.stringify(report,null,2));console.log({...report,glassChecks:undefined,wallSupport:undefined,wallSupportPasses:wallSupport.filter(p=>p.hit).length});
import sharp from 'sharp';
for(const [name,position] of [['northwest',[-65,30,-60]],['southwest',[-60,30,65]],['east',[65,30,30]],['high',[55,75,-65]]] as [string,number[]][]){
 const camera=new T.PerspectiveCamera(36,1.4,.1,300);camera.position.set(...position as [number,number,number]);camera.lookAt(0,9,0);camera.updateMatrixWorld();const inverse=camera.matrixWorldInverse;
 const faces:{z:number,svg:string}[]=[];
 for(const m of meshes){const p=m.geometry.getAttribute('position'),ix=m.geometry.index;for(let i=0;i<(ix?.count??p.count);i+=3){const pts=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,ix?ix.getX(i+j):i+j));const normal=new T.Vector3().crossVectors(pts[1].clone().sub(pts[0]),pts[2].clone().sub(pts[0])).normalize(),centre=pts.reduce((a,p)=>a.add(p),new T.Vector3()).multiplyScalar(1/3);if(normal.dot(camera.position.clone().sub(centre))<0)continue;const col=new T.Color(colours[m.geometry.userData.colour]).multiplyScalar(.68+.32*Math.max(0,normal.dot(new T.Vector3(-.4,.8,-.3).normalize())));const coordinates=pts.map(p=>{p.project(camera);return `${((p.x+1)*700).toFixed(2)},${((1-p.y)*500).toFixed(2)}`;}).join(' ');faces.push({z:centre.applyMatrix4(inverse).z,svg:`<polygon points="${coordinates}" fill="#${col.getHexString()}"/>`});}}
 faces.sort((a,b)=>a.z-b.z);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="1000"><rect width="1400" height="1000" fill="#e3ebed"/>${faces.map(f=>f.svg).join('')}</svg>`;await sharp(Buffer.from(svg)).png().toFile(`${out}/cpu-${name}.png`);
}
