import fs from 'node:fs';
import sharp from 'sharp';
import {rdToLngLat} from '../../src/canalRecall/rdCoordinates';
const raw='../map-recall2-source-data/models/posthoornkerk/raw/';
const bag=JSON.parse(fs.readFileSync(raw+'bag-area.json','utf8'));
const church=bag.features.find((f:any)=>f.properties.identificatie==='0363100012167529');
const anchor:[number,number]=[4.89063,52.381275],ring=church.geometry.coordinates[0];
const native=(q:number[])=>[(q[0]-anchor[0])*111319.49*Math.cos(anchor[1]*Math.PI/180),-(q[1]-anchor[1])*111319.49];
const [a,c]=[native(ring[60]),native(ring[67])];
const turn=Math.atan2(-(c[1]-a[1]),c[0]-a[0]);
const local=(q:number[])=>{const [x,z]=native(q);return [x*Math.cos(turn)-z*Math.sin(turn),x*Math.sin(turn)+z*Math.cos(turn)]};
const d=JSON.parse(fs.readFileSync(raw+'3dbag.json','utf8')),tr=d.metadata.transform;
const vertices=d.feature.vertices.map((v:number[])=>{const rd=v.map((n,i)=>n*tr.scale[i]+tr.translate[i]);const q=local(rdToLngLat(rd[0],rd[1]));return [q[0],rd[2]-1.795,q[1]];});
const g=d.feature.CityObjects['NL.IMBAG.Pand.0363100012167529-0'].geometry.find((g:any)=>g.lod==='2.2');
const roofPlanes=g.boundaries[0].flatMap((s:any,i:number)=>{const sem=g.semantics.surfaces[g.semantics.values[0][i]];return sem.type==='RoofSurface'?[{semantic:sem,rings:s.map((r:number[])=>r.map(v=>vertices[v]))}]:[]});
const all=bag.features.map((f:any)=>({bagId:f.properties.identificatie,geometry:f.geometry,localRings:f.geometry.coordinates.map((r:number[][])=>r.map(local))}));
const prior=fs.existsSync('scripts/landmarks/posthoornkerk-footprints.json')?JSON.parse(fs.readFileSync('scripts/landmarks/posthoornkerk-footprints.json','utf8')):{};
const out={...prior,modelId:'posthoornkerk',anchor,localRotationDegrees:turn*180/Math.PI,coordinateConvention:'church axes x transverse, +z street front (SW); builder bakes rotation to east/south metres',parts:[{...prior.parts?.[0],bagId:church.properties.identificatie,geometry:church.geometry,localRing:ring.map(local)}],surveyRoofPlanes:roofPlanes,preserveNeighbors:all.filter((f:any)=>f.bagId!==church.properties.identificatie).map((f:any)=>({...prior.preserveNeighbors?.find((n:any)=>n.bagId===f.bagId),...f}))};
fs.writeFileSync('scripts/landmarks/posthoornkerk-footprints.json',JSON.stringify(out,null,2));
fs.mkdirSync('artifacts/posthoornkerk-survey',{recursive:true});
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1100" height="1000" viewBox="-60 -60 120 110"><rect x="-60" y="-60" width="120" height="110" fill="#eee"/>${all.map((f:any)=>`<path d="${f.localRings.map((r:number[][])=>'M'+r.map(q=>q.join(',')).join('L')+'Z').join('')}" fill="${f.bagId===church.properties.identificatie?'#e3a774':'#bbb'}" stroke="#333" stroke-width=".1"/><text x="${f.localRings[0][0][0]}" y="${f.localRings[0][0][1]}" font-size="1.4">${f.bagId.slice(-6)}</text>`).join('')}${out.parts[0].localRing.map((q:number[],i:number)=>`<text x="${q[0]}" y="${q[1]}" font-size=".8" fill="#900">${i}</text>`).join('')}</svg>`;
await sharp(Buffer.from(svg)).png().toFile('artifacts/posthoornkerk-survey/footprint.png');
const roofs=`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1200" viewBox="-25 -30 50 60"><rect x="-25" y="-30" width="50" height="60" fill="#eee"/>${roofPlanes.map((p:any,i:number)=>{const r=p.rings[0],max=Math.max(...r.map((q:number[])=>q[1])),cx=r.reduce((s:number,q:number[])=>s+q[0]/r.length,0),cz=r.reduce((s:number,q:number[])=>s+q[2]/r.length,0);return `<path d="M${r.map((q:number[])=>[q[0],q[2]].join(',')).join('L')}Z" fill="hsl(${max*8},45%,65%)" stroke="#222" stroke-width=".08"/><text x="${cx}" y="${cz}" font-size=".6">${i}:${max.toFixed(1)}</text>`}).join('')}</svg>`;
await sharp(Buffer.from(roofs)).png().toFile('artifacts/posthoornkerk-survey/roofs.png');
console.log(JSON.stringify({angle:out.localRotationDegrees,parts:out.parts.length,roofs:roofPlanes.length}));
