/** Isolated draft exporter; never touches shared manifests, catalogue or public models. */
import fs from 'node:fs';import * as T from 'three';
import {Document,NodeIO} from '@gltf-transform/core';import {dedup,prune,weld,meshopt} from '@gltf-transform/functions';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {MeshoptEncoder} from 'meshoptimizer';
import {buildPosthoornkerk} from './posthoornkerk-builder';import type {BuildingTools} from './cultural-builders';import spec from './posthoornkerk-spec.json';
await MeshoptEncoder.ready;
const palette={brick:'#9a5240',stone:'#cfc2a6',slate:'#4a525d',white:'#efe9db',gold:'#d9b24c',glass:'#527787',dark:'#303b43',frame:'#9daaa8',red:'#ac624e',blue:'#3f5f9a',pink:'#be9295',bronze:'#3d5148',copper:'#43888b',green:'#718b58',ochre:'#9f825c',concrete:'#d4d5d0',greyBrick:'#7d7871',...spec.materialOverrides};
const doc=new Document(),buffer=doc.createBuffer(),scene=doc.createScene(spec.id),mesh=doc.createMesh(spec.id),parts=new Map<string,T.BufferGeometry[]>();doc.getRoot().setDefaultScene(scene);
const b={add(g:T.BufferGeometry,c:string){if(!parts.has(c))parts.set(c,[]);parts.get(c)!.push(g.index?g.toNonIndexed():g);}} as BuildingTools;buildPosthoornkerk(1,1,b);
for(const [c,geos] of parts){const rgb=new T.Color(palette[c as keyof typeof palette]),m=doc.createMaterial(c).setBaseColorFactor([rgb.r,rgb.g,rgb.b,1]).setMetallicFactor(0).setRoughnessFactor(.9).setDoubleSided(true);const p=doc.createPrimitive().setAttribute('POSITION',doc.createAccessor().setType('VEC3').setArray(Float32Array.from(geos.flatMap(g=>Array.from(g.getAttribute('position').array)))).setBuffer(buffer)).setAttribute('NORMAL',doc.createAccessor().setType('VEC3').setArray(Float32Array.from(geos.flatMap(g=>Array.from(g.getAttribute('normal').array)))).setBuffer(buffer)).setMaterial(m);mesh.addPrimitive(p);}
scene.addChild(doc.createNode(spec.id).setMesh(mesh));await doc.transform(weld(),dedup(),prune(),meshopt({encoder:MeshoptEncoder,level:'medium'}));fs.mkdirSync('artifacts/posthoornkerk-draft',{recursive:true});await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder}).write('artifacts/posthoornkerk-draft/posthoornkerk.glb',doc);const triangles=doc.getRoot().listMeshes().flatMap(m=>m.listPrimitives()).reduce((n,p)=>n+(p.getIndices()?.getCount()??p.getAttribute('POSITION')!.getCount())/3,0);console.log(JSON.stringify({triangles,bytes:fs.statSync('artifacts/posthoornkerk-draft/posthoornkerk.glb').size,textures:doc.getRoot().listTextures().length}));
