import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const origin=process.env.CANAL_REVIEW_URL || 'http://127.0.0.1:5196';
await fs.mkdir('artifacts/manual-landmarks',{recursive:true});
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const id of ['nemo']){
  await page.goto(origin+'/canal-drive/manual-landmarks.html?only='+id);await page.waitForFunction(()=>window.review?.done,{timeout:60000});assert.deepEqual(await page.evaluate(()=>review.errors),[]);await page.addStyleTag({content:'main{display:block}article{max-width:none;width:100%}.view{height:740px!important}'});await page.evaluate(()=>dispatchEvent(new Event('resize')));await page.waitForTimeout(300);await page.screenshot({path:`artifacts/manual-landmarks/${id}-original-gallery.png`}); const canvas=page.locator('article canvas'),rect=await canvas.boundingBox();await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.5);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.5+314,rect.y+rect.height*.5,{steps:8});await page.mouse.up();await page.screenshot({path:`artifacts/manual-landmarks/${id}-original-gallery-opposite.png`});
 }
 await page.goto(origin+'/canal-drive/');await page.waitForFunction(()=>window.canalRecallGame?.vectorMap?._signatureLandmarks,{timeout:60000});const route=await page.evaluate(()=>canalRecallGame.routePois.find(p=>/NEMO|science center/i.test(p.name)));console.log({route});assert(route);await page.selectOption('#poi-destination',route.id);await page.locator('#route-card').evaluate(f=>f.requestSubmit());await page.waitForFunction(()=>canalRecallGame.state===4&&canalRecallGame.camera?.introOverview===0,{timeout:60000});await page.evaluate(()=>canalRecallGame.vectorMap.sync=()=>{});
 const results=[];
 for(const [id,center,zoom,bearing,parent] of [['nemo',[4.912322028079611,52.3741956935447],18,125,'w57856769']]){
  await page.evaluate(({center,zoom,bearing})=>canalRecallGame.vectorMap.map.jumpTo({center,zoom,pitch:57,bearing}),{center,zoom,bearing});await page.waitForFunction(id=>canalRecallGame.vectorMap._signatureLandmarks.shown.has(id)&&canalRecallGame.vectorMap._completeCityHasBuildings,id,{timeout:60000});await page.waitForTimeout(8500);
  const result=await page.evaluate(id=>{const v=canalRecallGame.vectorMap,s=v._signatureLandmarks;return{id,placement:s.describe().find(x=>x.id===id).placement,suppression:v._signatureSuppressOsmIds(),broad:s.shownFootprints().includes(s.models.find(x=>x.id===id).footprint)};},id);
  assert.equal(result.placement.scale,1);assert.equal(result.broad,false);assert.ok(result.suppression.includes(parent));const own=JSON.parse(await fs.readFile('scripts/landmarks/nemo-spec.json','utf8'));for(const key of own.suppressOsmIds)assert.ok(result.suppression.includes(key));for(const retained of ['w117064148','w640142120','w640142124','w269078519','w269078547'])assert.ok(!own.suppressOsmIds.includes(retained)); results.push(result);
  await page.screenshot({path:`artifacts/manual-landmarks/${id}-original-game.png`});
  await page.evaluate(b=>canalRecallGame.vectorMap.map.jumpTo({bearing:b}),bearing+180);await page.waitForTimeout(3000);await page.screenshot({path:`artifacts/manual-landmarks/${id}-original-game-opposite.png`});
 }
 const contract=await page.evaluate(async()=>{const g=canalRecallGame,v=g.vectorMap,lm=g.landmarks.find(l=>l.id==='extract_landmarks_1875483593'),T=CanalRecallThree.THREE,c=v.map.getCanvas(),entry=v._signatureLandmarks._entries.find(e=>e.spec.id==='nemo');let target=null;entry.group.updateWorldMatrix(true,true);entry.group.traverse(o=>{if(target||!o.isMesh)return;const a=o.geometry.getAttribute('position');for(let i=0;i<a.count;i+=Math.max(1,Math.floor(a.count/120))){const p=new T.Vector3().fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).applyMatrix4(entry.pickProjection),x=(p.x+1)/2*c.clientWidth,y=(1-p.y)/2*c.clientHeight;if(x<100||y<100||x>c.clientWidth-100||y>c.clientHeight-100)continue;const hit=v.inspectBuilding(x,y,{width:c.clientWidth,height:c.clientHeight});if(hit?.landmarkId===lm.id){const r=g.canvas.getBoundingClientRect();target={x:r.left+x/c.clientWidth*r.width,y:r.top+y/c.clientHeight*r.height};break;}}});const pins=await v.map.getSource('amsterdam-pois').getData();return {target,finish:g._finishLandmark()?.id,pin:pins.features.some(f=>f.properties.id===lm.id),name:lm.name,source:lm.sourceUrl};});assert(contract.target,'canonical NEMO mesh remains pickable');assert.equal(contract.finish,'extract_landmarks_1875483593');assert(contract.pin);await page.mouse.click(contract.target.x,contract.target.y);await page.waitForTimeout(500);const card=await page.evaluate(()=>({id:canalRecallGame._landmarkNotice?.id,bounds:canalRecallGame._landmarkCardBounds,source:canalRecallGame._landmarkNotice?.sourceUrl}));assert.equal(card.id,'extract_landmarks_1875483593');assert(card.bounds,'canonical card drawn');assert(card.source);await page.screenshot({path:'artifacts/manual-landmarks/nemo-original-game-card.png'});console.log(JSON.stringify({contract,card}));
 assert.deepEqual(errors,[]);console.log(JSON.stringify({results,errors}));
}finally{await browser.close();}
