import json,pathlib,hashlib,time,xml.etree.ElementTree as E
root=pathlib.Path('../map-recall2-source-data/models/this-is-holland');r=root/'files';prior=json.loads((root/'acquisition.json').read_text());records={pathlib.Path(p['file']).name:p for p in prior if p.get('file')};now=time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime())
for p in r.iterdir():
 if p.name.startswith('fe024b_') and p.suffix in ['.jpg','.png']:u='https://static.wixstatic.com/media/'+p.name;rights='Copyright DAMAST architects/Stijn Poelstra; research only';date='unstated'
 elif len(p.stem)==32 and p.suffix=='.jpg':u='https://static.wixstatic.com/media/fe024b_'+p.stem+'~mv2.jpg';rights='Copyright DAMAST architects/Stijn Poelstra; research only';date='unstated'
 elif p.name=='commons-2023.jpg':u='https://upload.wikimedia.org/wikipedia/commons/0/0e/2023_Overhoeksplein%2C_Asd-This_is_Holland.jpg';rights='Ceescamel, CC0';date='2023-09-24'
 elif p.name=='3dbag.json':u='https://api.3dbag.nl/collections/pand/items/NL.IMBAG.Pand.0363100012246118';rights='3DBAG, CC BY4.0; survey reference only';date='AHN5 2023'
 elif p.name=='osm-map.xml':u='https://api.openstreetmap.org/api/0.6/map?bbox=4.90210,52.38400,4.90260,52.38440';rights='OpenStreetMap contributors, ODbL';date='current response'
 elif p.name=='vbo1.json':u='https://api.pdok.nl/kadaster/bag/ogc/v2/collections/verblijfsobject/items/bb22dc06-a807-55fd-bf28-69d4ae073a4d';rights='BAG open data';date='not-realised historical record'
 elif p.name=='vbo2.json':u='https://api.pdok.nl/kadaster/bag/ogc/v2/collections/verblijfsobject/items/02e22473-9d41-5aaf-a9b1-549a4b88125f';rights='BAG open data';date='current in-use record'
 elif p.name=='roof-aerial.jpg':u=json.loads((r/'roof-aerial-request.json').read_text())['url'];rights='PDOK aerial, WMS AccessConstraints None; exact imagery reuse licence not independently resolved; research reference only';date='latest Actueel_orthoHR layer, exact flightdate unresolved'
 elif p.name=='aerial-capabilities.xml':u='https://service.pdok.nl/hwh/luchtfotorgb/wms/v1_0?service=WMS&request=GetCapabilities';rights='PDOK service metadata';date='2026-10-08'
 elif p.name in records:u=records[p.name]['url'];rights=records[p.name]['rights'];date='current response'
 else:u=None;rights='Processed task extract, not original HTTP response';date='2026-10-08'
 records[p.name]={**records.get(p.name,{}),'path':'files/'+p.name,'url':u,'retrievedAt':records.get(p.name,{}).get('retrievedAt',time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime(p.stat().st_mtime))),'status':200 if u else None,'accessState':'available','raw':bool(u),'captureDate':date,'rights':rights,'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
gaps=[{'url':'https://archief.amsterdam/beeldbank/?query=This%20is%20Holland','state':'HTTP200 JavaScript viewer shell, no inspected catalogue hits; bounded building-name search complete','historicRegister':'2018 purpose-built pavilion, not historic monument. No asserted monument status.'},{'url':'https://overpass-api.de/api/interpreter','state':'GET406, POST429; alternative kumi POST500. Recovered through successful original OSM map API XML; failures not permanent unavailability.','attemptDate':'2026-10-08'}]
manifest={'modelId':'this-is-holland','createdAt':now,'repository':'blackmad/map-recall2-source-data','sourceCommit':None,'publisher':'root only; no worker git actions','files':list(records.values()),'accessGaps':gaps,'derivedPublicFiles':['scripts/landmarks/this-is-holland-footprints.json','scripts/landmarks/this-is-holland-signs.json','scripts/landmarks/this-is-holland-research.json']};(root/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');print({'files':len(records),'totalBytes':sum(p['bytes'] for p in records.values()),'checksumsVerified':all(hashlib.sha256((root/p['path']).read_bytes()).hexdigest()==p['sha256'] for p in records.values())})
