import fs from 'node:fs';import * as T from 'three';
import {Document,NodeIO} from '@gltf-transform/core';import {dedup,prune,weld,meshopt} from '@gltf-transform/functions';
import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {MeshoptEncoder} from 'meshoptimizer';await MeshoptEncoder.ready;
import {buildThisIsHolland} from './this-is-holland-builder';import type {BuildingTools} from './cultural-builders';
import spec from './this-is-holland-spec.json';
const palette={brick:'#9a5240',stone:'#cfc2a6',slate:'#4a525d',white:'#efe9db',gold:'#d9b24c',glass:'#527787',dark:'#303b43',frame:'#9daaa8',red:'#ac624e',blue:'#3f5f9a',pink:'#be9295',bronze:'#3d5148',copper:'#43888b',green:'#718b58',ochre:'#9f825c',concrete:'#d4d5d0',greyBrick:'#7d7871'},parts:{g:T.BufferGeometry,c:keyof typeof palette}[]=[];
buildThisIsHolland(29,29,{add(g,c,x=0,y=0,z=0,angle=0){g.rotateY(angle);g.translate(x,y,z);parts.push({g,c})}} as BuildingTools);
const doc=new Document(),buffer=doc.createBuffer(),scene=doc.createScene('this-is-holland'),mesh=doc.createMesh('this-is-holland');doc.getRoot().setDefaultScene(scene);
for(const c of new Set(parts.map(p=>p.c))){const geos=parts.filter(p=>p.c===c).map(p=>p.g.index?p.g.toNonIndexed():p.g),rgb=new T.Color((spec.materialOverrides as Record<string,string>)[c]??palette[c]);mesh.addPrimitive(doc.createPrimitive().setAttribute('POSITION',doc.createAccessor().setType('VEC3').setArray(Float32Array.from(geos.flatMap(g=>Array.from(g.getAttribute('position').array)))).setBuffer(buffer)).setAttribute('NORMAL',doc.createAccessor().setType('VEC3').setArray(Float32Array.from(geos.flatMap(g=>Array.from(g.getAttribute('normal').array)))).setBuffer(buffer)).setMaterial(doc.createMaterial(c).setBaseColorFactor([rgb.r,rgb.g,rgb.b,1]).setRoughnessFactor(.9).setMetallicFactor(0).setDoubleSided(true)));}
scene.addChild(doc.createNode('this-is-holland').setMesh(mesh));await doc.transform(weld(),dedup(),prune());await doc.transform(meshopt({encoder:MeshoptEncoder,level:'medium'}));const out='artifacts/this-is-holland-draft/this-is-holland.glb';await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder}).write(out,doc);const triangles=doc.getRoot().listMeshes().flatMap(m=>m.listPrimitives()).reduce((n,p)=>n+p.getIndices()!.getCount()/3,0),bytes=fs.statSync(out).size;console.log(JSON.stringify({triangles,bytes,textures:doc.getRoot().listTextures().length,scope:'Isolated compressed draft; native visual/game acceptance pending'}));if(triangles>=40000||bytes>=500000)throw Error('Budget exceeded');
