import json,pathlib,hashlib,datetime,re
root=pathlib.Path('../map-recall2-source-data/models/uilenburger-synagoge');raw=root/'raw';records=[]
for p in sorted(raw.glob('*.provenance.json')):
 m=json.loads(p.read_text());original=pathlib.Path(str(p).removesuffix('.provenance.json'));m.update(rawPath=str(original.resolve()),path=str(original.relative_to(root)),checksumVerified=hashlib.sha256(original.read_bytes()).hexdigest()==m['sha256']);records.append(m)
manifest={'id':'uilenburger-synagoge','retrievedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sources':records,'accessFailures':[json.loads(p.read_text()) for p in raw.glob('*.access.json')],'processedImages':[{'path':p.name,'original':'raw/operator-brochure.pdf','operation':'pdftoppm first two pages1300px'} for p in root.glob('processed*')],'publishState':'coordinator owns source publication; worker does not stage/commit/push'}
(root/'source-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
register=re.sub('<[^>]+>',' ',(raw/'register5798.html').read_text());description=re.search(r'Synagoge\. Op binnenerf.*?Deuromlijsting\.',register,re.S).group(0)
(root/'parsed-register.json').write_text(json.dumps({'source':'raw/register5798.html','originalDescription':description,'part':'whole1766 synagogue','confidence':'high','parsedSeparately':True},indent=2)+'\n')
assertions=[]
def claim(url,part,date,confidence,features):assertions.append(dict(source=url,part=part,date=date,confidence=confidence,features=features))
claim('https://monumentenregister.cultureelerfgoed.nl/monumenten/5798','whole/front','read2026-10-08','high','1766 rectangular building behind a wall on an inner courtyard; lower former ritual slaughter room; three-aisled upper hall; centre risalit, bell-shaped front top, framed doorway. Register states no roof pitch, window dimensions or pane counts.')
claim('https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten/0363010000758197/','identity','2026-10-08','high','Address91 VBO explicitly belongs to pand0363100012181889.665m² is usable floor area, not254m² footprint. Current parent records free-standing synagogue and active geometry/year/status investigations.')
claim('https://api.3dbag.nl/collections/pand/items/NL.IMBAG.Pand.0363100012181889','roof','AHN5 2023','high-survey','Four semantic roof planes: lower57.38/60.09°,upper12.22/14.36°. GroundNAP0.785m; roof ridge15.03m aboveground. b3_h_nok16.97m bounds approximate17m bell gable, not wholebuilding roof plate.')
claim('https://www.uilenburgersjoel.nl/wp-content/uploads/2024/03/01.Uilenburgersjoel-informatie-en-catering.pdf','front','brochureMarch2024; photo date unstated','high-form/medium-dimensions','Brown brick; three upper arched windows with raised centre; two lower gridded windows; pale stone doorcase, fanlight, dark double doors; three oculi and outer stone volutes. Current restored photo agrees2016 source. Native facade dimensions remain photo-guided approximations.')
claim('https://www.amsterdam-monumentenstad.nl/database/pics/3/20210912-35.jpg','rear','filename2021-09-12','high-form/medium-dimensions','Rendered stonegray face with stepped peaked crest. Glazed centre upper arch, blind outer arches, lower white gridded windows and two darkglass doors with steps. Distinct from brick front.')
claim('https://www.amsterdam-monumentenstad.nl/database/pics/2/OSIM00001004038.jpg','historic roof/context','historic; exact capture date unresolved','medium','Historic photo confirms mansard break, tiled roof and longside arched windows. Low rear annex/chimneys/roofrails are historical state, not copied into current2023/2021 building.')
research={'id':'uilenburger-synagoge','status':'isolated-draft-geometry-passed-visual-acceptance-pending','retrievedAt':'2026-10-08','identity':{'poiId':'extract_landmarks_452804039','osmId':'w268782551','bagId':'0363100012181889','vbo':'0363010000758197','monument':'5798','address':'Nieuwe Uilenburgerstraat91','scope':'Current freestanding parent only; retain open forecourt and all recorded adjacent parents.'},'assertions':assertions,'sources':records,'sourceArchive':{'repository':'blackmad/map-recall2-source-data','path':'models/uilenburger-synagoge','commit':None,'publicationOwner':'coordinator'},'criticalRecognition':['bell-shaped brick front','raised centre arch and three oculi','white subdivided side arches','mansard break','rendered blind-arch rear','open forecourt'],'access':{'Beeldbank':{'url':'https://archief.amsterdam/beeldbank/?mode=gallery&view=horizontal&q=Nieuwe%20Uilenburgerstraat%2091','state':'Bounded exact-address search returned JS viewer shell. No catalogue record/drawing inspected.'},'Bouwdossiers':{'url':'https://beta.archief.amsterdam/handleiding/bouwdossiers','state':'Guidance captured; no building-specific drawing downloaded; no email request sent.'},'aerial':'PDOK2024/2025/current responses200 but white images. Explicit access gap; not inspected roof photos. Roof planes available from AHN5; historic photo cross-check inspected.','panorama':'2021 canal rear inspected.2025 street photo too distant/occluded to resolve front;2024 operator brochure supplies clear restored front.','network':'Two Overpass endpoints failed with bounded retries; third succeeded. Failed attempts preserved as transient failures, not permanent unavailability.'},'uncertainties':['Photo dates/rights unresolved where catalogue does not specify.','BAG geometry/year/status active investigations retained.','Exact gable/profile dimensions, rear crest and five-bay side spacing are photo-guided; root independent comparison required.','Current roof photo access gap remains explicit; semantic survey and historic mansard reference support modeled roof.'],'review':{'worker':'CPU source/render inspected; found and fixed buried central front arch. Failed PNG and initial mullion probe samples preserved.','acceptance':'Pending independent/gallery/live both sides/loaded suppression and neighbors/route/pin/physical sourced card/performance.'}}
pathlib.Path('scripts/landmarks/uilenburger-synagoge-research.json').write_text(json.dumps(research,indent=2)+'\n')
print(json.dumps({'originals':len(records),'checksumVerified':all(r['checksumVerified'] for r in records)}))
