/** Generate detailed and bulk review UIs for structural façade grammar labels. */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve('.cache/building-enrichment/panorama'), output = path.join(root, 'grammar-review'); await mkdir(output, { recursive: true });
const manifest = JSON.parse(await readFile(path.join(root, 'manifest.json'), 'utf8')) as { items: Array<Record<string, unknown>> };
const grammar = JSON.parse(await readFile(path.join(root, 'facade-grammar-machine-labels.json'), 'utf8')) as { labels: Array<Record<string, unknown>> };
const itemById = new Map(manifest.items.map(x => [String(x.buildingId), x]));
const items = grammar.labels.map(label => ({ ...itemById.get(String(label.buildingId)), grammar: label })).sort((a, b) => Number((a.grammar as Record<string, unknown>).confidence) - Number((b.grammar as Record<string, unknown>).confidence));
const enums = {
  windowPattern: ['narrow-vertical','regular-grid','wide-horizontal','curtain-wall','irregular','mostly-blank','unknown'], windowToWall: ['low','medium','high','unknown'], windowFrameColour: ['white','cream','grey','black','brown','green','blue','red','metal','mixed','unknown'], windowRecess: ['flush','shallow','deep','unknown'], groundFloorType: ['same-as-upper','residential-base','shopfront','commercial-glazing','arcade','garage-loading','mostly-blank','unknown'], entranceType: ['single-residential','shared-residential','multiple-doors','commercial','garage-loading','mixed','none-visible','unknown'], balconyType: ['none','projecting','recessed','gallery','mixed','not-visible','unknown'], facadeComposition: ['single-field','base-body','ground-floor-distinct','vertical-zones','mixed','unknown'], roofline: ['flat-parapet','stepped-gable','bell-gable','neck-gable','spout-gable','triangular-gable','mansard-eave','other','not-visible','unknown'], ornament: ['minimal','moderate','elaborate','unknown'],
};
const data = JSON.stringify(items).replaceAll('<', '\\u003c'), enumData = JSON.stringify(enums);
const common = `<style>:root{font:14px system-ui;color:#17212a;background:#e9e7e1}*{box-sizing:border-box}body{margin:0}header{position:sticky;top:0;z-index:4;display:flex;gap:9px;align-items:center;padding:12px 18px;background:#172a36;color:white}button,input,select{font:inherit}button{border:0;border-radius:7px;padding:9px 12px}.primary{background:#1680a8;color:white}.muted{background:#e5e7eb}.progress{margin-left:auto}</style>`;
const detail = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Façade grammar review</title>${common}<style>.card{max-width:1150px;margin:20px auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px #0002}.photo{display:block;width:100%;max-height:58vh;object-fit:contain;background:#222}.meta,.form{padding:12px 18px}.form{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.form label{display:grid;gap:4px;font-weight:650}.wide{grid-column:1/-1}.proposal{background:#eef4f6;border-radius:8px;padding:10px}@media(max-width:760px){.form{grid-template-columns:1fr}}</style></head><body><header><strong>Façade grammar review</strong><button id="prev" class="muted">← Previous</button><button id="next" class="primary">Save & next →</button><button id="import" class="muted">Import</button><button id="export" class="muted">Export</button><input id="file" type="file" hidden><a href="overview.html" style="color:white">Overview</a><span id="progress" class="progress"></span></header><main id="app"></main><script>
const items=${data},enums=${enumData},key='mapRecall.facadeGrammarReview.v1';let labels=JSON.parse(localStorage.getItem(key)||'{}'),requested=new URLSearchParams(location.search).get('building'),index=Math.max(0,items.findIndex(x=>x.buildingId===requested));const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),opts=(xs,v)=>xs.map(x=>'<option '+(x===v?'selected':'')+'>'+x+'</option>').join('');
function save(){const x=items[index],value={buildingId:x.buildingId,panoId:x.panoId,source:'human-panorama-facade-grammar',reviewedAt:new Date().toISOString(),visibleStoreys:Number(q('#storeys').value)||null,bayCount:Number(q('#bays').value)||null,groundFloorDistinct:q('#distinct').value==='unknown'?null:q('#distinct').value==='true',notes:q('#notes').value};for(const field of Object.keys(enums))value[field]=q('#'+field).value;labels[x.buildingId]=value;localStorage.setItem(key,JSON.stringify(labels))}
function render(){const x=items[index],g=labels[x.buildingId]||x.grammar;q('#progress').textContent=(index+1)+' / '+items.length+' · '+Object.keys(labels).length+' reviewed';q('#app').innerHTML='<article class="card"><img class="photo" src="../'+x.image+'"><div class="meta"><b>'+x.buildingId+'</b> · '+x.observedAt+' · model confidence '+Math.round(x.grammar.confidence*100)+'%</div><div class="form"><label>Visible storeys<input id="storeys" type="number" min="1" value="'+(g.visibleStoreys||'')+'"></label><label>Façade bays<input id="bays" type="number" min="1" value="'+(g.bayCount||'')+'"></label><label>Ground floor distinct<select id="distinct">'+opts(['true','false','unknown'],g.groundFloorDistinct===null?'unknown':String(g.groundFloorDistinct))+'</select></label>'+Object.entries(enums).map(([field,values])=>'<label>'+field.replaceAll(/([A-Z])/g,' $1')+'<select id="'+field+'">'+opts(values,g[field])+'</select></label>').join('')+'<div class="proposal wide"><b>Model rationale:</b> '+esc(x.grammar.rationale)+'</div><label class="wide">Notes<input id="notes" value="'+esc(g.notes||'')+'"></label></div></article>'}
q('#next').onclick=()=>{save();index=Math.min(items.length-1,index+1);render()};q('#prev').onclick=()=>{save();index=Math.max(0,index-1);render()};q('#export').onclick=()=>{save();const a=document.createElement('a'),blob=new Blob([JSON.stringify({schemaVersion:1,labels:Object.values(labels)},null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download='facade-grammar-human-labels.json';a.click()};q('#import').onclick=()=>q('#file').click();q('#file').onchange=async e=>{const d=JSON.parse(await e.target.files[0].text());for(const x of d.labels||[])labels[x.buildingId]=x;localStorage.setItem(key,JSON.stringify(labels));render()};render();
</script></body></html>`;
const overview = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Façade grammar overview</title>${common}<style>.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px;padding:12px}.card{background:white;border-radius:9px;overflow:hidden;color:inherit;text-decoration:none;box-shadow:0 2px 12px #0002}.card img{display:block;width:100%;height:210px;object-fit:cover;background:#222}.meta{padding:9px}.chips{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.chip{background:#edf1f3;border-radius:8px;padding:3px 6px}.low{color:#a32626}</style></head><body><header><strong>Façade grammar overview</strong><label>Confidence <select id="confidence"><option value="all">All</option><option value="low">Below 60%</option><option value="high">60%+</option></select></label><label><input id="unreviewed" type="checkbox"> Unreviewed only</label><a href="index.html" style="color:white">Detailed editor →</a><span id="count" class="progress"></span></header><main id="grid" class="grid"></main><script>
const items=${data},key='mapRecall.facadeGrammarReview.v1';let labels=JSON.parse(localStorage.getItem(key)||'{}');const q=s=>document.querySelector(s);function render(){const mode=q('#confidence').value,only=q('#unreviewed').checked,shown=items.filter(x=>(!only||!labels[x.buildingId])&&(mode==='all'||mode==='low'&&x.grammar.confidence<.6||mode==='high'&&x.grammar.confidence>=.6));q('#count').textContent=shown.length+' / '+items.length;q('#grid').innerHTML=shown.map(x=>'<a class="card" href="index.html?building='+encodeURIComponent(x.buildingId)+'"><img loading="lazy" src="../'+x.image+'"><div class="meta"><b>'+x.buildingId.replace('bag:','')+'</b> <b class="'+(x.grammar.confidence<.6?'low':'')+'">'+Math.round(x.grammar.confidence*100)+'%</b><div class="chips"><span class="chip">'+(x.grammar.visibleStoreys||'?')+' storeys</span><span class="chip">'+(x.grammar.bayCount||'?')+' bays</span><span class="chip">'+x.grammar.windowPattern+'</span><span class="chip">'+x.grammar.groundFloorType+'</span><span class="chip">'+x.grammar.balconyType+' balconies</span><span class="chip">'+x.grammar.roofline+'</span></div></div></a>').join('')}q('#confidence').onchange=render;q('#unreviewed').onchange=render;render();
</script></body></html>`;
await writeFile(path.join(output, 'index.html'), detail); await writeFile(path.join(output, 'overview.html'), overview); process.stdout.write(`Wrote ${items.length} façade grammar review items\n`);
