/** Author a visibly separate private-garden canopy prior, never municipal/OSM identities. */
import {readFileSync,writeFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {hash01} from '../src/canalRecall/facadeExtraCore.ts';
import {allotmentParks,contains} from './allotment-house-source.ts';
const patches=JSON.parse(readFileSync('src/canalRecall/allotmentGardenPatches.json','utf8'));
const mapped=['15-16825-10766','15-16826-10766'].flatMap(k=>JSON.parse(gunzipSync(readFileSync(`public/data/extracts/amsterdam/municipal-trees/tiles/${k}.json.gz`)).toString()).trees).filter(t=>allotmentParks.some(p=>contains(p.geometry,[t.lng,t.lat])));
const distance=(a:any,b:any)=>Math.hypot((a.lng-b.lng)*111320*Math.cos(a.lat*Math.PI/180),(a.lat-b.lat)*110540);
const candidates=Object.entries(patches).flatMap(([id,rows])=>(rows as number[][]).map((r,i)=>({id:`allotment-canopy:${id}:${i}`,lng:r[0]+(hash01(`${id}:${i}:x`)-.5)*1.2/(111320*Math.cos(r[1]*Math.PI/180)),lat:r[1]+(hash01(`${id}:${i}:y`)-.5)*1.2/110540,source:'allotment-prior',height:8+hash01(`${id}:${i}:canopy-height`)*5,species:'',type:'Approximate private garden canopy',rank:hash01(`${id}:${i}:canopy-placement`)}))).sort((a,b)=>a.rank-b.rank);
const authored:typeof candidates=[];
for(const c of candidates)if(!mapped.some(t=>distance(c,t)<4.5)&&!authored.some(t=>distance(c,t)<5))authored.push(c);
const data={version:1,approximate:true,meaning:'Authored private-garden canopy placement on source-screened clear ground; not surveyed individual trees. Mapped trees remain unchanged in source inventory. Crown widths are aerial-guided scoped priors, not measurements.',parks:allotmentParks.map(p=>p.geometry),trees:authored.map(({rank,...t})=>({...t,height:Number(t.height.toFixed(1))}))};
writeFileSync('public/canal-drive/js/allotment-canopy-data.js',`// Generated by scripts/build-allotment-canopy.ts; explicit approximate visual layer.\nexport default ${JSON.stringify(data)};\n`);
writeFileSync('artifacts/sloterdijkermeer-review/allotment-canopy-generation.json',JSON.stringify({mapped:mapped.length,authored:authored.length,parkCounts:allotmentParks.map(p=>({park:p.properties.name,mapped:mapped.filter(t=>contains(p.geometry,[t.lng,t.lat])).length,authored:authored.filter(t=>contains(p.geometry,[t.lng,t.lat])).length})),minimumTrunkDistanceToMappedM:4.5,minimumAuthoredSpacingM:5,privateHeightPriorM:[8,13],source:'User aerial image and GardenDrum ground reference; screened cells from cached OSM path/water/building geometry. Individual private-tree positions/heights are authored.',scope:'Both recorded allotment polygons only; communal lawns without screened house-adjacent cells remain open.'},null,2)+'\n');
console.log({mapped:mapped.length,authored:authored.length});
