/** Generate a local human-review UI with orthophoto tiles and BAG overlays. */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
type Point = [number, number]; type Geometry = { type: 'Polygon'; coordinates: Point[][] } | { type: 'MultiPolygon'; coordinates: Point[][][] };
type Building = { properties: Record<string, unknown>; geometry: Geometry };
type Observation = { buildingId: string; measuredColour: string; quantizedColour: string; confidence: number; diagnostics: { tileKeys: string[]; channelIqr: number; acceptedPixels: number } };
const root = path.resolve('.cache/roof-enrichment'), outputDirectory = path.join(root, 'review'); await mkdir(outputDirectory, { recursive: true });
const bag = JSON.parse(await readFile(path.join(root, 'a10-bag-buildings.geojson'), 'utf8')) as { features: Building[] };
const results = JSON.parse(await readFile(path.join(root, 'roof-color-observations.json'), 'utf8')) as { observations: Observation[] };
const buildings = new Map(bag.features.map(x => [String(x.properties.buildingId), x]));
const R = 6378137, TILE_METRES = 128, TILE_PIXELS = 1024, m = ([lon, lat]: Point): Point => [(lon * Math.PI / 180) * R, Math.log(Math.tan(Math.PI / 4 + lat * Math.PI / 360)) * R];
const polygons = (g: Geometry): Point[][][] => g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
const items = results.observations.sort((a, b) => a.confidence - b.confidence).map(observation => {
  const building = buildings.get(observation.buildingId); if (!building) return null;
  const projected = polygons(building.geometry).map(p => p.map(r => r.map(m)));
  const tiles = observation.diagnostics.tileKeys.map(key => { const [tx, ty] = key.split(',').map(Number), ox = tx * TILE_METRES, oy = ty * TILE_METRES; const paths = projected.map(polygon => polygon.map(ring => ring.map(([x, y]) => `${((x - ox) / TILE_METRES * TILE_PIXELS).toFixed(1)},${(TILE_PIXELS - (y - oy) / TILE_METRES * TILE_PIXELS).toFixed(1)}`).join(' '))); return { key, image: `../pdok-ortho-tiles/${tx}_${ty}.jpg`, paths }; });
  return { ...observation, buildYear: building.properties.bouwjaar, tiles };
}).filter(Boolean);
const embedded = JSON.stringify(items).replaceAll('<', '\\u003c');
const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Roof colour review</title><style>
:root{font:15px system-ui;color:#18212a;background:#e9e7e1}*{box-sizing:border-box}body{margin:0}header{position:sticky;top:0;z-index:5;display:flex;gap:9px;align-items:center;padding:12px 18px;background:#172a36;color:white}button,input{font:inherit}.progress{margin-left:auto}.card{max-width:1100px;margin:20px auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px #0002}.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));background:#222}.tile{position:relative;aspect-ratio:1;overflow:hidden}.tile img,.tile svg{position:absolute;width:100%;height:100%}.tile svg{pointer-events:none}.meta,.controls{padding:14px 18px}.controls{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.swatch{width:42px;height:42px;border-radius:7px;border:2px solid #222}.proposal{padding:8px 12px;background:#eef3f5;border-radius:8px}button{border:0;border-radius:7px;padding:9px 12px;cursor:pointer}.primary{background:#147da5;color:white}.muted{background:#e4e7e9}</style></head><body><header><strong>Inside-A10 roof review</strong><button id="prev" class="muted">← Previous</button><button id="next" class="primary">Save & next →</button><button id="import" class="muted">Import</button><button id="export" class="muted">Export</button><input id="file" type="file" hidden><span id="progress" class="progress"></span></header><main id="app"></main><script>
const items=${embedded},key='mapRecall.roofReview.v1';let labels=JSON.parse(localStorage.getItem(key)||'{}'),index=0;const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){const x=items[index];if(!x)return;labels[x.buildingId]={buildingId:x.buildingId,roofColour:q('#colour').value,accepted:q('#accept').checked,notes:q('#notes').value,source:'human-roof-review',reviewedAt:new Date().toISOString()};localStorage.setItem(key,JSON.stringify(labels))}
function render(){const x=items[index];q('#progress').textContent=(index+1)+' / '+items.length+' · '+Object.keys(labels).length+' reviewed';const old=labels[x.buildingId]||{};q('#app').innerHTML='<article class="card"><div class="tiles">'+x.tiles.map(t=>'<div class="tile"><img src="'+t.image+'"><svg viewBox="0 0 1024 1024">'+t.paths.flatMap(p=>p.map(points=>'<polygon points="'+points+'" fill="#ff2aa355" stroke="#ff2aa3" stroke-width="4"/>')).join('')+'</svg></div>').join('')+'</div><div class="meta"><b>'+x.buildingId+'</b> · built '+x.buildYear+' · confidence '+Math.round(x.confidence*100)+'% · IQR '+x.diagnostics.channelIqr+'</div><div class="controls"><span class="swatch" style="background:'+x.measuredColour+'"></span><span class="proposal">Measured '+x.measuredColour+' → quantized '+x.quantizedColour+'</span><label>Chosen colour <input id="colour" type="color" value="'+esc(old.roofColour||x.quantizedColour)+'"></label><label><input id="accept" type="checkbox" '+(old.accepted!==false?'checked':'')+'> Accept</label><label>Notes <input id="notes" value="'+esc(old.notes||'')+'"></label></div></article>'}
q('#next').onclick=()=>{save();index=Math.min(items.length-1,index+1);render()};q('#prev').onclick=()=>{save();index=Math.max(0,index-1);render()};q('#export').onclick=()=>{save();const a=document.createElement('a'),blob=new Blob([JSON.stringify({schemaVersion:1,labels:Object.values(labels)},null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download='roof-colour-human-labels.json';a.click()};q('#import').onclick=()=>q('#file').click();q('#file').onchange=async e=>{const data=JSON.parse(await e.target.files[0].text());for(const x of data.labels||[])labels[x.buildingId]=x;localStorage.setItem(key,JSON.stringify(labels));render()};render();
</script></body></html>`;
await writeFile(path.join(outputDirectory, 'index.html'), html);
process.stdout.write(`Wrote ${items.length} low-confidence-first roof review items\n`);
