/** Build an offline review desk joining panorama crops to multi-model façade grammar proposals. */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const arg = (name: string) => process.argv.find(value => value.startsWith(`--${name}=`))?.slice(name.length + 3);
const root = path.resolve(arg('root') || '.cache/facade-review');
type Item = { osmId: string; panoId: string; image: string; observedAt?: string; heading?: number; sourceUrl?: string };
type Proposal = { model: string; label?: Record<string, unknown>; error?: string };
type Result = { osmId: string; panoId: string; proposals: Proposal[]; consensus: Record<string, unknown>; autoEligible: boolean };
const manifest = JSON.parse(await readFile(path.join(root, 'manifest.json'), 'utf8')) as { items: Item[] };
const inference = JSON.parse(await readFile(path.join(root, 'facade-grammar-proposals.json'), 'utf8')) as { models: string[]; budget?: { observedCostUsd?: number }; results: Result[] };
const results = new Map(inference.results.map(result => [`${result.osmId}\0${result.panoId}`, result]));
const joined = manifest.items.flatMap(item => {
  const result = results.get(`${item.osmId}\0${item.panoId}`);
  return result ? [{ ...item, result }] : [];
});
if (!joined.length) throw new Error('No façade proposals match manifest osmId + panoId');
const embedded = JSON.stringify(joined).replaceAll('<', '\\u003c');
const models = JSON.stringify(inference.models).replaceAll('<', '\\u003c');
const cost = Number(inference.budget?.observedCostUsd || 0).toFixed(4);
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Amsterdam façade grammar review</title><style>
:root{font:14px/1.4 Inter,system-ui;color:#e8edf0;background:#10161b;--panel:#182128;--line:#34434d;--cyan:#71d9ee;--muted:#98a8b2;--agree:#b8f5ce;--split:#ffd29a}*{box-sizing:border-box}body{margin:0}header{position:sticky;top:0;z-index:3;display:flex;align-items:center;gap:10px;padding:12px 18px;background:#10161bf2;border-bottom:1px solid var(--line)}h1{margin:0 16px 0 0;font-size:18px;color:var(--cyan)}button{font:inherit;padding:8px 12px;border:1px solid #50616b;border-radius:6px;background:#24313a;color:#fff;cursor:pointer}button.primary{background:#2388a1;border-color:#59cde8}.progress{margin-left:auto;color:var(--muted)}main{max-width:1500px;margin:18px auto;padding:0 18px}.hero{display:grid;grid-template-columns:minmax(440px,1.18fr) minmax(500px,1fr);overflow:hidden;border:1px solid var(--line);border-radius:10px;background:var(--panel)}.photo-wrap{min-height:620px;background:#080b0d;display:grid;place-items:center}.photo{display:block;max-width:100%;max-height:78vh}.review{padding:18px;overflow:auto}.meta{color:var(--muted);margin-bottom:12px}.meta strong{color:#fff}.flag{display:inline-block;padding:3px 7px;border-radius:99px;background:#273a42;color:var(--cyan)}h2{font-size:13px;text-transform:uppercase;letter-spacing:.1em;color:var(--muted);margin:18px 0 8px}.consensus{display:flex;flex-wrap:wrap;gap:6px}.chip{padding:5px 8px;border-radius:5px;background:#183b32;color:var(--agree)}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{text-align:left;vertical-align:top;padding:7px;border-bottom:1px solid var(--line);overflow-wrap:anywhere}th:first-child{width:24%;color:var(--muted)}td.same{color:var(--agree)}td.split{color:var(--split)}.rationale{margin-top:12px;padding:10px;border-left:3px solid #52636d;color:#bac6cc;background:#121a1f}.fine{color:#71818a;font-size:11px}@media(max-width:950px){.hero{grid-template-columns:1fr}.photo-wrap{min-height:300px}.photo{max-height:60vh}}
</style></head><body><header><h1>Amsterdam façade grammar</h1><button id="prev">← Previous</button><button id="next" class="primary">Next façade →</button><button id="splits">Disagreements only</button><span class="progress" id="progress"></span></header><main><section class="hero"><div class="photo-wrap"><img id="photo" class="photo"></div><div class="review"><div class="meta" id="meta"></div><span class="flag" id="visible"></span><h2>Exact model consensus</h2><div class="consensus" id="consensus"></div><h2>Full comparison</h2><table><thead><tr id="head"><th>field</th></tr></thead><tbody id="rows"></tbody></table><div id="rationales"></div><p class="fine">Machine proposals only. Green values agree exactly; amber values need review. Crop and inference are joined by both building and panorama identity.</p></div></section></main><script>
const items=${embedded},models=${models},cost='${cost}',fields=['targetVisible','visibilityConfidence','visibleStoreys','bayCount','windowPattern','windowToWall','windowRecess','groundFloorType','entranceType','balconyType','facadeComposition','roofline','ornament','facadeMaterial','facadeColour','groundFloorDistinct','windowFrameColour'];let index=0,splitsOnly=false;const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
head.innerHTML='<th>field</th>'+models.map(m=>'<th>'+esc(m.split('/').pop())+'</th>').join('');function render(){const x=items[index],r=x.result,labels=r.proposals.map(p=>p.label||{});photo.src=x.image;meta.innerHTML='<strong>'+esc(x.osmId)+'</strong> · '+esc(x.observedAt)+' · heading '+esc(x.heading)+'° · '+models.length+' models · pilot cost $'+cost;visible.textContent=labels.every(l=>l.targetVisible)?'target visible':'visibility disputed';consensus.innerHTML=Object.entries(r.consensus).filter(([k])=>k!=='targetVisible').map(([k,v])=>'<span class="chip">'+esc(k)+': <b>'+esc(v)+'</b></span>').join('')||'<span class="fine">No exact agreement</span>';rows.innerHTML=fields.flatMap(k=>{const values=labels.map(l=>l[k]),same=values.length>1&&values.every(v=>JSON.stringify(v)===JSON.stringify(values[0]));if(splitsOnly&&same)return[];return['<tr><th>'+esc(k)+'</th>'+values.map(v=>'<td class="'+(same?'same':'split')+'">'+esc(v)+'</td>').join('')+'</tr>']}).join('');rationales.innerHTML=r.proposals.map(p=>'<div class="rationale"><b>'+esc(p.model.split('/').pop())+'</b>: '+esc(p.error||p.label?.rationale)+'</div>').join('');progress.textContent=(index+1)+' / '+items.length+' · '+Object.keys(r.consensus).length+' agreed fields'}prev.onclick=()=>{index=(index-1+items.length)%items.length;render()};next.onclick=()=>{index=(index+1)%items.length;render()};splits.onclick=()=>{splitsOnly=!splitsOnly;splits.textContent=splitsOnly?'Show every field':'Disagreements only';render()};render();
</script></body></html>`;
await writeFile(path.join(root, 'index.html'), html);
process.stdout.write(`Built façade grammar review for ${joined.length}/${manifest.items.length} crops.\n`);
