/** Generate a local human-review UI with orthophoto tiles and BAG overlays. */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
type Point = [number, number]; type Geometry = { type: 'Polygon'; coordinates: Point[][] } | { type: 'MultiPolygon'; coordinates: Point[][][] };
type Building = { properties: Record<string, unknown>; geometry: Geometry };
type Observation = { buildingId: string; measuredColour: string; quantizedColour: string; confidence: number; selectionArea?: string; diagnostics: { tileKeys: string[]; channelIqr: number; acceptedPixels: number } };
const root = path.resolve('.cache/roof-enrichment'), outputDirectory = path.join(root, 'review'); await mkdir(outputDirectory, { recursive: true });
const bag = JSON.parse(await readFile(path.join(root, 'a10-bag-buildings.geojson'), 'utf8')) as { features: Building[] };
const results = JSON.parse(await readFile(path.join(root, 'roof-color-observations.json'), 'utf8')) as { observations: Observation[] };
const buildings = new Map(bag.features.map(x => [String(x.properties.buildingId), x]));
const R = 6378137, TILE_METRES = 128, TILE_PIXELS = 1024, m = ([lon, lat]: Point): Point => [(lon * Math.PI / 180) * R, Math.log(Math.tan(Math.PI / 4 + lat * Math.PI / 360)) * R];
const polygons = (g: Geometry): Point[][][] => g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
const items = results.observations.sort((a, b) => a.confidence - b.confidence).map(observation => {
  const building = buildings.get(observation.buildingId); if (!building) return null;
  const projected = polygons(building.geometry).map(p => p.map(r => r.map(m)));
  const tiles = observation.diagnostics.tileKeys.map(key => { const [tx, ty] = key.split(',').map(Number), ox = tx * TILE_METRES, oy = ty * TILE_METRES; const local = projected.map(polygon => polygon.map(ring => ring.map(([x, y]) => [((x - ox) / TILE_METRES * TILE_PIXELS), (TILE_PIXELS - (y - oy) / TILE_METRES * TILE_PIXELS)] as Point))); const paths = local.map(polygon => polygon.map(ring => ring.map(([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`).join(' '))); const points = local.flat(2), minX = Math.max(0, Math.min(...points.map(p => p[0]))), maxX = Math.min(1024, Math.max(...points.map(p => p[0]))), minY = Math.max(0, Math.min(...points.map(p => p[1]))), maxY = Math.min(1024, Math.max(...points.map(p => p[1]))), coverage = Math.max(0, maxX - minX) * Math.max(0, maxY - minY), size = Math.min(1024, Math.max(180, maxX - minX, maxY - minY) * 1.6), cx = Math.max(size / 2, Math.min(1024 - size / 2, (minX + maxX) / 2)), cy = Math.max(size / 2, Math.min(1024 - size / 2, (minY + maxY) / 2)); return { key, image: `../pdok-ortho-tiles/${tx}_${ty}.jpg`, paths, coverage, viewBox: `${cx - size / 2} ${cy - size / 2} ${size} ${size}` }; }).sort((a, b) => b.coverage - a.coverage);
  return { ...observation, buildYear: building.properties.bouwjaar, tiles };
}).filter(Boolean);
const embedded = JSON.stringify(items).replaceAll('<', '\\u003c');
const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Roof colour review</title><style>
:root{font:15px system-ui;color:#18212a;background:#e9e7e1}*{box-sizing:border-box}body{margin:0}header{position:sticky;top:0;z-index:5;display:flex;gap:9px;align-items:center;padding:12px 18px;background:#172a36;color:white}button,input{font:inherit}.progress{margin-left:auto}.card{max-width:1100px;margin:20px auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px #0002}.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));background:#222}.tile{position:relative;aspect-ratio:1;overflow:hidden}.tile img,.tile svg{position:absolute;width:100%;height:100%}.tile svg{pointer-events:none}.hide-overlay .tile svg{display:none}.meta,.controls{padding:14px 18px}.controls{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.swatch{width:42px;height:42px;border-radius:7px;border:2px solid #222}.proposal{padding:8px 12px;background:#eef3f5;border-radius:8px}button{border:0;border-radius:7px;padding:9px 12px;cursor:pointer}.primary{background:#147da5;color:white}.muted{background:#e4e7e9}</style></head><body><header><strong>Inside-A10 roof review</strong><button id="prev" class="muted">← Previous</button><button id="next" class="primary">Save & next →</button><button id="overlay" class="muted">Hide outline</button><button id="import" class="muted">Import</button><button id="export" class="muted">Export</button><input id="file" type="file" hidden><span id="progress" class="progress"></span></header><main id="app"></main><script>
const items=${embedded},key='mapRecall.roofReview.v1';let labels=JSON.parse(localStorage.getItem(key)||'{}'),requested=new URLSearchParams(location.search).get('building'),index=Math.max(0,items.findIndex(x=>x.buildingId===requested));const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){const x=items[index];if(!x)return;labels[x.buildingId]={buildingId:x.buildingId,roofColour:q('#colour').value,accepted:q('#accept').checked,notes:q('#notes').value,source:'human-roof-review',reviewedAt:new Date().toISOString()};localStorage.setItem(key,JSON.stringify(labels))}
function render(){const x=items[index];q('#progress').textContent=(index+1)+' / '+items.length+' · '+Object.keys(labels).length+' reviewed';const old=labels[x.buildingId]||{};q('#app').innerHTML='<article class="card"><div class="tiles">'+x.tiles.map(t=>'<div class="tile"><img src="'+t.image+'"><svg viewBox="0 0 1024 1024">'+t.paths.flatMap(p=>p.map(points=>'<polygon points="'+points+'" fill="none" stroke="#ff2aa3" stroke-width="5" vector-effect="non-scaling-stroke"/>')).join('')+'</svg></div>').join('')+'</div><div class="meta"><b>'+x.buildingId+'</b> · built '+x.buildYear+' · confidence '+Math.round(x.confidence*100)+'% · IQR '+x.diagnostics.channelIqr+'</div><div class="controls"><span class="swatch" style="background:'+x.measuredColour+'"></span><span class="proposal">Measured '+x.measuredColour+' → quantized '+x.quantizedColour+'</span><label>Chosen colour <input id="colour" type="color" value="'+esc(old.roofColour||x.quantizedColour)+'"></label><label><input id="accept" type="checkbox" '+(old.accepted!==false?'checked':'')+'> Accept</label><label>Notes <input id="notes" value="'+esc(old.notes||'')+'"></label></div></article>'}
q('#next').onclick=()=>{save();index=Math.min(items.length-1,index+1);render()};q('#prev').onclick=()=>{save();index=Math.max(0,index-1);render()};q('#overlay').onclick=()=>{document.body.classList.toggle('hide-overlay');q('#overlay').textContent=document.body.classList.contains('hide-overlay')?'Show outline':'Hide outline'};q('#export').onclick=()=>{save();const a=document.createElement('a'),blob=new Blob([JSON.stringify({schemaVersion:1,labels:Object.values(labels)},null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download='roof-colour-human-labels.json';a.click()};q('#import').onclick=()=>q('#file').click();q('#file').onchange=async e=>{const data=JSON.parse(await e.target.files[0].text());for(const x of data.labels||[])labels[x.buildingId]=x;localStorage.setItem(key,JSON.stringify(labels));render()};render();
</script></body></html>`;
await writeFile(path.join(outputDirectory, 'index.html'), html);
const overview = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Roof extraction overview</title><style>
:root{font:14px system-ui;color:#17212a;background:#e8e6df}*{box-sizing:border-box}body{margin:0}header{position:sticky;top:0;z-index:3;display:flex;gap:12px;align-items:center;padding:12px 18px;background:#172a36;color:white}select,input{font:inherit}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:12px;padding:12px}.card{display:block;color:inherit;text-decoration:none;background:white;border-radius:9px;overflow:hidden;box-shadow:0 2px 10px #0002}.image{position:relative;aspect-ratio:1;overflow:hidden;background:#222}.image img,.image svg{position:absolute;width:100%;height:100%}.meta{padding:9px}.row{display:flex;justify-content:space-between;gap:8px}.swatches{display:flex;gap:4px}.swatch{width:26px;height:20px;border:1px solid #222;border-radius:4px}.area{color:#61717b}.low{color:#a32626}.high{color:#187047}</style></head><body><header><strong>Inside-A10 roof overview</strong><label>Area <select id="area"></select></label><label>Confidence <select id="confidence"><option value="all">All</option><option value="low">Below 40%</option><option value="medium">40–70%</option><option value="high">Above 70%</option></select></label><label><input id="unreviewed" type="checkbox"> Unreviewed only</label><a href="index.html" style="color:white">Detailed editor →</a><span id="count" style="margin-left:auto"></span></header><main id="grid" class="grid"></main><script>
const items=${embedded},key='mapRecall.roofReview.v1';let labels=JSON.parse(localStorage.getItem(key)||'{}');const q=s=>document.querySelector(s),enc=encodeURIComponent,areas=['all',...new Set(items.map(x=>x.selectionArea||'centre'))];q('#area').innerHTML=areas.map(x=>'<option value="'+x+'">'+x.replaceAll('-',' ')+'</option>').join('');
function render(){const mode=q('#confidence').value,area=q('#area').value,only=q('#unreviewed').checked,shown=items.filter(x=>(area==='all'||(x.selectionArea||'centre')===area)&&(!only||!labels[x.buildingId])&&(mode==='all'||mode==='low'&&x.confidence<.4||mode==='medium'&&x.confidence>=.4&&x.confidence<=.7||mode==='high'&&x.confidence>.7));q('#count').textContent=shown.length+' / '+items.length;q('#grid').innerHTML=shown.map(x=>{const t=x.tiles[0];return '<a class="card" href="index.html?building='+enc(x.buildingId)+'"><div class="image"><svg viewBox="'+t.viewBox+'"><image href="'+t.image+'" width="1024" height="1024"/>'+t.paths.flatMap(p=>p.map(points=>'<polygon points="'+points+'" fill="none" stroke="#ff2aa3" stroke-width="6" vector-effect="non-scaling-stroke"/>')).join('')+'</svg></div><div class="meta"><div class="row"><b>'+x.buildingId.replace('bag:','')+'</b><b class="'+(x.confidence<.4?'low':'high')+'">'+Math.round(x.confidence*100)+'%</b></div><div class="row"><span>built '+x.buildYear+' · IQR '+x.diagnostics.channelIqr+'</span><span class="swatches"><i class="swatch" style="background:'+x.measuredColour+'"></i><i class="swatch" style="background:'+x.quantizedColour+'"></i></span></div><span class="area">'+(x.selectionArea||'centre').replaceAll('-',' ')+'</span></div></a>'}).join('')};q('#area').onchange=render;q('#confidence').onchange=render;q('#unreviewed').onchange=render;render();
</script></body></html>`;
await writeFile(path.join(outputDirectory, 'overview.html'), overview);
process.stdout.write(`Wrote ${items.length} low-confidence-first roof review items\n`);
