import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';import {makeLutherMuseum} from './landmarks/luther-museum-draft';import source from './landmarks/luther-museum-footprints.json';import spec from './landmarks/luther-museum-spec.json';
const{group,parts}=makeLutherMuseum(),box=new T.Box3().setFromObject(group);let triangles=0;for(const{g}of parts){const p=g.getAttribute('position');for(const v of p.array)assert(Number.isFinite(v));triangles+=(g.index?.count??p.count)/3;}assert(triangles<40000);assert(box.max.y<24&&box.max.y>20);assert(box.max.x-box.min.x<111&&box.max.z-box.min.z<67);assert.equal(spec.spatialSuppression,false);assert(spec.suppressOsmIds.includes('NL.IMBAG.Pand.'+source.bagId));for(const n of source.mustRetain)assert(!spec.suppressOsmIds.includes(n.id));
//Actual uncompressed roofs must face upward, remain planar, and meet their
//supporting wall at every vertex. Test real mesh positions, not nominal heights.
let roofTriangles=0,maxPlanarityResidual=0;for(const p of parts.filter(p=>p.mesh.userData.role==='roof')){const g=p.g,position=g.getAttribute('position'),index=g.index!,wall=parts.find(q=>q.mesh.userData.role==='survey-domain-wall'&&q.mesh.userData.roof===p.mesh.userData.roof)!.g.getAttribute('position');for(let k=0;k<position.count;k++){const v=new T.Vector3().fromBufferAttribute(position,k);let nearest=Infinity;for(let l=0;l<wall.count;l++)nearest=Math.min(nearest,v.distanceTo(new T.Vector3().fromBufferAttribute(wall,l)));assert(nearest<.0001,'roof boundary has actual wall support');}
 let largestArea=0,planeNormal=new T.Vector3(),planeOrigin=new T.Vector3();for(let i=0;i<index.count;i+=3){const a=new T.Vector3().fromBufferAttribute(position,index.getX(i)),b=new T.Vector3().fromBufferAttribute(position,index.getX(i+1)),c=new T.Vector3().fromBufferAttribute(position,index.getX(i+2)),normal=b.clone().sub(a).cross(c.clone().sub(a));if(normal.lengthSq()<1e-10)continue;assert(normal.y>0,'roof winding upward');roofTriangles++;if(normal.length()>largestArea){largestArea=normal.length();planeNormal.copy(normal).normalize();planeOrigin.copy(a);}}for(let k=0;k<position.count;k++)maxPlanarityResidual=Math.max(maxPlanarityResidual,Math.abs(new T.Vector3().fromBufferAttribute(position,k).sub(planeOrigin).dot(planeNormal)));}
assert(maxPlanarityResidual<.001,'stable centred plane avoids roof fins');
//Native courts are entirely clear, including several points away from the
//centroid. Boundary detail stays on walls, never spans the open courtyard.
const courtProbes:number[][]=[];for(const r of source.outline.slice(1)){const ring=r.slice(0,-1),cx=ring.reduce((s,p)=>s+p[0],0)/ring.length,cz=ring.reduce((s,p)=>s+p[1],0)/ring.length;for(const f of [0,.22])for(const v of ring){const x=cx+(v[0]-cx)*f,z=cz+(v[1]-cz)*f;courtProbes.push([x,z]);assert.equal(new T.Raycaster(new T.Vector3(x,30,z),new T.Vector3(0,-1,0),0,31).intersectObject(group,true).length,0,'courtyard open roof-to-ground');}}
const failures:any[]=[];let panes=0,probes=0;for(const p of parts.filter(p=>p.mesh.userData.role==='pane')){panes++;const m=p.mesh.userData,centre=p.g.boundingBox??(p.g.computeBoundingBox(),p.g.boundingBox!),c=centre.getCenter(new T.Vector3()),n=new T.Vector3(...m.normal as [number,number,number]),t=new T.Vector3(...m.tangent as [number,number,number]);for(const u of [.17,.37,.67,.87])for(const v of [.19,.39,.69,.89]){const q=c.clone().addScaledVector(t,(u-.5)*m.width).add(new T.Vector3(0,(v-.5)*m.height,0)),hits=new T.Raycaster(q.clone().addScaledVector(n,.70),n.clone().negate(),0,.85).intersectObject(group,true);probes++;if(hits[0]?.object!==p.mesh&&hits[0]?.object.userData.colour!=='white'&&hits[0]?.object.userData.colour!=='frame')failures.push({centre:c.toArray(),u,v,hit:hits[0]?.object.userData,distance:hits[0]?.distance});}}
const report={triangles,bounds:box,roofs:52,roofTriangles,maxPlanarityResidual,courts:2,courtProbes:courtProbes.length,panes,probes,failedPaneProbes:failures.length,failures};fs.mkdirSync('artifacts/luther-museum-draft',{recursive:true});fs.writeFileSync('artifacts/luther-museum-draft/geometry-check.json',JSON.stringify(report,null,2));console.log({...report,failures:failures.slice(0,5)});assert.equal(failures.length,0,'all sampled panes physically exposed; preserve failure evidence');
