import assert from 'node:assert/strict';import * as T from 'three';import fs from 'node:fs';import {buildUilenburgerSynagoge} from './landmarks/uilenburger-synagoge-builder';import source from './landmarks/uilenburger-synagoge-footprints.json';import spec from './landmarks/uilenburger-synagoge-spec.json';import type {BuildingTools} from './landmarks/cultural-builders';
const gs:T.BufferGeometry[]=[];const add:BuildingTools['add']=(g,c,x=0,y=0,z=0,a=0)=>{g.userData.palette=c;g.rotateY(a);g.translate(x,y,z);gs.push(g)},box:BuildingTools['box']=(x,y,z,w,h,d,c,a=0)=>add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a),unused=()=>{throw Error('unused')};buildUilenburgerSynagoge(0,0,{add,box,prism:unused,hip:unused,gableRoof:unused,window:unused,clock:unused,sign:unused});
const mat=new T.MeshBasicMaterial({side:T.FrontSide}),meshes=gs.map(g=>new T.Mesh(g,mat)),bounds=new T.Box3();let tris=0;for(const g of gs){for(const v of g.getAttribute('position').array)assert(Number.isFinite(v));g.computeBoundingBox();bounds.union(g.boundingBox!);tris+=(g.index?.count??g.getAttribute('position').count)/3}
assert(tris<40000);assert(bounds.min.y>=-.001);assert(bounds.max.y>15&&bounds.max.y<17.1);
const a=source.authorAngleRadians,at=(x:number,y:number,z:number)=>new T.Vector3(x*Math.cos(a)+z*Math.sin(a),y,-x*Math.sin(a)+z*Math.cos(a));
const hit=(x:number,y:number,z:number,dx:number,dy:number,dz:number)=>new T.Raycaster(at(x,y,z),at(dx,dy,dz)).intersectObjects<T.Mesh>(meshes)[0];

const plinthProbes:Array<[number,number,number,number,number,number]>=[];
for(const x of[-5.42,-4,-3,3,4,5.42])for(const y of[.15,.3,.55])plinthProbes.push([x,y,-20,0,0,1]);
for(const side of[-1,1]){const p=source.ring[side<0?0:7],q=source.ring[side<0?1:6],dx=q[0]-p[0],dz=q[1]-p[1],len=Math.hypot(dx,dz);for(const t of[.1,.3,.5,.7,.9])for(const y of[.15,.3,.55])plinthProbes.push([p[0]+dx*t+side*dz/len*5,y,p[1]+dz*t-side*dx/len*5,-side*dz/len,0,side*dx/len]);}
const checkPlinth=(targets:T.Mesh[],palette:(m:T.Mesh)=>string|undefined,label:string)=>{
 for(const probe of plinthProbes){const[x,y,z,dx,dy,dz]=probe,hits=new T.Raycaster(at(x,y,z),at(dx,dy,dz).normalize()).intersectObjects<T.Mesh>(targets),first=hits[0];assert.equal(first&&palette(first.object),'greyBrick',`${label}: lower wall first-hit owns gray plinth at ${probe}`);assert(!hits.some(h=>palette(h.object)==='brick'&&Math.abs(h.distance-first.distance)<1e-4),`${label}: no brick coincident with exposed gray face at ${probe}`);}
 for(const x of[-4,-3,3,4]){const first=new T.Raycaster(at(x,.85,-20),at(0,0,1)).intersectObjects<T.Mesh>(targets)[0];assert.equal(first&&palette(first.object),'brick',`${label}: brick begins above gray plinth datum`);}
};
checkPlinth(meshes,m=>m.geometry.userData.palette,'authored');

const failures:any[]=[];for(const x of [-3.62,0,3.62])for(const offset of [-.77,-.37,.07,.37,.77])for(const y of x===0?[7.21,8.31,9.41]:[5.91,7.01,8.11]){const h=hit(-.141-x+offset,y,-20,0,0,1);if(h?.object.geometry.userData.palette!=='glass')failures.push({face:'front',x,offset,y,palette:h?.object.geometry.userData.palette})}
for(const side of [-1,1]){const p=source.ring[side<0?0:7],q=source.ring[side<0?1:6],dx=q[0]-p[0],dz=q[1]-p[1],len=Math.hypot(dx,dz);for(const t of [.12,.31,.5,.69,.88])for(const off of [-.69,-.35,.07,.35,.69])for(const y of [6.51,7.61,8.71]){const x=p[0]+dx*t+dx/len*off,z=p[1]+dz*t+dz/len*off,h=hit(x+side*dz/len*5,y,z-side*dx/len*5,-side*dz/len,0,side*dx/len);if(h?.object.geometry.userData.palette!=='glass')failures.push({face:'side',side,t,off,y,palette:h?.object.geometry.userData.palette})}}
for(const x of [-.69,-.35,.07,.35,.69]){const h=hit(.23+x,9.89,20,0,0,-1);if(h?.object.geometry.userData.palette!=='glass')failures.push({face:'rearCentre',x,palette:h?.object.geometry.userData.palette})}
for(const x of [-.35,.07,.35])for(const y of [10.96,11.23,11.50]){const h=hit(-.141+x,y,-20,0,0,1);if(h?.object.geometry.userData.palette!=='glass'&&h?.object.geometry.userData.palette!=='white')failures.push({face:'frontArchTop',x,y,palette:h?.object.geometry.userData.palette})}
const roofs=gs.filter(g=>g.userData.role==='roof');assert.equal(roofs.length,4);for(const g of roofs){assert(g.userData.residual<.01);const p=g.getAttribute('position'),ix=g.index;for(let i=0;i<(ix?.count??p.count);i+=3){const q=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,ix?ix.getX(i+j):i+j));assert(q[1].sub(q[0]).cross(q[2].sub(q[0])).y>0,'roof winding upward')}}
for(const[x,y,z]of source.openSpaceProbes)assert(!hit(x,y,z,0,-1,0),'forecourt and side gaps remain open');assert.equal(spec.spatialSuppression,false);assert.deepEqual(spec.suppressOsmIds,['w268782551','NL.IMBAG.Pand.0363100012181889']);assert(source.retainedNeighbors.length>=5);
fs.mkdirSync('artifacts/uilenburger-synagoge-draft',{recursive:true});fs.writeFileSync('artifacts/uilenburger-synagoge-draft/geometry-check.json',JSON.stringify({tris,bounds,failures,upwardRoofPlanes:roofs.length},null,2));assert.equal(failures.length,0,`fractional pane visibility failures: ${JSON.stringify(failures.slice(0,8))}`);console.log(JSON.stringify({triangles:tris,bounds,upwardRoofPlanes:4,firstHitGlazing:true,openForecourt:true,grayPlinthOwnership:true,plinthProbes:plinthProbes.length}));
// Inspect decoded export too: quantization must not introduce downward roof slivers.
const draft=process.argv[2]??'artifacts/uilenburger-synagoge-draft/uilenburger-synagoge.glb';if(fs.existsSync(draft)){
 const {NodeIO}=await import('@gltf-transform/core'),{ALL_EXTENSIONS}=await import('@gltf-transform/extensions'),{MeshoptDecoder}=await import('meshoptimizer');await MeshoptDecoder.ready;
 const doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(draft);assert.equal(doc.getRoot().listTextures().length,0);assert(fs.statSync(draft).size<500000);let decodedTriangles=0,roofTriangles=0;for(const mesh of doc.getRoot().listMeshes())for(const prim of mesh.listPrimitives()){
  const p=prim.getAttribute('POSITION')!,ix=prim.getIndices(),count=ix?.getCount()??p.getCount();decodedTriangles+=count/3;if(prim.getMaterial()?.getName()!=='slate')continue;
  for(let i=0;i<count;i+=3){const q=[0,1,2].map(j=>new T.Vector3(...p.getElement(ix?ix.getScalar(i+j):i+j,[])));const cross=q[1].sub(q[0]).cross(q[2].sub(q[0]));assert(cross.y>0,'decoded roof faces point up');roofTriangles++}
 }const decoded:T.Mesh[]=[];for(const node of doc.getRoot().listNodes())for(const prim of node.getMesh()?.listPrimitives()??[]){const p=prim.getAttribute('POSITION')!,ix=prim.getIndices(),matrix=new T.Matrix4().fromArray(node.getWorldMatrix()),values:number[]=[];for(let i=0;i<p.getCount();i++)values.push(...new T.Vector3(...p.getElement(i,[])).applyMatrix4(matrix).toArray());const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(values,3));if(ix)g.setIndex(Array.from(ix.getArray()!));const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));m.name=prim.getMaterial()?.getName()??'';m.updateMatrixWorld();decoded.push(m);}checkPlinth(decoded,m=>m.name,'decoded');assert(decodedTriangles<40000);console.log(JSON.stringify({decodedTriangles,roofTriangles,exportBytes:fs.statSync(draft).size,textures:0,grayPlinthOwnership:true,plinthProbes:plinthProbes.length}));
}
