import * as T from 'three';import assert from 'node:assert/strict';import {buildNieuwendammerkerk} from './landmarks/nieuwendammerkerk-builder';import type {BuildingTools} from './landmarks/cultural-builders';import source from './landmarks/nieuwendammerkerk-footprints.json';import spec from './landmarks/nieuwendammerkerk-spec.json';
const group=new T.Group();let triangles=0;const b={add(g:T.BufferGeometry,c:string){const mesh=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.name=c;group.add(mesh);triangles+=(g.index?.count??g.getAttribute('position').count)/3;}} as unknown as BuildingTools;buildNieuwendammerkerk(1,1,b);group.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(group);assert(bounds.min.toArray().concat(bounds.max.toArray()).every(Number.isFinite));assert(bounds.max.y>26.6&&bounds.max.y<28);assert(bounds.max.x-bounds.min.x<27);assert(bounds.max.z-bounds.min.z<16);assert(triangles<40000);
const turn=new T.Matrix4().makeRotationY(source.localRotationDegrees*Math.PI/180),p=(x:number,y:number,z:number)=>new T.Vector3(x,y,z).applyMatrix4(turn);
const ray=(x:number,y:number,z:number,dx:number,dz:number)=>new T.Raycaster(p(x,y,z),new T.Vector3(dx,0,dz).transformDirection(turn)).intersectObjects(group.children)[0];
// Fractional pane samples test actual glass surfaces, excluding intentionally drawn iron mullions.
let samples=0;for(const child of group.children){const mesh=child as T.Mesh,face=mesh.geometry.userData.pane;if(!face)continue;const {x,y,z,w,h,a}=face,n=[Math.sin(a),Math.cos(a)],t=[Math.cos(a),-Math.sin(a)];for(const f of [-.32,.31])for(const v of (h-w/2<.2?[.40,.55]:[.22,.56])){const px=x+t[0]*w*f,pz=z+t[1]*w*f;const hit=ray(px+n[0]*2,y+v*(h-w/2<.2?h:h-w/2),pz+n[1]*2,-n[0],-n[1]);assert.equal(hit?.object.name,'glass',`Pane masonry occlusion: ${JSON.stringify({face,f,v,hit:hit?.object.name})}`);samples++;}}
assert.equal(ray(-7,1.2,.3,1,0)?.object.name,'green','Public west door must be exposed');
for(const probe of source.openSpaceProbes)assert(!new T.Raycaster(p(probe.local[0],40,probe.local[1]),new T.Vector3(0,-1,0)).intersectObjects(group.children)[0],probe.name+' remains open');
for(const child of group.children){const g=(child as T.Mesh).geometry;if(g.userData.role!=='roof')continue;const n=g.getAttribute('normal');for(let i=0;i<n.count;i++)assert(n.getY(i)>.001,'Roof faces must be upward');}
for(const z of [-4,4]){const hit=new T.Raycaster(p(12,35,z),new T.Vector3(0,-1,0)).intersectObjects(group.children)[0];assert.equal(hit?.object.name,'red');assert(hit!.point.y>9&&hit!.point.y<10,'Actual supported nave slope at local z=4');}
for(const n of source.preserveNeighbors)assert(!spec.suppressOsmIds.includes(n.osmId)&&!spec.suppressOsmIds.includes('NL.IMBAG.Pand.'+n.bagId));assert.deepEqual(spec.suppressOsmIds,['w280804509','NL.IMBAG.Pand.0363100012144206']);
console.log(JSON.stringify({model:'nieuwendammerkerk',triangles,paneSamples:samples,bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},checks:['fractional first-hit glazing','west public door','supported upward nave roofs','cemetery and Kosterij gaps','native bounds and exact identities'],visualAcceptance:'pending root gallery/live-game/source comparison'}));
// Decode the exact isolated compressed export when present; source tests alone do not
// prove quantized panes or roof winding survive the production compression path.
const {existsSync,statSync}=await import('node:fs');const draft='artifacts/nieuwendammerkerk-draft/nieuwendammerkerk.glb';
if(existsSync(draft)){
 const {NodeIO}=await import('@gltf-transform/core'),{ALL_EXTENSIONS}=await import('@gltf-transform/extensions'),{MeshoptDecoder}=await import('meshoptimizer');await MeshoptDecoder.ready;
 const doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(draft);assert.equal(doc.getRoot().listTextures().length,0);assert(statSync(draft).size<500000);
 const decoded=new T.Group();let decodedTriangles=0,tiny=0;
 for(const node of doc.getRoot().listNodes()){const mesh=node.getMesh();if(!mesh)continue;const matrix=new T.Matrix4().fromArray(node.getWorldMatrix());for(const primitive of mesh.listPrimitives()){const pos=primitive.getAttribute('POSITION')!,ix=primitive.getIndices(),values:number[]=[];for(let i=0;i<(ix?.getCount()??pos.getCount());i++)values.push(...new T.Vector3().fromArray(pos.getElement(ix?ix.getScalar(i):i,[0,0,0])).applyMatrix4(matrix).toArray());const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(values,3));geometry.computeVertexNormals();const m=new T.Mesh(geometry,new T.MeshBasicMaterial({side:T.DoubleSide}));m.name=primitive.getMaterial()!.getName();decoded.add(m);decodedTriangles+=values.length/9;
 if(m.name==='slate')for(let i=0;i<values.length;i+=9){const a=new T.Vector3(...values.slice(i,i+3) as [number,number,number]),v=new T.Vector3(...values.slice(i+3,i+6) as [number,number,number]).sub(a),w=new T.Vector3(...values.slice(i+6,i+9) as [number,number,number]).sub(a),n=v.cross(w);if(n.length()<1e-6){tiny++;continue;}assert(n.y>0,'Compressed slate roof winding remains upward');}}
 }
 decoded.updateMatrixWorld(true);assert(decodedTriangles<40000);
 for(const child of group.children){const f=(child as T.Mesh).geometry.userData.pane;if(!f)continue;const {x,y,z,w,h,a}=f,n=[Math.sin(a),Math.cos(a)],t=[Math.cos(a),-Math.sin(a)];for(const u of [-.32,.31]){const v=h-w/2<.2?.4*h:.22*(h-w/2),origin=p(x+t[0]*w*u+n[0]*2,y+v,z+t[1]*w*u+n[1]*2),direction=new T.Vector3(-n[0],0,-n[1]).transformDirection(turn);assert.equal(new T.Raycaster(origin,direction).intersectObjects(decoded.children)[0]?.object.name,'glass','Decoded pane remains exposed');}}
 console.log(JSON.stringify({draft,bytes:statSync(draft).size,decodedTriangles,tinyRoofTriangles:tiny,textures:0,decodedPaneChecks:34,compressedRoofWinding:'pass'}));
}
