import fs from 'node:fs';import assert from 'node:assert/strict';import * as T from 'three';
import {Document,NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {weld,dedup,prune,meshopt} from '@gltf-transform/functions';import {MeshoptEncoder,MeshoptDecoder} from 'meshoptimizer';
import {buildElTawheed,elTawheedFront,elTawheedOpenings} from './landmarks/el-tawheed-builder';import source from './landmarks/el-tawheed-footprints.json';import type {BuildingTools} from './landmarks/cultural-builders';
await MeshoptEncoder.ready;await MeshoptDecoder.ready;
const group=new T.Group(),parts:{g:T.BufferGeometry,c:string}[]=[];
function add(g:T.BufferGeometry,c:string,x=0,y=0,z=0,angle=0){g.rotateY(angle);g.translate(x,y,z);parts.push({g,c});const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));m.name=c;group.add(m);}
const b={add,box:(x:number,y:number,z:number,w:number,h:number,d:number,c:string,a=0)=>add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a)} as BuildingTools;buildElTawheed(1,1,b);group.updateMatrixWorld(true);
const bounds=new T.Box3().setFromObject(group);assert(bounds.min.y>=-.001);assert(bounds.max.y<13);let roofFaces=0;
for(const p of parts){const a=p.g.attributes.position;assert(Array.from(a.array).every(Number.isFinite));if(p.g.userData.explicitRoof){const g=p.g.index?p.g.toNonIndexed():p.g,pos=g.attributes.position;for(let i=0;i<pos.count;i+=3){const a=new T.Vector3().fromBufferAttribute(pos,i),b=new T.Vector3().fromBufferAttribute(pos,i+1),c=new T.Vector3().fromBufferAttribute(pos,i+2),n=b.sub(a).cross(c.sub(a));assert(n.y>0,'roof winding');roofFaces++;}}}
const {a,u,n}=elTawheedFront,ray=new T.Raycaster();let checked=0,failed:any[]=[];
for(const o of elTawheedOpenings.filter(o=>o.tier!=='door'))for(const x of [-.35,-.10,.10,.35])for(const f of [.15,.42,.64,.90]){const t=o.u+x*o.w,y=o.y+f*o.h,origin=new T.Vector3(a[0]+u[0]*t+n[0]*2,y,a[1]+u[1]*t+n[1]*2);ray.set(origin,new T.Vector3(-n[0],0,-n[1]));const first=ray.intersectObject(group,true)[0];if(!(o.tier==='basement'?['dark','frame'].includes(first?.object.name??''):first?.object.name==='glass'))failed.push({o,x,f,first:first?.object.name});checked++;}
assert.equal(failed.length,0,JSON.stringify(failed.slice(0,4)));
// Concave excluded northern shoulder is open rather than covered by a parcel-size plate.
const point=new T.Vector3(-24,20,-4);ray.set(point,new T.Vector3(0,-1,0));assert.equal(ray.intersectObject(group,true).length,0,'outside shoulder filled');
const palette:any={brick:'#786150',stone:'#bcb6a7',slate:'#494b4c',white:'#f4f4ef',dark:'#303b43',frame:'#9daaa8',glass:'#527787',concrete:'#adada5'};
const doc=new Document(),buffer=doc.createBuffer(),scene=doc.createScene('el-tawheed'),mesh=doc.createMesh();doc.getRoot().setDefaultScene(scene);
for(const c of [...new Set(parts.map(p=>p.c))]){const ps=parts.filter(p=>p.c===c).map(p=>p.g.index?p.g.toNonIndexed():p.g),material=doc.createMaterial(c);const rgb=new T.Color(palette[c]);material.setBaseColorFactor([rgb.r,rgb.g,rgb.b,1]).setRoughnessFactor(.9).setDoubleSided(true);const p=Float32Array.from(ps.flatMap(g=>Array.from(g.attributes.position.array))),n=Float32Array.from(ps.flatMap(g=>Array.from(g.attributes.normal.array)));mesh.addPrimitive(doc.createPrimitive().setMaterial(material).setAttribute('POSITION',doc.createAccessor().setType('VEC3').setArray(p).setBuffer(buffer)).setAttribute('NORMAL',doc.createAccessor().setType('VEC3').setArray(n).setBuffer(buffer)));}
scene.addChild(doc.createNode('el-tawheed').setMesh(mesh));await doc.transform(weld(),dedup(),prune(),meshopt({encoder:MeshoptEncoder,level:'medium'}));const decodedPath=process.argv[2]??'artifacts/landmark-next-batch/el-tawheed.glb';if(!process.argv[2]){fs.mkdirSync('artifacts/landmark-next-batch',{recursive:true});await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder}).write(decodedPath,doc);}
const decoded=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(decodedPath);let decodedUp=0;const decodedGroup=new T.Group();for(const node of decoded.getRoot().listNodes()){const matrix=new T.Matrix4().fromArray(node.getWorldMatrix());for(const prim of node.getMesh()?.listPrimitives()??[]){const pa=prim.getAttribute('POSITION')!,positions:number[]=[];for(let k=0;k<pa.getCount();k++)positions.push(...new T.Vector3(...pa.getElement(k,[])).applyMatrix4(matrix).toArray());const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute(positions,3));if(prim.getIndices())geom.setIndex(Array.from(prim.getIndices()!.getArray()!));geom.computeVertexNormals();const m=new T.Mesh(geom,new T.MeshBasicMaterial({side:T.DoubleSide}));m.name=prim.getMaterial()?.getName()??'';decodedGroup.add(m);if(prim.getMaterial()?.getName()!=='slate')continue;const pos=prim.getAttribute('POSITION')!,ix=prim.getIndices();for(let i=0;i<(ix?.getCount()??pos.getCount());i+=3){const ps=[0,1,2].map(k=>new T.Vector3(...pos.getElement(ix?ix.getScalar(i+k):i+k,[])).applyMatrix4(matrix));const n=ps[1].sub(ps[0]).cross(ps[2].sub(ps[0]));if(n.lengthSq()>1e-10){if(n.y<=0)console.log('BAD_DECODED_ROOF',n.toArray(),n.length()/2,ps.map(p=>p.toArray()));assert(n.y>0,'decoded roof reversed');decodedUp++;}}}}assert(decodedUp>0);decodedGroup.updateMatrixWorld(true);let decodedPaneRays=0;for(const o of elTawheedOpenings.filter(o=>o.tier!=='door'))for(const x of [-.35,-.10,.10,.35])for(const f of [.15,.42,.64,.90]){const t=o.u+x*o.w,y=o.y+f*o.h;ray.set(new T.Vector3(a[0]+u[0]*t+n[0]*2,y,a[1]+u[1]*t+n[1]*2),new T.Vector3(-n[0],0,-n[1]));const first=ray.intersectObject(decodedGroup,true)[0];assert(o.tier==='basement'?['dark','frame'].includes(first?.object.name??''):first?.object.name==='glass',`decoded ${o.tier} pane occlusion: ${first?.object.name}`);decodedPaneRays++;}
let upperPierRays=0,maxUpperPierProjection=-Infinity;for(let i=1;i<6;i++)for(const y of [8.4,9.3,10.5]){const t=.05+i*(elTawheedFront.length-.1)/6;ray.set(new T.Vector3(a[0]+u[0]*t+n[0]*2,y,a[1]+u[1]*t+n[1]*2),new T.Vector3(-n[0],0,-n[1]));const first=ray.intersectObject(decodedGroup,true)[0];assert.equal(first?.object.name,'brick');const offset=(first.point.x-a[0])*n[0]+(first.point.z-a[1])*n[1];maxUpperPierProjection=Math.max(maxUpperPierProjection,offset);assert(offset<.045,`upper pier relief casts unsupported deep seam: ${offset}`);upperPierRays++;}
console.log(JSON.stringify({model:'el-tawheed',nativeBounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},roofFaces,decodedUp,decodedPaneRays,upperPierRays,maxUpperPierProjection,glazingRays:checked,failed,sourceScope:source.bagId,decodedPath,bytes:fs.statSync(decodedPath).size,gameAcceptance:'pending'}));
