/** Focused batching and bounded tile lifecycle contracts, without browser/server. */
import fs from 'node:fs';import assert from 'node:assert/strict';import * as THREE from 'three';
import {batchParts,stateKey,pickOwner} from '../src/canalRecall/buildingLibraryTileBatching';
import {BuildingLibraryTileStore,decodeBuildingLibraryTile} from '../src/canalRecall/buildingLibraryTileLoader';
const root='artifacts/district-tile-batching',manifest=JSON.parse(fs.readFileSync(root+'/tiles.json','utf8'));
const bytes=(url:string)=>{const b=fs.readFileSync(root+'/'+url);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);};
const triangle=new THREE.BufferGeometry();triangle.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,1,0,0,0,1,0],3));triangle.setAttribute('normal',new THREE.Float32BufferAttribute([0,0,1,0,0,1,0,0,1],3));
const material=new THREE.MeshStandardMaterial({side:THREE.FrontSide,color:'#ff0033',roughness:.86});const reflection=batchParts([{owner:{id:'mathematical-reflection-fixture'},mesh:new THREE.Mesh(triangle,material),matrix:new THREE.Matrix4().makeScale(-1,1,1)}]).batches[0];assert.deepEqual(Array.from(reflection.index as Uint16Array),[0,2,1]);
const p=Array.from(reflection.index as Uint16Array).map(i=>new THREE.Vector3(reflection.position[i*3],reflection.position[i*3+1],reflection.position[i*3+2]));assert.ok(p[1].clone().sub(p[0]).cross(p[2].clone().sub(p[0])).dot(new THREE.Vector3(0,0,1))>0);assert.ok(reflection.normal[2]===1);
const variant=material.clone();variant.color.set('#44ff22');assert.equal(stateKey(material),stateKey(variant));for(const change of [{roughness:.5},{metalness:.5},{side:THREE.DoubleSide}]){const other=material.clone();Object.assign(other,change);assert.notEqual(stateKey(material),stateKey(other));}variant.transparent=true;assert.throws(()=>stateKey(variant));
const parent=new THREE.Group();let fetches=0,active=0,maxActive=0;const store=new BuildingLibraryTileStore(manifest,{parent,maxTiles:2,maxConcurrent:1,fetchBinary:async(tile)=>{fetches++;active++;maxActive=Math.max(maxActive,active);await Promise.resolve();active--;return bytes(tile.binaryUrl);}});
const [a,b,c]=manifest.tiles;const first=await Promise.all([store.load(a.key),store.load(a.key)]);assert.equal(first[0],first[1]);assert.equal(fetches,1);assert.equal(parent.children.length,1);
let geometryDisposes=0,materialDisposes=0;for(const mesh of first[0]!.meshes){mesh.geometry.addEventListener('dispose',()=>geometryDisposes++);(mesh.material as THREE.Material).addEventListener('dispose',()=>materialDisposes++);}
const mapping=(resource:any)=>resource.meshes.flatMap((mesh:any)=>mesh.userData.ownerRanges.map((r:any)=>pickOwner(mesh,r.firstTriangle)));
const originalMapping=mapping(first[0]);await store.load(b.key);assert.equal(store.stats.residentTiles,2);await store.load(c.key);assert.equal(store.stats.residentTiles,2);assert.equal(first[0]!.disposed,true);assert.equal(first[0]!.group.parent,null);assert.equal(geometryDisposes,first[0]!.meshes.length);assert.equal(materialDisposes,first[0]!.meshes.length);
const reloaded=await store.load(a.key);assert.notEqual(reloaded,first[0]);assert.deepEqual(mapping(reloaded),originalMapping);assert.equal(new Set(store.stats.owners).size,store.stats.owners.length);assert.equal(parent.children.length,2);assert.equal(maxActive,1);
store.unload(a.key);assert.equal(reloaded!.disposed,true);store.dispose();assert.equal(parent.children.length,0);assert.equal(store.stats.residentTiles,0);await assert.rejects(store.load(a.key),/disposed/);
let release!:(data:ArrayBuffer)=>void;const cancellationStore=new BuildingLibraryTileStore(manifest,{parent,maxTiles:1,maxConcurrent:1,fetchBinary:()=>new Promise(resolve=>{release=resolve;})});
const pending=cancellationStore.load(a.key),queued=cancellationStore.load(b.key);assert.equal(cancellationStore.stats.activeRequests,1);assert.equal(cancellationStore.stats.queuedRequests,1);cancellationStore.unload(a.key);assert.equal(await pending,null);cancellationStore.unload(b.key);assert.equal(await queued,null);release(bytes(a.binaryUrl));await new Promise(resolve=>setTimeout(resolve,0));assert.equal(parent.children.length,0);assert.equal(cancellationStore.stats.pendingTiles,0);assert.equal(cancellationStore.stats.activeRequests,0);cancellationStore.dispose();
const atomicStore=new BuildingLibraryTileStore(manifest,{parent,maxTiles:1,fetchBinary:async(tile)=>tile.key===b.key?new ArrayBuffer(4):bytes(tile.binaryUrl)});const good=await atomicStore.load(a.key);await assert.rejects(atomicStore.load(b.key),/buffer range/);assert.equal(atomicStore.stats.residentTiles,1);assert.equal(good!.disposed,false);assert.equal(parent.children.length,1);atomicStore.dispose();assert.equal(parent.children.length,0);
const byteStore=new BuildingLibraryTileStore(manifest,{parent,maxTiles:10,maxResidentGeometryBytes:1000000,fetchBinary:async(tile)=>bytes(tile.binaryUrl)});const byteFirst=await byteStore.load(a.key);await byteStore.load(b.key);assert.equal(byteFirst!.disposed,true);assert.equal(byteStore.stats.residentTiles,1);assert.ok(byteStore.stats.residentGeometryBytes<=1000000);await assert.rejects(byteStore.load(c.key),/byte budget/);assert.equal(byteStore.stats.residentTiles,1);byteStore.dispose();
const owners=new Map(manifest.owners.map((o:any)=>[o.id,o]));const invalid=JSON.parse(JSON.stringify(a));invalid.batches[0].ownerRanges[0].sourceModelHash='wrong';assert.throws(()=>decodeBuildingLibraryTile(invalid,bytes(a.binaryUrl),owners as Map<string,any>),/owner triangle/);assert.throws(()=>decodeBuildingLibraryTile(a,new ArrayBuffer(4),owners as Map<string,any>),/buffer range/);
const missingOwner=JSON.parse(JSON.stringify(a));missingOwner.owners.push(manifest.tiles[1].owners[0]);assert.throws(()=>decodeBuildingLibraryTile(missingOwner,bytes(a.binaryUrl),owners as Map<string,any>),/missing from tile/);
const duplicate=JSON.parse(JSON.stringify(manifest));duplicate.tiles[1].owners.push(duplicate.tiles[0].owners[0]);assert.throws(()=>new BuildingLibraryTileStore(duplicate,{parent,maxTiles:1,fetchBinary:async()=>new ArrayBuffer(0)}),/ownership/);
const report={passed:true,negativeDeterminantRegression:true,materialCompatibility:true,pendingDuplicateCoalescing:true,maxResidentTiles:2,maxActiveRequests:maxActive,geometryDisposes,materialDisposes,ownerMappingPreserved:true,lateCancelledLoadDidNotAttach:true,queuedCancellation:true,invalidPayloadRejected:true,failedReplacementPreservesResident:true,residentByteBudgetEvictsAndRejectsOversizedTiles:true};fs.writeFileSync(root+'/lifecycle-checks.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
