import * as T from 'three';import assert from 'node:assert/strict';import{buildHannekesBoom}from './landmarks/hannekes-boom-builder';import source from './landmarks/hannekes-boom-footprints.json';import type{BuildingTools}from './landmarks/cultural-builders';
const group=new T.Group();const add:BuildingTools['add']=(g,c,x=0,y=0,z=0,a=0)=>{const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));m.name=c;m.position.set(x,y,z);m.rotation.y=a;group.add(m);};const box:BuildingTools['box']=(x,y,z,w,h,d,c,a=0)=>add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a);buildHannekesBoom(18,17,{add,box}as BuildingTools);group.updateMatrixWorld(true);
let tris=0;for(const m of group.children as T.Mesh[]){const p=m.geometry.getAttribute('position');for(let i=0;i<p.count;i++)assert(Number.isFinite(p.getX(i)+p.getY(i)+p.getZ(i)));tris+=(m.geometry.index?.count??p.count)/3;}const bounds=new T.Box3().setFromObject(group);assert(bounds.max.y<6.1&&bounds.max.y>5.6,'localized surveyed canopy height');assert(tris<40000);const ray=(p:T.Vector3,d:T.Vector3)=>new T.Raycaster(p,d,0,30).intersectObjects(group.children);
// Deck centre and lower northern service roof must be upward first hits.
for(const [x,z,min,max]of [[0,3,3.7,3.95],[5,-6.3,3,3.4]] as number[][]){const h=ray(new T.Vector3(x,9,z),new T.Vector3(0,-1,0));assert(h.length&&h[0].point.y>min&&h[0].point.y<max,`roof winding/height ${x},${z}`);}
// The old maximum-height extrusion would block open occupied deck above4m.
const deckHit=ray(new T.Vector3(0,4.5,2),new T.Vector3(1,0,0))[0];assert(!deckHit||deckHit.distance>2,'deck interior should stay open');
// No padded parcel/water slab, and adjoining city buildings remain outside model.
for(const [x,z]of [[-15,0],[0,18],[18,0],[0,-18]])assert.equal(ray(new T.Vector3(x,9,z),new T.Vector3(0,-1,0)).length,0,'water/path/retained-neighbor space blocked');
// Exterior glazing at fractional window locations; exclude modeled mullions.
const glazing=group.children.filter((m)=>m.name==='glass')as T.Mesh[];let probes=0;for(const m of glazing){const size=new T.Box3().setFromObject(m).getSize(new T.Vector3());if(size.y<1.3)continue;for(const fraction of [-.30,.30]){const p=new T.Vector3(fraction*(m.geometry.parameters as {width:number}).width,0,.045).applyMatrix4(m.matrixWorld),normal=new T.Vector3(0,0,1).transformDirection(m.matrixWorld);const h=ray(p.clone().addScaledVector(normal,.25),normal.clone().negate());assert(h[0]?.object.name==='glass','glazing hidden by parent wall/frame');probes++;}}assert(probes>=8);
console.log(JSON.stringify({triangles:tris,glazingFirstHitProbes:probes,bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},checks:['finite native geometry','localized canopy height','main/lower roof upward first hits','open occupied deck','open surrounding parcel and water','fractional exposed glazing first hits']}));

const canopy=source.roofPlanes.find(p=>p.sourceSurface===36)!.rings[0];for(const i of [0,2,4,6]){const p=canopy[i],centroid=new T.Vector2(canopy.reduce((v,p)=>v+p[0],0)/canopy.length,canopy.reduce((v,p)=>v+p[2],0)/canopy.length),support=new T.Vector2(p[0],p[2]).addScaledVector(centroid.sub(new T.Vector2(p[0],p[2])).normalize(),.02);const h=ray(new T.Vector3(support.x,3.77,support.y),new T.Vector3(0,-1,0));assert(h[0]&&h[0].point.y>3.5,'canopy post base has no deck support');}

// Independent review failures: exposed east main wall reaches owning deck,
// stair landing crosses the gap to that deck and access remains unblocked.
const anchor=source.anchorLatLon,factor=111320*Math.cos(anchor[0]*Math.PI/180),ring=source.mainCandidateFeature.geometry.coordinates[0].slice(0,-1).map(([lng,lat])=>new T.Vector2((lng-anchor[1])*factor,-(lat-anchor[0])*110540)),eastA=ring[0],eastQ=ring[1],eastD=eastQ.clone().sub(eastA),eastV=eastD.clone().normalize(),eastN=new T.Vector2(-eastV.y,eastV.x),exit=eastA.clone().lerp(eastQ,.25+5.4/eastD.length());
function checkEastAndLanding(cast:(p:T.Vector3,d:T.Vector3)=>T.Intersection[]){let facade=0,landing=0;for(const t of [.2,.5,.85])for(const y of [3.55,3.76]){const p=eastA.clone().lerp(eastQ,t),h=cast(new T.Vector3(p.x+eastN.x*.5,y,p.y+eastN.y*.5),new T.Vector3(-eastN.x,0,-eastN.y));assert(h[0]&&h[0].distance<.65,'east main wall misses deck; first hit is far wall');facade++;}for(const offset of [-.1,0,.2,.4,.7,.9,1.2,1.4,1.7]){const p=exit.clone().addScaledVector(eastN,offset),h=cast(new T.Vector3(p.x,4.2,p.y),new T.Vector3(0,-1,0));assert(h[0]&&h[0].point.y>3.7&&h[0].point.y<3.95,'stair-to-deck landing surface disconnected');landing++;}const h=cast(new T.Vector3(exit.x,4.3,exit.y),new T.Vector3(eastN.x,0,eastN.y));assert(!h[0]||h[0].distance>1.8,'parapet obstructs stair access opening');return{nearEastFacadeHits:facade,continuousLandingProbes:landing};}
console.log(JSON.stringify({authoredReviewCorrections:checkEastAndLanding(ray)}));

const solarMeshes=(group.children as T.Mesh[]).filter(m=>m.name==='blue'&&Math.abs((m.geometry.parameters as {width?:number}).width!-1.35)<.001);
function checkSolarRoofSupport(objects:T.Object3D[]){let count=0;for(const panel of solarMeshes){const p=panel.geometry.getAttribute('position');for(let i=0;i<p.count;i++){const v=new T.Vector3().fromBufferAttribute(p,i).applyMatrix4(panel.matrixWorld),h=new T.Raycaster(v.clone().add(new T.Vector3(0,.01,0)),new T.Vector3(0,-1,0),0,.15).intersectObjects(objects.filter(m=>m.name==='slate'))[0];assert(h&&h.object.name==='slate'&&v.y-h.point.y>=-.005,'solar bank corner has no owning corrugated awning');count++;}}return count;}
assert.equal(solarMeshes.length,3);console.log(JSON.stringify({solarCornerSupportProbes:checkSolarRoofSupport(group.children.filter(m=>!solarMeshes.includes(m as T.Mesh)))}));

// Dense perimeter probes derive expected owners from archived roof polygons;
// they allow a bounded surveyed setback but reject far-wall hits through seams.
function densePerimeter(cast:(p:T.Vector3,d:T.Vector3)=>T.Intersection[]){let count=0;const polygons=source.roofPlanes.filter(p=>[33,35].includes(p.sourceSurface)).map(p=>p.rings[0]);const inside=(p:T.Vector2,r:number[][])=>{let odd=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const a=r[i],q=r[j];if((a[2]>p.y)!==(q[2]>p.y)&&p.x<(q[0]-a[0])*(p.y-a[2])/(q[2]-a[2])+a[0])odd=!odd;}return odd;};for(let i=0;i<ring.length;i++){const a=ring[i],q=ring[(i+1)%ring.length],v=q.clone().sub(a).normalize(),n=new T.Vector2(-v.y,v.x);for(const t of [.05,.2,.5,.8,.95]){const p=a.clone().lerp(q,t);let sample:T.Vector2|undefined;for(const inset of [.1,.2,.3,.45,.6]){const s=p.clone().addScaledVector(n,-inset);if(polygons.some(r=>inside(s,r))){sample=s;break;}}if(!sample)continue;const roofHit=cast(new T.Vector3(sample.x,3.95,sample.y),new T.Vector3(0,-1,0));assert(roofHit[0]&&roofHit[0].point.y>2.85,`source-owned perimeter roof seam open edge${i} t${t}`);const y=roofHit[0].point.y-.08,hit=cast(new T.Vector3(p.x+n.x*.5,y,p.y+n.y*.5),new T.Vector3(-n.x,0,-n.y));const owner=polygons.find(r=>inside(sample!,r))!,origin=p.clone().addScaledVector(n,.5),direction=n.clone().negate();let borderDistance=Infinity;for(let j=0;j<owner.length;j++){const u=new T.Vector2(owner[j][0],owner[j][2]),w=new T.Vector2(owner[(j+1)%owner.length][0],owner[(j+1)%owner.length][2]).sub(u),delta=u.clone().sub(origin),cross=(a:T.Vector2,b:T.Vector2)=>a.x*b.y-a.y*b.x,denom=cross(direction,w);if(Math.abs(denom)<1e-8)continue;const distance=cross(delta,w)/denom,t=cross(delta,direction)/denom;if(distance>=0&&t>=0&&t<=1)borderDistance=Math.min(borderDistance,distance);}assert(Number.isFinite(borderDistance)&&hit[0]&&hit[0].distance<=Math.max(.65,borderDistance+.12),`source-owned wall/roof continuity edge${i} t${t} y${y} expected${borderDistance} first${hit[0]?.distance}`);for(const inset of [.12,.18]){const seam=p.clone().addScaledVector(n,-inset);if(!inside(seam,ring.map(p=>[p.x,0,p.y])))continue;const h=cast(new T.Vector3(seam.x,3.95,seam.y),new T.Vector3(0,-1,0));assert(h[0]&&h[0].point.y>2.85,`narrow installed/survey seam unroofed edge${i} t${t} inset${inset}`);}count++;}}assert(count>=50);return count;}
console.log(JSON.stringify({sourceOwnedPerimeterContinuityProbes:densePerimeter(ray)}));

// Optional exact compressed-export pass: decode accessors, retain single-sided
// ray tests so double-sided gallery materials cannot conceal winding defects.
if(process.argv[2]){
 const {NodeIO}=await import('@gltf-transform/core'),{ALL_EXTENSIONS}=await import('@gltf-transform/extensions'),{MeshoptDecoder}=await import('meshoptimizer');await MeshoptDecoder.ready;
 const doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(process.argv[2]),decoded=new T.Group();let decodedTris=0;
 for(const node of doc.getRoot().listNodes()){const mesh=node.getMesh();if(!mesh)continue;for(const primitive of mesh.listPrimitives()){const p=primitive.getAttribute('POSITION')!,n=primitive.getAttribute('NORMAL'),geometry=new T.BufferGeometry(),positions:number[]=[],normals:number[]=[];for(let i=0;i<p.getCount();i++){const a=p.getElement(i,[]);assert(a.every(Number.isFinite),'compressed coordinate nonfinite');positions.push(...a);if(n)normals.push(...n.getElement(i,[]));}geometry.setAttribute('position',new T.Float32BufferAttribute(positions,3));if(n)geometry.setAttribute('normal',new T.Float32BufferAttribute(normals,3));const indices=primitive.getIndices();if(indices)geometry.setIndex(Array.from(indices.getArray()!));geometry.applyMatrix4(new T.Matrix4().fromArray(node.getWorldMatrix()));const m=new T.Mesh(geometry,new T.MeshBasicMaterial({side:T.FrontSide}));m.name=primitive.getMaterial()?.getName()??'';decoded.add(m);decodedTris+=(indices?.getCount()??p.getCount())/3;}}
 decoded.updateMatrixWorld(true);const decodedRay=(p:T.Vector3,d:T.Vector3)=>new T.Raycaster(p,d,0,30).intersectObjects(decoded.children);
 for(const [x,z,min,max]of [[0,3,3.7,3.95],[5,-6.3,3,3.4]]as number[][]){const h=decodedRay(new T.Vector3(x,9,z),new T.Vector3(0,-1,0));assert(h[0]&&h[0].point.y>min&&h[0].point.y<max,'compressed upward roof/height');}
 let paneProbes=0;for(const m of glazing){const size=new T.Box3().setFromObject(m).getSize(new T.Vector3());if(size.y<1.3)continue;for(const fraction of [-.3,.3]){const p=new T.Vector3(fraction*(m.geometry.parameters as {width:number}).width,0,.045).applyMatrix4(m.matrixWorld),normal=new T.Vector3(0,0,1).transformDirection(m.matrixWorld),h=decodedRay(p.clone().addScaledVector(normal,.25),normal.clone().negate());assert(h[0]?.object.name==='glass','compressed fractional pane first hit is masonry/frame/missing');paneProbes++;}}
 for(const i of [0,2,4,6]){const p=canopy[i],center=new T.Vector2(canopy.reduce((v,p)=>v+p[0],0)/canopy.length,canopy.reduce((v,p)=>v+p[2],0)/canopy.length),s=new T.Vector2(p[0],p[2]).addScaledVector(center.sub(new T.Vector2(p[0],p[2])).normalize(),.02),h=decodedRay(new T.Vector3(s.x,3.77,s.y),new T.Vector3(0,-1,0));assert(h[0]&&h[0].point.y>3.5,'compressed canopy deck support missing');}
 for(const [x,z]of [[-15,0],[0,18],[18,0],[0,-18]])assert.equal(decodedRay(new T.Vector3(x,9,z),new T.Vector3(0,-1,0)).length,0,'compressed surrounding water/path blocked');
 const sourceOwnedPerimeterContinuityProbes=densePerimeter(decodedRay),reviewerCorrections=checkEastAndLanding(decodedRay),solarCornerSupportProbes=checkSolarRoofSupport(decoded.children.filter(m=>m.name!=='blue'));const fs=await import('node:fs'),crypto=await import('node:crypto');console.log(JSON.stringify({compressedFile:process.argv[2],sha256:crypto.createHash('sha256').update(fs.readFileSync(process.argv[2])).digest('hex'),triangles:decodedTris,fractionalPaneFirstHits:paneProbes,canopySupportedBases:4,reviewerCorrections,solarCornerSupportProbes,sourceOwnedPerimeterContinuityProbes,checks:['decoded finite coordinates','single-sided upward owning roofs','fractional pane first hits','supported canopy bases','open surrounding parcel']}));
}
