import * as T from 'three';import assert from 'node:assert/strict';import {buildStraatMuseum} from './landmarks/straat-museum-builder';import source from './landmarks/straat-museum-footprints.json';import type{BuildingTools}from './landmarks/cultural-builders';
const group=new T.Group();const add:BuildingTools['add']=(g,c,x=0,y=0,z=0,a=0)=>{const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));m.name=c;m.position.set(x,y,z);m.rotation.y=a;group.add(m);};const box:BuildingTools['box']=(x,y,z,w,h,d,c,a=0)=>add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a);buildStraatMuseum(118,57,{add,box}as BuildingTools);group.updateMatrixWorld(true);let triangles=0;for(const mesh of group.children as T.Mesh[]){const p=mesh.geometry.getAttribute('position');for(let i=0;i<p.count;i++)assert(Number.isFinite(p.getX(i)+p.getY(i)+p.getZ(i)));triangles+=(mesh.geometry.index?.count??p.count)/3;}assert(triangles<40000);const bounds=new T.Box3().setFromObject(group);assert(bounds.max.y>27.5&&bounds.max.y<28,'rooflight crest/whole-hall maximum conflated');assert(bounds.max.x-bounds.min.x<121&&bounds.max.z-bounds.min.z<131,'wrong shared-host scope');const ray=(p:T.Vector3,d:T.Vector3)=>new T.Raycaster(p,d,0,200).intersectObjects(group.children);
// Four distinct skylight crests, all eight real slopes visible from above rather than buried under cap.
let slopeProbes=0;for(const roof of source.roofPlanes){const vertices=roof.rings[0];if(roof.semantic.b3_hellingshoek<30)continue;const centre=vertices.reduce((p,q)=>p.add(new T.Vector3(...q as[number,number,number])),new T.Vector3()).multiplyScalar(1/vertices.length);centre.lerp(new T.Vector3(...vertices[0] as[number,number,number]),.073);const hit=ray(new T.Vector3(centre.x,40,centre.z),new T.Vector3(0,-1,0))[0];assert(hit&&hit.object.name==='glass','roof light hidden, unsupported projection or winding');assert(Math.abs(hit.point.y-centre.y)<.12,'source roof plane distortion');slopeProbes++;}assert.equal(slopeProbes,8);
const [lng0,lat0]=source.anchor,ring=source.bag.geometry.coordinates[0].slice(0,-1).map(([lng,lat])=>new T.Vector2((lng-lng0)*111320*Math.cos(lat0*Math.PI/180),-(lat-lat0)*110540));const sign=Math.sign(ring.reduce((v,p,i)=>{const q=ring[(i+1)%ring.length];return v+p.x*q.y-q.x*p.y;},0));const facadeProbe=(a:T.Vector2,q:T.Vector2,y:number,u:number)=>{const d=q.clone().sub(a),n=new T.Vector2(d.y,-d.x).normalize().multiplyScalar(sign),m=a.clone().lerp(q,u);const hit=ray(new T.Vector3(m.x+n.x*12,y,m.y+n.y*12),new T.Vector3(-n.x,0,-n.y))[0];assert(hit&&hit.object.name==='glass','native facade glass hidden inside parent');};facadeProbe(ring[18],ring[9],20,.62);facadeProbe(ring[10],ring[14],20,.37);facadeProbe(ring[2],ring[3],6,.37);facadeProbe(ring[2],ring[3],9.3,.37);
// Entry-side windows are a source-visible assembly; probe off their central
// mullions to establish first-hit glazing instead of accepting buried boxes.
facadeProbe(ring[0],ring[2],5.6,.67);facadeProbe(ring[0],ring[2],9.0,.67);
assert.equal(ray(new T.Vector3(65,1,0),new T.Vector3(0,0,1)).length,0,'east adjoining site/warehouse space consumed');assert.equal(ray(new T.Vector3(-70,1,0),new T.Vector3(0,0,1)).length,0,'west street consumed');const top=ray(new T.Vector3(-42,35,47),new T.Vector3(0,-1,0))[0];assert(top&&top.point.y<12.1&&top.point.y>11.6,'office flattened into high hall');console.log(JSON.stringify({triangles,roofLightSlopeFirstHits:slopeProbes,facadeFirstHits:6,bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},checks:['finite native scope','four flattened skylights at measured heights','upward first-hit exposed glazing','low office and two entry-side window groups retained','east/west sites open']}));
