import assert from 'node:assert/strict';import * as T from 'three';import {buildGerardDouSynagogue} from './landmarks/gerard-dou-synagogue-builder';import source from './landmarks/gerard-dou-synagogue-footprints.json';import type {BuildingTools} from './landmarks/cultural-builders';
const meshes:T.Mesh[]=[],material=new T.MeshBasicMaterial({side:T.DoubleSide});buildGerardDouSynagogue(0,0,{add(g:T.BufferGeometry,c:string){assert(g.getAttribute('position').array.every(Number.isFinite));const m=new T.Mesh(g,material);m.userData={...g.userData,colour:c};m.updateMatrixWorld();meshes.push(m);}}as BuildingTools);
const bounds=new T.Box3();for(const m of meshes)bounds.expandByObject(m);assert(bounds.max.y<18&&bounds.max.y>16);assert(bounds.min.x>-9&&bounds.max.x<12);let triangles=0,roofTriangles=0;for(const m of meshes){const g=m.geometry,p=g.getAttribute('position'),ix=g.index;triangles+=(ix?.count??p.count)/3;if(m.userData.role!=='roof')continue;for(let i=0;i<(ix?.count??p.count);i+=3){const q=[0,1,2].map(j=>new T.Vector3().fromBufferAttribute(p,ix?.getX(i+j)??i+j)),n=q[1].clone().sub(q[0]).cross(q[2].clone().sub(q[0]));assert(n.y>=-1e-6,'Downward roof face');roofTriangles++;}}
const [a,c]=[0,1].map(i=>new T.Vector2(source.localRing[i][0],source.localRing[i][1])),u=c.clone().sub(a).normalize(),n=new T.Vector2(-u.y,u.x),mid=a.clone().lerp(c,.5);let paneProbes=0;
function first(x:number,y:number,z:number,expected:string){const p=mid.clone().addScaledVector(u,x).addScaledVector(n,z),origin=new T.Vector3(p.x,y,p.y),ray=new T.Raycaster(origin,new T.Vector3(-n.x,0,-n.y),0,8),hit=ray.intersectObjects(meshes)[0];assert.equal(hit?.object.userData.role,expected,`First-hit ${x},${y}: ${hit?.object.userData.role}`);paneProbes++;}
for(const x of [-1.40,1.40])for(const f of [-.40,-.15,.15,.40])for(const y of [5.49,6.03,6.74,7.91,8.63])first(x+f*1.92,y,3,'high-arched-glass');
for(const x of [-2.86,2.86])first(x+.05,2.02,3,'ground-glass');first(.16,13.61,3,'star-glass');
const [rs,re]=[55,59].map(i=>new T.Vector3(source.surveyVertices[i][0],source.surveyVertices[i][1],source.surveyVertices[i][2])),rt=re.clone().sub(rs),rn=new T.Vector3(-rt.z,0,rt.x).normalize(),rm=rs.clone().lerp(re,.5);for(const y of [5.9,7.1,8.4]){const o=rm.clone().setY(y).addScaledVector(rn,3),hit=new T.Raycaster(o,rn.clone().negate(),0,6).intersectObjects(meshes)[0];assert.equal(hit?.object.userData.role,'rear-glass','Rear hall glazing must clear the surveyed wall');paneProbes++;}
// Source silhouette checks: formerly glazed arch heads are now blind masonry above rectangular panes.
for(const x of [-2.86,2.86]){for(const dx of [-.31,.31])for(const y of [1.67,2.24,3.48])first(x+dx,y,3,'ground-glass');for(const dx of [-.18,.18])first(x+dx,3.89,3,'ground-blind-arched-field');}
// Inner round-frame samples sit on photographed concentric curves, away from connecting bars.
for(const x of [-1.40,1.40])for(const scale of [.36,.70])for(const a of [Math.PI/3,Math.PI*2/3])first(x+.96*scale*Math.cos(a),9.34+.99*scale*Math.sin(a),3,'concentric-arch-frame');
assert.equal(source.holes.length,0);assert(source.neighbors.length>2);assert.equal(source.bagId,'NL.IMBAG.Pand.0363100012140916');assert(triangles<40000);console.log(JSON.stringify({triangles,roofTriangles,paneProbes,bounds:{min:bounds.min,max:bounds.max},scope:'Native geometry and first-hit source-front panes; GPU/gallery/live route-pin-card and neighbor retention pending'}));
