import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {MeshoptDecoder} from 'meshoptimizer';
import {collectMeerpadkerk} from './landmarks/meerpadkerk-export';import source from './landmarks/meerpadkerk-footprints.json';import spec from './landmarks/meerpadkerk-spec.json';
await MeshoptDecoder.ready;const path=process.argv[2]??'artifacts/meerpadkerk-draft/meerpadkerk.glb';
const {parts,probes}=collectMeerpadkerk(),group=new T.Group();for(const p of parts){const m=new T.Mesh(p.g,new T.MeshBasicMaterial({side:T.FrontSide}));m.userData.colour=p.c;group.add(m);}group.updateMatrixWorld(true);
assert.deepEqual(spec.suppressOsmIds,['w280806252','NL.IMBAG.Pand.0363100012162810']);assert.equal(spec.surveyed.northOffsetDegrees,0);
const xy=(p:number[])=>new T.Vector2((p[0]-source.anchor[0])*111320*Math.cos(source.anchor[1]*Math.PI/180),-(p[1]-source.anchor[1])*110540);
for(const n of source.retainedNeighbors){assert(!spec.suppressOsmIds.includes(n.id));const ring=n.geometry.coordinates[0],p=ring.slice(0,-1).reduce((s,p)=>[s[0]+p[0]/(ring.length-1),s[1]+p[1]/(ring.length-1)],[0,0]),q=xy(p);assert.equal(new T.Raycaster(new T.Vector3(q.x,20,q.y),new T.Vector3(0,-1,0)).intersectObject(group,true).length,0,`Retain ${n.id}`);}
for(const p of source.openSpaceProbes){const q=xy(p.lonLat);assert.equal(new T.Raycaster(new T.Vector3(q.x,20,q.y),new T.Vector3(0,-1,0)).intersectObject(group,true).length,0,p.name);}
// Fractions over the exposed pane interiors, avoiding intentional frame/mullions.
for(const p of probes.glazingProbes){const n=new T.Vector2(...p.normal),u=new T.Vector2(n.y,-n.x);for(const x of [-.29,.29])for(const f of [.18,.50,.83]){const q=new T.Vector2(...p.center).addScaledVector(u,x*p.width).addScaledVector(n,1.5),hits=new T.Raycaster(new T.Vector3(q.x,p.bottom+p.height*f,q.y),new T.Vector3(-n.x,0,-n.y),0,2).intersectObject(group,true);assert(hits.length);assert.equal(hits[0].object.userData.colour,'glass','Masonry must not bury pane interiors');}}
let roofFaces=0;for(const p of parts){const pos=p.g.getAttribute('position');for(let i=0;i<pos.count;i++)assert(Number.isFinite(pos.getX(i))&&Number.isFinite(pos.getY(i))&&Number.isFinite(pos.getZ(i)));if(p.c==='slate'){const flat=p.g.index?p.g.toNonIndexed():p.g,ps=flat.getAttribute('position');for(let i=0;i<ps.count;i+=3){const a=new T.Vector3().fromBufferAttribute(ps,i),b=new T.Vector3().fromBufferAttribute(ps,i+1),c=new T.Vector3().fromBufferAttribute(ps,i+2);assert(b.clone().sub(a).cross(c.clone().sub(a)).y>0,'Explicit roof must face up');roofFaces++;}}}
const doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(path);assert.equal(doc.getRoot().listTextures().length,0);let triangles=0,decodedRoofFaces=0;const bounds=new T.Box3();
for(const node of doc.getRoot().listNodes()){const m=node.getMesh();if(!m)continue;const matrix=new T.Matrix4().fromArray(node.getWorldMatrix());for(const p of m.listPrimitives()){const pos=p.getAttribute('POSITION')!,idx=p.getIndices()!;triangles+=idx.getCount()/3;for(let i=0;i<pos.getCount();i++)bounds.expandByPoint(new T.Vector3(...pos.getElement(i,[])).applyMatrix4(matrix));if(p.getMaterial()?.getName()==='slate')for(let i=0;i<idx.getCount();i+=3){const v=[0,1,2].map(k=>new T.Vector3(...pos.getElement(idx.getScalar(i+k),[])).applyMatrix4(matrix));const cross=v[1].clone().sub(v[0]).cross(v[2].clone().sub(v[0]));assert(cross.y>0,'Decoded compressed roof must face up');decodedRoofFaces++;}}}
const decoded=new T.Group();
for(const node of doc.getRoot().listNodes()){const mesh=node.getMesh();if(!mesh)continue;const matrix=new T.Matrix4().fromArray(node.getWorldMatrix());for(const primitive of mesh.listPrimitives()){const pa=primitive.getAttribute('POSITION')!,g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(Array.from({length:pa.getCount()},(_,i)=>pa.getElement(i,[])).flat(),3));g.setIndex(Array.from(primitive.getIndices()!.getArray()!));g.applyMatrix4(matrix);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));m.userData.colour=primitive.getMaterial()?.getName();decoded.add(m);}}
decoded.updateMatrixWorld(true);
for(const p of probes.glazingProbes){const n=new T.Vector2(...p.normal),u=new T.Vector2(n.y,-n.x);for(const x of [-.29,.29])for(const f of [.18,.50,.83]){const q=new T.Vector2(...p.center).addScaledVector(u,x*p.width).addScaledVector(n,1.5),hits=new T.Raycaster(new T.Vector3(q.x,p.bottom+p.height*f,q.y),new T.Vector3(-n.x,0,-n.y),0,2).intersectObject(decoded,true);assert(hits.length);assert.equal(hits[0].object.userData.colour,'glass','Decoded pane interior must remain first-hit glass');}}
const ring=source.localRing.slice(0,-1);function inside(x:number,z:number){let yes=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,zi]=ring[i],[xj,zj]=ring[j];if(((zi>z)!==(zj>z))&&x<(xj-xi)*(z-zi)/(zj-zi)+xi)yes=!yes;}return yes;}
for(const mesh of decoded.children as T.Mesh[])if(mesh.userData.colour==='slate'){const g=mesh.geometry,p=g.getAttribute('position'),ix=g.index!;for(let i=0;i<ix.count;i+=3){const v=[0,1,2].map(k=>new T.Vector3().fromBufferAttribute(p,ix.getX(i+k))),c=v.reduce((sum,p)=>sum.add(p),new T.Vector3()).multiplyScalar(1/3);assert(inside(c.x,c.z),'Roof face must be supported by surveyed plan');const hit=new T.Raycaster(new T.Vector3(c.x,20,c.z),new T.Vector3(0,-1,0)).intersectObject(decoded,true);assert(hit.length);assert.equal(hit[0].object.userData.colour,'slate','Explicit roof must own top; no wall-colored cap');}}
assert(triangles<40000);assert(fs.statSync(path).size<500000);assert(Math.abs(bounds.max.y-source.heights.ridgeAboveGround)<.20);assert(bounds.max.y<8&&bounds.min.y>-.05);
const result={path,triangles,bytes:fs.statSync(path).size,roofFaces,decodedRoofFaces,glazingProbes:probes.glazingProbes.length*6,decodedGlazingProbes:probes.glazingProbes.length*6,retainedNeighbors:source.retainedNeighbors.length,bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},scope:'Geometry preflight only. Gallery/live/physical pointer/route/pin acceptance pending.'};fs.writeFileSync('artifacts/meerpadkerk-draft/geometry-check.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
