/** Actual binary decoding, bounded visibility and atomic representation changes. */
import fs from 'node:fs';import assert from 'node:assert/strict';import * as THREE from 'three';
import {BuildingViewportStreamer} from '../src/canalRecall/buildingLibraryViewportStreaming';
import {batchParts,pickOwner} from '../src/canalRecall/buildingLibraryTileBatching';
import type {ViewportManifest,ViewportSelection} from '../src/canalRecall/buildingLibraryViewport';
const root='artifacts/district-render-chunks',manifest=JSON.parse(fs.readFileSync(root+'/fine/tiles.json','utf8')),parent=new THREE.Group();
const camera=new THREE.PerspectiveCamera(70,1.3,.1,500);camera.up.set(0,0,1);
const aim=(tile:any)=>{const centre=new THREE.Vector3(...tile.bounds.min).add(new THREE.Vector3(...tile.bounds.max)).multiplyScalar(.5).add(new THREE.Vector3(...tile.offset));camera.position.copy(centre).add(new THREE.Vector3(0,-35,20));camera.lookAt(centre);};
let maxActive=0,maxTriangles=0,maxBytes=0,fetches=0,pickingChecks=0;
const bytes=(url:string)=>{const b=fs.readFileSync(root+'/fine/'+url);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);};
const actual=new BuildingViewportStreamer({detail:manifest},{parent,maxChunks:8,maxTriangles:20000,maxGeometryBytes:2000000,maxConcurrent:2,fetchBinary:async(s)=>{fetches++;await Promise.resolve();return bytes(s.tile.binaryUrl);}});
for(const tile of manifest.tiles){aim(tile);const pending=actual.update(camera);maxActive=Math.max(maxActive,actual.stats.activeRequests);const result=await pending;assert.ok(result.results.every(r=>r.status==='fulfilled'));assert.ok(actual.stats.owners.includes(tile.owners[0]));assert.equal(actual.stats.owners.length,new Set(actual.stats.owners).size);assert.ok(actual.stats.residentTriangles<=20000);assert.ok(actual.stats.residentGeometryBytes<=2000000);assert.equal(parent.children.length,actual.stats.residentChunks);for(const group of parent.children)for(const node of group.children as THREE.Mesh[])for(const range of node.userData.ownerRanges){assert.equal(pickOwner(node,range.firstTriangle)?.ownerId,range.ownerId);assert.equal(pickOwner(node,range.firstTriangle+range.triangleCount-1)?.buildingId,range.buildingId);pickingChecks++;}maxTriangles=Math.max(maxTriangles,actual.stats.residentTriangles);maxBytes=Math.max(maxBytes,actual.stats.residentGeometryBytes);}
actual.dispose();assert.equal(parent.children.length,0);assert.equal(actual.stats.residentTriangles,0);await assert.rejects(actual.update(camera),/disposed/);
// Mathematical LOD fixture: distinct valid one/two-triangle payloads of one owner.
function fixture(level:string,count:number){
 const geo=new THREE.BufferGeometry();const p=[0,0,0,1,0,0,0,0,1],n=[0,-1,0,0,-1,0,0,-1,0];geo.setAttribute('position',new THREE.Float32BufferAttribute(Array.from({length:count},()=>p).flat(),3));geo.setAttribute('normal',new THREE.Float32BufferAttribute(Array.from({length:count},()=>n).flat(),3));
 const owner={id:'fixture',buildingId:'fixture-BAG',geometryRevision:'original',sourceModelHash:level+'-hash',canonicalOwnershipKey:'14/1/1'};
 const batch=batchParts([{owner,mesh:new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:'#887766',roughness:.86})),matrix:new THREE.Matrix4()}]).batches[0];
 const chunks:Buffer[]=[];let offset=0;const attributes:any={};
 for(const key of ['position','normal','colour','index']as const){const data=batch[key],padding=(4-offset%4)%4;if(padding){chunks.push(Buffer.alloc(padding));offset+=padding;}attributes[key]={byteOffset:offset,length:data.length,type:key==='index'?(data instanceof Uint16Array?'uint16':'uint32'):'float32'};const b=Buffer.from(data.buffer,data.byteOffset,data.byteLength);chunks.push(b);offset+=b.byteLength;}
 const buffer=Buffer.concat(chunks);const manifest:ViewportManifest={version:1,binaryEndianness:'little',owners:[owner],tiles:[{key:'18/1/1',offset:[0,0,0],bounds:{min:[0,0,0],max:[1,0,1]},binaryUrl:level+'.bin',geometryBytes:buffer.byteLength,triangles:count,owners:['fixture'],batches:[{state:batch.state,attributes,ownerRanges:batch.ownerRanges,triangles:count}]}]};return {manifest,binary:buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.byteLength)};
}
const detailed=fixture('detail',2),massing=fixture('massing',1);let broken=true,release:((b:ArrayBuffer)=>void)|undefined,delayed=false;
const lodCamera=new THREE.PerspectiveCamera(60,1,.1,1000);lodCamera.up.set(0,0,1);lodCamera.position.set(.5,-40,.5);lodCamera.lookAt(.5,0,.5);
const lod=new BuildingViewportStreamer({detail:detailed.manifest,massing:massing.manifest},{parent,maxChunks:1,maxTriangles:3,maxGeometryBytes:2000,maxConcurrent:1,fetchBinary:async(s)=>{if(delayed)return new Promise(resolve=>{release=resolve;});if(s.level==='massing'&&broken)return new ArrayBuffer(4);return s.level==='detail'?detailed.binary:massing.binary;}});
await lod.update(lodCamera);const good=parent.children[0];let disposedGeometries=0,disposedMaterials=0;const originalMeshes=[...good.children]as THREE.Mesh[];for(const mesh of originalMeshes){mesh.geometry.addEventListener('dispose',()=>disposedGeometries++);(mesh.material as THREE.Material).addEventListener('dispose',()=>disposedMaterials++);}assert.equal(lod.stats.residentTriangles,2);
lodCamera.position.y=-300;lodCamera.lookAt(.5,0,.5);const failed=await lod.update(lodCamera);assert.ok(failed.results.some(r=>r.status==='rejected'));assert.equal(parent.children[0],good);assert.equal(lod.stats.levels['18/1/1'],'detail');
broken=false;await lod.update(lodCamera);assert.equal(lod.stats.levels['18/1/1'],'massing');assert.equal(lod.stats.residentTriangles,1);assert.equal(parent.children.length,1);assert.equal(good.parent,null);assert.equal(disposedGeometries,originalMeshes.length);assert.equal(disposedMaterials,originalMeshes.length);
delayed=true;lodCamera.position.y=-40;lodCamera.lookAt(.5,0,.5);const late=lod.update(lodCamera);await Promise.resolve();assert.ok(release);lod.dispose();assert.equal(parent.children.length,0);release!(detailed.binary);await late;await new Promise(resolve=>setTimeout(resolve,0));assert.equal(parent.children.length,0);assert.equal(lod.stats.activeRequests,0);
const report={passed:true,realOwners:20,realViewportCases:manifest.tiles.length,actualAssetLevels:['detail'],realBinaryFetches:fetches,maxActiveRequests:maxActive,maxResidentTriangles:maxTriangles,maxResidentGeometryBytes:maxBytes,wholeOwnerPickingIdentityRetained:true,pickingChecks,disposedGeometries,disposedMaterials,atomicLodReplacementFixture:true,failedReplacementRetainsGoodResident:true,lateCancelledVariantCannotAttach:true,resourcesDisposed:true,fixtureLodGeometryIsNotClaimedAsAuthoredBuildingLod:true};fs.writeFileSync(root+'/viewport-streaming-checks.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
