import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';
import {buildThisIsHolland,hollandBoundary,hollandHeights} from './landmarks/this-is-holland-builder';import type {BuildingTools} from './landmarks/cultural-builders';import source from './landmarks/this-is-holland-footprints.json';
const group=new T.Group(),meshes:T.Mesh[]=[];
buildThisIsHolland(29,29,{add(g,c,x=0,y=0,z=0,a=0){g.rotateY(a);g.translate(x,y,z);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));m.userData={role:g.userData.role,colour:c};group.add(m);meshes.push(m)}} as BuildingTools);group.updateMatrixWorld(true);
const bounds=new T.Box3().setFromObject(group);for(const v of [...bounds.min.toArray(),...bounds.max.toArray()])assert(Number.isFinite(v));assert(bounds.max.y<25.5&&bounds.max.y>=25.15);assert(bounds.getSize(new T.Vector3()).x>28&&bounds.getSize(new T.Vector3()).x<30);
let triangles=0,roofTriangles=0;for(const m of meshes){const p=m.geometry.getAttribute('position'),ix=m.geometry.index;triangles+=(ix?.count??p.count)/3;for(let i=0;i<p.count;i++)assert(Number.isFinite(p.getX(i))&&Number.isFinite(p.getY(i))&&Number.isFinite(p.getZ(i)));if(['supported-roof','roof-rim-top'].includes(m.userData.role)){for(let i=0;i<(ix?.count??p.count);i+=3){const v=[0,1,2].map(k=>new T.Vector3().fromBufferAttribute(p,ix?ix.getX(i+k):i+k));const n=v[1].sub(v[0]).cross(v[2].sub(v[0]));assert(n.y>0,'Explicit roof triangle faces upward');roofTriangles++;}}}assert(triangles<40000);
const ray=(x:number,y:number,z:number,dx:number,dz:number)=>new T.Raycaster(new T.Vector3(x,y,z),new T.Vector3(dx,0,dz).normalize()).intersectObject(group,true);
// Sample fractional spans on every source foyer edge: first hit must remain glazing or narrow frame.
const foyer=source.glazedFoyer.slice(0,-1),probes=[];for(let i=0;i<foyer.length;i++){const a=foyer[i],q=foyer[(i+1)%foyer.length],len=Math.hypot(q[0]-a[0],q[1]-a[1]);if(len<.6)continue;for(const t of[.2,.5,.8])for(const y of[1.1,3.2,5.3]){const x=a[0]+(q[0]-a[0])*t,z=a[1]+(q[1]-a[1])*t,n=new T.Vector2(x,z).normalize(),hits=ray(x+n.x*1.5,y,z+n.y*1.5,-n.x,-n.y);assert(hits.length);const role=hits[0].object.userData.role;assert(/foyer-glazing|foyer-mullion|entrance-door/.test(role),`Buried glazing edge${i} t${t} y${y}: ${role}`);probes.push({edge:i,t,y,firstHit:role})}}
// Twisted silver panels must be first-hit visible; shallow surveyed backing can bury them.
let panelProbes=0;for(let row=0;row<8;row++)for(let col=0;col<24;col++)for(const t of[.2,.5,.8]){const angle=(col+t)*Math.PI/12+(row+.5)*.055,[x,z]=hollandBoundary(angle,-2),n=new T.Vector2(x,z).normalize(),hits=ray(x,6.4+(row+.5)*(25.15-6.4)/8,z,-n.x,-n.y);assert.equal(hits.find(h=>!String(h.object.userData.role).startsWith('source-sign-'))?.object.userData.role,'silver-panel',`Buried silver panel row${row} col${col} fraction${t}`);panelProbes++;}
// Source BAG ring overhang is open below the upper shell; it must not become a solid base.
for(let i=0;i<24;i++){const angle=i*Math.PI/12,[x,z]=hollandBoundary(angle,.4);const hits=new T.Raycaster(new T.Vector3(x,2,z),new T.Vector3(0,1,0),0,3.8).intersectObject(group,true);assert.equal(hits.length,0,'Overhang annulus remains open below6m');}
// Actual mapped door point is southeast, on the foyer, and source identity belongs to this BAG parent.
assert(source.entrance.local[0]>0&&source.entrance.local[1]>0);assert.equal(source.vbo.status,'Verblijfsobject in gebruik');assert.equal(source.buildingId,'NL.IMBAG.Pand.0363100012246118');
const result={status:'passed',bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},triangles,roofTriangles,foyerFractionalProbes:probes.length,openOverhangProbes:24,panelFractionalProbes:panelProbes,heights:hollandHeights,limitations:'Geometry only. Root must review source/render, gallery/live sides, current exact suppression and retained neighbors, route/pin/physical sourced card.'};fs.mkdirSync('artifacts/this-is-holland-draft',{recursive:true});fs.writeFileSync('artifacts/this-is-holland-draft/geometry-check.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));

// Inspect the actual compressed draft, including world transforms introduced by quantization.
if(fs.existsSync('artifacts/this-is-holland-draft/this-is-holland.glb')){
 const {NodeIO}=await import('@gltf-transform/core'),{ALL_EXTENSIONS}=await import('@gltf-transform/extensions'),{MeshoptDecoder}=await import('meshoptimizer');await MeshoptDecoder.ready;
 const doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read('artifacts/this-is-holland-draft/this-is-holland.glb');assert.equal(doc.getRoot().listTextures().length,0);let decodedRoof=0,decodedTriangles=0;const decodedBounds=new T.Box3();
 for(const node of doc.getRoot().listNodes()){const mesh=node.getMesh();if(!mesh)continue;const matrix=new T.Matrix4().fromArray(node.getWorldMatrix());for(const prim of mesh.listPrimitives()){const pos=prim.getAttribute('POSITION')!,ix=prim.getIndices(),count=ix?.getCount()??pos.getCount();decodedTriangles+=count/3;for(let i=0;i<count;i+=3){const ps=[0,1,2].map(k=>{const v=new T.Vector3(...pos.getElement(ix?ix.getScalar(i+k):i+k,[])).applyMatrix4(matrix);assert(v.toArray().every(Number.isFinite));decodedBounds.expandByPoint(v);return v});if(prim.getMaterial()?.getName()==='slate'){const n=ps[1].clone().sub(ps[0]).cross(ps[2].clone().sub(ps[0]));assert(n.y>0,'Compressed supported roof must face upward');decodedRoof++;}}}}
 const bytes=fs.statSync('artifacts/this-is-holland-draft/this-is-holland.glb').size;assert(bytes<500000&&decodedTriangles<40000);assert(decodedRoof>0);const report={status:'passed',bytes,triangles:decodedTriangles,decodedUpwardRoofTriangles:decodedRoof,textures:0,bounds:{min:decodedBounds.min.toArray(),max:decodedBounds.max.toArray()}};fs.writeFileSync('artifacts/this-is-holland-draft/compressed-check.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}
