import assert from 'node:assert/strict';
import * as T from 'three';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {NodeIO} from '@gltf-transform/core';
import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
import {MeshoptDecoder} from 'meshoptimizer';
import {buildCafeKobalt} from './landmarks/cafe-kobalt-builder';
import type {BuildingTools} from './landmarks/cultural-builders';
import spec from './landmarks/cafe-kobalt-spec.json';
import {openTopPrism} from './landmarks/house-geometry';
import source from './landmarks/cafe-kobalt-footprints.json';
const meshes:T.Mesh[]=[],b={add(g:T.BufferGeometry,c:string){const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));m.userData.colour=c;m.updateMatrixWorld();meshes.push(m);}} as BuildingTools;
buildCafeKobalt(0,0,b);const bounds=new T.Box3();let triangles=0,paneSamples=0;const failed:any[]=[];
for(const m of meshes){const p=m.geometry.getAttribute('position');for(let i=0;i<p.count;i++)assert([p.getX(i),p.getY(i),p.getZ(i)].every(Number.isFinite));m.geometry.computeBoundingBox();bounds.union(m.geometry.boundingBox!);triangles+=(m.geometry.index?.count??p.count)/3;}
assert(triangles<40000);assert(bounds.min.y>-.001);assert(bounds.max.y>18&&bounds.max.y<19.3);
for(const m of meshes.filter(m=>m.userData.colour==='glass')){const dir=new T.Vector2(...m.geometry.userData.facadeFacing),tangent=new T.Vector2(dir.y,-dir.x),p=m.geometry.getAttribute('position');let lo=Infinity,hi=-Infinity,face=-Infinity;for(let i=0;i<p.count;i++){const q=new T.Vector2(p.getX(i),p.getZ(i));lo=Math.min(lo,q.dot(tangent));hi=Math.max(hi,q.dot(tangent));face=Math.max(face,q.dot(dir));}const bb=m.geometry.boundingBox!;for(const f of [.15,.35,.65,.85])for(const h of [.15,.35,.65,.85]){paneSamples++;const q=tangent.clone().multiplyScalar(lo+(hi-lo)*f).addScaledVector(dir,face+.005),y=bb.min.y+(bb.max.y-bb.min.y)*h,hit=new T.Raycaster(new T.Vector3(q.x,y,q.y),new T.Vector3(-dir.x,0,-dir.y)).intersectObjects(meshes,false)[0];if(hit?.object!==m&&hit?.object.userData.colour!=='white')failed.push({f,h,y,colour:hit?.object.userData.colour});}}
assert.equal(failed.length,0,'Buried glazing');assert.equal(paneSamples,976);
const frontA=new T.Vector2(...source.localRing[2]),frontC=new T.Vector2(...source.localRing[6]),frontU=frontC.clone().sub(frontA).normalize(),frontN=new T.Vector2(-frontU.y,frontU.x),frontMid=frontA.clone().lerp(frontC,.5);let shutterSamples=0;
for(const y of [10.25,13.10,15.6])for(const side of [-1,1]){const q=frontMid.clone().addScaledVector(frontU,side*1.13).addScaledVector(frontN,5),hit=new T.Raycaster(new T.Vector3(q.x,y+.62,q.y),new T.Vector3(-frontN.x,0,-frontN.y)).intersectObjects(meshes,false)[0];assert(hit);assert.equal((hit.object as T.Mesh).geometry.userData.role,'shutter','Signature shutter buried');assert.equal(hit.object.userData.colour,'red','Signature shutter colour lost');shutterSamples++;}
const neighbors:T.Mesh[]=[];for(const f of source.retainedNeighbors){const rings=f.geometry.coordinates.map(r=>r.map(ll=>new T.Vector2((ll[0]-source.anchor[0])*111320*Math.cos(source.anchor[1]*Math.PI/180),(source.anchor[1]-ll[1])*111320))),shape=new T.Shape(rings[0]);for(const h of rings.slice(1))shape.holes.push(new T.Path(h));const m=new T.Mesh(openTopPrism(shape,0,f.height),new T.MeshBasicMaterial());m.userData.neighbor=f.id;m.updateMatrixWorld();neighbors.push(m);}
let contextShutterSamples=0;for(const y of [10.25,13.10,15.6])for(const side of [-1,1]){const q=frontMid.clone().addScaledVector(frontU,side*1.13).addScaledVector(frontN,7),hit=new T.Raycaster(new T.Vector3(q.x,y+.62,q.y),new T.Vector3(-frontN.x,0,-frontN.y)).intersectObjects([...meshes,...neighbors],false)[0];assert(hit);assert.equal((hit.object as T.Mesh).geometry.userData.role,'shutter','Retained neighbor blocks public Singel shutter');contextShutterSamples++;}
const signPoint=frontMid.clone().addScaledVector(frontN,7),signHit=new T.Raycaster(new T.Vector3(signPoint.x,3.88,signPoint.y),new T.Vector3(-frontN.x,0,-frontN.y)).intersectObjects([...meshes,...neighbors],false)[0];assert(signHit);assert.equal((signHit.object as T.Mesh).geometry.userData.role,'real-sign-panel','Actual sign panel blocked from public Singel');assert.equal(spec.suppressOsmIds.length,1);assert.equal(spec.suppressOsmIds[0],source.bagId);assert(!spec.spatialSuppression);
let ownershipEdges=0;for(const f of source.retainedNeighbors)for(const r of f.geometry.coordinates)ownershipEdges+=r.length-1;assert.equal(ownershipEdges,69);
const rearSkirts=meshes.filter(m=>m.geometry.userData.sourcePart==='rear-partywall');assert.equal(rearSkirts.length,2);for(const m of rearSkirts)assert.equal(m.userData.colour,'brick');
const rearA=new T.Vector2(...source.localRing[0]),rearC=new T.Vector2(...source.localRing[1]),rearU=rearC.clone().sub(rearA).normalize(),rearN=new T.Vector2(-rearU.y,rearU.x);let rearOwnershipSamples=0;
for(const f of [.25,.40,.60,.75]){const contact=rearA.clone().lerp(rearC,f),outside=contact.clone().addScaledVector(rearN,3),ray=new T.Raycaster(new T.Vector3(outside.x,13,outside.y),new T.Vector3(-rearN.x,0,-rearN.y)),hits=ray.intersectObjects(meshes,false);assert(hits[0]);assert.equal((hits[0].object as T.Mesh).geometry.userData.sourcePart,'rear-partywall');const coincident=hits.filter(h=>Math.abs(h.distance-hits[0].distance)<.001);assert.equal(new Set(coincident.map(h=>h.object)).size,1,'Duplicate rear gable ownership');rearOwnershipSamples++;}
function inside(x:number,z:number){let flag=false;const r=source.localRing;for(let i=0,j=r.length-1;i<r.length;j=i++){const p=r[i],q=r[j];if((p[1]>z)!==(q[1]>z)&&x<(q[0]-p[0])*(z-p[1])/(q[1]-p[1])+p[0])flag=!flag;}return flag;}
const roofs=meshes.filter(m=>m.geometry.userData.role==='roof');let roofSamples=0,roofMisses=0;for(let x=-8.8;x<6.7;x+=.1)for(let z=-9.5;z<8.2;z+=.1)if(inside(x,z)){roofSamples++;if(!new T.Raycaster(new T.Vector3(x,30,z),new T.Vector3(0,-1,0)).intersectObjects(roofs,false)[0])roofMisses++;}assert.equal(roofMisses,0);assert.equal(roofSamples,13572);
await MeshoptDecoder.ready;const file='artifacts/cafe-kobalt-cpu/cafe-kobalt-compressed.glb',bytes=fs.readFileSync(file),doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(file);let decodedRoofTriangles=0;const roofFaces:any[]=[];
for(const node of doc.getRoot().listNodes()){const mesh=node.getMesh();if(!mesh)continue;const matrix=new T.Matrix4().fromArray(node.getWorldMatrix());for(const prim of mesh.listPrimitives()){if(prim.getExtras().role!=='roof')continue;const p=prim.getAttribute('POSITION')!,ix=prim.getIndices()?.getArray();for(let i=0;i<(ix?.length??p.getCount());i+=3){const pts=[0,1,2].map(k=>new T.Vector3(...p.getElement(ix?ix[i+k]:i+k,[])).applyMatrix4(matrix)),cross=pts[1].clone().sub(pts[0]).cross(pts[2].clone().sub(pts[0])),area=cross.length()/2,normalY=cross.normalize().y;roofFaces.push({area,normalY,points:pts.map(p=>p.toArray())});assert(area>1e-5);assert(normalY>.3,'Decoded roof reversed');decodedRoofTriangles++;}}}
assert(decodedRoofTriangles>10);assert.equal(doc.getRoot().listTextures().length,0);assert(bytes.length<500000);
const result={ok:true,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,triangles,paneSamples,shutterSamples,contextShutterSamples,retainedNeighborCount:neighbors.length,retainedNeighborEdges:ownershipEdges,signPanelPublicFirstHit:true,rearOwnershipSamples,failedPaneSamples:failed.length,roofSamples,roofMisses,decodedRoofTriangles,decodedRoofFaces:roofFaces};fs.writeFileSync('artifacts/cafe-kobalt-cpu/geometry-check.json',JSON.stringify(result,null,2));console.log(JSON.stringify({...result,decodedRoofFaces:undefined}));
