import assert from 'node:assert/strict';
import * as T from 'three';
import {buildStadhuis} from './landmarks/stadhuis-builder';
import source from './landmarks/stadhuis-footprints.json';
import spec from './landmarks/stadhuis-spec.json';
import type {BuildingTools} from './landmarks/cultural-builders';
const group=new T.Group(),geometries:T.BufferGeometry[]=[],panes:{mesh:T.Mesh;centre:T.Vector3;normal:T.Vector3;tangent:T.Vector3}[]=[];
const add:BuildingTools['add']=(g,c,x=0,y=0,z=0,a=0)=>{const params=(g as T.BoxGeometry).parameters;const pane=c==='glass'&&g instanceof T.BoxGeometry&&params.depth<.15;g.rotateY(a);g.translate(x,y,z);geometries.push(g);const mesh=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.userData.colour=c;group.add(mesh);if(pane)panes.push({mesh,centre:new T.Vector3(x,y,z),normal:new T.Vector3(Math.sin(a),0,Math.cos(a)),tangent:new T.Vector3(Math.cos(a),0,-Math.sin(a))});};
const tools:BuildingTools={add,box(x,y,z,w,h,d,c,a=0){add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a);},prism(){throw Error('unused');},hip(){throw Error('unused');},gableRoof(){throw Error('unused');},window(){throw Error('unused');},clock(){throw Error('unused');},sign(){throw Error('unused');}};
buildStadhuis(spec.footprint.lengthMetres,spec.footprint.widthMetres,tools);group.updateMatrixWorld(true);
let triangles=0;for(const g of geometries){const p=g.getAttribute('position');for(const x of p.array)assert.ok(Number.isFinite(x));triangles+=(g.index?.count||p.count)/3;}assert.ok(triangles<40000);const bounds=new T.Box3().setFromObject(group);assert.ok(Math.abs(bounds.max.y-22)<.01,'recorded exterior component maximum, not inferred equipment height');assert.ok(bounds.max.x-bounds.min.x<212&&bounds.max.z-bounds.min.z<201);
const vertices=geometries.flatMap(g=>{const p=g.getAttribute('position');return Array.from({length:p.count},(_,i)=>[p.getX(i),p.getY(i),p.getZ(i)]);});for(const part of source.parts){if(part.properties['building:part']==='roof')continue;const base=Number((part.properties as Record<string,string>).min_height||0);for(const poly of part.localPolygons)for(const ring of poly)for(const [x,z]of ring){assert.ok(vertices.some(p=>Math.abs(p[0]-x)<1e-4&&Math.abs(p[1]-base)<1e-4&&Math.abs(p[2]-z)<1e-4),'native mapped wall base '+part.osmId);const top=Number(part.properties.height);assert.ok(vertices.filter(p=>Math.abs(p[0]-x)<1e-4&&Math.abs(p[1]-top)<1e-4&&Math.abs(p[2]-z)<1e-4).length>=2,'actual roof and wall share native top perimeter '+part.osmId);}}
assert.equal(source.parts.length,23);assert.equal(spec.spatialSuppression,false);assert.equal(spec.suppressOsmIds.length,26);assert.ok(spec.suppressOsmIds.includes('w268782345'));assert.ok(spec.suppressOsmIds.includes('w751591420'));assert.ok(spec.suppressOsmIds.includes('NL.IMBAG.Pand.0363100012186092'));for(const id of ['w268782532','w268782535','w268782486','w268782513'])assert.ok(!spec.suppressOsmIds.includes(id),'independent neighbors retained');
// Actual uploaded geometry must leave ground clear below mapped lifted wings
// and glazed passage roofs. A parent extrusion would fail all these rays.
for(const p of source.openGroundProbes){const [x,z]=p.point;assert.equal(new T.Raycaster(new T.Vector3(x,.2,z),new T.Vector3(0,1,0),0,3.6).intersectObject(group,true).length,0,'source-defined ground aperture '+p.point);}
for(const [x,z]of source.unbuiltPlotProbes)assert.equal(new T.Raycaster(new T.Vector3(x,30,z),new T.Vector3(0,-1,0),0,31).intersectObject(group,true).length,0,'no opaque wholeplot/plaza cap');
// Verify façade panes are in front of actual mesh walls, not buried beneath
// source parent bodies or adjacent part extrusions. Offset from narrow mullion.
let visible=0;for(const p of panes){const target=p.centre.clone().addScaledVector(p.tangent,.3);const hit=new T.Raycaster(target.clone().addScaledVector(p.normal,2),p.normal.clone().negate(),0,2.4).intersectObject(group,true)[0];if(hit?.object===p.mesh)visible++;}assert.ok(visible>100,'many physically visible office/foyer panes');assert.ok(visible/panes.length>.9,'facade first-hit visibility ratio');
// Canopy ridge is actual glass at7m, with lower clearance above source street.
const roof=source.glazedStreetRoof,part=source.parts.find(p=>p.osmId==='w751573305')!,point=[(part.bounds[0]+part.bounds[2])/2,(part.bounds[1]+part.bounds[3])/2];const d=point[0]*roof.normal[0]+point[1]*roof.normal[1]-roof.mid,x=point[0]-(d-.25)*roof.normal[0],z=point[1]-(d-.25)*roof.normal[1];const roofHits=new T.Raycaster(new T.Vector3(x,7.2,z),new T.Vector3(0,-1,0),0,.4).intersectObject(group,true);assert.ok(roofHits.some(h=>h.object.userData.colour==='glass'),'real source glass roof is present at ridge');
// Double-sided materials can hide reversed winding. Inspect real triangle
// winding and cast from above with front-face culling on every authored roof.
const roofs=group.children.filter(m=>m instanceof T.Mesh&&m.geometry instanceof T.ShapeGeometry) as T.Mesh<T.ShapeGeometry>[];assert.equal(roofs.length,24,'23 part roofs including split glazed street');
for(const roofMesh of roofs){const g=roofMesh.geometry,p=g.getAttribute('position'),n=g.getAttribute('normal'),index=g.index!;for(let i=0;i<p.count;i++)assert.ok(n.getY(i)>.1,'actual roof normal faces upward');for(let i=0;i<index.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,index.getX(i)),b=new T.Vector3().fromBufferAttribute(p,index.getX(i+1)),c=new T.Vector3().fromBufferAttribute(p,index.getX(i+2)),normal=b.clone().sub(a).cross(c.clone().sub(a));if(normal.lengthSq()<1e-9)continue;assert.ok(normal.y>0,'actual roof triangle winding faces up');const centre=a.add(b).add(c).multiplyScalar(1/3);const frontOnly=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));frontOnly.updateMatrixWorld(true);const hit=new T.Raycaster(centre.clone().add(new T.Vector3(0,.5,0)),new T.Vector3(0,-1,0),0,.7).intersectObject(frontOnly);assert.ok(hit.length,'roof triangle visible from above with front-face culling');(frontOnly.material as T.Material).dispose();}}
console.log({triangles,parts:source.parts.length,exactAliases:spec.suppressOsmIds.length,openGroundProbes:source.openGroundProbes.length,unbuiltPlotProbes:source.unbuiltPlotProbes.length,facadePanes:panes.length,firstHitVisible:visible,bounds});
