import assert from 'node:assert/strict';import * as T from 'three';import fs from 'node:fs';
import {buildElectricLadyland} from './landmarks/electric-ladyland-builder';import source from './landmarks/electric-ladyland-footprints.json';import spec from './landmarks/electric-ladyland-spec.json';import type {BuildingTools} from './landmarks/cultural-builders';
const group=new T.Group(),panes:T.Mesh[]=[],roofs:T.Mesh[]=[];const add:BuildingTools['add']=(g,c,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);const m=new T.Mesh(g,new T.MeshBasicMaterial({side:T.FrontSide}));m.userData.colour=c;group.add(m);if(c==='glass')panes.push(m);if(c==='slate'&&(g.type==='BufferGeometry'||g.type==='ShapeGeometry'))roofs.push(m);};const unused=()=>{throw Error('unexpected primitive')};buildElectricLadyland(0,0,{add,box(x,y,z,w,h,d,c,a=0){add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a);},prism:unused,hip:unused,gableRoof:unused,window:unused,clock:unused,sign:unused});group.updateMatrixWorld(true);
let triangles=0;for(const m of group.children as T.Mesh[]){const p=m.geometry.getAttribute('position');for(const v of p.array)assert.ok(Number.isFinite(v));triangles+=(m.geometry.index?.count??p.count)/3;}assert.ok(triangles<40000);
const bounds=new T.Box3().setFromObject(group);assert.ok(bounds.max.y<13.3&&bounds.max.y>12.8,'survey-bounded hipped crown');assert.ok(bounds.max.x-bounds.min.x<20,'ensemble excludes rounded neighbor');assert.equal(spec.spatialSuppression,false);assert.ok(!source.neighborsToRetain.some(x=>spec.suppressOsmIds.includes(x)));
for(const m of roofs){const p=m.geometry.getAttribute('position'),n=m.geometry.getAttribute('normal');const used=m.geometry.index?new Set(Array.from(m.geometry.index.array)):new Set(Array.from({length:p.count},(_,i)=>i));for(const i of used)assert.ok(n.getY(i)>.1,'roof owns upward surface');}
// Footprint boundary vertices remain represented by exact native wall bases.
const walls=(group.children as T.Mesh[]).filter(m=>m.userData.colour==='brick'&&m.geometry.type==='BufferGeometry');
for(const part of source.parts)for(const [x,z]of part.ring)assert.ok(walls.some(m=>{const p=m.geometry.getAttribute('position');for(let i=0;i<p.count;i++)if(Math.abs(p.getX(i)-x)<.0001&&Math.abs(p.getZ(i)-z)<.0001&&Math.abs(p.getY(i))<.0001)return true;return false;}),'native footprint wall vertex preserved');
const probes=[[9,-5],[-1.5,-5],[-4.8,-4.0]];for(const [x,z]of probes)assert.equal(new T.Raycaster(new T.Vector3(x,25,z),new T.Vector3(0,-1,0),0,26).intersectObject(group,true).length,0,'native rear recess remains open');
function inside(x:number,z:number,ring:number[][]){let b=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],c=ring[j];if((a[1]>z)!==(c[1]>z)&&x<(c[0]-a[0])*(z-a[1])/(c[1]-a[1])+a[0])b=!b;}return b;}
let coveredSamples=0;for(let x=-5.6;x<13.6;x+=.24)for(let z=-6.6;z<4.7;z+=.24)if(source.parts.some(p=>inside(x,z,p.ring))){coveredSamples++;assert.ok(new T.Raycaster(new T.Vector3(x,40,z),new T.Vector3(0,-1,0),0,50).intersectObject(group,true).length,'native polygon interior roof coverage');}
assert.ok(new T.Raycaster(new T.Vector3(9,40,-3.3),new T.Vector3(0,-1,0),0,50).intersectObject(group,true).length,'south rear strip heldout coverage');
const failures=[];let visible=0;for(const m of panes){const bb=new T.Box3().setFromObject(m),center=bb.getCenter(new T.Vector3()),size=bb.getSize(new T.Vector3());let hits=0;for(const u of [-.31,-.17,.13,.29])for(const v of [-.19,.11,.24]){const p=center.clone().add(new T.Vector3(size.x*u,size.y*v,0));const hit=new T.Raycaster(p.clone().add(new T.Vector3(0,0,1.5)),new T.Vector3(0,0,-1),0,2).intersectObject(group,true)[0];if(hit?.object===m)hits++;}if(hits>=4)visible++;else failures.push({pane:center.toArray(),visibleSamples:hits});}assert.equal(visible,panes.length,JSON.stringify(failures));
const basement=panes.filter(m=>new T.Box3().setFromObject(m).getCenter(new T.Vector3()).y<1);assert.equal(basement.length,4,'four actual basement shop bays, not blank plinth');const upper=panes.filter(m=>{const y=new T.Box3().setFromObject(m).getCenter(new T.Vector3()).y;return y>4.4&&y<9.8});assert.equal(upper.length,24,'twelve independently visible leaves each upper floor');
const heads=(group.children as T.Mesh[]).filter(m=>m.userData.colour==='red'&&m.geometry.type==='ShapeGeometry');assert.equal(heads.length,16,'broad pair single heads and narrow leaf heads');let headVisible=0;for(const m of heads){const p=m.geometry.getAttribute('position'),ix=m.geometry.index!,samples=[];for(let k=0;k<ix.count;k+=3){const v=new T.Vector3();for(let j=0;j<3;j++)v.add(new T.Vector3().fromBufferAttribute(p,ix.getX(k+j)));samples.push(v.multiplyScalar(1/3));}if(samples.some(p=>new T.Raycaster(p.clone().add(new T.Vector3(0,0,1.5)),new T.Vector3(0,0,-1),0,2).intersectObject(group,true)[0]?.object===m))headVisible++;}assert.equal(headVisible,heads.length,'brick arches exposed in front of wall and separate from stone courses');
const result={triangles,compressedBytes:fs.statSync('artifacts/electric-ladyland/electric-ladyland.glb').size,panes:panes.length,visible,basement:basement.length,upperLeaves:upper.length,roofMeshes:roofs.length,coveredSamples,brickHeads:heads.length,visibleBrickHeads:headVisible,openSpaceProbes:probes,bounds:bounds.min.toArray().concat(bounds.max.toArray()),scope:'CPU risk checks only; independent reference/native-gallery/live-game acceptance pending'};assert.ok(result.compressedBytes<=500000);fs.writeFileSync('artifacts/electric-ladyland/geometry-check.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
