import assert from 'node:assert/strict';
import * as T from 'three';
import type { BuildingTools } from './landmarks/cultural-builders';
import {buildPiramides} from './landmarks/piramides-builder';
import spec from './landmarks/piramides-spec.json';
import source from './landmarks/piramides-footprints.json';
const geometries:T.BufferGeometry[]=[];
const add:BuildingTools['add']=(g,_c,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);geometries.push(g)};
const box:BuildingTools['box']=(x,y,z,w,h,d,c,a=0)=>add(new T.BoxGeometry(w,h,d),c,x,y+h/2,z,a);
const tools:BuildingTools={add,box,prism:()=>{throw Error('unused')},gableRoof:()=>{},hip:()=>{},window:()=>{},clock:()=>{},sign:(label,x,y,z,pixel,c='dark')=>{for(let j=0;j<label.length*35;j++)box(x+(j%40)*pixel,y+Math.floor(j/40)*pixel,z,pixel,pixel,pixel*.45,c)}};
buildPiramides(0,0,tools);
const bounds=new T.Box3();let triangles=0;
const material=new T.MeshBasicMaterial({side:T.DoubleSide});const meshes=geometries.map(g=>{g.computeBoundingBox();bounds.union(g.boundingBox!);triangles+=(g.index?.count??g.getAttribute('position').count)/3;for(const v of g.getAttribute('position').array)assert(Number.isFinite(v));return new T.Mesh(g,material)});
const roofAt=(x:number,z:number)=>{const ray=new T.Raycaster(new T.Vector3(x,60,z),new T.Vector3(0,-1,0));return ray.intersectObjects(meshes,false)[0]?.point.y??0};
assert(triangles<40000,`Triangle budget ${triangles}`);assert(bounds.max.y<55.1);assert(bounds.max.y>54.99);
assert(Math.abs(roofAt(-13,3)-55.012)<.1,'west crown reaches actual55m');
assert(Math.abs(roofAt(10,-4)-55.012)<.1,'east crown reaches actual55m');
assert(roofAt(-1,0)<33.1,'notch between twin crowns remains open above shared body');
assert(roofAt(0,20)===0,'public forecourt not extruded into a building');
assert(spec.suppressOsmIds.includes('w276272893'));assert(spec.suppressOsmIds.includes('NL.IMBAG.Pand.0363100012110293'));
assert.equal(spec.spatialSuppression,false);assert.equal(source.parts.length,14);
assert(!spec.suppressOsmIds.includes('w276273289'),'Marcanti College retained');
assert(source.measurements.b3RoofRelativeMetres>54.9&&source.measurements.b3RoofRelativeMetres<55.2);
assert(spec.suppressOsmIds.every(id=>/^(?:[nwr]\d+|NL\.IMBAG\.Pand\.\d{16})$/.test(id)));
console.log('De Piramides geometry passed',JSON.stringify({triangles,height:bounds.max.y,span:bounds.max.x-bounds.min.x,depth:bounds.max.z-bounds.min.z,westCrown:roofAt(-13,3),eastCrown:roofAt(10,-4),openNotch:roofAt(-1,0),relativeMeasuredRoof:source.measurements.b3RoofRelativeMetres}));
meshes.forEach(m=>m.geometry.dispose());material.dispose();
