import * as T from 'three';import fs from 'node:fs';import crypto from 'node:crypto';import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {MeshoptDecoder} from 'meshoptimizer';import {buildMelkweg} from './landmarks/melkweg-builder';import {buildRabozaalCompanion} from './landmarks/rabozaal-companion-builder';import footprint from './landmarks/melkweg-footprints.json';import coupled from './landmarks/melkweg-coupled-footprints.json';import {buildIndustrialTheaterCoupledLandmark} from './landmarks/stadsschouwburg-coupled-builder';import {legacyTools} from './landmarks/melkweg-coupled-legacy-tools';import specs from './landmarks/industrial-theater-specs.json';import type {BuildingTools} from './landmarks/cultural-builders';
await MeshoptDecoder.ready;const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder});const records=[];
for(const id of['melkweg','rabozaal-companion']){const path=`artifacts/landmark-next-batch/${id}.glb`,doc=await io.read(path);let downRoof=0,tri=0,min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];
 for(const m of doc.getRoot().listMeshes())for(const p of m.listPrimitives()){const a=p.getAttribute('POSITION')!,ix=p.getIndices()?.getArray(),len=ix?.length??a.getCount();for(let i=0;i<len;i+=3){const vs=[0,1,2].map(k=>new T.Vector3(...a.getElement(Number(ix?ix[i+k]:i+k),[])).applyMatrix4(new T.Matrix4().fromArray(doc.getRoot().listNodes().find(n=>n.getMesh()===m)!.getWorldMatrix())));for(const v of vs)for(let k=0;k<3;k++){min[k]=Math.min(min[k],v.getComponent(k));max[k]=Math.max(max[k],v.getComponent(k));if(!Number.isFinite(v.getComponent(k)))throw Error('nonfinite');}tri++;const cross=vs[1].clone().sub(vs[0]).cross(vs[2].clone().sub(vs[0]));if(p.getMaterial()?.getName()==='slate'&&cross.y<-.00001)downRoof++;}}
 const metal=doc.getRoot().listMaterials().map(m=>m.getMetallicFactor());console.log({id,downRoof});if(downRoof||metal.some(m=>m!==0)||tri>40000||fs.statSync(path).size>500000)throw Error('export geometry/budget');records.push({id,sha256:crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex'),triangles:tri,bytes:fs.statSync(path).size,min,max,downwardRoofFaces:downRoof,metallicFactors:metal});}
const meshes:T.Mesh[]=[];const add:BuildingTools['add']=(g,c,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);const mesh=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.name=g.name;mesh.userData.colour=c;mesh.updateMatrixWorld();meshes.push(mesh);};const unused=()=>{throw Error('unused')};const b={add,box:unused,prism:unused,hip:unused,gableRoof:unused,window:unused,clock:unused,sign:unused};buildMelkweg(0,0,b);buildRabozaalCompanion(0,0,b);
const inside=(p:number[],r:number[][])=>{let yes=false;for(let i=0,j=r.length-1;i<r.length;j=i++)if((r[i][1]>p[1])!==(r[j][1]>p[1])&&p[0]<(r[j][0]-r[i][0])*(p[1]-r[i][1])/(r[j][1]-r[i][1])+r[i][0])yes=!yes;return yes;};const inParts=(p:number[],parts:{ring:number[][];holes:number[][][]}[])=>parts.some(q=>inside(p,q.ring)&&!q.holes.some(h=>inside(p,h)));
const air=[];for(let x=18;x<52;x+=2)for(let z=-12;z<40;z+=2){const p=[x,z];if(!inParts(p,coupled.upperParts)||inParts(p,[...coupled.lowerParts,...coupled.insetCores])||inside(p,footprint.exactBagRing))continue;const ray=new T.Raycaster(new T.Vector3(x,.5,z),new T.Vector3(0,1,0),0,13.8);const hit=ray.intersectObjects(meshes,false)[0];air.push({point:p,empty:!hit,first:hit?.object.name??null,hitY:hit?.point.y??null});}fs.mkdirSync('artifacts/melkweg-coupled',{recursive:true});fs.writeFileSync('artifacts/melkweg-coupled/air-all-samples.json',JSON.stringify(air,null,2));const edgeDistance=(p:number[],r:number[][])=>Math.min(...r.map((a,i)=>{const b=r[(i+1)%r.length],dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dz)/(dx*dx+dz*dz)));return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dz);}));const facadeEdgeSamples=air.filter(a=>Math.min(...coupled.insetCores.map(c=>edgeDistance(a.point,c.ring)))<.3);const expected8mCorridor=air.filter(a=>(inParts(a.point,coupled.corridorParts)||Math.min(...coupled.corridorParts.map(c=>edgeDistance(a.point,c.ring)))<.1)&&a.first?.startsWith('shared-blue-corridor')&&Math.abs((a.hitY??-1)-8)<.02);const wallFailures=air.filter(a=>!facadeEdgeSamples.includes(a)&&!expected8mCorridor.includes(a)&&!a.empty);if(air.length<5||wallFailures.length)throw Error('cantilever solid wall obstruction');
const exposed=[];for(const mesh of meshes.filter(m=>m.name.includes('modern-')&&m.name.endsWith('-glazing'))){const bb=new T.Box3().setFromObject(mesh),center=bb.getCenter(new T.Vector3());let normal=new T.Vector3(0,0,1);const flat=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry;const pos=flat.getAttribute('position');let found=false,bestArea=0;for(let i=0;i<pos.count;i+=3){const a=new T.Vector3().fromBufferAttribute(pos,i),b=new T.Vector3().fromBufferAttribute(pos,i+1),c=new T.Vector3().fromBufferAttribute(pos,i+2),cross=b.sub(a).cross(c.sub(a)),area=cross.length(),n=cross.normalize();if(Math.abs(n.y)<.1&&area>bestArea){normal=n;found=true;bestArea=area;}}if(!found)continue;const tangent=new T.Vector3(0,1,0).cross(normal);const tp=Array.from({length:pos.count},(_,i)=>new T.Vector3().fromBufferAttribute(pos,i).dot(tangent));const quarter=(Math.max(...tp)-Math.min(...tp))*.25;const hits=[-quarter,quarter].flatMap(u=>[-1,1].map(s=>new T.Raycaster(center.clone().addScaledVector(tangent,u).addScaledVector(normal,s*.5),normal.clone().multiplyScalar(-s),0,.6).intersectObjects(meshes,false)[0]));const visible=hits.some(h=>h?.object===mesh);exposed.push({name:mesh.name,center:center.toArray(),visible,firstHits:hits.map(h=>h?.object.name??null)});}fs.writeFileSync('artifacts/melkweg-coupled/pane-all-samples.json',JSON.stringify(exposed,null,2));if(exposed.some(p=>!p.visible))throw Error('buried modern pane');
const theater=specs.find(s=>s.id==='stadsschouwburg')!,a=footprint.anchorLngLat,st=theater.surveyed.anchor,world=new T.Matrix4().makeRotationY((90-theater.footprint.headingDegrees)*Math.PI/180);world.setPosition((st[0]-a[0])*111320*Math.cos(a[1]*Math.PI/180),0,(a[1]-st[1])*111320);
const historicAdd:BuildingTools['add']=(g,c,x=0,y=0,z=0,angle=0)=>{g.rotateY(angle);g.translate(x,y,z);g.applyMatrix4(world);g.name='historic-'+c;add(g,c);};buildIndustrialTheaterCoupledLandmark('stadsschouwburg',theater.footprint.lengthMetres,theater.footprint.widthMetres,legacyTools(historicAdd));
const focalEdge=footprint.modernHall.facadeEdges.find(e=>e.id==='modern-canalside')!,dx=focalEdge.b[0]-focalEdge.a[0],dz=focalEdge.b[1]-focalEdge.a[1],outward=new T.Vector3(-dz,0,dx).normalize(),tangent=new T.Vector3(dx,0,dz).normalize();const contextPanes=[];
for(const m of meshes.filter(m=>m.name==='modern-canalside-glazing')){const bb=new T.Box3().setFromObject(m),center=bb.getCenter(new T.Vector3()),flat=m.geometry.index?m.geometry.toNonIndexed():m.geometry,p=flat.getAttribute('position'),uu=Array.from({length:p.count},(_,i)=>new T.Vector3().fromBufferAttribute(p,i).dot(tangent)),quarter=(Math.max(...uu)-Math.min(...uu))*.25;
 for(const u of[-quarter,quarter]){const target=center.clone().addScaledVector(tangent,u),hit=new T.Raycaster(target.clone().addScaledVector(outward,12),outward.clone().negate(),0,12.2).intersectObjects(meshes,false)[0];contextPanes.push({target:target.toArray(),visible:hit?.object===m,first:hit?.object.name??null});}}
const foyerPart=coupled.lowerParts.find(p=>p.id==='rabozaal-low-connector-1-0')!,A=foyerPart.ring[5],B=foyerPart.ring[6],dX=B[0]-A[0],dZ=B[1]-A[1],foyerOut=new T.Vector3(-dZ,0,dX).normalize(),foyerT=new T.Vector3(dX,0,dZ).normalize();
for(const m of meshes.filter(m=>m.name==='rabozaal-outer-foyer-5-glazing')){const center=new T.Box3().setFromObject(m).getCenter(new T.Vector3());for(const u of[-.25,.25]){const target=center.clone().addScaledVector(foyerT,u),hit=new T.Raycaster(target.clone().addScaledVector(foyerOut,12),foyerOut.clone().negate(),0,12.2).intersectObjects(meshes,false)[0];contextPanes.push({target:target.toArray(),visible:hit?.object===m,first:hit?.object.name??null});}}
fs.writeFileSync('artifacts/melkweg-coupled/triple-source-side-first-hits.json',JSON.stringify(contextPanes,null,2));if(contextPanes.some(p=>!p.visible))throw Error('source-facing pane hidden in coupled historic context');

const result={scope:'Export/CPU check only; native city, independent review, POI pointer/route/performance pending',exports:records,cantileverAir:air,facadeEdgeSamples,expected8mCorridor,sourceFacingContextSamples:contextPanes.length,sourceFacingContextFailures:contextPanes.filter(p=>!p.visible),exposedModernPanes:exposed.length,buriedModernPanes:exposed.filter(p=>!p.visible),legacyFailurePreserved:'a55b133... and unaccepted56c06... remain recorded in source archive'};fs.mkdirSync('artifacts/melkweg-coupled',{recursive:true});fs.writeFileSync('artifacts/melkweg-coupled/geometry-check.json',JSON.stringify(result,null,2));console.log(JSON.stringify({exports:records,cantileverAir:air.length,exposedModernPanes:exposed.length}));
