import fs from 'node:fs';import * as T from 'three';import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {meshopt,weld,dedup,prune} from '@gltf-transform/functions';import {MeshoptEncoder} from 'meshoptimizer';import {buildKeizersgrachtkerk} from './landmarks/keizersgrachtkerk-builder';import source from './landmarks/keizersgrachtkerk-footprints.json';import spec from './landmarks/keizersgrachtkerk-spec.json';
await MeshoptEncoder.ready;const scene=new T.Scene(),parts:{g:T.BufferGeometry,c:string}[]=[],palette={brick:'#986f5d',stone:'#d5cfbd',slate:'#707e86',glass:'#526362',white:'#e5dfcc',bronze:'#67583d',dark:'#303b43',frame:'#9daaa8'};
const add=(g:T.BufferGeometry,c:string,x=0,y=0,z=0,a=0)=>{g.rotateY(a);g.translate(x,y,z);g.computeVertexNormals();parts.push({g,c});scene.add(new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide})));};buildKeizersgrachtkerk(15,29,{add} as any);scene.updateMatrixWorld(true);
const bounds=new T.Box3().setFromObject(scene);if(![...bounds.min,...bounds.max].every(Number.isFinite))throw Error('Nonfinite geometry');let roofFaces=0;for(const {g} of parts){if(g.userData.role!=='roof')continue;const flat=g.index?g.toNonIndexed():g,p=flat.getAttribute('position');for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),q=new T.Vector3().fromBufferAttribute(p,i+1),r=new T.Vector3().fromBufferAttribute(p,i+2);if(q.sub(a).cross(r.sub(a)).y<=0)throw Error('Downward roof');roofFaces++;}}
const {basisAcross:u,basisOut:n,frontMidNative:m}=source,point=(x:number,y:number,z:number)=>new T.Vector3(m[0]+u[0]*x+n[0]*z,y,m[1]+u[1]*x+n[1]*z);let probes=0;
for(let i=-3;i<=3;i++)for(const fraction of [-.32,.32])for(const y of [8.48,9.98]){const ray=new T.Raycaster(point(i*1.17+fraction, y,3),new T.Vector3(-n[0],0,-n[1]));const hits=ray.intersectObjects(scene.children);if(!hits.length||parts[scene.children.indexOf(hits[0].object)].c!=='glass')throw Error(`Gallery pane buried ${i}/${fraction}/${y}`);probes++;}
for(const [x,y] of [[0,14.84],[-.20,14.7],[.20,14.7],[.42,2.07]]){const ray=new T.Raycaster(point(x,y,3),new T.Vector3(-n[0],0,-n[1]));const hit=ray.intersectObjects(scene.children)[0];if(!hit||parts[scene.children.indexOf(hit.object)].c!=='glass')throw Error(`Rose/entrance pane buried ${x}/${y}`);probes++;}
// Reference-led regression points: curved portal shoulders were absent in the
// failed triangular head, and wheel tracery covered the tower opening centres.
let sourceAssemblyGlassProbes=0;for(const [x,y] of [[-1.90,4.2],[1.90,4.2],[-1.7,4.8],[1.7,4.8],[-5.65,17.02],[5.65,17.02],[-5.83,17.02],[5.83,17.02],[-5.65,17.2],[5.65,17.2]]){const hit=new T.Raycaster(point(x,y,3),new T.Vector3(-n[0],0,-n[1])).intersectObjects(scene.children)[0];if(!hit||parts[scene.children.indexOf(hit.object)].c!=='glass')throw Error(`Source portal/sixfoil opening obscured ${x}/${y}`);sourceAssemblyGlassProbes++;}
// Broad footprint and dense front-junction grid catch floor-reaching roof gaps.
let roofCoverageSamples=0;const roofCoverageFailures:{x:number,z:number,y:number|null}[]=[];
function roofProbe(x:number,z:number){const hit=new T.Raycaster(point(x,35,z),new T.Vector3(0,-1,0)).intersectObjects(scene.children)[0];roofCoverageSamples++;if(!hit||hit.point.y<1)roofCoverageFailures.push({x,z,y:hit?.point.y??null});}
for(let x=-7;x<=7;x+=.5)for(let z=-28;z<=-.3;z+=.5)roofProbe(x,z);
for(let x=-4.8;x<4.8;x+=.1)for(let z=-3.5;z<-.05;z+=.1)roofProbe(x,z);
if(roofCoverageFailures.length)throw Error(`Roof grid reaches floor: ${JSON.stringify(roofCoverageFailures.slice(0,8))}`);
const {Document}=await import('@gltf-transform/core'),doc=new Document(),buf=doc.createBuffer(),mesh=doc.createMesh('keizersgrachtkerk');doc.createScene().addChild(doc.createNode().setMesh(mesh));for(const c of new Set(parts.map(p=>p.c))){const gs=parts.filter(p=>p.c===c).map(p=>p.g.index?p.g.toNonIndexed():p.g),rgb=new T.Color(palette[c as keyof typeof palette]);const mat=doc.createMaterial(c).setBaseColorFactor([rgb.r,rgb.g,rgb.b,1]).setRoughnessFactor(.9).setDoubleSided(true);mesh.addPrimitive(doc.createPrimitive().setAttribute('POSITION',doc.createAccessor().setType('VEC3').setArray(Float32Array.from(gs.flatMap(g=>Array.from(g.getAttribute('position').array)))).setBuffer(buf)).setAttribute('NORMAL',doc.createAccessor().setType('VEC3').setArray(Float32Array.from(gs.flatMap(g=>Array.from(g.getAttribute('normal').array)))).setBuffer(buf)).setMaterial(mat));}
await doc.transform(weld(),dedup(),prune(),meshopt({encoder:MeshoptEncoder,level:'medium',quantizePosition:16}));fs.mkdirSync('artifacts/landmark-next-batch',{recursive:true});await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder}).write('artifacts/landmark-next-batch/keizersgrachtkerk.glb',doc);const report={bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},roofFaces,roofCoverageSamples,roofCoverageFailures,sourceAssemblyGlassProbes,firstHitGlassProbes:probes,triangles:doc.getRoot().listMeshes().flatMap(m=>m.listPrimitives()).reduce((s,p)=>s+(p.getIndices()?.getCount()??p.getAttribute('POSITION')!.getCount())/3,0),bytes:fs.statSync('artifacts/landmark-next-batch/keizersgrachtkerk.glb').size,scope:'CPU geometry/export preflight only; gallery/game acceptance pending'};if(report.triangles>40000||report.bytes>500000)throw Error('Budget');fs.writeFileSync('artifacts/keizersgrachtkerk/geometry-report.json',JSON.stringify(report,null,2));console.log(report);
