import * as T from 'three';import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {MeshoptDecoder} from 'meshoptimizer';import fs from 'node:fs';import crypto from 'node:crypto';import source from './landmarks/lekstraat-synagoge-footprints.json';
await MeshoptDecoder.ready;const file='artifacts/lekstraat-synagoge/lekstraat-synagoge.glb',doc=await new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}).read(file),meshes:T.Mesh[]=[],bounds=new T.Box3();let triangles=0,roofUp=0,roofDown=0;const roofFirstHitObstructions:any[]=[];
for(const node of doc.getRoot().listNodes())for(const p of node.getMesh()?.listPrimitives()??[]){const at=p.getAttribute('POSITION')!,positions:number[]=[];for(let i=0;i<at.getCount();i++)positions.push(...at.getElement(i,[]));const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));const ids=p.getIndices()?.getArray();if(ids)g.setIndex(Array.from(ids));g.computeVertexNormals();const mat=new T.MeshBasicMaterial({side:T.DoubleSide});const mesh=new T.Mesh(g,mat);mesh.name=p.getMaterial()?.getName()??'';mesh.applyMatrix4(new T.Matrix4().fromArray(node.getWorldMatrix()));mesh.updateMatrixWorld(true);meshes.push(mesh);bounds.expandByObject(mesh);const flat=g.index?g.toNonIndexed():g,v=flat.getAttribute('position');triangles+=v.count/3;for(let i=0;i<v.count;i+=3){const a=new T.Vector3().fromBufferAttribute(v,i).applyMatrix4(mesh.matrixWorld),b=new T.Vector3().fromBufferAttribute(v,i+1).applyMatrix4(mesh.matrixWorld),c=new T.Vector3().fromBufferAttribute(v,i+2).applyMatrix4(mesh.matrixWorld),n=b.sub(a).cross(c.sub(a));if(![a.x,a.y,a.z,b.x,b.y,b.z,c.x,c.y,c.z].every(Number.isFinite))throw Error('nonfinite');if(mesh.name==='slate'){if(n.y>0)roofUp+=n.y/2;else roofDown-=n.y/2;}}}
const failures:any[]=[],ray=(origin:T.Vector3,direction:T.Vector3)=>new T.Raycaster(origin,direction,0,50).intersectObjects(meshes,false)[0];const o=source.outline[0];
function face(a:number[],z:number[],outside:number){const len=Math.hypot(z[0]-a[0],z[1]-a[1]),ux=(z[0]-a[0])/len,uz=(z[1]-a[1])/len,nx=-uz*outside,nz=ux*outside;return{len,probe:(u:number,y:number,id:string)=>{const hit=ray(new T.Vector3(a[0]+ux*u+nx*.40,y,a[1]+uz*u+nz*.40),new T.Vector3(-nx,0,-nz));if(hit?.object.name!=='glass')failures.push({id,y,u,first:hit?.object.name,distance:hit?.distance});}};}
const front=face(o[11],o[10],-1),side=face(o[11],o[12],1);let glassProbes=0;
function pane(f:ReturnType<typeof face>,center:number,y:number,w:number,h:number,id:string){for(const frac of [.18,.38,.62,.82])for(const fy of [.22,.72]){f.probe(center+(frac-.5)*w,y+fy*h,id);glassProbes++;}}
for(const t of [.10,.30,.50,.70,.90])pane(front,front.len*t,2.35,1.45,1.45,'front');for(let i=0;i<7;i++){pane(side,side.len*(i+.5)/7,2.35,1.45,1.45,`side-low-${i}`);pane(side,side.len*(i+.5)/7,10.10,2.50,3.85,`side-high-${i}`);}
const ne=face(o[10],source.roofs.find(r=>r.index===71)!.rings[0][1],-1);for(let i=0;i<7;i++)pane(ne,ne.len*(i+.5)/7,10.10,2.50,3.85,`ne-high-${i}`);
const wf=face(o[9],o[8],-1);for(const t of [.22,.53])for(const y of [3.2,6.2])pane(wf,wf.len*t,y,3.55,1.85,'wingfront');
const residence=source.roofs.find(r=>r.index===75)!.rings[0],rf=face(residence[6],residence[3],-1);for(const t of [.14,.30,.80,.94])pane(rf,rf.len*t,9.6,1.32,1.8,'residence-front');
let roofProbes=0;for(const r of source.roofs){if([66,67,73].includes(r.index))continue;const s=new T.Shape(r.rings[0].map(p=>new T.Vector2(p[0],p[1]))),g=new T.ShapeGeometry(s),v=g.getAttribute('position'),ix=g.index!;for(let i=0;i<ix.count;i+=3){const a=new T.Vector2(v.getX(ix.getX(i)),v.getY(ix.getX(i))),b=new T.Vector2(v.getX(ix.getX(i+1)),v.getY(ix.getX(i+1))),c=new T.Vector2(v.getX(ix.getX(i+2)),v.getY(ix.getX(i+2)));if(Math.abs((b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x))<.1)continue;const p=a.add(b).add(c).multiplyScalar(1/3),expected=r.index===69?14.8677:r.index===76?8.9565:r.medianHeight,hit=ray(new T.Vector3(p.x,18,p.y),new T.Vector3(0,-1,0));roofProbes++;if(!hit||Math.abs(hit.point.y-expected)>.20){const slateHit=new T.Raycaster(new T.Vector3(p.x,18,p.y),new T.Vector3(0,-1,0),0,50).intersectObjects(meshes.filter(m=>m.name==='slate'),false)[0];if(slateHit&&Math.abs(slateHit.point.y-expected)<.20)roofFirstHitObstructions.push({roof:r.index,expected,first:hit?.object.name,actual:hit?.point.y,x:p.x,z:p.y,note:r.index===68?'Source67curvedbay intentionally occupies this terrace part; verify native':'Upper residence facade trim near roofedge; verify native'});else failures.push({roof:r.index,expected,actual:hit?.point.y,slate:slateHit?.point.y});}}}
// Street gardens outside surveyed silhouette must remain sky-open.
for(const t of [.25,.65]){const a=o[11],z=o[10],dx=z[0]-a[0],dz=z[1]-a[1],len=Math.hypot(dx,dz),p=[a[0]+dx*t+dz/len*2,a[1]+dz*t-dx/len*2];const h=ray(new T.Vector3(p[0],18,p[1]),new T.Vector3(0,-1,0));if(h)failures.push({garden:p,first:h.object.name});}
const report={input:file,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),bytes:fs.statSync(file).size,triangles,bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},roofUpArea:roofUp,roofDownArea:roofDown,glassProbes,roofProbes,roofFirstHitObstructions,failures,scope:'Decoded mesh/source surface checks only; nativeGPU/gallery/game/neighbor/route/pin/card/performance pending'};fs.writeFileSync('artifacts/lekstraat-synagoge/geometry-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(failures.length||roofDown>.001||triangles>40000||report.bytes>500000)process.exitCode=1;
