import assert from 'node:assert/strict';
import { boundFacadeSource, fitFacadeFeature, type FacadeFeature } from '../src/canalRecall/facadeDescription.js';
import { sourceToRenderHeight, napToSourceHeight, LEGACY_BLOCK_DATUM } from '../src/canalRecall/appearanceHeight.js';
import { openingAccuracy, fidelityGate } from './city-appearance/fidelity/gates.js';
import { facadeRecipePatches, compileFacadePatches } from '../src/canalRecall/cityAppearanceFacadeRecipes.js';
import { createCityAppearanceThreeAdapter } from '../src/canalRecall/cityAppearanceThree.js';
import { deduplicateMachineSigns, planMachineSignPlacements } from '../src/canalRecall/cityAppearanceMachineSigns.js';
import * as THREE from 'three';
import {owner,image,opening,source,record} from './city-appearance/fidelity/synthetic-fixture.js';
const bound=boundFacadeSource(record,owner,0,'ground')!;assert.ok(bound);
assert.deepEqual({...fitFacadeFeature(opening,bound,record)}, {...opening,t:1.5,y:1.75,width:1,height:2.5,uncertaintyM:.05});
const render=()=>facadeRecipePatches(owner,owner.geometry.building.surfaces[0],0,[record],[owner]);
assert.ok(render().some(p=>p.featureKind==='observed-door'));
const initialPatches=render();
const observedGroundYs=initialPatches.filter(p=>p.featureKind==='observed-door').flatMap(p=>p.triangles.filter((_,index)=>index%3===1));
const proceduralUpperYs=initialPatches.filter(p=>p.featureKind==='window-prior').flatMap(p=>p.triangles.filter((_,index)=>index%3===1));
assert.ok(observedGroundYs.length>0&&proceduralUpperYs.length>0,'fixture must emit both the observed lower tier and the upper prior');
const observedGroundTop=Math.max(...observedGroundYs);
const proceduralUpperBottom=Math.min(...proceduralUpperYs);
assert.ok(proceduralUpperBottom>observedGroundTop,'registered ground owns its observed lower region; a missing full tier may retain only an upper procedural prior');
for(const state of ['unknown','absent','retracted','extended']){
 source.features=[{id:'awning',bounds:[100,20,600,60],kind:'awning',state,disposition:'machine-observed-unreviewed'} as FacadeFeature];
 const patches=render();if(state==='unknown'||state==='absent')assert.equal(patches.filter(p=>p.featureKind==='observed-awning').length,0);else assert.ok(patches.some(p=>p.featureKind==='observed-awning'));
 if(state==='extended')assert.ok(patches.filter(p=>p.featureKind==='observed-awning').flatMap(p=>p.triangles.filter((_,i)=>i%3===2)).some(z=>Math.abs(z)>.3),'extended fabric projects away from wall');
 if(state==='retracted')assert.ok(patches.filter(p=>p.featureKind==='observed-awning').flatMap(p=>p.triangles.filter((_,i)=>i%3===2)).every(z=>Math.abs(z)<=.1),'rolled fabric stays on wall');
}
source.features=[opening];record.featureRevocations={door:true};assert.equal(render().filter(p=>p.featureKind==='observed-door').length,0);assert.ok(render().filter(p=>p.featureKind==='window-prior').flatMap(p=>p.triangles.filter((_,i)=>i%3===1)).every(y=>y>3.5));delete record.featureRevocations;
record.featureRevocations={door:true};const revoked=compileFacadePatches(owner,owner.geometry.building.surfaces[0],0,[record],[owner],{procedural:true,contextual:true});assert.ok(revoked.every(p=>!p.featureKind.startsWith('contextual-')&&p.featureKind!=='observed-door'),'revocation must not resurrect a contextual lower opening grid');delete record.featureRevocations;
record.review={facadeFeatures:{door:{disposition:'human-reviewed',head:'rectangular'}}};assert.ok(render().some(p=>p.styleSource==='human-reviewed'));assert.ok(render().filter(p=>p.featureKind==='observed-door').every(p=>p.styleSource==='human-reviewed'||(p.styleSource==='procedural-prior-not-measured'&&p.heuristics?.length)), 'inferred door furniture must keep its procedural provenance');delete record.review;
source.captureDate='2024-01-01';assert.equal(boundFacadeSource(record,owner,0,'ground'),null);source.captureDate=image.date;
source.registration.uncertaintyM=.5;assert.equal(boundFacadeSource(record,owner,0,'ground'),null);source.registration.uncertaintyM=.05;
assert.equal(sourceToRenderHeight(2,LEGACY_BLOCK_DATUM,.65),2);
assert.equal(sourceToRenderHeight(napToSourceHeight(1.12,LEGACY_BLOCK_DATUM),LEGACY_BLOCK_DATUM,1.12),0);
assert.throws(()=>sourceToRenderHeight(0,'unknown'));
source.features=[{id:'sign',kind:'fascia',text:'Example shop',bounds:[100,20,600,60],disposition:'machine-observed-unreviewed',colour:'#123456'}];
const signs=planMachineSignPlacements(owner,owner.geometry.building.surfaces[0],0,[record],[owner]);assert.equal(signs.length,1);assert.equal(signs[0].text,'Example shop');
assert.equal(deduplicateMachineSigns([...signs,...signs],[record]).length,1);
assert.equal(deduplicateMachineSigns([{...signs[0],physicalSignId:'one'},{...signs[0],physicalSignId:'two'}],[record]).length,2,'distinct source-bound physical signs may repeat');
source.features=[opening];record.derivationKey='fixture';owner.observations=[{id:record.id,buildingId:owner.id,geometryRevision:owner.geometryRevision,evidenceKey:record.evidenceKey,payload:record}];
const scene=new THREE.Scene(),adapter=createCityAppearanceThreeAdapter({parent:scene,targetOriginRD:{x:0,y:0}});
const resource=adapter([owner]);resource.setLod(owner.id,'detail');resource.flush();assert.equal(resource.stats.doors,1,'registered details default on without procedural priors');
const first=resource.stats;resource.dispose();assert.equal(scene.children.length,0);
const restored=adapter([owner]);restored.setLod(owner.id,'detail');restored.flush();assert.deepEqual(restored.stats,first,'deterministic rehydration');restored.dispose();
const ref=[{id:'a',kind:'door' as const,head:'rounded',bounds:[0,0,1,2] as [number,number,number,number],visible:true}];
assert.deepEqual(openingAccuracy(ref,[...ref,...ref]),{tp:1,fp:1,fn:0,precision:.5,recall:1});
assert.equal(openingAccuracy(ref,[{...ref[0],head:'rectangular'}]).tp,0);
assert.equal(fidelityGate({developmentResolved:false,unseenExclusionsResolved:false,referenceCount:0,accuracy:openingAccuracy([],[]),developmentFailures:[],awningFailures:[],materialFailures:[],contacts:[],registrationFailures:0,abstentions:0,visualInspectionComplete:false,resourceChecksPassed:true}).pass,false);
console.log('Facade fidelity: dated bindings, projection abstention, curved doors, awning states, revocation, human precedence, height conversions and non-vacuous gates passed.');
