import assert from 'node:assert/strict';
import fs from 'node:fs';
import {wallVerticalExtent} from './da-costa-block/neighbourhood-core.ts';
const wall={localStart:[0,0],localEnd:[10,0]};
const surface=(type:string,ring:number[][])=>({type,rings:[ring]});
const face=surface('wall',[[0,0,0],[10,0,0],[10,10,0],[0,10,0]]);
const distant=surface('wall',[[20,0,20],[30,0,20],[30,30,20],[20,30,20]]);
const building=(surfaces:any[])=>({groundNAP:0,height:30,surfaces});
const options={sceneDatumNAP:0};
assert.equal(wallVerticalExtent(building([face,distant]),wall,options).topNAP,10,'annex does not inherit distant tower height');
const pitched=surface('roof',[[0,10,0],[10,10,0],[10,16,5],[0,16,5]]);
assert.equal(wallVerticalExtent(building([face,distant,pitched]),wall,options).topNAP,16,'adjacent roof ridge remains inside vertical extent');
const touch=surface('roof',[[0,10,0],[-10,30,10],[-20,30,10]]);
assert.equal(wallVerticalExtent(building([face,distant,touch]),wall,options).topNAP,10,'coincidental roof-corner contact does not import other wing');
const short=surface('wall',[[0,0,0],[5,0,0],[5,10,0],[0,10,0]]);
assert.equal(wallVerticalExtent(building([short,distant]),wall,options).source,'building-maximum-fallback','partial wall match falls back conservatively');
const slope=surface('wall',[[0,0,0],[20,0,0],[20,20,0],[0,10,0]]);
assert.equal(wallVerticalExtent(building([slope,distant]),wall,options).topNAP,15,'clip sloped height to frontage endpoints');
assert.equal(wallVerticalExtent(building([face]),{localStart:[0,2],localEnd:[10,2]},options).source,'building-maximum-fallback','offset wall not matched');
assert.equal(wallVerticalExtent(building([face]),{localStart:[0,0],localEnd:[0,0]},options).source,'building-maximum-fallback','degenerate wall handled');
const split=[surface('wall',[[0,0,0],[5,0,0],[5,10,0],[0,10,0]]),surface('wall',[[5,0,0],[10,0,0],[10,10,0],[5,10,0]])];
assert.equal(wallVerticalExtent(building(split),wall,options).coverageFraction,1,'split faces cover whole wall');
const b=JSON.parse(fs.readFileSync('public/data/da-costa-block/block.json','utf8')).buildings.find((b:any)=>b.id==='0363100012237064');
const m=JSON.parse(fs.readFileSync('.cache/da-costa-neighbourhood/manifest.json','utf8'));
const r=m.records.find((r:any)=>r.id==='0363100012237064_e_17b9vzf');
const result=wallVerticalExtent(b,r);
assert.equal(result.source,'matched-wall-and-adjacent-roof');
assert.ok(result.coverageFraction>.95&&result.topNAP<16&&result.overshootM>16,'Amsta low annex is tightly supported by wall geometry');
console.log('Height extent checks passed; Amsta regression:',result);
