import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import * as THREE from 'three';import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';import maplibre from 'maplibre-gl';
import {placementFor} from '../src/canalRecall/landmarks/signaturePlacement';import {rdProjectedSurvey} from '../src/canalRecall/landmarks/rdProjectionBasis';import {rdToLngLat} from '../src/canalRecall/facade/rdNew';
import {planBuildingRenderChunks} from '../src/canalRecall/buildingLibraryRenderChunks';import {tileBounds} from '../src/canalRecall/slippyTiles';
import {batchParts,makeBatchMesh,pickOwner,stateKey,type Part} from '../src/canalRecall/buildingLibraryTileBatching';
const argument=(name:string)=>{const index=process.argv.indexOf(name);if(index<0||!process.argv[index+1]||process.argv[index+1].startsWith('--'))throw new Error(name+' is required');return process.argv[index+1];};
const out=argument('--output-root'),base=argument('--input-root');fs.mkdirSync(out,{recursive:true});const read=(p:string)=>JSON.parse(fs.readFileSync(p,'utf8'));
(globalThis as any).window={CanalRecallThree:{THREE,GLTFLoader},CanalRecallSignatureLandmarks:{placementFor},location:{href:'http://fixture.local/'}};
const Consumer=new Function(fs.readFileSync('public/canal-drive/js/signature-landmarks-source.js','utf8').replace('export class SignatureLandmarks','class SignatureLandmarks')+';return SignatureLandmarks;')();
const owner=Object.create(Consumer.prototype);Object.assign(owner,{maplibregl:maplibre,_entries:[],shown:new Set(),_applySuppression(){},onModelShown(){}});
const sourceManifest=read(base+'/manifest.json');const models=sourceManifest.models.filter((m:any)=>!m.synthetic&&m.sourceRDFrame).sort((a:any,b:any)=>a.id.localeCompare(b.id));assert.ok(models.length>0,'No real assets with source RD frame');
const mean=models.reduce((p:number[],m:any)=>p.map((v,i)=>v+m.sourceRDFrame.anchorRD[i]/models.length),[0,0]);const origin=maplibre.MercatorCoordinate.fromLngLat(rdToLngLat({x:mean[0],y:mean[1]})),units=origin.meterInMercatorCoordinateUnits();
const records=[];let sourceBytes=0,sourceTriangles=0,sourceDraws=0;
for(const model of models){
 const recipe=read(base+'/'+model.id+'.recipe.json'),frame=model.sourceRDFrame;assert.equal(recipe.buildingId,model.buildingId);assert.equal(recipe.geometryRevision,model.geometryRevision);assert.deepEqual(recipe.placement.sourceRDFrame,frame);const bytes=fs.readFileSync(base+'/'+model.id+'.glb');sourceBytes+=bytes.byteLength;sourceTriangles+=model.triangles;sourceDraws+=model.drawCalls;
 const hash=crypto.createHash('sha256').update(bytes).digest('hex');
 const gltf=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');owner._add(new THREE.Scene(),{id:model.id,name:model.name,groundAltitudeMetres:0,facingOffsetDegrees:0,surveyed:{northOffsetDegrees:model.xAxisBearingDegrees-90,...rdProjectedSurvey(frame,maplibre.MercatorCoordinate)}},gltf.scene,{triggerRepaint(){}});const entry=owner._entries.at(-1);entry.group.updateMatrixWorld(true);
 const geographic=recipe.footprint.map((p:number[])=>rdToLngLat({x:frame.anchorRD[0]+p[0]*frame.xAxisRD[0]+p[1]*frame.yAxisRD[0],y:frame.anchorRD[1]+p[0]*frame.xAxisRD[1]+p[1]*frame.yAxisRD[1]}));geographic.push(geographic[0]);
 records.push({id:model.buildingId,geometryRevision:model.geometryRevision,footprint:{type:'Polygon',coordinates:[geographic]},geometry:{model,entry,sourceModelHash:hash}});
}
const renderZoom=process.argv.includes('--render-zoom')?Number(argument('--render-zoom')):14;const planned=planBuildingRenderChunks(records,renderZoom);const report:any={distinctRealOwners:models.length,canonicalZoom:planned.canonicalZoom,renderZoom:planned.renderZoom,canonicalTileCount:planned.canonicalTileCount,renderChunkCount:planned.tiles.length,skipped:sourceManifest.models.filter((m:any)=>m.synthetic||!m.sourceRDFrame).map((m:any)=>({id:m.id,reason:m.synthetic?'synthetic':'source RD frame unavailable'})),sourceBytes,sourceTriangles,sourceMaterialDraws:sourceDraws,tiles:[],growth:[],maxPositionErrorM:0,maxNormalError:0,maxLinearColourError:0,geometryGroupsForPicking:0,maxIndependentSourceNormalError:0,maxIndependentNormalAngleDegrees:0,reflectedSourceParts:0,independentNormalComparisons:0};
const manifest:any={version:1,scope:'Batched delivery study; source reconstruction/acceptance unchanged',sourceScope:sourceManifest.scope,coordinateSystem:'Mercator-local east/south/up metres; horizontal RD projection basis, vertical independent',binaryEndianness:'little',ownersCount:models.length,canonicalZoom:planned.canonicalZoom,renderZoom:planned.renderZoom,originMercator:[origin.x,origin.y,origin.z],units,owners:records.map(r=>({...r.geometry.model,sourceModelHash:r.geometry.sourceModelHash,sourceModelUrl:'/'+base+'/'+r.geometry.model.id+'.glb',canonicalOwnershipKey:planned.canonicalOwnerTiles.get(r.id),consumerTransform:r.geometry.entry.transform.toArray(),groundShift:r.geometry.entry.group.children[0].position.y})),tiles:[]};
const globalOriginalBounds=new THREE.Box3(),globalBatchBounds=new THREE.Box3();let binaryBytes=0,totalTriangles=0,batchDraws=0,rangeTriangles=0;
for(const tile of planned.tiles.filter(t=>t.owners.length)){
 const [z,x,y]=tile.key.split('/').map(Number),bounds=tileBounds({z,x,y});const centre=maplibre.MercatorCoordinate.fromLngLat([(bounds[0]+bounds[2])/2,(bounds[1]+bounds[3])/2]);
 const offset=[(centre.x-origin.x)/units,(centre.y-origin.y)/units,(centre.z-origin.z)/units];const parts:Part[]=[];
 const tileLocal=new THREE.Matrix4().makeScale(1/units,1/units,1/units).multiply(new THREE.Matrix4().makeTranslation(-centre.x,-centre.y,-centre.z));
 for(const r of tile.owners){const g=r.geometry;g.entry.group.traverse((mesh:any)=>{if(mesh.isMesh){const matrix=tileLocal.clone().multiply(g.entry.transform).multiply(mesh.matrixWorld);parts.push({mesh,matrix,owner:{id:g.model.id,buildingId:r.id,geometryRevision:r.geometryRevision,sourceModelHash:g.sourceModelHash}});const attr=mesh.geometry.attributes.position;for(let i=0;i<attr.count;i++)globalOriginalBounds.expandByPoint(new THREE.Vector3().fromBufferAttribute(attr,i).applyMatrix4(matrix).add(new THREE.Vector3(...offset)));}});}
 report.reflectedSourceParts+=parts.filter(p=>p.matrix.determinant()<0).length;
 const compiled=batchParts(parts);totalTriangles+=compiled.triangles;batchDraws+=compiled.batches.length;report.maxPositionErrorM=Math.max(report.maxPositionErrorM,compiled.positionErrorM);report.maxNormalError=Math.max(report.maxNormalError,compiled.normalError);report.maxLinearColourError=Math.max(report.maxLinearColourError,compiled.colourError);
 const tileLocalBounds=new THREE.Box3();const filename='tile-'+tile.key.replaceAll('/','-')+'.bin';const chunks:Buffer[]=[];let byteOffset=0;const serialized=[];
 for(const batch of compiled.batches){const mesh=makeBatchMesh(batch);tileLocalBounds.union(mesh.geometry.boundingBox!);assert.equal(mesh.geometry.groups.length,0);const b=mesh.geometry.boundingBox!.clone().translate(new THREE.Vector3(...offset));globalBatchBounds.union(b);
  for(const range of batch.ownerRanges){
   const part=parts.find(p=>p.owner.id===range.ownerId&&p.mesh.name===range.sourceMesh)!;assert.ok(part);
   const inverseTranspose=part.matrix.clone().invert().transpose(),geo=part.mesh.geometry,order=part.matrix.determinant()<0?[0,2,1]:[0,1,2];
   for(let t=0;t<range.triangleCount;t++)for(let corner=0;corner<3;corner++){
    const sourceIndex=range.sourceIndexStart+t*3+order[corner],sourceVertex=geo.index?geo.index.getX(sourceIndex):sourceIndex;
    const normal=geo.attributes.normal,raw=new THREE.Vector4(normal.getX(sourceVertex),normal.getY(sourceVertex),normal.getZ(sourceVertex),0).applyMatrix4(inverseTranspose),expected=new THREE.Vector3(raw.x,raw.y,raw.z).normalize();
    const vertex=batch.index[(range.firstTriangle+t)*3+corner],actual=new THREE.Vector3(batch.normal[vertex*3],batch.normal[vertex*3+1],batch.normal[vertex*3+2]);
    report.maxIndependentSourceNormalError=Math.max(report.maxIndependentSourceNormalError,expected.distanceTo(actual));report.maxIndependentNormalAngleDegrees=Math.max(report.maxIndependentNormalAngleDegrees,Math.acos(Math.min(1,Math.max(-1,expected.dot(actual.clone().normalize()))))*180/Math.PI);report.independentNormalComparisons++;
   }
   assert.equal(pickOwner(mesh,range.firstTriangle)?.ownerId,range.ownerId);assert.equal(pickOwner(mesh,range.firstTriangle+range.triangleCount-1)?.buildingId,range.buildingId);rangeTriangles+=range.triangleCount;}assert.equal(pickOwner(mesh,batch.index.length/3),null);
  const attributes:any={};for(const key of ['position','normal','colour','index']){const data=batch[key];const padding=(4-byteOffset%4)%4;if(padding){chunks.push(Buffer.alloc(padding));byteOffset+=padding;}const chunk=Buffer.from(data.buffer,data.byteOffset,data.byteLength);attributes[key]={byteOffset,length:data.length,type:key==='index'?(data instanceof Uint16Array?'uint16':'uint32'):'float32'};chunks.push(chunk);byteOffset+=chunk.byteLength;}
  serialized.push({state:batch.state,attributes,ownerRanges:batch.ownerRanges,triangles:batch.index.length/3});
 }
 fs.writeFileSync(out+'/'+filename,Buffer.concat(chunks));binaryBytes+=byteOffset;manifest.tiles.push({key:tile.key,offset,bounds:tileLocalBounds.toJSON(),geometryBytes:byteOffset,triangles:compiled.triangles,materialDraws:compiled.batches.length,binaryUrl:filename,batches:serialized,owners:tile.owners.map(r=>r.geometry.model.id)});report.tiles.push({key:tile.key,owners:tile.owners.length,originalDraws:parts.length,batchDraws:compiled.batches.length,triangles:compiled.triangles,bytes:byteOffset});
}
assert.equal(totalTriangles,sourceTriangles);assert.equal(rangeTriangles,totalTriangles);assert.ok(report.maxPositionErrorM<.0001);assert.ok(report.maxNormalError<1e-6);assert.ok(report.maxLinearColourError<1e-6);
for(const count of [...new Set([1,3,5,8,models.length])].filter(n=>n<=models.length)){const selected=new Set(models.slice(0,count).map((m:any)=>m.id));let draws=0,original=0,occupied=0;for(const tile of manifest.tiles){const compatible=new Set<string>();for(const batch of tile.batches)for(const range of batch.ownerRanges)if(selected.has(range.ownerId)){compatible.add(JSON.stringify(batch.state));original++;}if(compatible.size)occupied++;draws+=compatible.size;}report.growth.push({distinctRealOwners:count,occupiedTiles:occupied,originalMeshParts:original,batchMaterialDraws:draws});}
assert.ok(report.reflectedSourceParts>0);assert.equal(report.independentNormalComparisons,sourceTriangles*3);assert.ok(report.maxIndependentSourceNormalError<1e-6);
// The first two noncolour material variants must remain distinct.
const a=new THREE.MeshStandardMaterial({color:'#aa1122',roughness:.86,metalness:0}),b=a.clone();b.color.set('#33aa11');assert.equal(stateKey(a),stateKey(b));b.metalness=.5;assert.notEqual(stateKey(a),stateKey(b));b.metalness=0;b.roughness=.5;assert.notEqual(stateKey(a),stateKey(b));b.roughness=.86;b.side=THREE.DoubleSide;assert.notEqual(stateKey(a),stateKey(b));b.transparent=true;assert.throws(()=>stateKey(b));
report.maxChunkTriangles=Math.max(0,...report.tiles.map((t:any)=>t.triangles));report.maxChunkGeometryBytes=Math.max(0,...report.tiles.map((t:any)=>t.bytes));report.batchMaterialDraws=batchDraws;report.batchTriangles=totalTriangles;report.batchGeometryBytes=binaryBytes;report.originalBounds=globalOriginalBounds.toJSON();report.batchBounds=globalBatchBounds.toJSON();report.boundDeltaM=globalOriginalBounds.min.distanceTo(globalBatchBounds.min)+globalOriginalBounds.max.distanceTo(globalBatchBounds.max);assert.ok(report.boundDeltaM<.0002);
fs.writeFileSync(out+'/tiles.json',JSON.stringify(manifest));report.batchMetadataBytes=fs.statSync(out+'/tiles.json').size;report.batchTotalBytes=binaryBytes+report.batchMetadataBytes;report.byteRatio=report.batchTotalBytes/sourceBytes;report.originalAssetsUnchanged=models.every((m:any)=>crypto.createHash('sha256').update(fs.readFileSync(base+'/'+m.id+'.glb')).digest('hex')===manifest.owners.find((o:any)=>o.id===m.id).sourceModelHash);assert.ok(report.originalAssetsUnchanged);
fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
