/**
 * Publish shared enamel CSS for Map Quest (Vite) and Canal (static HTML).
 *
 * Source of truth for hex values: `src/canalRecall/hudTheme.ts`.
 * Chrome rules: `src/theme/enamel-chrome.css` (no raw palette hexes).
 *
 * Writes:
 *   src/theme/enamel-tokens.css          — for Map Quest @import
 *   public/canal-drive/css/enamel.css    — tokens + chrome for Canal <link>
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { enamelCssVariables } from '../src/canalRecall/hudTheme.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const themeDir = path.join(root, 'src', 'theme');
const canalCssDir = path.join(root, 'public', 'canal-drive', 'css');
const chromePath = path.join(themeDir, 'enamel-chrome.css');
const tokensPath = path.join(themeDir, 'enamel-tokens.css');
const canalBundlePath = path.join(canalCssDir, 'enamel.css');

const vars = enamelCssVariables();
const lines = Object.entries(vars).map(([key, value]) => `  ${key}: ${value};`);

const tokensCss = `/**
 * Enamel palette as CSS custom properties.
 * GENERATED by \`npm run publish:enamel-css\` from hudTheme.ts — do not edit.
 */
:root {
${lines.join('\n')}
}
`;

writeFileSync(tokensPath, tokensCss);
mkdirSync(canalCssDir, { recursive: true });
const chrome = readFileSync(chromePath, 'utf8');
writeFileSync(canalBundlePath, `${tokensCss}\n${chrome}`);

process.stdout.write(
  `Published enamel CSS\n`
  + `  tokens → ${path.relative(root, tokensPath)}\n`
  + `  canal  → ${path.relative(root, canalBundlePath)} (${Object.keys(vars).length} vars)\n`,
);
