import assert from 'node:assert/strict';
import { compileSourceShapePreview } from './source-shape-preview.ts';
import { applySourceAssemblies } from './apply-source-assemblies.ts';
const input:any={width:600,height:500,cropSha256:'a'.repeat(64),captureDate:'2025-01-01',features:[{id:'ground:door-1',kind:'door',head:'rectangular',colour:'#38271f',transom:.2,mullions:[.34],bounds:[240,100,340,380],disposition:'agent-inspected'}]};
const before=compileSourceShapePreview(input),beforeDoor=before.patches.filter((p:any)=>p.featureId.endsWith('ground:door-1'));
const visible=applySourceAssemblies(compileSourceShapePreview(input),input,[{id:'visible-stairs',featureId:'ground:door-1',visibleOpeningBounds:[230,90,350,390],sourceAccess:{openingBottomPixelY:380,pavementPixelY:450,accessKind:'stairs',visibleStepCount:2,visibleAccessBounds:[230,380,350,450]},projectionIntent:{recess:true,inferMetricDepth:true}}]);
assert.ok(visible.owner.geometry.building.surfaces[0].rings.length>1,'recessed entrance cuts a source-study opening void from the support wall');
const assembly=visible.patches.filter((p:any)=>p.sourceStudyOnly);
const recessedDoor=visible.patches.filter((p:any)=>!p.sourceStudyOnly&&p.featureId.endsWith('ground:door-1'));
assert.equal(recessedDoor.length,beforeDoor.length,'the original observed door grammar survives the recess conversion');
assert.ok(recessedDoor.flatMap((p:any)=>p.triangles.filter((_:number,index:number)=>index%3===2)).some((z:number)=>z>0),'source door panels/glazing move behind the cut wall instead of being removed');
assert.ok(assembly.length>0&&assembly.every((p:any)=>p.previewOnly&&p.inferredDimensions),'only inferred preview assembly patches are added');
assert.ok(assembly.every((p:any)=>p.accessEvidence==='visible-partial-or-inferred-steps'),'visible pixel stair evidence remains explicitly partial/inferred');
assert.ok(assembly.every((p:any)=>{for(let i=0;i<p.triangles.length;i+=9){const a=p.triangles.slice(i,i+3),b=p.triangles.slice(i+3,i+6),c=p.triangles.slice(i+6,i+9),ab=b.map((v:number,j:number)=>v-a[j]),ac=c.map((v:number,j:number)=>v-a[j]),area=Math.hypot(ab[1]*ac[2]-ab[2]*ac[1],ab[2]*ac[0]-ab[0]*ac[2],ab[0]*ac[1]-ab[1]*ac[0]);if(area<1e-8)return false;}return true;}),'adapter emits no degenerate stair or recess triangles');
const unknown=applySourceAssemblies(compileSourceShapePreview(input),input,[{id:'blocked',featureId:'ground:door-1',visibleOpeningBounds:[230,90,350,390],sourceAccess:{openingBottomPixelY:380,pavementPixelY:null,accessKind:'stairs'},projectionIntent:{recess:true,inferMetricDepth:true}}]);
assert.ok(unknown.omissions.some((value:string)=>value.includes('pavement contact unresolved')),'null pavement is retained as an explicit contact omission');
assert.ok(unknown.patches.filter((p:any)=>p.sourceStudyOnly).every((p:any)=>p.accessEvidence==='pavement-unresolved-no-stairs'),'unknown pavement does not invent steps');
const partial=applySourceAssemblies(compileSourceShapePreview(input),input,[{id:'partial-run',featureId:'ground:door-1',visibleOpeningBounds:[230,90,350,390],sourceAccess:{openingBottomPixelY:380,pavementPixelY:null,accessKind:'stairs',visibleStepCount:2,visibleAccessBounds:[230,380,350,450]},projectionIntent:{recess:false,inferMetricDepth:false}}]);
const partialPatches=partial.patches.filter((p:any)=>p.sourceStudyOnly);
assert.ok(partialPatches.length>0,'a visible stair run remains inspectable when pavement is outside the photograph');
assert.ok(partialPatches.every((p:any)=>p.accessEvidence==='partial-visible-run-no-pavement'&&p.contactCertified===false),'partial stairs never certify a pavement contact');
assert.ok(partial.omissions.some((value:string)=>value.includes('pavement unresolved; only visible portion rendered')),'the missing pavement is reported alongside the rendered partial run');
assert.ok(partialPatches.flatMap((p:any)=>p.triangles.filter((_:number,index:number)=>index%3===1)).some((y:number)=>Math.abs(y-.5)<1e-8),'the partial run ends at the photographed lower access edge, not an invented pavement');
const perspectiveInput={...input,features:[...input.features,{id:'ground:door-left',kind:'door',head:'rectangular',colour:'#ffffff',bounds:[91,143,163,449],disposition:'machine-observed-unreviewed'},{id:'ground:window-display-left',kind:'window',head:'rectangular',colour:'#ffffff',bounds:[361,146,447,405],disposition:'machine-observed-unreviewed'},{id:'ground:window-display-right',kind:'window',head:'rectangular',colour:'#ffffff',bounds:[447,141,529,411],disposition:'machine-observed-unreviewed'}]};
const perspective=applySourceAssemblies(compileSourceShapePreview(perspectiveInput),perspectiveInput,[{id:'bike-shop',featureId:'ground:door-1',visibleOpeningBounds:[91,137,529,449],sourceAccess:{openingBottomPixelY:413,pavementPixelY:468,accessKind:'landing'},projectionIntent:{recess:true,inferMetricDepth:true},perspectiveRecess:{apertureBounds:[91,137,529,449],backDoorBounds:[226,158,357,413],leftDoorBounds:[91,143,163,449],rightGlazedReturnBounds:[361,146,447,405],rightFrontGlazingBounds:[447,141,529,411],landingBottomPixelY:468,corniceBounds:[83,112,541,142]}}]);
const perspectivePatches=perspective.patches.filter((p:any)=>p.sourceStudyOnly&&['recess-left-return','recess-soffit','recess-floor','recess-cornice'].includes(p.assembly));
assert.deepEqual(new Set(perspectivePatches.map((p:any)=>p.assembly)),new Set(['recess-left-return','recess-soffit','recess-floor','recess-cornice']),'the perspective source study emits a single cavity, floor, and photographed surround');
const perspectiveDepths=perspective.patches.filter((p:any)=>p.sourceStudyOnly||p.perspectiveWarped).flatMap((p:any)=>p.triangles.filter((_:number,index:number)=>index%3===2));
assert.ok(new Set(perspectiveDepths.map((value:number)=>value.toFixed(3))).size>3,'the source-study faces occupy multiple inferred depths rather than a flat facade plane');
assert.ok(perspectivePatches.every((p:any)=>p.accessEvidence==='visible-recess-perspective-inferred-depth'&&p.contactCertified===false),'perspective depth remains explicitly preview-only and does not certify contact');
const warped=perspective.patches.filter((p:any)=>p.perspectiveWarped);
assert.ok(['ground:door-left','ground:window-display-left','ground:window-display-right'].every(id=>warped.some((p:any)=>p.featureId.endsWith(id))),'the detailed observed leaf and both glazing feature identities survive their perspective warp');
assert.ok(warped.filter((p:any)=>p.featureId.includes('window-display')).every((p:any)=>p.colour!=='#fff'&&p.colour!=='#ffffff'),'painted white trim is not rendered as window infill');
console.log('Source entrance assembly adapter: pixel access evidence, voids, and unresolved pavement passed.');
