import assert from 'node:assert/strict';
import {regularizeDoor} from '../../src/canalRecall/facadeDoorHeuristics';
import {owner,record} from '../city-appearance/fidelity/synthetic-fixture';
import {compileFacadePatches} from '../../src/canalRecall/cityAppearanceFacadeRecipes';
const door:any={kind:'door',disposition:'machine-observed-unreviewed',width:.58,height:1.7,y:1.05,t:2,head:'segmental',archRise:.12,transom:.25};
const changed=regularizeDoor(door,0);assert.equal(changed.feature.width,.65);assert.equal(changed.feature.y-changed.feature.height/2,0);assert.equal(changed.feature.y+changed.feature.height/2,1.9);assert.ok(Math.abs(changed.feature.archRise!*changed.feature.height-door.archRise*door.height)<1e-9);
for(const f of [{...door,y:2},{...door,y:.6},{...door,kind:'window'},{...door,thresholdHeightM:.2},{...door,disposition:'human-reviewed'},{...door,height:.3,width:.2}])assert.deepEqual(regularizeDoor(f,0).adjustments,[]);
assert.deepEqual(regularizeDoor(door,undefined).adjustments,[]);
assert.equal(regularizeDoor({...door,height:1.6,y:.8,width:.8},0).feature.height,1.8);
const r:any=structuredClone(record);r.facadeDescription.sources.ground.features=[{id:'near-ground-door',kind:'door',bounds:[150,210,208,380],head:'segmental',archRise:.12,disposition:'machine-observed-unreviewed'}];
const render=()=>compileFacadePatches(owner,owner.geometry.building.surfaces[0],0,[r],[owner],{observed:true,procedural:false,contextual:false});
const patches=render().filter(p=>p.featureId.endsWith('near-ground-door'));assert.ok(patches.length);assert.ok(patches.every(p=>p.heuristics?.includes('door-ground-extension')));const ys=patches.flatMap(p=>p.triangles.filter((_,i)=>i%3===1));assert.ok(Math.abs(Math.min(...ys))<1e-8,'door frame and leaf reach existing ground without geometry below the wall');
assert.equal(r.facadeDescription.sources.ground.features[0].bounds[3],380,'raw observation remains unchanged');
console.log('Door priors: ground contact, modest minimum size, preserved arch rise, raised/basement/explicit thresholds, no window conversion, metric-only and shared compiler provenance passed.');
const details=patches.filter(p=>p.heuristics?.some(h=>h.includes('grammar')));assert.ok(details.some(p=>p.heuristics?.includes('door-panel-grammar')));assert.ok(details.some(p=>p.heuristics?.includes('door-furniture-grammar')));
r.facadeDescription.sources.ground.features[0].doorStyle='plain';r.facadeDescription.sources.ground.features[0].doorFurniture='none';const plain=render();assert.ok(!plain.some(p=>p.heuristics?.some(h=>h.includes('grammar'))));
r.facadeDescription.sources.ground.features[0].doorStyle='glazed';r.facadeDescription.sources.ground.features[0].doorFurniture='pull';const glazed=render();assert.ok(glazed.some(p=>p.heuristics?.includes('door-panel-grammar')&&p.colour==='windowGlass'));
r.facadeDescription.sources.ground.features[0].doorGlazingRatio=.88;r.facadeDescription.sources.ground.features[0].paired=true;const balconyGlazed=render();
const ySpan=(p:any)=>{const values=p.triangles.filter((_:number,index:number)=>index%3===1);return Math.max(...values)-Math.min(...values)};
const explicitGlass=balconyGlazed.filter(p=>p.colour==='windowGlass'&&!p.heuristics?.includes('door-panel-grammar')).sort((a,b)=>ySpan(b)-ySpan(a));
assert.ok(balconyGlazed.some(p=>p.colour==='windowGlass'&&!p.heuristics?.includes('door-panel-grammar')),'source-observed glazing ratio emits source-styled window-like glass');
assert.ok(!balconyGlazed.some(p=>p.heuristics?.includes('door-panel-grammar')),'explicit glazing ratio bypasses the generic solid-panel grammar');
assert.ok(explicitGlass.length&&ySpan(explicitGlass[0])>1.45,'explicit .88 ratio emits a tall glazed field rather than only a transom');
const centreFrame=balconyGlazed.filter(p=>p.colour==='windowFrame'&&ySpan(p)>1.4);assert.ok(centreFrame.length,'paired glazed door keeps a full-height pale centre division');
delete r.facadeDescription.sources.ground.features[0].doorStyle;delete r.facadeDescription.sources.ground.features[0].doorGlazingRatio;delete r.facadeDescription.sources.ground.features[0].doorFurniture;r.facadeDescription.sources.ground.features[0].kind='window';const asWindow=render();assert.ok(asWindow.length&&asWindow.some(p=>p.colour==='windowGlass'));assert.ok(!asWindow.some(p=>p.heuristics?.some(h=>h.includes('grammar'))),'windows never acquire door panels or furniture');
console.log('Door grammar: panels and furniture, plain opt-out, glazed/pull variant, and window exclusion passed.');
