import assert from 'node:assert/strict';
import fs from 'node:fs';
import { buildTemporalCandidate, buildVerifiedFusion, deriveGroundToFullTransform } from './next-stage-temporal.ts';
const cases=JSON.parse(fs.readFileSync('public/data/facade-repair-preview/cases.json','utf8'));
const record=cases.cases.find((item:any)=>item.caseId==='case-17');
const originalStudies=JSON.stringify(record.shapeFeatures);
const candidate=buildTemporalCandidate(record);
assert.equal(JSON.stringify(record.shapeFeatures),originalStudies,'per-date source studies remain unchanged');
assert.equal(candidate.previewOnly,true);
assert.equal(candidate.cropSha256,record.source.full.sha256);
assert.equal(candidate.provenance.sourceGround.cropSha256,record.source.ground.sha256);
assert.equal(candidate.provenance.metricGate.accepted,false);
assert.ok(Number.isFinite(candidate.provenance.cropEndpointMarginM)&&candidate.provenance.cropEndpointMarginM>0);
assert.match(candidate.provenance.cropEndpointMarginNote,/not registration uncertainty/);
assert.equal(candidate.provenance.metricGate.checks.sourceRegistrationCertificate,false);
assert.equal(candidate.provenance.sourceSpaceTransferGate.accepted,true);
assert.ok(candidate.provenance.groundToFull.maxLandmarkResidualPx<3);
const display:any=candidate.features.find((feature:any)=>feature.id==='full:temporal:ground-display');
const door:any=candidate.features.find((feature:any)=>feature.id==='full:temporal:rear-right-door');
assert.deepEqual(display.bounds,[39.585,766.858,229.216,856.613]);
assert.deepEqual(door.bounds,[268.643,771.485,309.941,859.041]);
assert.equal(door.temporalEvidence.sourceFeatureId,'ground:review:rear-right-door');
for(const feature of [display,door])for(const field of ['colour','frameColour','material','region','state','text','physicalSignId','doorFurniture'])assert.equal(feature[field],undefined,`${field} leaked across dates`);
assert.ok(!candidate.features.some((feature:any)=>['awning','material','fascia'].includes(feature.kind)),'dated appearance classes excluded');
assert.equal(candidate.features.find((feature:any)=>feature.id==='full:w1').disposition,'machine-observed-unreviewed','same-date unreviewed features are not promoted');
assert.throws(()=>deriveGroundToFullTransform({width:10,height:10,sha256:'x',plane:{start:{x:0,y:0},end:{x:1,y:0},baseZ:0,topZ:1}} as any,{width:10,height:10,sha256:'y',plane:{start:{x:0,y:0},end:{x:0,y:1},baseZ:0,topZ:1}} as any),/coordinate-direction/);
const clone=()=>structuredClone(record);
for(const [field,value] of [['sha256','b'.repeat(64)],['captureDate','2024-12-12T11:16:00Z'],['width',923]] as const){const stale=clone();stale.source.ground[field]=value;assert.throws(()=>buildTemporalCandidate(stale),/correspondence-source-binding-mismatch/,`stale ${field} rejected`);}
const shifted=clone();const shiftedImage=shifted.owner.observations[0].payload.images.ground;shiftedImage.plane.start.x+=.2;shiftedImage.plane.end.x+=.2;const shiftedCandidate=buildTemporalCandidate(shifted);assert.equal(shiftedCandidate.provenance.sourceSpaceTransferGate.accepted,false);assert.equal(shiftedCandidate.features.some((feature:any)=>feature.temporalEvidence),false,'shifted plane abstains from transfer');
const outside=clone();outside.shapeFeatures.ground.features.find((feature:any)=>feature.id==='ground:window-01').bounds=[-20,230,560,450];const outsideCandidate=buildTemporalCandidate(outside);assert.equal(outsideCandidate.provenance.sourceSpaceTransferGate.boundsFit,false);assert.equal(outsideCandidate.features.some((feature:any)=>feature.temporalEvidence),false,'out-of-image mapping abstains');
const registration={status:'registered',uncertaintyM:.1,verified:true} as const,hash='a'.repeat(64),date='2023-01-10T10:44:05Z';
const source:any={id:'o',buildingId:'b',frontageKey:'f',coordinateFrameKey:'frame',registration,sourceHash:hash,sourceDate:date,features:[{id:'d',kind:'door',bounds:[1,2,3,4],head:'rectangular',disposition:'agent-inspected',visible:true,colour:'#f00',doorFurniture:'pull'}]};
const target:any={buildingId:'b',frontageKey:'f',coordinateFrameKey:'frame',captureDate:'2024-12-11T11:16:00Z',registration};
const link:any={targetFeatureId:'d2',observationId:'o',sourceFeatureId:'d',sourceHash:hash,sourceDate:date,sameBuildingVerified:true,sameFrontageVerified:true,sameCoordinateFrameVerified:true,targetOcclusionVerified:true,visibilityVerified:true,structuralContinuityVerified:true};
const fused=buildVerifiedFusion(target,[source],[link]);assert.equal(fused.recovered.length,1);assert.equal((fused.recovered[0] as any).colour,undefined);assert.equal((fused.recovered[0] as any).doorFurniture,undefined);
console.log('Next-stage temporal candidate: source-space composite and certified fusion pathway verified.');
