/** Real cached sources, isolated notes: never writes the user's review ledgers. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { createHash } from 'node:crypto';
import express from 'express';
import { chromium } from 'playwright';
import { build } from 'esbuild';
import { collectWorkbench, reconstructionWorkbenchRouter } from './reconstruction-workbench-router.js';
import { facadePreviewNotesRouter } from './district-notes.js';

const root = process.cwd();
const temporary = await fs.mkdtemp(path.join(os.tmpdir(), 'reconstruction-workbench-'));
const captures = path.join(root, '.cache/city-appearance/reconstruction-workbench-check');
await fs.mkdir(captures, { recursive: true });
const sha = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex');
const previewBytes = await fs.readFile(path.join(root, 'public/data/facade-repair-preview/cases.json'));
const preview = JSON.parse(previewBytes.toString());
const pointerBefore = sha(await fs.readFile(path.join(root, 'public/data/city-expansion/current.json')));
const ledgerBefore = sha(await fs.readFile(path.join(root, '.cache/city-appearance/spend.json')));
const report = await collectWorkbench(root);
assert.equal(report.preview.sha256, sha(previewBytes), 'API uses the exact notes candidate identity');
assert.deepEqual(report.preview.cases.map(c => c.caseId), preview.cases.map((c: any) => c.caseId), 'notes and navigation share case IDs');
assert.equal(report.project.activeReleaseId, JSON.parse(await fs.readFile(path.join(root, 'public/data/city-expansion/current.json'), 'utf8')).releaseId);
assert.equal(report.project.acceptedRegistrations, 0);
assert.ok(report.project.accountedUsd! > 5 && report.project.ceilingUsd! > report.project.accountedUsd!, 'global cost is distinct from batch cost');
assert.ok(report.quality.diagnostics.length > 0, 'real source-space diagnostic cases are present');
assert.ok(report.preview.cases.some(c => c.source.full && c.source.ground), 'valid source photos are available');
const bundle = await build({ entryPoints: [path.join(root, 'src/canalRecall/reconstructionWorkbench.ts')], bundle: true, format: 'esm', write: false });
let rejectSaves = false;
const app = express(); app.use(express.json());
app.post('/api/facade-repair/notes/:id', (req, res, next) => { if (rejectSaves && req.body.caseId) res.status(503).json({ error: 'Temporary test outage' }); else next(); });
app.use('/api/reconstruction', reconstructionWorkbenchRouter(root, { load: async () => report }));
app.use('/api/facade-repair/notes', facadePreviewNotesRouter(root, path.join(temporary, 'notes')));
app.get('/canal-drive/js/reconstruction-workbench.bundle.js', (_req, res) => res.type('js').send(bundle.outputFiles[0].text));
app.use(express.static(path.join(root, 'public')));
const server = app.listen(0, '127.0.0.1'); await new Promise<void>(resolve => server.on('listening', resolve));
const base = `http://127.0.0.1:${(server.address() as any).port}`;
const launch: any = { headless: true };
try { await fs.access('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'); launch.executablePath = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'; } catch {}
const browser = await chromium.launch(launch);
try {
  for (const [width, height] of [[1440, 900], [1366, 768], [390, 844]]) {
    const page = await browser.newPage({ viewport: { width, height } });
    await page.route('**/*', route => new URL(route.request().url()).origin === base ? route.continue() : route.abort());
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(`${base}/canal-drive/reconstruction-workbench.html?case=case-01&focus=roof`);
    await page.waitForFunction(() => !(document.getElementById('repair-note') as HTMLTextAreaElement).disabled);
    assert.equal(await page.locator('#case-select option').count(), preview.cases.length);
    assert.equal(await page.evaluate(() => document.activeElement?.id), 'repair-note', 'ready to type without a click');
    assert.equal(await page.locator('#project-overview').getAttribute('open'), null);
    for (const selector of ['#repair-note', '#save-next']) {
      const box = await page.locator(selector).boundingBox();
      assert.ok(box && box.y >= 0 && box.y + box.height <= height, `${selector} must be above the fold at ${width} × ${height}: ${JSON.stringify(box)}`);
    }
    const candidate = page.frameLocator('#current-preview');
    await candidate.locator('canvas[data-case-id="case-01"][data-review-focus="roof"][data-source-tier="full"]').waitFor();
    assert.equal(await page.locator('#full-panel').isVisible(), true);
    assert.equal(await page.locator('#ground-panel').isVisible(), false);
    assert.ok((await candidate.locator('canvas').boundingBox())!.height >= (width < 760 ? 160 : 250), 'candidate canvas retains useful space after controls');
    await page.locator('#full-link[data-framing="measured-candidate-viewport"]').waitFor();
    const parentPhoto = (await page.locator('#full-image').boundingBox())!;
    const embeddedPhoto = (await candidate.locator('.candidate-stage img').boundingBox())!;
    assert.ok(Math.abs(parentPhoto.width - embeddedPhoto.width) < 1, 'parent and embedded source use the same measured width');
    assert.ok(Math.abs(parentPhoto.height - embeddedPhoto.height) < 1, 'parent and embedded source use the same measured height');
    assert.ok(Math.abs(parentPhoto.y - embeddedPhoto.y) < 1, 'toolbar offset is included in parent photo framing');
    await page.screenshot({ path: path.join(captures, `roof-review-${width}.png`), fullPage: false });
    const originalCase = await page.locator('#case-select').inputValue();
    const note1 = `Roof review ${width}: <script>window.noteExecuted=true</script>`;
    await page.locator('#repair-note').fill(note1);
    await page.locator('#repair-note').press('Tab');
    assert.equal(await page.evaluate(() => document.activeElement?.id), 'save-next', 'Tab lands on save and next');
    await page.keyboard.press('Enter');
    await page.waitForFunction(id => (document.getElementById('case-select') as HTMLSelectElement).value !== id, originalCase);
    assert.equal(await page.evaluate(() => document.activeElement?.id), 'repair-note', 'next case returns typing focus');
    const secondCase = await page.locator('#case-select').inputValue();
    const note2 = `Second roof ${width}: chimney missing, keep its own source identity.`;
    await page.locator('#repair-note').fill(note2);
    await page.locator('#repair-note').press('Control+Enter');
    await page.waitForFunction(id => (document.getElementById('case-select') as HTMLSelectElement).value !== id, secondCase);
    await page.locator('#repair-note').press('Control+Shift+Enter');
    await page.waitForFunction(id => (document.getElementById('case-select') as HTMLSelectElement).value === id, secondCase);
    const storedPath = path.join(temporary, 'notes', `${report.preview.sha256}.json`);
    let saved = JSON.parse(await fs.readFile(storedPath, 'utf8'));
    assert.equal(saved.notes[originalCase].text, note1); assert.equal(saved.notes[secondCase].text, note2);
    await page.reload();
    await page.waitForFunction(() => !(document.getElementById('repair-note') as HTMLTextAreaElement).disabled);
    assert.equal(await page.locator('#case-select').inputValue(), secondCase);
    assert.equal(await page.locator('#repair-note').inputValue(), note2);
    await page.locator('#repair-note').press('ArrowLeft');
    assert.equal(await page.locator('#case-select').inputValue(), secondCase, 'normal text arrows remain editing keys');
    await page.locator('#repair-note').press('Escape');
    await page.keyboard.press('n');
    assert.equal(await page.evaluate(() => document.activeElement?.id), 'repair-note');
    if (width === 1440) {
      rejectSaves = true;
      await page.locator('#repair-note').fill('Unsaved roof detail during outage');
      await page.locator('#repair-note').press('Control+Enter');
      await page.waitForFunction(() => document.getElementById('repair-note-message')?.textContent?.includes('retry'));
      assert.equal(await page.locator('#case-select').inputValue(), secondCase, 'failed save does not advance');
      assert.equal(await page.locator('#repair-note').inputValue(), 'Unsaved roof detail during outage');
      rejectSaves = false;
      await page.locator('#repair-note').press('Control+s');
      await page.waitForFunction(() => document.getElementById('repair-note-message')?.textContent === 'Saved to project');
    }
    await page.locator('#repair-notes-ready').click();
    await page.waitForFunction(() => document.getElementById('repair-note-message')?.textContent?.includes('Ready for the next repair pass'));
    saved = JSON.parse(await fs.readFile(storedPath, 'utf8'));
    assert.equal(saved.readyForFixes, true); assert.equal(saved.packetSha256, report.preview.sha256);
    assert.ok(saved.regressionCases.some((c: any) => c.caseId === secondCase && c.source.previewSha256 === report.preview.sha256));
    assert.equal(await page.evaluate(() => (window as any).noteExecuted), undefined);
    await page.locator('#case-select').selectOption('case-27');
    await candidate.locator('canvas[data-case-id="case-27"][data-review-focus="roof"]').waitFor();
    await page.locator('[data-review-focus="ground"]').click();
    await candidate.locator('canvas[data-case-id="case-27"][data-review-focus="ground"]').waitFor();
    assert.ok(Number(await candidate.locator('canvas').getAttribute('data-door-meshes')) > 0, 'roof focus preserves ground-floor repair work');
    assert.equal(await candidate.locator('html').getAttribute('data-preview-sha256'), report.preview.sha256);
    assert.equal(await page.locator('#previous-release').getAttribute('open'), null);
    assert.equal(await candidate.locator('#repair-feedback').isVisible(), false);
    await page.locator('[data-review-focus="roof"]').click();
    await page.locator('#case-select').selectOption('case-20');
    await candidate.locator('canvas[data-case-id="case-20"][data-review-focus="roof"]').waitFor();
    assert.match(await page.locator('#roof-summary').textContent() ?? '', /Existing outline correction/);
    await page.locator('#candidate-variant').selectOption('roof-planes');
    await candidate.locator('canvas[data-case-id="case-20"][data-review-focus="roof"][data-candidate-variant="roof-planes"]').waitFor();
    const experimentalDraft = await page.locator('#repair-note').inputValue();
    assert.equal(await page.locator('#repair-note').isDisabled(), false, 'experimental notes remain focusable');
    assert.equal(await page.locator('#repair-note').getAttribute('readonly'), '', 'experimental notes are read-only');
    assert.equal(await page.locator('#repair-note-status').isDisabled(), true, 'experimental status changes are disabled');
    assert.equal(await page.locator('#repair-note-save').isDisabled(), true, 'experimental save is disabled');
    assert.equal(await page.locator('#repair-notes-ready').isDisabled(), true, 'experimental ready action is disabled');
    assert.equal(await page.locator('#save-next').isDisabled(), true, 'experimental review cannot save against baseline identity');
    assert.match(await page.locator('#comparison-status').textContent() ?? '', /review only/);
    await page.locator('#repair-note').press('a');
    await page.locator('[data-roof-issue="Dormer"]').click();
    assert.equal(await page.locator('#repair-note').inputValue(), experimentalDraft, 'experimental review cannot mutate the baseline draft');
    await page.locator('#repair-note').press('Control+s');
    await page.locator('[data-review-focus="ground"]').click();
    assert.equal(await page.locator('#candidate-variant').inputValue(), 'baseline', 'unsupported ground focus resets experimental variant');
    assert.equal(await page.locator('#save-next').isDisabled(), false, 'ground focus restores baseline saving');
    await page.locator('[data-review-focus="roof"]').click();
    await page.locator('#candidate-variant').selectOption('baseline');
    await candidate.locator('canvas[data-case-id="case-20"][data-review-focus="roof"][data-candidate-variant="baseline"]').waitFor();
    assert.equal(await page.locator('#save-next').isDisabled(), false, 'baseline restores candidate-bound saving');
    await page.locator('#queue-select').selectOption('roofs');
    assert.equal(await page.locator('#case-select option').first().getAttribute('value'), 'case-26');
    assert.equal(await page.locator('#case-select').inputValue(), 'case-20', 'priority queue preserves selected case');
    await page.locator('[data-roof-issue="Dormer"]').click();
    assert.match(await page.locator('#repair-note').inputValue(), /Dormer: /);
    assert.equal(await page.locator('#repair-note-status').inputValue(), 'needs-work');
    await page.locator('#repair-note').press('Control+s');
    await page.waitForFunction(() => document.getElementById('repair-note-message')?.textContent === 'Saved to project');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.deepEqual(errors, []); await page.close();
  }
  assert.equal(sha(await fs.readFile(path.join(root, 'public/data/city-expansion/current.json'))), pointerBefore);
  assert.equal(sha(await fs.readFile(path.join(root, '.cache/city-appearance/spend.json'))), ledgerBefore);
  assert.equal(sha(await fs.readFile(path.join(root, 'public/data/facade-repair-preview/cases.json'))), sha(previewBytes));
  console.log('Reconstruction workbench passed: roof focus, preserved doors, exact candidate identity, above-fold editor, Tab/Enter and save shortcuts, save-failure navigation guard, priority queue, source-bound feedback, desktop/laptop/phone, unchanged release and spend.');
} finally { await browser.close(); await new Promise<void>(resolve => server.close(() => resolve())); }
