import assert from 'node:assert/strict';
import {compileFacadePatches} from '../../src/canalRecall/cityAppearanceFacadeRecipes.ts';
import {fitFacadeFeature} from '../../src/canalRecall/facadeDescription.ts';
import {owner,record,source,image} from '../city-appearance/fidelity/synthetic-fixture.ts';
const wall=owner.geometry.building.surfaces[0];
const render=(feature:any)=>{const value:any=structuredClone(record),ground:any=structuredClone(source);ground.features=[feature];value.images={ground:{...image,sha256:ground.cropSha256}};value.facadeDescription.sources={ground};return compileFacadePatches(owner,wall,0,[value],[owner],{observed:true});};
const awning=(state:string,extra:any={})=>({id:'retail-awning',kind:'awning',bounds:[150,100,650,230],state,colour:'#274740',frameColour:'#e1dac6',text:'DORUS',textColour:'#1d2927',signFont:'bold 42px serif',physicalSignId:'dorus:awning:2025',stripeColour:'#f2ead7',stripeCount:6,valance:'scalloped',disposition:'agent-inspected',...extra});
const extended=render(awning('extended'));const extendedSign=extended.filter(p=>p.sign);
assert.equal(extendedSign.length,1,'extended awning emits exactly one physical valance sign');assert.deepEqual(extendedSign[0].sign&&{text:extendedSign[0].sign.text,background:extendedSign[0].sign.background,colour:extendedSign[0].sign.colour,font:extendedSign[0].sign.font,physicalSignId:extendedSign[0].sign.physicalSignId},{text:'DORUS',background:'#e1dac6',colour:'#1d2927',font:'bold 42px serif',physicalSignId:'dorus:awning:2025'});assert.equal(extendedSign[0].sign!.uv.length,extendedSign[0].triangles.length/3*2);
const fittedAwning=fitFacadeFeature(awning('extended'),source,record)!;
const valanceHeight=Math.min(.26,fittedAwning.height*.22),scallopInset=Math.min(.06,valanceHeight*.3);
const signBottom=fittedAwning.y-fittedAwning.height/2+scallopInset;
const signYs=extendedSign[0].triangles.filter((_:number,index:number)=>index%3===1);
assert.ok(Math.min(...signYs)>=signBottom-1e-8,'scalloped valance sign begins above the highest scallop hem');
assert.ok(Math.abs(extendedSign[0].sign!.aspectRatio!-fittedAwning.width/(valanceHeight-scallopInset))<1e-8,'extended valance records the actual unscalloped sign-face ratio');
const mirrored=awning('extended');const mirroredValue:any=structuredClone(record),mirroredSource:any=structuredClone(source);mirroredSource.registration.imageToWall=[-.01,0,8,0,-.01,4,0,0,1];mirroredSource.features=[mirrored];mirroredValue.images={ground:{...image,sha256:mirroredSource.cropSha256}};mirroredValue.facadeDescription.sources={ground:mirroredSource};const mirroredSign=compileFacadePatches(owner,wall,0,[mirroredValue],[owner],{observed:true}).find(p=>p.sign)!;const minX=Math.min(...mirroredSign.triangles.filter((_:number,i:number)=>i%3===0));assert.ok(mirroredSign.triangles.reduce((out:number[],_:number,i:number)=>i%3===0&&Math.abs(mirroredSign.triangles[i]-minX)<1e-8?[...out,mirroredSign.sign!.uv[(i/3)*2]]:out,[]).some(u=>u>.99),'valance UV respects a reversed signed source axis');
assert.equal(render(awning('retracted')).filter(p=>p.sign).length,1,'retracted photographed valance can carry its explicit sign');
for(const state of ['unknown','absent'])assert.equal(render(awning(state)).filter(p=>p.sign).length,0,`${state} awning emits no sign`);
assert.equal(render(awning('extended',{physicalSignId:undefined})).filter(p=>p.sign).length,0,'text without a physical sign identity is not emitted');
const fascia=(signMount:any)=>({id:'retail-window-sign',kind:'fascia',bounds:[180,80,620,145],colour:'#243734',text:'DORUS',physicalSignId:'dorus:window:2025',signMount,disposition:'agent-inspected'});
const wallSign=render(fascia('wall')).find(p=>p.sign)!;const glazingSign=render(fascia('glazing')).find(p=>p.sign)!;
assert.notDeepEqual(glazingSign.triangles,wallSign.triangles,'a glazing-mounted fascia is offset forward from wall-mounted sign geometry');
assert.ok(Math.abs(glazingSign.sign!.aspectRatio!-440/65)<1e-8,'fascia signs carry their physical face ratio for canvas generation');
assert.equal(render(fascia('invalid')).filter(p=>p.sign).length,0,'invalid sign mounts fail feature fitting rather than guessing depth');
console.log('retail awning valance signs passed');
