/** Fail-closed retail/residential registration evidence audit. */
import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';
const targets=['case-21','case-29','case-18'];const norm=(x:number,y:number)=>{const n=Math.hypot(x,y);return [x/n,y/n] as [number,number]};
export function signedCandidate(image:any,wall:any,groundNAP:number){const [ux,uy]=norm(wall.end.x-wall.start.x,wall.end.y-wall.start.y),along=(p:any)=>(p.x-wall.start.x)*ux+(p.y-wall.start.y)*uy,t0=along(image.plane.start),t1=along(image.plane.end),w=image.width,h=image.height;return {wallDirection:[ux,uy],planeAlongM:[t0,t1],imageToWall:[(t1-t0)/w,0,t0,0,(image.plane.baseZ-image.plane.topZ)/h,image.plane.topZ-groundNAP,0,0,1],sourceDatum:'NAP',canonicalDatum:'surface-base',pixelConvention:'pixel-edge'};}
export function assessCandidate(image:any,wall:any,groundNAP:number,{retail=false}={}){const candidate=signedCandidate(image,wall,groundNAP),margins=Math.max(Math.hypot(image.plane.start.x-wall.start.x,image.plane.start.y-wall.start.y),Math.hypot(image.plane.end.x-wall.end.x,image.plane.end.y-wall.end.y));const blockers=['reviewed raw-pixel wall-boundary correspondences with residuals','camera centre height in NAP and stated accuracy','camera/panorama calibration convention and datum provenance'];if(retail)blockers.push('surface-specific anchor set for recessed/angled shopfront planes');return {status:'ambiguous',candidate,planeMarginM:margins,obliquityDeg:image.obliquity,standoffM:image.standoff,heightInferred:image.heightInferred,datum:image.datum,canonicalPavementNAP:groundNAP,contact:{status:'unresolved',reason:'groundNAP is geometry datum; no same-date measured pavement pixel contact'},acceptance:{maxUncertaintyM:.15,uncertaintyM:null,blockers}};}
async function walk(dir:string):Promise<string[]>{const out:string[]=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(p));else if(e.name==='manifest.json')out.push(p);}return out;}
async function records(hashes:Set<string>){const found=new Map<string,any>();for(const p of await walk('.cache/city-appearance/areas')){try{const x=JSON.parse(await fs.readFile(p,'utf8'));for(const r of x.records??[])for(const [tier,image] of Object.entries(r.images??{}) as any[])if(hashes.has(image.sha256))found.set(image.sha256,{record:r,tier,manifest:p});}catch{}}return found;}
export async function buildRetailRegistration(root='.') {const regressions=JSON.parse(await fs.readFile(path.join(root,'scripts/review/facade-regressions.json'),'utf8')),cases=regressions.cases.filter((x:any)=>targets.includes(x.caseId)),found=await records(new Set(cases.flatMap((c:any)=>Object.values(c.source).map((s:any)=>s.sha256)) as string[]));const output=[];for(const item of cases){const tiers:any={};for(const tier of ['full','ground']){const source=item.source[tier],hit=found.get(source.sha256),file=path.join(root,source.path),sha=crypto.createHash('sha256').update(await fs.readFile(file)).digest('hex');if(!hit){tiers[tier]={status:'ambiguous',abstention:'canonical-native-record-not-found'};continue;}const image=hit.record.images[tier],retail=item.caseId!=='case-18';tiers[tier]={...assessCandidate(image,hit.record.wall,hit.record.groundNAP,{retail}),sourceBinding:{sha256:source.sha256,fileHashVerified:sha===source.sha256,captureDate:source.captureDate,actualDimensions:{width:source.width,height:source.height},nativeDimensions:{width:image.width,height:image.height},manifest:hit.manifest,observationId:hit.record.id}};}const preferred=['ground','full'].sort((a,b)=>(tiers[a].obliquityDeg??999)-(tiers[b].obliquityDeg??999))[0];output.push({caseId:item.caseId,buildingId:item.binding.buildingId,kind:item.caseId==='case-18'?'residential':'retail',tiers,preferredCandidateTier:preferred,status:'ambiguous'});}return {version:1,kind:'retail-registration-evidence',maxAcceptedUncertaintyM:.15,canonicalDatum:'surface-base',pixelConvention:'pixel-edge',cases:output};}
if(import.meta.url===`file://${process.argv[1]}`){const x=await buildRetailRegistration('.');await fs.writeFile('scripts/review/retail-registration.json',JSON.stringify(x,null,2)+'\n');console.log(JSON.stringify({cases:x.cases.length,registered:0,output:'scripts/review/retail-registration.json'}));}
