import { createHash, randomUUID } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
const ALLOWED = ['.cache/city-appearance/review-notes','.cache/city-appearance/repair-preview-notes','.cache/facade-rebuild/router-review/labels.json'];
const BINDINGS = ['public/data/city-expansion/current.json','scripts/review/thousand-building-candidate-report.json'];
const digest=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
const canonical=(x:unknown)=>JSON.stringify(x,(k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(a=>[a,v[a]])):v);
export interface SnapshotEntry { path:string; sha256:string; bytes:number; }
export interface SnapshotManifest { schemaVersion:1; snapshotSha256:string; createdAt:string; entries:SnapshotEntry[]; }
function safeRelative(p:string){if(!p||path.isAbsolute(p)||p.split(/[\\/]/).includes('..')||p.startsWith('./'))throw Error(`unsafe snapshot path: ${p}`);}
function inside(root:string,p:string,dir:string){const r=path.relative(path.resolve(root,dir),p);return r===''||(!r.startsWith('..')&&!path.isAbsolute(r));}
async function filesUnder(root:string, relDir:string):Promise<string[]> { const base=path.resolve(root,relDir); const out:string[]=[]; async function walk(d:string){let es;try{es=await fs.readdir(d,{withFileTypes:true});}catch(e:any){if(e?.code==='ENOENT')return;throw e;} for(const e of es.sort((a,b)=>a.name.localeCompare(b.name))){if(e.isSymbolicLink())throw Error(`symlink is not allowed: ${path.join(d,e.name)}`);const p=path.join(d,e.name);if(e.isDirectory())await walk(p);else if(e.isFile()&&e.name.endsWith('.json'))out.push(p);}} await walk(base); return out; }
async function sourcePaths(root:string):Promise<string[]> {const out:string[]=[]; for(const d of ALLOWED.slice(0,2))out.push(...await filesUnder(root,d)); const bindings=[...BINDINGS];
  // Include the packet bytes named by human notes when they are available, so a
  // restored label remains interpretable without copying the whole cache.
  for(const p of out.filter(p=>p.includes('/review-notes/')||p.includes('/repair-preview-notes/'))){try{const x=JSON.parse(await fs.readFile(p,'utf8'));const id=typeof x.packetSha256==='string'?x.packetSha256:undefined;if(id&&/^[a-f0-9]{64}$/.test(id))bindings.push(`public/data/city-expansion/evaluations/${id}/comparison-packet.json`);}catch{/* malformed notes are still preserved byte-for-byte */}}
  for(const p of [...ALLOWED.slice(2),...bindings]){try{const s=await fs.lstat(path.resolve(root,p));if(s.isFile())out.push(path.resolve(root,p));}catch(e:any){if(e?.code!=='ENOENT')throw e;}} return [...new Set(out)].sort();}
async function readEntries(root:string):Promise<{entries:SnapshotEntry[]; bytes:Map<string,Buffer>}> {const bytes=new Map<string,Buffer>(),entries:SnapshotEntry[]=[];for(const p of await sourcePaths(root)){const b=await fs.readFile(p), r=path.relative(root,p).split(path.sep).join('/');bytes.set(r,b);entries.push({path:r,sha256:digest(b),bytes:b.length});} return {entries,bytes};}
function snapshotHash(entries:SnapshotEntry[]){return digest(Buffer.from(canonical(entries)));}
function validateEntries(entries:any): asserts entries is SnapshotEntry[] {if(!Array.isArray(entries))throw Error('snapshot manifest entries are invalid');const seen=new Set<string>();for(const e of entries){if(!e||typeof e.path!=='string'||seen.has(e.path)||!/^[a-f0-9]{64}$/.test(e.sha256)||!Number.isInteger(e.bytes)||e.bytes<0){throw Error('snapshot manifest entry is invalid');}seen.add(e.path);safeRelative(e.path);}}
export async function planReviewSnapshot(root=process.cwd()){const x=await readEntries(path.resolve(root));return {snapshotSha256:snapshotHash(x.entries),entries:x.entries};}
export async function createReviewSnapshot(root=process.cwd(), destination?:string):Promise<{directory:string;manifest:SnapshotManifest}> {root=path.resolve(root);const first=await readEntries(root), hash=snapshotHash(first.entries);const dir=path.resolve(root,destination??path.join('review-data','snapshots',hash));if(inside(root,dir,'.cache')||inside(root,dir,'public'))throw Error('snapshot destination must be outside .cache and public');const existing=await verifyReviewSnapshot(dir);if(existing.valid&&existing.manifest?.snapshotSha256===hash)return {directory:dir,manifest:existing.manifest};if(existing.valid||existing.error&&existing.error!=='manifest: ENOENT') {try{await fs.access(dir);throw Error('snapshot destination exists and is not the requested immutable snapshot');}catch(e:any){if(e.message.includes('requested immutable'))throw e;}}const staging=path.join(root,'review-data',`.snapshot-${randomUUID()}`);await fs.mkdir(path.join(staging,'files'),{recursive:true});try{for(const e of first.entries){const target=path.join(staging,'files',e.path);safeRelative(path.relative(staging,target));await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,first.bytes.get(e.path)!,{flag:'wx'});}const latest=await planReviewSnapshot(root);if(latest.snapshotSha256!==hash)throw Error('review sources changed during snapshot; retry after edits settle');const manifest:SnapshotManifest={schemaVersion:1,createdAt:new Date().toISOString(),snapshotSha256:hash,entries:first.entries};await fs.writeFile(path.join(staging,'manifest.json'),JSON.stringify(manifest,null,2)+'\n',{flag:'wx'});const checked=await verifyReviewSnapshot(staging);if(!checked.valid)throw Error(`snapshot verification failed: ${checked.error}`);await fs.mkdir(path.dirname(dir),{recursive:true});await fs.rename(staging,dir);return {directory:dir,manifest};}catch(e){await fs.rm(staging,{recursive:true,force:true});throw e;}}
export async function verifyReviewSnapshot(directory:string):Promise<{valid:boolean;manifest?:SnapshotManifest;error?:string}> {try{const dir=path.resolve(directory),m=JSON.parse(await fs.readFile(path.join(dir,'manifest.json'),'utf8'));validateEntries(m.entries);if(m.schemaVersion!==1||m.snapshotSha256!==snapshotHash(m.entries))throw Error('manifest content hash mismatch');for(const e of m.entries){const p=path.resolve(dir,'files',e.path);if(!inside(dir,p,'files'))throw Error('path traversal in manifest');const b=await fs.readFile(p);if(b.length!==e.bytes||digest(b)!==e.sha256)throw Error(`file hash mismatch: ${e.path}`);}return {valid:true,manifest:m};}catch(e:any){return {valid:false,error:e?.message??String(e)};}}
export async function restoreReviewSnapshot(directory:string,destination:string):Promise<SnapshotManifest>{const checked=await verifyReviewSnapshot(directory);if(!checked.valid||!checked.manifest)throw Error(checked.error??'invalid snapshot');const out=path.resolve(destination);if((await fs.readdir(out).catch((e:any)=>e?.code==='ENOENT'?[]:Promise.reject(e))).length)throw Error('restore destination must be an existing or new empty directory');await fs.mkdir(out,{recursive:true});for(const e of checked.manifest.entries){safeRelative(e.path);const p=path.join(out,e.path);await fs.mkdir(path.dirname(p),{recursive:true});await fs.copyFile(path.join(path.resolve(directory),'files',e.path),p);}return checked.manifest;}
export const snapshotReviewData=createReviewSnapshot;
export const verifySnapshot=verifyReviewSnapshot;
export const restoreSnapshot=restoreReviewSnapshot;
async function main(){const a=process.argv.slice(2),cmd=a[0]==='verify'||a[0]==='restore'||a[0]==='write'?a.shift():'plan';let root=process.cwd(),out:string|undefined,snapshot:string|undefined;for(let i=0;i<a.length;i++){if(a[i]==='--root')root=a[++i];else if(a[i]==='--out'||a[i]==='--destination')out=a[++i];else if(a[i]==='--snapshot')snapshot=a[++i];else if(a[i]==='--write'){}else if(a[i]==='--help'){console.log('Usage: review-snapshot.ts [plan|write|verify|restore] [--root DIR] [--out DIR] [--snapshot DIR]');return;}}if(cmd==='plan'){console.log(JSON.stringify(await planReviewSnapshot(root),null,2));return;}if(cmd==='write'){if(!out)throw Error('--out/--destination is required');console.log(JSON.stringify(await createReviewSnapshot(root,out),null,2));return;}if(cmd==='verify'){const x=await verifyReviewSnapshot(snapshot??out??'');if(!x.valid){console.error(x.error);process.exitCode=1;}console.log(JSON.stringify(x,null,2));return;}if(!snapshot||!out)throw Error('restore requires --snapshot DIR --out EMPTY_DIR');await restoreReviewSnapshot(snapshot,out);console.log(JSON.stringify({restoredTo:path.resolve(out)},null,2));}
if(import.meta.url===`file://${process.argv[1]}`)main().catch(e=>{console.error(e.message);process.exitCode=1;});
