import { strict as assert } from 'node:assert';
import { mkdtemp, mkdir, readFile, writeFile, readdir, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createReviewSnapshot, restoreReviewSnapshot, verifyReviewSnapshot } from './review-snapshot';

async function setup(){const root=await mkdtemp(path.join(os.tmpdir(),'review-snapshot-'));await mkdir(path.join(root,'.cache/city-appearance/review-notes'),{recursive:true});await mkdir(path.join(root,'.cache/facade-rebuild/router-review'),{recursive:true});await mkdir(path.join(root,'public/data/city-expansion'),{recursive:true});await mkdir(path.join(root,'scripts/review'),{recursive:true});await writeFile(path.join(root,'.cache/city-appearance/review-notes/a.json'),'{"text":"literal bytes \\u00e9"}\n');await writeFile(path.join(root,'.cache/facade-rebuild/router-review/labels.json'),' { "human": true }\n');await writeFile(path.join(root,'public/data/city-expansion/current.json'),' {"releaseId":"r"}\n');await writeFile(path.join(root,'scripts/review/thousand-building-candidate-report.json'),' {"stagedReleaseId":"s"}\n');return root;}
export async function runReviewSnapshotTests(){const root=await setup();try{const made=await createReviewSnapshot(root);assert.equal((await verifyReviewSnapshot(made.directory)).valid,true);const out=path.join(root,'restored');await restoreReviewSnapshot(made.directory,out);assert.equal((await readFile(path.join(out,'.cache/city-appearance/review-notes/a.json'),'utf8')),'{"text":"literal bytes \\u00e9"}\n');await assert.rejects(()=>restoreReviewSnapshot(made.directory,out));await writeFile(path.join(made.directory,'files/.cache/city-appearance/review-notes/a.json'),'corrupt');assert.equal((await verifyReviewSnapshot(made.directory)).valid,false);await assert.rejects(()=>createReviewSnapshot(root,made.directory));await assert.rejects(()=>createReviewSnapshot(root,path.join(root,'.cache/bad')));return 'review snapshot tests passed';}finally{await rm(root,{recursive:true,force:true});}}
if(import.meta.url===`file://${process.argv[1]}`)runReviewSnapshotTests().then(console.log);
