import assert from 'node:assert/strict';
import {materializeThousandBuildingCandidates} from './thousand-building-materialize.ts';
const sha=(letter:string)=>letter.repeat(64);
const source=(extra:any={})=>({observationId:'obs-1',buildingId:'b-1',geometryRevision:'g-1',evidenceKey:sha('e'),frontage:[[0,0],[5,0]],surfaceIndex:4,tier:'ground' as const,cropSha256:sha('a'),captureDate:'2025-01-02T10:00:00Z',width:100,height:80,path:'cached/ground.jpg',imageToWall:[.05,0,0,0,-.04,3.2,0,0,1],wallDirection:[1,0] as [number,number],analysisKey:'analysis-a',...extra});
const analysis=(extra:any={})=>({key:'analysis-a',status:'complete',source:{cropSha256:sha('a'),width:100,height:80},proposal:{openingsComplete:true,features:[{id:'door',kind:'door',bounds:[5,10,35,75]},{id:'window',kind:'window',bounds:[45,15,85,60]}]},...extra});
const protectedFeatures=[{id:'ground:door',kind:'door',bounds:[1,1,2,2],disposition:'human-reviewed',colour:'#112233'},{id:'ground:removed',kind:'window',bounds:[1,1,2,2],disposition:'revoked'}];
const record=(extra:any={})=>({id:'obs-1',buildingId:'b-1',renderBuildingId:'b-1',geometryRevision:'g-1',evidenceKey:sha('e'),localStart:[0,0],localEnd:[5,0],mid:[2.5,0],renderSurfaceIndices:[4],roofGeometry:{source:'preserved-roof-mesh',height:12.4},facadeDescription:{version:1,extractionVersion:'old',buildingId:'b-1',geometryRevision:'g-1',evidenceKey:sha('e'),frontage:[[0,0],[5,0]],surfaceIndices:[4],sources:{ground:{cropSha256:sha('a'),captureDate:'2025-01-02T10:00:00Z',imageDimensions:{width:100,height:80},features:protectedFeatures}}},...extra});
const baseline=record(),result=materializeThousandBuildingCandidates({records:[baseline],sources:[source()],analyses:[analysis()]});
assert.equal(result.report.attached.length,1);assert.equal(result.report.releaseMutation,false);assert.equal(result.candidateManifest.activated,false);
const attached=result.records[0],tier=attached.facadeDescription.sources.ground;
assert.equal(attached.roofGeometry.source,'preserved-roof-mesh','existing roof geometry remains unchanged');
assert.equal(attached.images.ground.captureDate??attached.images.ground.date,'2025-01-02T10:00:00Z','new source capture date is retained');
assert.equal(tier.registration.status,'ambiguous');assert.equal(tier.registration.preview.kind,'native-crop-plane');assert.deepEqual(tier.registration.preview.imageToWall,source().imageToWall);
assert.deepEqual(tier.features.filter((f:any)=>['human-reviewed','revoked'].includes(f.disposition)).map((f:any)=>f.id),['ground:door','ground:removed'],'human and revoked features are retained');
assert.equal(tier.features.find((f:any)=>f.id==='ground:door').colour,'#112233','human correction wins over cached feature');
assert.equal(baseline.images,undefined,'materialization does not mutate preserved input');
const differentCapture=materializeThousandBuildingCandidates({records:[record({images:{ground:{sha256:sha('b'),date:'2024-01-01T00:00:00Z',width:100,height:80}}})],sources:[source()],analyses:[analysis()]});
assert.equal(differentCapture.report.omitted[0].reason,'existing-image-is-another-capture');
const revoked=materializeThousandBuildingCandidates({records:[record({machineRevocation:{revoked:true}})],sources:[source()],analyses:[analysis()]});
assert.equal(revoked.report.omitted[0].reason,'observation-revoked');
const competing=materializeThousandBuildingCandidates({records:[record()],sources:[source(),source({cropSha256:sha('c'),captureDate:'2025-01-03T10:00:00Z'})],analyses:[analysis()]});
assert.equal(competing.report.omitted[0].reason,'competing-candidate-captures','two dates never receive an arbitrary winner');
const badTransform=materializeThousandBuildingCandidates({records:[record()],sources:[source({imageToWall:[]})],analyses:[analysis()]});
assert.equal(badTransform.report.omitted[0].reason,'invalid-native-candidate-transform');
console.log('thousand-building candidate materialization passed');
import {prepareInventoryCandidateSources,prepareThousandBuildingRecords} from './thousand-building-materialize.ts';
const inventory={records:[{observationId:'obs-1',sources:{full:{sha256:sha('f'),captureDate:'2025-02-01T00:00:00Z',width:80,height:100,path:'cached/full.jpg'},ground:{sha256:sha('a'),captureDate:'2025-01-02T10:00:00Z',width:100,height:80,path:'cached/ground.jpg'}},wall:{index:999}}]};
const registrations=[{observationId:'obs-1',tier:'ground' as const,cropSha256:sha('a'),captureDate:'2025-01-02T10:00:00Z',imageDimensions:{width:100,height:80},status:'ambiguous' as const,surfaceIndex:4,wallDirection:[1,0] as [number,number],preview:{kind:'native-crop-plane',cropSha256:sha('a'),imageDimensions:{width:100,height:80},imageToWall:source().imageToWall}}];
const preparedInventory=prepareInventoryCandidateSources(inventory,[record()],registrations);
assert.equal(preparedInventory.sources.length,1,'only a prepared native transform enters candidate materialization');
assert.equal(preparedInventory.sources[0].surfaceIndex,4,'target render surface wins over raw inventory wall.index');
assert.equal(preparedInventory.omitted.find((entry:any)=>entry.key==='obs-1:full').reason,'native-registration-missing-or-stale');
console.log('inventory-to-candidate interface passed');
const staged=prepareThousandBuildingRecords({...inventory,version:1,manifestId:'fixture-batch',trancheObservationIds:['obs-1'],requestedTranche:1},{records:[record()],results:[analysis()],registrations});
assert.equal(staged.records.length,1,'only attached candidate records are returned for publishAreaGeometryDemo replacement');
assert.equal(staged.records[0].appearancePublication,'candidate-registration-preview');
assert.equal(staged.evidenceFiles.get(sha('a')),'cached/ground.jpg','attached source bytes are returned by hash without reading or publishing them');
assert.equal(staged.candidateManifest.stageOnly,true);
assert.throws(()=>prepareThousandBuildingRecords({version:1,records:[]},{records:[],results:[]}),/requires target records and native registrations/);
console.log('publish-area candidate preparation passed');
const stagedPrepared=prepareThousandBuildingRecords({version:1,manifestId:'fixture-batch',records:inventory.records,requestedTranche:1},{results:[analysis()],targets:{targetRecords:[record()],candidateSources:preparedInventory.sources,omissions:preparedInventory.omitted,evidenceFiles:new Map([[sha('a'),'cached/ground.jpg']])}});
assert.equal(stagedPrepared.records.length,1,'prebound owner targets feed direct candidate staging without reinterpreting source wall indexes');
assert.equal(stagedPrepared.evidenceFiles.get(sha('a')),'cached/ground.jpg');
console.log('prebound inventory target staging passed');
