import * as T from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { openTopPrism, upwardRoofPlane } from '../../../scripts/landmarks/house-geometry';
const base=new URL('.',document.baseURI),manifest=await fetch(new URL('ordinary-buildings-data/catalogue.json',base)).then(r=>r.json());
const $=s=>document.querySelector(s),container=$('#scene'),renderer=new T.WebGLRenderer({antialias:true});
renderer.setClearColor('#e5ecec');renderer.setPixelRatio(Math.min(devicePixelRatio,2));container.append(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,2000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new T.HemisphereLight(0xffffff,0x909c98,2));const sun=new T.DirectionalLight(0xffffff,2);sun.position.set(50,100,-70);scene.add(sun);
const loader=new GLTFLoader(),select=$('#building');let current=null,shell=null,entry=null,bare=false,token=0,distance=100;
for(const m of manifest.models){const o=document.createElement('option');o.value=m.id;o.textContent=m.name;select.append(o);}
function cleanup(group){if(!group)return;scene.remove(group);group.traverse(o=>{if(!o.isMesh)return;o.geometry?.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const v of Object.values(m||{}))if(v?.isTexture)v.dispose();m?.dispose();}});}
function sourceView(wide=false,back=false){const a=((entry.cameraBearing??220)+(back?180:0))*Math.PI/180,scale=wide?1.8:1;camera.position.set(Math.sin(a)*distance*scale,entry.height*.6+distance*.42*scale,-Math.cos(a)*distance*scale);controls.target.set(0,entry.height*.38,0);controls.update();}
function resize(){renderer.setSize(container.clientWidth,container.clientHeight);camera.aspect=container.clientWidth/container.clientHeight;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(container);
function nativeShell(m){const root=new T.Group(),material=new T.MeshStandardMaterial({color:'#aaa39a',roughness:1}),roof=new T.MeshStandardMaterial({color:'#7d8580',roughness:1}),kx=111320*Math.cos(m.anchor[1]*Math.PI/180);const polygons=m.footprint.type==='Polygon'?[m.footprint.coordinates]:m.footprint.coordinates;for(const poly of polygons){const ring=r=>r.slice(0,-1).map(([x,y])=>new T.Vector2((x-m.anchor[0])*kx,-(y-m.anchor[1])*111320)),shape=new T.Shape(ring(poly[0]));shape.holes=poly.slice(1).map(r=>new T.Path(ring(r)));root.add(new T.Mesh(openTopPrism(shape,0,m.nativeHeight??m.height),material),new T.Mesh(upwardRoofPlane(shape,m.nativeHeight??m.height),roof));}return root;}
async function load(id){const held=++token;entry=manifest.models.find(m=>m.id===id)??manifest.models[0];select.value=entry.id;cleanup(current);cleanup(shell);current=null;shell=null;$('#stats').textContent='Loading…';const url=new URL(entry.modelUrl,base);url.searchParams.set('asset',entry.hash);const gltf=await loader.loadAsync(url.href);if(held!==token){cleanup(gltf.scene);return;}current=gltf.scene;scene.add(current);shell=nativeShell(entry);scene.add(shell);shell.visible=bare;current.visible=!bare;const box=new T.Box3().setFromObject(current),size=box.getSize(new T.Vector3());distance=Math.max(60,size.x*1.25,size.z*1.25,entry.height*2.4);sourceView();$('#identity').textContent=entry.buildingId;$('#traits').replaceChildren(...entry.traits.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));$('#limits').textContent=entry.simplifications.join(' ');$('#references').replaceChildren(...entry.referenceImages.slice(0,3).map(src=>{const img=document.createElement('img');img.src=new URL(src,base).href;img.alt='Municipal reference facade';return img;}));$('#download').href=url.href;$('#download').download=entry.id+'.glb';$('#status').textContent=entry.reviewState;const params=new URLSearchParams(location.search);params.set('building',entry.id);history.replaceState(null,'','?'+params);}
select.onchange=()=>load(select.value);$('#wide').onclick=()=>sourceView(true);$('#front').onclick=()=>sourceView();$('#rear').onclick=()=>sourceView(false,true);$('#baseline').onclick=()=>{bare=!bare;if(current)current.visible=!bare;if(shell)shell.visible=bare;$('#baseline').textContent=bare?'Show custom treatment':'Show native shell';};
let frames=0;renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);if(entry&&current&&++frames%20===0)$('#stats').textContent=`${renderer.info.render.calls} calls · ${renderer.info.render.triangles.toLocaleString()} triangles in viewer · ${(entry.bytes/1024).toFixed(0)} KB GLB`;});
resize();await load(new URLSearchParams(location.search).get('building')??manifest.models[0]?.id);
