import { boundFacadeSource, fitFacadeFeature } from './facadeDescription.js';
import { sourceToRenderHeight, napToSourceHeight } from './appearanceHeight.js';
/** Machine-read shop name bands for expansion viewer. Unreviewed literal text only. */
// @ts-expect-error Shared browser JS module has no separate declaration file.
import { wallObservationIntervals, intervalFaceFrame } from '../../public/canal-drive/da-costa-block/wall-intervals.js';
// @ts-expect-error Shared browser JS module has no separate declaration file.
import { rectangleFitsFace } from '../../public/canal-drive/da-costa-block/face-containment.js';
import { facadeRecipeRecords, facadeWallFrame } from './cityAppearanceFacadeRecipes.js';
import type { BlockAppearanceGeometry } from './cityAppearanceThree.js';
import type { AppearanceTile } from './cityAppearanceTiles.js';
type Owner = AppearanceTile<BlockAppearanceGeometry, any>['owners'][number];
type Surface = BlockAppearanceGeometry['building']['surfaces'][number];
type Frame = NonNullable<ReturnType<typeof facadeWallFrame>>;
export const GAME_SIGN_RELIEF_OFFSET_M=.2;
export const MACHINE_SIGN_BAND_HEIGHT=.55, MACHINE_SIGN_TEXTURE_HEIGHT=128, MACHINE_SIGN_PROVENANCE='Shop names are machine-read from dated panoramas — unreviewed', MACHINE_SIGN_MAX_TEXT_WIDTH=7.4;
const validPlacement=(r:any)=>!['rejected','uncertain','crop-repair'].includes(r?.review?.placement);
const usableSource=(r:any,k:string)=>{const i=r?.images?.[k];return !!i&&/^[a-f0-9]{64}$/i.test(i.sha256??'')&&/^[a-f0-9]{64}$/i.test(i.panoramaSha256??'');};
const groundSupported=(r:any)=>{if(!usableSource(r,'ground')||!['yes','no'].includes(r.effectiveProposal?.shopfront))return false;const human=r.review?.placement==='accepted'&&r.proposalSources?.shopfront==='human-review';if(human)return true;if(r.visualReview?.fieldEligibility?.shopfront===false)return false;return r.visualReview?.fieldEligibility?.shopfront===true||r.effectiveProposal?.groundUsable==='yes';};
export function machineSignRevocationReason(r:any):string|null{if(!r)return'missing-record';if(r.machineRevocation?.revoked)return'revoked-observation';if(!validPlacement(r))return'revoked-placement';if(!r.evidenceKey||!r.derivationKey)return'missing-source-identity';if(!usableSource(r,'ground'))return'missing-current-ground-source';if(!r.images?.ground?.date&&!r.images?.ground?.capturedAt)return'missing-capture-date';if(r.effectiveProposal?.shopfront!=='yes')return'shopfront-not-positive';if(r.visualReview?.fieldEligibility?.shopfront===false||r.visualReview?.fieldEligibility?.signText===false)return'field-withheld';if(!groundSupported(r))return'ground-source-not-supported';const p=r.machineRoutingProposal;if(!p)return'missing-machine-proposal';if(p.signTextEligible!=='yes')return'sign-text-not-eligible';const t=String(p.signText??'').trim();if(!t)return'empty-sign-text';if(/[\u0000-\u001f\u007f]/.test(t))return'control-character-sign-text';return null;}
export function truncateMachineSignText(t:string,max=28){const s=String(t??'').trim();return s.length<=max?s:`${s.slice(0,max-1)}…`;}
export function machineSignEligible(r:any){return machineSignRevocationReason(r)===null;}
export function machineSignBandWidth(t:string,w:number){return Math.min(w-.3,MACHINE_SIGN_MAX_TEXT_WIDTH,Math.max(1.4,t.length*.24+.5));}
const onFace=(f:Frame,t:number,y:number,d:number):[number,number,number]=>[f.a[0]+f.u[0]*t+f.n[0]*d,y,f.a[1]+f.u[1]*t+f.n[1]*d];
export function drawMachineSignTexture(ctx:CanvasRenderingContext2D,text:string,width=1024,colour='#25372e'){const height=ctx.canvas?.height||MACHINE_SIGN_TEXTURE_HEIGHT;ctx.fillStyle=/^#[a-f0-9]{6}$/i.test(colour)?colour:'#25372e';ctx.fillRect(0,0,width,height);ctx.fillStyle='#e7e5d9';ctx.textAlign='center';ctx.textBaseline='middle';let size=height*.75;ctx.font=`700 ${size}px Arial`;while(ctx.measureText(text).width>width*.84&&size>height*.1875){size-=1;ctx.font=`700 ${size}px Arial`;}ctx.fillText(text,width/2,height*.53);}
export type MachineSignPlacement={observationId:string;text:string;displayText:string;localPosition:[number,number,number];rotationY:number;width:number;height:number;intervalWidth:number;physicalSignId?:string;colour?:string;};
export type GameMachineSign={text:string;displayText:string;position:[number,number,number];normal:[number,number];width:number;height:number;observationId:string;captureDate:string;sourceSha256:string;provenance:string;colour?:string;physicalSignId?:string;};
export function machineSignPlacementsForGame(owners:Owner[],records?:any[]):GameMachineSign[]{const out:GameMachineSign[]=[];const source=records??facadeRecipeRecords(owners);for(const owner of owners)for(const [index,surface] of owner.geometry.building.surfaces.entries())for(const p of planMachineSignPlacements(owner,surface,index,source,owners)){const n=[Math.sin(p.rotationY),Math.cos(p.rotationY)] as [number,number],r=source.find((x:any)=>x.id===p.observationId);out.push({text:p.text,displayText:p.displayText,colour:p.colour,physicalSignId:p.physicalSignId,position:[p.localPosition[0]+n[0]*GAME_SIGN_RELIEF_OFFSET_M,-p.localPosition[2]-n[1]*GAME_SIGN_RELIEF_OFFSET_M,sourceToRenderHeight(p.localPosition[1],owner.geometry.frame.heightDatum,Number(owner.geometry.building.groundNAP??.65))],normal:[n[0],-n[1]],width:p.width,height:p.height,observationId:p.observationId,captureDate:String(r?.images?.ground?.date??r?.images?.ground?.capturedAt??''),sourceSha256:String(r?.images?.ground?.panoramaSha256??''),provenance:MACHINE_SIGN_PROVENANCE});}return deduplicateMachineSigns(out,source);}
export function planMachineSignPlacement(r:any,frame:Frame,interval:{startM:number;endM:number;observation:any;status:string},axis:NonNullable<ReturnType<typeof wallObservationIntervals>['axis']>,groundBase:number):MachineSignPlacement|null{if(!machineSignEligible(r)||interval.status==='conflict'||interval.observation?.id!==r.id)return null;const f=intervalFaceFrame(frame,axis,interval);if(!f||f.width<1.5||f.bottom>groundBase+1.5)return null;const gh=Math.min(2.35,3.5*.66),groundY=groundBase+.55+gh/2,signY=groundY+gh/2+.55/2+.05,text=truncateMachineSignText(String(r.machineRoutingProposal.signText).trim()),width=machineSignBandWidth(text,f.width),t=f.width/2;if(!rectangleFitsFace(f,t,signY,width,.55))return null;return{observationId:r.id,text,displayText:text,localPosition:onFace(f,t,signY,.06),rotationY:Math.atan2(f.n[0],f.n[1]),width,height:.55,intervalWidth:f.width};}
export function planMachineSignPlacements(owner:Owner,surface:Surface,surfaceIndex:number,records:any[],neighbours:Owner[]):MachineSignPlacement[]{if(surface.type!=='wall')return[];const frame=facadeWallFrame(surface,owner,neighbours);if(!frame||frame.top-frame.bottom<2.5)return[];const descriptions=records.filter(r=>r.renderBuildingId===owner.id&&r.renderSurfaceIndices?.includes(surfaceIndex)&&r.facadeDescription);
if(descriptions.length){const out:MachineSignPlacement[]=[];for(const r of descriptions){const source=boundFacadeSource(r,owner,surfaceIndex,'ground');if(!source)continue;const partition=wallObservationIntervals(surface,surfaceIndex,owner.id,descriptions.map(x=>({...x,effectiveProposal:{wholeUsable:'unknown'}})));for(const interval of partition.intervals){if(interval.observation?.id!==r.id||interval.status==='conflict')continue;const f=intervalFaceFrame(frame,partition.axis,interval);if(!f)continue;const shift=(f.a[0]-frame.a[0])*frame.u[0]+(f.a[1]-frame.a[1])*frame.u[1];for(const feature of source.features){const fitted=fitFacadeFeature(feature,source,r);if(!fitted||fitted.kind!=='fascia'||!fitted.text?.trim()||/[\u0000-\u001f\u007f]/.test(fitted.text)||!rectangleFitsFace(f,fitted.t-shift,fitted.y,fitted.width,fitted.height))continue;out.push({observationId:r.id,text:fitted.text.trim(),displayText:truncateMachineSignText(fitted.text),localPosition:onFace(frame,fitted.t,fitted.y,.09),rotationY:Math.atan2(frame.n[0],frame.n[1]),width:fitted.width,height:fitted.height,intervalWidth:f.width,physicalSignId:fitted.physicalSignId,colour:fitted.colour});}}}return out;}
const eligible=records.filter(r=>r.renderBuildingId===owner.id&&machineSignEligible(r)&&Array.isArray(r.renderSurfaceIndices)&&r.renderSurfaceIndices.includes(surfaceIndex));if(!eligible.length)return[];const ys=owner.geometry.building.surfaces.filter(f=>f.type==='wall').flatMap(f=>f.rings[0].map(p=>p[1])),base=Number.isFinite(owner.geometry.building.groundNAP)?napToSourceHeight(owner.geometry.building.groundNAP!,owner.geometry.frame.heightDatum):Math.min(...ys),views=records.map(r=>({...r,effectiveProposal:groundSupported(r)?{wholeUsable:'unknown'}:null})),partition=wallObservationIntervals(surface,surfaceIndex,owner.id,views);if(!partition.axis)return[];return eligible.flatMap(r=>partition.intervals.map((i:any)=>planMachineSignPlacement(r,frame,i,partition.axis!,base)).filter(Boolean) as MachineSignPlacement[]);}
export function machineSignRecords(owners:Owner[]){return facadeRecipeRecords(owners).filter(machineSignEligible);}
/** One inferred physical sign per tenant/panorama/date, unless separate sign
 * identities are explicitly source-bound. Wall subdivisions are not evidence
 * for repeated signage. Prefer the widest candidate with deterministic ties. */
export function deduplicateMachineSigns<T extends {observationId:string;width:number;text?:string;physicalSignId?:string}>(placements:T[],records:any[]):T[]{
  const winners=new Map<string,T>();
  for(const p of placements){
    const r=records.find(r=>r.id===p.observationId);if(!r)continue;
    const text=String(p.text??r.machineRoutingProposal?.signText??'').trim().toLocaleLowerCase('en');
    const key=JSON.stringify([r.images?.ground?.panoramaSha256??r.renderBuildingId,text,r.images?.ground?.date??r.images?.ground?.capturedAt,p.physicalSignId??null]);
    const previous=winners.get(key);
    if(!previous||p.width>previous.width||(p.width===previous.width&&p.observationId<previous.observationId))winners.set(key,p);
  }
  return [...winners.values()];
}
export function machineSignBandFitsFrame(frame:Frame,text:string,groundBase=0){const gh=Math.min(2.35,3.5*.66),y=groundBase+.55+gh/2+gh/2+.55/2+.05;return rectangleFitsFace(frame,frame.width/2,y,machineSignBandWidth(text,frame.width),.55);}
