import assert from 'node:assert/strict';
import { fuseStableFacadeEvidence } from './facadeTemporalEvidence.ts';
const date='2023-03-20T10:00:00Z',hash='a'.repeat(64),registration={status:'registered',uncertaintyM:.08,verified:true} as const;
const door:any={id:'door-old',kind:'door',head:'segmental',archRise:.12,lintelHead:'rounded',lintelRise:.08,bounds:[1,2,3,4],visible:true,disposition:'agent-inspected',paired:true,transom:.25,mullions:[.5],thresholdHeightM:.12,colour:'#123456',frameColour:'#abcdef',doorStyle:'panelled',doorFurniture:'pull'};
const source:any={id:'old',buildingId:'b',frontageKey:'front',coordinateFrameKey:'wall:b:front:v1',registration,sourceHash:hash,sourceDate:date,features:[door]};
const target:any={buildingId:'b',frontageKey:'front',coordinateFrameKey:'wall:b:front:v1',captureDate:'2025-06-01T12:30:00+02:00',registration};
const link:any={targetFeatureId:'door-now',observationId:'old',sourceFeatureId:'door-old',sourceHash:hash,sourceDate:date,sameBuildingVerified:true,sameFrontageVerified:true,sameCoordinateFrameVerified:true,targetOcclusionVerified:true,visibilityVerified:true,structuralContinuityVerified:true};
const accepted=fuseStableFacadeEvidence(target,[source],[link]);
assert.equal(accepted.recovered.length,1);assert.deepEqual(accepted.recovered[0].bounds,door.bounds);assert.equal(accepted.recovered[0].archRise,.12);assert.equal(accepted.recovered[0].temporalEvidence.sourceFeatureId,'door-old');
for(const field of ['colour','frameColour','surroundColour','doorStyle','doorFurniture','material','region','state','text','physicalSignId'])assert.equal((accepted.recovered[0] as any)[field],undefined,`${field} must not transfer`);
const rejects=(message:string,t:any,s:any,l:any,reason:string)=>{const result=fuseStableFacadeEvidence(t,[s],[l]);assert.equal(result.recovered.length,0,message);assert.equal(result.unresolved[0]?.reason,reason,message);};
for(const feature of [{...door,id:'dated',kind:'awning',state:'extended'},{...door,id:'dated',kind:'fascia',text:'OLD SHOP',physicalSignId:'old-sign'},{...door,id:'dated',kind:'material',material:'paint',region:'ground-floor'}])rejects(`${feature.kind} never transfers`,target,{...source,features:[feature]},{...link,sourceFeatureId:'dated'},'stable-visible-opening-unavailable');
rejects('invalid calendar date',target,{...source,sourceDate:'2023-02-30T10:00:00Z'},{...link,sourceDate:'2023-02-30T10:00:00Z'},'metric-source-unavailable');
rejects('date-only invalid',target,{...source,sourceDate:'2023-03-20'},{...link,sourceDate:'2023-03-20'},'metric-source-unavailable');
rejects('mixed hash',target,source,{...link,sourceHash:'b'.repeat(64)},'source-evidence-binding-mismatch');
rejects('mixed date',target,source,{...link,sourceDate:'2023-03-21T10:00:00Z'},'source-evidence-binding-mismatch');
rejects('building mismatch',{...target,buildingId:'other'},source,link,'building-or-frontage-unverified');
rejects('frame mismatch',{...target,coordinateFrameKey:'other'},source,link,'coordinate-frame-unverified');
rejects('occlusion unverified',target,source,{...link,targetOcclusionVerified:false},'target-occlusion-unverified');
rejects('source registration unverified',target,{...source,registration:{...registration,verified:undefined}},link,'metric-source-unavailable');
rejects('target registration unverified',{...target,registration:{...registration,verified:undefined}},source,link,'target-registration-or-date-unavailable');
rejects('observation revoked',target,{...source,revoked:true},link,'source-observation-revoked');
rejects('feature revoked',target,{...source,features:[{...door,disposition:'revoked'}]},link,'source-feature-revoked');
rejects('target revoked',{...target,revokedFeatureIds:['door-now']},source,link,'target-revoked');
const duplicateLinks=fuseStableFacadeEvidence(target,[source],[link,{...link}]);assert.equal(duplicateLinks.recovered.length,0);assert.deepEqual(duplicateLinks.unresolved,[{targetFeatureId:'door-now',reason:'duplicate-association'}]);
const duplicateSourceLinks=fuseStableFacadeEvidence(target,[source],[link,{...link,targetFeatureId:'door-copy'}]);assert.equal(duplicateSourceLinks.recovered.length,0);assert.ok(duplicateSourceLinks.unresolved.every(item=>item.reason==='duplicate-source-association'));
const duplicateObservations=fuseStableFacadeEvidence(target,[source,{...source}],[link]);assert.equal(duplicateObservations.unresolved[0]?.reason,'duplicate-observation-id');
const duplicateFeatures=fuseStableFacadeEvidence(target,[{...source,features:[door,{...door}]}],[link]);assert.equal(duplicateFeatures.unresolved[0]?.reason,'duplicate-source-feature-id');
assert.equal(fuseStableFacadeEvidence({buildingId:'b',frontageKey:'front'},[source],[link]).recovered.length,0,'legacy callers safely abstain');
console.log('Facade temporal evidence: exact verified structural opening geometry only.');
