import test from 'node:test';import assert from 'node:assert/strict';import {GroundElevation} from './groundElevationBrowser.ts';
const meta={version:1,datum:'NAP',encoding:'mapbox',tileSize:256,minzoom:10,maxzoom:18,bounds:[4.7,52.2,5.2,52.5],fingerprint:'test'};
function map(){const sources=new Map<string,any>(),events=new Map<string,any>();let terrain:any=null;return {_canalElevation:null,on:(name:string,f:any)=>events.set(name,f),off:(name:string)=>events.delete(name),getStyle:()=>({layers:[]}),getSource:(id:string)=>sources.get(id),addSource:(id:string,v:any)=>sources.set(id,v),removeSource:(id:string)=>sources.delete(id),setTerrain:(v:any)=>{terrain=v;},getTerrain:()=>terrain,fire:()=>{},triggerRepaint:()=>{},events,sources};}
async function context(run:(m:any,service:GroundElevation)=>Promise<void>,loader?:any){const oldFetch=globalThis.fetch,oldDocument=(globalThis as any).document;(globalThis as any).document={baseURI:'http://example.test/canal-drive/'};globalThis.fetch=async()=>new Response(JSON.stringify(meta));const m=map(),service=new GroundElevation(m,true,loader);try{await run(m,service);}finally{service.dispose();globalThis.fetch=oldFetch;(globalThis as any).document=oldDocument;}}
test('style reload reattaches terrain; switching cities and disabling restores flat scene',()=>context(async(m,s)=>{await s.load('../data/extracts/amsterdam');assert.equal(m.getTerrain().source,'amsterdam-ground-dem');s.setEnabled(false);assert.equal(m.getTerrain(),null);s.setEnabled(true);assert.equal(m.getTerrain().source,'amsterdam-ground-dem');m.sources.clear();m.setTerrain(null);m.events.get('style.load')();assert.equal(m.getTerrain().source,'amsterdam-ground-dem');await s.load('../data/extracts/utrecht');assert.equal(m.getTerrain(),null);assert.equal(s.ready,false);}));
test('sampler bounds concurrency and discards old-city pixel requests',()=>context(async(m,s)=>{await s.load('../data/extracts/amsterdam');for(let i=0;i<12;i++)s.sample([4.8+i*.006,52.37]);assert.equal(s.status().pending,4);assert.ok(s.status().queued>0);await s.load('../data/extracts/utrecht');assert.equal(s.status().pending,0);assert.equal(s.status().queued,0);assert.equal(s.heightAt([4.8,52.37]),0);},()=>new Promise(()=>{})));
test('missing metadata reports actual error and never hides the flat basemap',()=>context(async(m,s)=>{globalThis.fetch=async()=>new Response('unavailable',{status:503});await s.load('../data/extracts/amsterdam');assert.equal(s.ready,false);assert.match(s.error!,/503/);assert.equal(m.getTerrain(),null);}));
test('draped roads share one terrain pass, with live layers preserved and flat order restored',()=>context(async(m,s)=>{
 const original=[{id:'land',type:'fill'},{id:'buildings',type:'custom'},{id:'bridge-road',type:'line'},{id:'labels',type:'symbol'},{id:'route',type:'line'}];
 let layers=[...original];m.getStyle=()=>({layers});m.moveLayer=(id:string)=>{const layer=layers.find(l=>l.id===id)!;layers=layers.filter(l=>l.id!==id);layers.push(layer);};
 await s.load('../data/extracts/amsterdam');assert.deepEqual(layers.map(l=>l.id),['land','bridge-road','route','buildings','labels']);
 s.setEnabled(false);assert.deepEqual(layers,original);
}));
