/**
 * One palette for the whole product: enamel street-plaque chrome.
 *
 * Route setup, settings/help panels, Map Quest dialogs, and the canvas HUD
 * share these values. Floating HUD cards stay translucent so the driving
 * corridor remains visible underneath.
 *
 * Naming:
 *   enamelTheme  — preferred (cobalt plaque fills + rivet/copper accents)
 *   paperTheme   — historical alias; same object (do not diverge)
 *   hudSurface   — navy plates for in-drive canvas (not cobalt — water is blue)
 *
 * CSS custom properties are generated by `npm run publish:enamel-css` from
 * `enamelCssVariables()` into `src/theme/enamel-tokens.css` and
 * `public/canal-drive/css/enamel.css`. Edit values here, then publish.
 */

/** Cobalt plaque fills and accents used by stop surfaces (setup, dialogs). */
export const enamelTheme = {
  enamel: '#0b3a8c',
  enamelBright: '#1450b8',
  enamelDeep: '#072861',
  night: '#071430',
  ink: '#ffffff',
  inkMuted: 'rgba(255,255,255,0.72)',
  inkDim: 'rgba(255,255,255,0.86)',
  line: 'rgba(255,255,255,0.28)',
  /** Rivet / gold accent (plaque corners, selected hairline). */
  rivet: '#c4a35a',
  rivetDeep: '#8a7040',
  /** Copper stamp (Start / Confirm). */
  copper: '#b87333',
  copperHi: '#d9a05b',
  copperDeep: '#8a5524',
  copperMid: '#c9844a',
  fontPlaque: '"Barlow Condensed", "Arial Narrow", "Helvetica Neue Condensed", sans-serif',
} as const;

/**
 * @deprecated Prefer `enamelTheme`. Kept so older callers (`moss`, `terracotta`,
 * `paper`) keep compiling; values mirror enamelTheme.
 */
export const paperTheme = {
  paper: enamelTheme.enamel,
  paperRaised: enamelTheme.enamelBright,
  paperMuted: enamelTheme.enamelDeep,
  ink: enamelTheme.ink,
  inkMuted: enamelTheme.inkMuted,
  line: enamelTheme.line,
  moss: enamelTheme.enamelBright,
  mossDark: enamelTheme.enamelDeep,
  mossSoft: 'rgba(20,80,184,0.28)',
  terracotta: enamelTheme.copper,
  ochre: enamelTheme.rivet,
} as const;

export type PaperTheme = typeof paperTheme;
export type EnamelTheme = typeof enamelTheme;

/** Card fills carry alpha so the map stays legible underneath. A HUD card that
 *  is fully opaque hides the corridor it is supposed to be annotating.
 *
 *  The in-drive HUD is deep navy, not cobalt: the basemap is mostly water and
 *  cobalt cards over blue canals read as blue-on-blue. Cobalt stays on the
 *  surfaces you stop at (setup, prompt, panels); the readouts over the map get
 *  the dark plate, white type and one gold accent. */
export const hudSurface = {
  /** Always-on readouts sitting directly on the map. */
  card: 'rgba(7,20,48,0.84)',
  /** Cards you stop and read: the trivia card, the postcard. */
  cardSolid: 'rgba(7,20,48,0.94)',
  /** Hairline border. */
  border: 'rgba(255,255,255,0.22)',
  borderStrong: 'rgba(196,163,90,0.65)',
  /** Drop shadow under a card that floats over the map. */
  shadow: 'rgba(4,12,28,0.45)',
  /** The d-pad, which sits over the map and must not hide it. */
  control: 'rgba(7,20,48,0.72)',
  controlPressed: 'rgba(196,163,90,0.92)',
  controlInk: 'rgba(255,255,255,0.88)',
  /** Type on the navy plate. */
  ink: enamelTheme.ink,
  inkMuted: 'rgba(255,255,255,0.68)',
  accent: enamelTheme.rivet,
  /** Only the finish arrow is copper, so it reads as "go there". */
  arrow: '#d08a4a',
  fontPlaque: enamelTheme.fontPlaque,
  fontMono: 'ui-monospace, "JetBrains Mono", Menlo, monospace',
  fontUi: 'system-ui, -apple-system, "Segoe UI", sans-serif',
} as const;

export const hudRadius = { card: 8, chip: 6, control: 14 } as const;

/** CSS custom properties shared by Map Quest and Canal stylesheets. */
export function enamelCssVariables(): Record<string, string> {
  return {
    '--enamel': enamelTheme.enamel,
    '--enamel-bright': enamelTheme.enamelBright,
    '--enamel-deep': enamelTheme.enamelDeep,
    '--enamel-ink': enamelTheme.ink,
    '--enamel-muted': enamelTheme.inkMuted,
    '--ink-muted': enamelTheme.inkMuted,
    '--ink-dim': enamelTheme.inkDim,
    '--ink': enamelTheme.ink,
    '--muted': enamelTheme.inkMuted,
    '--line': enamelTheme.line,
    '--night': enamelTheme.night,
    '--rivet': enamelTheme.rivet,
    '--rivet-deep': enamelTheme.rivetDeep,
    '--enamel-copper': enamelTheme.copper,
    '--enamel-copper-hi': enamelTheme.copperHi,
    '--enamel-copper-mid': enamelTheme.copperMid,
    '--enamel-copper-deep': enamelTheme.copperDeep,
    '--font-plaque': enamelTheme.fontPlaque,
    /* Historical aliases — same hexes; prefer --enamel* in new CSS. */
    '--paper': enamelTheme.enamel,
    '--paper-raised': enamelTheme.enamelBright,
    '--paper-muted': enamelTheme.enamelDeep,
    '--moss': enamelTheme.enamelBright,
    '--moss-dark': enamelTheme.enamelDeep,
    '--moss-soft': paperTheme.mossSoft,
    '--terracotta': enamelTheme.copper,
    '--ochre': enamelTheme.rivet,
    '--accent': enamelTheme.copper,
    '--primary': enamelTheme.copper,
  };
}

/** @deprecated Prefer `enamelCssVariables`. */
export function paperCssVariables(): Record<string, string> {
  return enamelCssVariables();
}
