/**
 * One palette for the whole product: enamel street-plaque chrome.
 *
 * Route setup, settings/help panels, Map Quest dialogs, and the canvas HUD
 * share these values. Floating HUD cards stay translucent so the driving
 * corridor remains visible underneath.
 *
 * Naming:
 *   enamelTheme  — preferred (cobalt plaque fills + rivet/copper accents)
 *   paperTheme   — historical alias; same object (do not diverge)
 *   hudSurface   — navy plates for in-drive canvas (not cobalt — water is blue)
 *
 * CSS custom properties are generated by `npm run publish:enamel-css` from
 * `enamelCssVariables()` into `src/theme/enamel-tokens.css` and
 * `public/canal-drive/css/enamel.css`. Edit values here, then publish.
 */

/** Cobalt plaque fills and accents used by stop surfaces (setup, dialogs). */
export const enamelTheme = {
  enamel: '#0b3a8c',
  enamelBright: '#1450b8',
  enamelDeep: '#072861',
  night: '#071430',
  ink: '#ffffff',
  inkMuted: 'rgba(255,255,255,0.72)',
  inkDim: 'rgba(255,255,255,0.86)',
  line: 'rgba(255,255,255,0.28)',
  /** Rivet / gold accent (plaque corners, selected hairline). */
  rivet: '#c4a35a',
  rivetDeep: '#8a7040',
  /** Copper stamp (Start / Confirm). */
  copper: '#b87333',
  copperHi: '#d9a05b',
  copperDeep: '#8a5524',
  copperMid: '#c9844a',
  fontPlaque: '"Barlow Condensed", "Arial Narrow", "Helvetica Neue Condensed", sans-serif',
} as const;

/**
 * Daylight paper — Canal Recall's surfaces since 2026-09-26.
 *
 * The all-cobalt/navy chrome read as heavy blue-on-blue over a mostly-water
 * map. Canal now runs on warm paper with near-black ink and exactly one accent:
 * copper, spent on action and selection. Cobalt enamel survives only where it
 * is literal — the title plaque, echoing Amsterdam's real street signs.
 * Map Quest still uses the cobalt tokens above; it has not been migrated.
 */
export const daylightTheme = {
  paper: '#f4efe5',
  paperRaised: '#fbf8f2',
  paperSunk: '#ebe4d6',
  ink: '#1f1c17',
  /** 6.3:1 on paper — secondary copy. */
  inkMuted: '#5f584d',
  line: 'rgba(31,28,23,0.14)',
  lineStrong: 'rgba(31,28,23,0.26)',
  fill: 'rgba(31,28,23,0.045)',
  fillHover: 'rgba(31,28,23,0.085)',
  accent: '#b4682c',
  /** Copper dark enough for text on paper (≈6:1). */
  accentInk: '#8a4a18',
  accentSoft: 'rgba(180,104,44,0.13)',
  scrim: 'rgba(28,24,18,0.38)',
  danger: '#a8321f',
} as const;

/**
 * @deprecated Prefer `enamelTheme`. Kept so older callers (`moss`, `terracotta`,
 * `paper`) keep compiling; values mirror enamelTheme.
 */
export const paperTheme = {
  paper: enamelTheme.enamel,
  paperRaised: enamelTheme.enamelBright,
  paperMuted: enamelTheme.enamelDeep,
  ink: enamelTheme.ink,
  inkMuted: enamelTheme.inkMuted,
  line: enamelTheme.line,
  moss: enamelTheme.enamelBright,
  mossDark: enamelTheme.enamelDeep,
  mossSoft: 'rgba(20,80,184,0.28)',
  terracotta: enamelTheme.copper,
  ochre: enamelTheme.rivet,
} as const;

export type PaperTheme = typeof paperTheme;
export type EnamelTheme = typeof enamelTheme;

/** Card fills carry alpha so the map stays legible underneath. A HUD card that
 *  is fully opaque hides the corridor it is supposed to be annotating.
 *
 *  Daylight paper plates with near-black ink (2026-09-26). The earlier navy
 *  plates avoided cobalt-on-canal, but the whole drive still read as a dark
 *  blue skin over a light map. Paper sits naturally on the CARTO basemap;
 *  copper is the single accent (distance, streak, selected), and the finish
 *  arrow stays copper so it reads as "go there". */
export const hudSurface = {
  /** Always-on readouts sitting directly on the map. */
  card: 'rgba(251,248,242,0.9)',
  /** Cards you stop and read: the trivia card, the postcard. */
  cardSolid: 'rgba(251,248,242,0.97)',
  /** Hairline border. */
  border: 'rgba(31,28,23,0.14)',
  borderStrong: 'rgba(180,104,44,0.6)',
  /** Drop shadow under a card that floats over the map. */
  shadow: 'rgba(31,28,23,0.22)',
  /** The thumbstick, which sits over the map and must not hide it. */
  control: 'rgba(251,248,242,0.72)',
  controlPressed: daylightTheme.accent,
  controlInk: 'rgba(31,28,23,0.62)',
  /** Thumbstick knob at rest. */
  controlKnob: 'rgba(31,28,23,0.2)',
  /** Type on the paper plate. */
  ink: daylightTheme.ink,
  inkMuted: daylightTheme.inkMuted,
  accent: daylightTheme.accentInk,
  /** Only the finish arrow is copper-bright, so it reads as "go there". */
  arrow: daylightTheme.accent,
  fontPlaque: enamelTheme.fontPlaque,
  fontMono: 'ui-monospace, "JetBrains Mono", Menlo, monospace',
  fontUi: 'system-ui, -apple-system, "Segoe UI", sans-serif',
} as const;

export const hudRadius = { card: 8, chip: 6, control: 14 } as const;

/** CSS custom properties shared by Map Quest and Canal stylesheets. */
export function enamelCssVariables(): Record<string, string> {
  return {
    '--enamel': enamelTheme.enamel,
    '--enamel-bright': enamelTheme.enamelBright,
    '--enamel-deep': enamelTheme.enamelDeep,
    '--enamel-ink': enamelTheme.ink,
    '--enamel-muted': enamelTheme.inkMuted,
    '--ink-muted': enamelTheme.inkMuted,
    '--ink-dim': enamelTheme.inkDim,
    '--ink': enamelTheme.ink,
    '--muted': enamelTheme.inkMuted,
    '--line': enamelTheme.line,
    '--night': enamelTheme.night,
    '--rivet': enamelTheme.rivet,
    '--rivet-deep': enamelTheme.rivetDeep,
    '--enamel-copper': enamelTheme.copper,
    '--enamel-copper-hi': enamelTheme.copperHi,
    '--enamel-copper-mid': enamelTheme.copperMid,
    '--enamel-copper-deep': enamelTheme.copperDeep,
    '--font-plaque': enamelTheme.fontPlaque,
    /* Historical aliases — same hexes; prefer --enamel* in new CSS. */
    '--paper': enamelTheme.enamel,
    '--paper-raised': enamelTheme.enamelBright,
    '--paper-muted': enamelTheme.enamelDeep,
    '--moss': enamelTheme.enamelBright,
    '--moss-dark': enamelTheme.enamelDeep,
    '--moss-soft': paperTheme.mossSoft,
    '--terracotta': enamelTheme.copper,
    '--ochre': enamelTheme.rivet,
    '--accent': enamelTheme.copper,
    '--primary': enamelTheme.copper,
    /* Daylight paper (Canal Recall). Canal's own :root maps its semantic
       tokens onto these; Map Quest ignores them. */
    '--day-paper': daylightTheme.paper,
    '--day-paper-raised': daylightTheme.paperRaised,
    '--day-paper-sunk': daylightTheme.paperSunk,
    '--day-ink': daylightTheme.ink,
    '--day-ink-muted': daylightTheme.inkMuted,
    '--day-line': daylightTheme.line,
    '--day-line-strong': daylightTheme.lineStrong,
    '--day-fill': daylightTheme.fill,
    '--day-fill-hover': daylightTheme.fillHover,
    '--day-accent': daylightTheme.accent,
    '--day-accent-ink': daylightTheme.accentInk,
    '--day-accent-soft': daylightTheme.accentSoft,
    '--day-scrim': daylightTheme.scrim,
    '--day-danger': daylightTheme.danger,
  };
}

/** @deprecated Prefer `enamelCssVariables`. */
export function paperCssVariables(): Record<string, string> {
  return enamelCssVariables();
}
