// Hand-tuned storefronts for notable businesses, one spec each, read off their panorama crops
// (scripts/storefronts/: candidates -> build-refs -> contact-sheet). Keys are reference slugs
// (storefrontWalls.generated.ts). `null` marks a reference checked and skipped: the crop shows
// the wrong wall, or the business has no street frontage of its own.
import type { StorefrontSpec } from './storefronts.js';

const WHITE = '#ece8de', CREAM = '#efe9d6', BLACK = '#1e1e1f', DARK = '#3b3d40', RED = '#c8321f', GREEN = '#2f6b47';

export const STOREFRONT_SPECS: Record<string, StorefrontSpec | null> = {
  // --- Sheet 00 ---
  'a-fushion-42477': { name: 'A-Fusion', frame: '#6b6b68', fascia: false, windows: 'split', door: 'centre' },
  'a-sentimento-pizza-33537': null,
  'a-tavola-81149': null,
  'a-volo-72841': { name: 'A Volo', frame: WHITE, fascia: false, windows: 'split', door: 'left', plants: true },
  'aaltje-54926': { name: 'Aaltje', frame: '#2f4a36', fascia: false, windows: 'panes', door: 'centre', sign: 'lamp' },
  'abyssinia-49625': { name: 'Abyssinia', frame: BLACK, fascia: '#e9e4da', letters: BLACK, windows: 'split', door: 'right', sign: 'square', signHex: RED, plants: true },
  'afhaalcentrum-terang-boelan-65034': { name: 'Terang Boelan', frame: '#4a3328', awning: 'striped', awningHex: '#b8442c', windows: 'big', door: 'left' },
  'akitsu-69827': { name: 'Akitsu', frame: WHITE, fascia: false, windows: 'split', door: 'none' },
  'al-argentino-65689': { name: 'Al Argentino', frame: DARK, fascia: '#7a1f2b', windows: 'split', door: 'centre' },
  'al-basha-47236': { name: 'Al Basha', frame: '#e9e6e0', letters: RED, windows: 'big', door: 'centre' },
  'alberto-pozzetto-private-dining-56811': null,
  'albina-10961': { name: 'Albina', frame: '#3f4a4a', fascia: false, windows: 'split', door: 'centre', plants: true },
  'ali-ocakbas-78972': { name: 'Ali Ocakbas', frame: '#e8e2d4', fascia: false, windows: 'big', door: 'none' },
  'ama-sushi-ramen-35932': { name: 'Coffeedate', frame: WHITE, letters: RED, windows: 'split', door: 'centre', terrace: true },
  'amra-74506': { name: 'Amra', frame: DARK, windows: 'split', door: 'left', sign: 'round', signHex: GREEN },
  'aneka-rasa-71504': { name: 'Aneka Rasa', frame: CREAM, letters: GREEN, windows: 'split', door: 'centre' },
  // Sheet 01.
  'anjappar-65520': { name: 'Anjappar', frame: DARK, fascia: false, windows: 'big', door: 'none' },
  'any-thaim-delivery-23690': { name: 'Any Thaim', frame: WHITE, fascia: false, windows: 'big', transom: true, door: 'none' },
  'argentalia-78811': { name: 'Argentalia', frame: BLACK, fascia: false, windows: 'arched', door: 'centre' },
  'arles-60398': { name: 'Arles', frame: '#4a2e22', fascia: false, windows: 'panes', transom: true, door: 'right' },
  'attila-turkish-food-78174': null,
  'auberge-36577': { name: 'Auberge', frame: '#5a3a24', fascia: false, windows: 'panes', door: 'left', terrace: true },
  'baibua-75627': { name: 'Baibua', frame: BLACK, fascia: BLACK, windows: 'big', door: 'left' },
  'baires-40662': { name: 'Baires', frame: '#3a2a22', fascia: false, awning: 'flat', awningHex: RED, windows: 'split', door: 'left' },
  'baires-60490': null,
  'baked-59205': null,
  'bakers-roasters-33622': { name: 'Bakers & Roasters', frame: '#3c5566', fascia: false, windows: 'split', door: 'right', terrace: true },
  'balraj-67821': { name: 'Balraj', frame: WHITE, fascia: '#f2efe8', letters: RED, windows: 'split', door: 'right', sign: 'square', signHex: RED },
  'banh-mi-ba-my-68914': { name: 'Banh Mi Ba My', frame: BLACK, fascia: false, windows: 'panes', door: 'left' },
  'bar-bistro-river-68038': { name: 'River', frame: '#3c3c3c', fascia: false, windows: 'split', door: 'none', plants: true },
  'bar-dancing-multipla-74176': null,
  'bar-karma-78156': { name: 'Karma', frame: BLACK, fascia: false, windows: 'big', door: 'centre', heightM: 4.2 },
  // Sheet 02.
  'bar-ristorante-gallizia-64155': { name: 'Gallizia', frame: DARK, fascia: false, awning: 'flat', awningHex: '#3a3d40', windows: 'split', door: 'left' },
  'barada-54271': { name: 'Barada', frame: '#4a6f95', fascia: false, windows: 'arched', door: 'centre', transom: true },
  'bella-storia-trattoria-italiana-64646': { name: 'Bella Storia', frame: DARK, fascia: false, windows: 'panes', door: 'right', sign: 'square', signHex: RED },
  'beyoglu-26283': { name: 'Beyoglu', frame: DARK, fascia: false, windows: 'split', door: 'centre', plants: true, sign: 'square', signHex: '#e0b020' },
  'beyrouth-36814': { name: 'Beyrouth', frame: '#7a4a2a', fascia: false, awning: 'striped', awningHex: RED, windows: 'panes', door: 'centre', terrace: true },
  'billy-s-thai-restaurant-73820': null,
  'bir-tat-37903': { name: 'Bir Tat', frame: WHITE, fascia: '#e8303a', windows: 'split', door: 'centre', transom: false },
  'bisous-52622': { name: 'Bisous', frame: '#2c3034', fascia: false, windows: 'panes', door: 'right', plants: true },
  'bistro-amsterdam-74130': { name: 'Bistro Amsterdam', frame: BLACK, fascia: BLACK, windows: 'panes', door: 'centre', sign: 'lamp' },
  'bistro-de-la-mer-77684': null,
  'bistrot-des-alpes-82275': { name: 'Bistrot des Alpes', frame: '#262626', fascia: false, windows: 'split', door: 'centre' },
  'bistrot-neuf-71114': { name: 'Bistrot Neuf', frame: '#e6e1d6', fascia: '#efe9d6', letters: RED, windows: 'split', door: 'right', terrace: true },
  'blauw-56113': { name: 'Blauw', frame: CREAM, fascia: false, windows: 'big', door: 'centre', transom: true, plants: true },
  'blin-queen-78949': { name: 'Blin Queen', frame: CREAM, fascia: DARK, windows: 'split', door: 'right' },
  'bloem-op-ijburg-06701': null,
  'blue-dragon-82246': { name: 'Indian Restaurant', frame: '#7a1f2b', fascia: '#7a1f2b', windows: 'split', door: 'right', sign: 'round', signHex: '#7a1f2b' },
  // Sheet 03.
  'blue-pepper-56684': { name: 'Blue Pepper', frame: '#2f4f7a', fascia: false, windows: 'arched', door: 'left' },
  'boeuf-53646': { name: 'Boeuf', frame: DARK, fascia: false, windows: 'split', door: 'centre', plants: true, terrace: true },
  'bojo-68561': { name: 'Bojo', frame: BLACK, fascia: RED, windows: 'big', door: 'left', sign: 'round', signHex: RED },
  'bougainville-65129': null,
  'bouillon-d-amsterdam-75580': { name: 'Bouillon', frame: '#8a4a22', fascia: false, windows: 'arched', door: 'none', heightM: 4.4, sign: 'square', signHex: '#c9a227' },
  'brandon-76429': { name: 'Brandon', frame: WHITE, fascia: false, awning: 'flat', awningHex: '#cfcac0', windows: 'split', door: 'centre', terrace: true },
  'brasserie-nenette-86764': { name: 'Nenette', frame: '#4a4036', fascia: false, awning: 'flat', awningHex: '#e3b62a', windows: 'split', door: 'centre', terrace: true },
  'bret-43513': { name: 'Bret', frame: '#b52a22', fascia: false, windows: 'panes', door: 'left', plants: true, terrace: true },
  'bridges-50983': null,
  'bromo-indah-70189': null,
  'brouwerij-t-ij-69757': { name: "Brouwerij 't IJ", frame: '#3a3a36', fascia: false, windows: 'panes', door: 'centre', terrace: true },
  'brouwerij-troost-26831': { name: 'Brouwerij Troost', frame: '#5a1f1a', fascia: false, windows: 'split', door: 'centre', terrace: true },
  'brunchdale-51598': { name: 'Brunchdale', frame: '#2a2c2e', fascia: false, windows: 'split', door: 'centre', heightM: 4.6 },
  'brunchie-71533': { name: 'Brunchie', frame: BLACK, fascia: BLACK, windows: 'big', door: 'left' },
  'brut-de-mer-57580': { name: 'Brut de Mer', frame: WHITE, fascia: '#2b3a55', windows: 'panes', door: 'centre', plants: true },
  'buffet-van-odette-76062': { name: 'Buffet van Odette', frame: WHITE, fascia: false, awning: 'canopy', awningHex: '#e8e4dc', windows: 'split', door: 'left', terrace: true },
  // Sheet 04.
  'buiten-amsterdam-48608': { name: 'Buiten', frame: '#2f6f7a', fascia: false, windows: 'panes', door: 'centre', plants: true, heightM: 4.2 },
  'bullewijck-par-hasard-01986': { name: 'Bullewijck', frame: '#3a2a26', fascia: '#b02a2a', windows: 'split', door: 'centre', terrace: true },
  'buurman-buurman-eetwinkel-de-with-02216': { name: 'Buurman & Buurman', frame: '#2a2c30', fascia: false, windows: 'split', door: 'left' },
  'cabron-59249': { name: 'Cabron', frame: '#5fa58a', fascia: '#5fa58a', windows: 'split', door: 'centre' },
  'cafe-carbon-72095': { name: 'Carbon', frame: DARK, fascia: false, awning: 'flat', awningHex: '#2a2c2e', windows: 'split', door: 'centre', terrace: true },
  'cafe-caron-05340': { name: 'Caron', frame: '#8fa6a4', fascia: false, windows: 'split', door: 'centre', heightM: 3.2, plants: true },
  'cafe-de-klos-72453': { name: 'De Klos', frame: '#1f1f1f', fascia: false, windows: 'panes', door: 'centre', sign: 'square', signHex: '#e3c020' },
  'cafe-diner-t-weesperplein-54930': { name: "'t Weesperplein", frame: '#2a2c2e', fascia: '#2a2c2e', windows: 'panes', door: 'centre', plants: true },
  'cafe-kadijk-70737': { name: 'Kadijk', frame: '#e8e6e0', fascia: false, windows: 'split', door: 'right', plants: true },
  'cafe-luxembourg-71813': { name: 'Luxembourg', frame: '#3a3634', fascia: false, awning: 'canopy', awningHex: '#3c3f3a', windows: 'split', door: 'centre', terrace: true },
  'cafe-maurits-18332': { name: 'Maurits', frame: BLACK, fascia: false, windows: 'big', door: 'centre', terrace: true },
  'cafe-modern-00305': { name: 'Modern', frame: '#efe9d6', fascia: false, windows: 'panes', door: 'centre', plants: true },
  'cafe-parlotte-69678': { name: 'Parlotte', frame: '#2a2a28', fascia: false, windows: 'split', door: 'none' },
  'cafe-piazza-82586': { name: 'Piazza', frame: '#6b1f1a', fascia: BLACK, windows: 'panes', door: 'left' },
  'cafe-warung-pas-22965': null,
  'cai-cai-15768': { name: 'Cai Cai', frame: '#5a1f22', fascia: '#1f4d3a', windows: 'panes', door: 'centre' },
  // Sheet 05.
  'calisto-76282': { name: 'Calisto', frame: '#e8e6e0', fascia: false, windows: 'split', door: 'centre', plants: true },
  'calle-ocho-59713': { name: 'Calle Ocho', frame: '#3a3a36', fascia: false, awning: 'canopy', awningHex: '#e8e4dc', windows: 'split', door: 'centre', terrace: true },
  'camino-taqueria-36027': { name: 'Camino', frame: '#2a2420', fascia: false, windows: 'panes', door: 'centre', transom: true, sign: 'round', signHex: '#e8e4dc' },
  'cannibale-royale-52862': { name: 'Cannibale Royale', frame: '#3d4652', fascia: false, awning: 'scalloped', awningHex: '#1f1f1f', windows: 'split', door: 'centre' },
  'cannibale-royale-handboogstraat-75878': { name: 'Cannibale Royale', frame: '#6b1f1a', fascia: BLACK, windows: 'split', door: 'left' },
  'cantina-caliente-70417': { name: 'Cantina Caliente', frame: '#2f6f7a', fascia: '#2f6f7a', windows: 'panes', door: 'centre', terrace: true },
  'cantine-de-caron-52471': null,
  'carletto-67455': { name: 'Carletto', frame: BLACK, fascia: BLACK, windows: 'split', door: 'centre', plants: true },
  'cartagena-62560': { name: 'Cartagena', frame: WHITE, fascia: false, windows: 'panes', transom: true, door: 'none', sign: 'square', signHex: '#d8501f' },
  'casa-nostra-52357': { name: 'Casa Nostra', frame: '#e8e6e0', fascia: false, windows: 'big', door: 'left' },
  'casa-peru-68820': { name: 'Casa Peru', frame: '#2a2420', fascia: false, windows: 'panes', door: 'right', plants: true },
  'cascada-40347': null,
  'castillo-79394': { name: 'Castillo', frame: '#2a2420', fascia: false, awning: 'scalloped', awningHex: '#1f4d3a', windows: 'panes', door: 'centre', plants: true },
  'cavataria-14248': { name: 'Cavataria', frame: '#4a2a1a', fascia: '#1f4d3a', awning: 'flat', awningHex: '#1f4d3a', windows: 'panes', door: 'centre', terrace: true },
  'cedars-05128': { name: 'Cedars', frame: '#9aa4aa', fascia: false, windows: 'split', door: 'none', heightM: 4.4 },
  'chadni-chowk-17679': { name: 'Chadni Chowk', frame: '#e8e2d4', fascia: false, windows: 'arched', door: 'left' },
  // Sheet 06.
  'cham-so-good-58473': { name: 'Cham So Good', frame: '#2a3a5a', fascia: '#2a3a5a', windows: 'big', door: 'left' },
  'chateau-amsterdam-13565': { name: 'Chateau', frame: '#3a3d40', fascia: false, windows: 'big', door: 'centre', heightM: 4.4 },
  'chhiwat-bladi-lunch-grill-62478': { name: 'Chhiwat Bladi', frame: '#2a2c2e', fascia: '#3a3d40', windows: 'split', door: 'centre' },
  'china-supreme-99001': null,
  'chuzo-king-77947': null,
  'cinq-oriental-bistro-47188': { name: 'Restaurant', frame: '#4a4440', fascia: '#4a4440', windows: 'big', door: 'centre', heightM: 4.2 },
  'city-noord-eethuis-84998': { name: 'City Noord', frame: WHITE, fascia: '#c8321f', windows: 'big', door: 'left' },
  'classico-37221': { name: 'Classico', frame: '#e3e0d8', fascia: '#d8d4ca', letters: '#5a5a58', windows: 'big', door: 'left' },
  'colima-71772': { name: 'Colima', frame: '#2a2c2e', fascia: '#3a3a36', windows: 'split', door: 'right' },
  'couscous-bar-61747': { name: 'Couscous Bar', frame: '#e6e2d6', fascia: false, awning: 'flat', awningHex: '#1f4d3a', windows: 'split', door: 'centre' },
  'couscous-club-53618': { name: 'Couscous Club', frame: '#4a3328', fascia: '#8a6a3a', windows: 'big', door: 'left' },
  'ctaste-77277': { name: 'Ctaste', frame: '#232a4a', fascia: '#232a4a', windows: 'arched', door: 'centre', transom: true },
  'cucina-casalinga-34703': { name: 'Cucina Casalinga', frame: WHITE, fascia: '#e3c020', letters: '#c8321f', windows: 'big', door: 'right' },
  'de-aardige-pers-58278': { name: 'De Aardige Pers', frame: '#8a4a26', fascia: '#8a4a26', windows: 'split', door: 'centre', heightM: 4 },
  'de-italiaan-66559': { name: 'De Italiaan', frame: '#2a2420', fascia: false, awning: 'flat', awningHex: '#b8282a', windows: 'panes', door: 'centre', terrace: true, plants: true },
  'de-juwelier-77678': { name: 'De Juwelier', frame: '#5a3a22', fascia: '#4a2e1c', windows: 'panes', transom: true, door: 'left', plants: true },
  // Sheet 07.
  'de-nieuwe-khl-80851': null,
  'de-nieuwe-rai-93538': { name: 'De Nieuwe Rai', frame: '#3a2a22', fascia: false, awning: 'flat', awningHex: '#c8282a', windows: 'panes', door: 'centre', terrace: true },
  'de-palmboom-71180': { name: 'De Palmboom', frame: '#e8e2d4', fascia: false, windows: 'panes', door: 'centre', transom: true },
  'de-patchka-56486': { name: 'De Patchka', frame: '#e8e6e0', fascia: '#f2f0ea', letters: '#c8321f', awning: 'flat', awningHex: '#e8e6e0', windows: 'big', door: 'right' },
  'de-pizzakamer-30670': { name: 'De Pizzakamer', frame: '#3a2a22', fascia: '#2a2420', windows: 'panes', door: 'centre', terrace: true },
  'desa-61346': null,
  'di-luca-43829': { name: 'Di Luca', frame: '#4a2e1c', fascia: false, windows: 'split', door: 'centre', terrace: true, plants: true },
  'dignita-93370': { name: 'Dignita', frame: '#e8e6e0', fascia: false, awning: 'flat', awningHex: '#d8d4ca', windows: 'arched', door: 'left', plants: true },
  'dionysos-taverna-36240': { name: 'Dionysos Taverna', frame: WHITE, fascia: '#b8282a', awning: 'flat', awningHex: '#e8e6e0', windows: 'split', door: 'centre', plants: true },
  'domenica-67762': null,
  'dong-son-takeaway-restaurant-72773': { name: 'Dong Son', frame: '#e3c020', fascia: '#e3c020', windows: 'split', door: 'centre' },
  'dos-73278': { name: 'Dos', frame: '#e8e2d4', fascia: false, windows: 'panes', door: 'centre', terrace: true },
  'eatmosfera-82121': { name: 'Eatmosfera', frame: WHITE, fascia: false, windows: 'big', door: 'left' },
  'eetcafe-koevoet-72933': { name: 'Koevoet', frame: '#1f1f1f', fascia: false, windows: 'panes', door: 'left', sign: 'lamp', plants: true },
  'eetcafe-t-pakhuis-75883': { name: "'t Pakhuis", frame: '#2a2a28', fascia: false, awning: 'striped', awningHex: '#1f1f1f', awningHex2: '#e8e4dc', windows: 'split', door: 'centre' },
  'eetcafe-van-beeren-82699': { name: 'Van Beeren', frame: '#1f2a24', fascia: '#e8e2d4', letters: '#c8321f', windows: 'panes', door: 'left', transom: true },
  // Sheet 08.
  'eggs-benaddicted-72390': { name: 'Eggs Benaddicted', frame: '#2a2c2e', fascia: false, awning: 'canopy', awningHex: '#e8e4dc', windows: 'split', door: 'centre', terrace: true },
  'el-torado-grill-68110': { name: 'El Torado', frame: BLACK, fascia: '#c8282a', windows: 'split', door: 'centre', transom: true },
  'ethiopisch-restaurant-addis-ababa-66610': { name: 'Addis Ababa', frame: '#3a2a22', fascia: false, windows: 'panes', door: 'left' },
  'fabian-78620': { name: 'Fabian', frame: '#1f2a24', fascia: '#1f2a24', windows: 'split', door: 'centre', sign: 'round', signHex: RED },
  'feduzzi-85026': { name: 'Feduzzi', frame: '#3a2a22', fascia: '#5a2a22', awning: 'flat', awningHex: '#9a1f22', windows: 'split', door: 'centre' },
  'fiaschetteria-pistoia-59698': null,
  'fiaschetteria-pistoia-73112': { name: 'Fiaschetteria Pistoia', frame: '#1f1f1f', fascia: false, windows: 'big', door: 'right' },
  'fiko-80855': null,
  'flore-68170': { name: 'Flore', frame: WHITE, fascia: false, awning: 'flat', awningHex: '#e8e4dc', windows: 'split', door: 'centre', terrace: true, heightM: 4.2 },
  'florentin-st-81813': null,
  'flow-62418': { name: 'Striphoek', frame: WHITE, fascia: '#c8282a', windows: 'big', transom: true, door: 'right', plants: true },
  'fondue-fondue-53352': { name: 'Fondue Fondue', frame: BLACK, fascia: false, windows: 'split', door: 'centre' },
  'food-brothers-83027': { name: 'Food Brothers', frame: '#3a3d40', fascia: '#2a6f8a', windows: 'split', door: 'left' },
  'franggo-63278': { name: 'Franggo', frame: '#2a2a2c', fascia: false, windows: 'big', door: 'left', sign: 'lamp' },
  'fujitora-61426': { name: 'Kaze', frame: '#2a2420', fascia: '#e8e2d4', letters: '#c8282a', windows: 'split', door: 'right' },
  'fuku-ramen-63449': { name: 'Fuku Ramen', frame: '#e8e2d4', fascia: false, windows: 'big', door: 'none' },
  // Sheet 09.
  'full-moon-garden-74474': { name: 'Full Moon Garden', frame: '#3a3634', fascia: false, windows: 'big', door: 'left', sign: 'round', signHex: '#e8e4dc' },
  'gaja-korean-bbq-bar-67636': { name: 'Gaja', frame: '#5a5a58', fascia: false, windows: 'big', door: 'left', heightM: 4.4 },
  'gartine-75728': { name: 'Gartine', frame: '#2a2a28', fascia: false, windows: 'big', door: 'left' },
  'gebr-hartering-82661': { name: 'Gebr. Hartering', frame: '#e8e6e0', fascia: false, windows: 'panes', transom: true, door: 'centre' },
  'golden-thali-50442': { name: 'Golden Thali', frame: WHITE, fascia: false, windows: 'big', transom: true, door: 'centre' },
  'grieks-restaurant-plato-38635': null,
  'hakata-senpachi-00201': { name: 'Hakata Senpachi', frame: '#e8e2d4', fascia: '#3a3d40', awning: 'flat', awningHex: '#3a3d40', windows: 'split', door: 'right' },
  'hannekes-boom-38899': null,
  'hanoi-old-quarter-restaurant-65114': null,
  'hans-im-gluck-51814': { name: 'Hans im Glück', frame: '#1f2a24', fascia: false, windows: 'arched', door: 'centre', terrace: true, heightM: 4.2 },
  'hap-hmm-63575': { name: 'Hap-Hmm', frame: '#2a2420', fascia: false, windows: 'panes', door: 'left' },
  'hap-li-90676': { name: 'Hap Li', frame: '#e8e2d4', fascia: false, windows: 'big', door: 'left', sign: 'square', signHex: RED },
  'harmani-63659': { name: 'Harmani', frame: '#1f1f1f', fascia: false, windows: 'panes', door: 'centre' },
  'havzan-37053': { name: 'Havzan', frame: '#3a3d40', fascia: '#3a3d40', windows: 'split', door: 'centre', sign: 'round', signHex: RED },
  'hawaiian-poke-bowl-37272': { name: 'Poke Bowl', frame: '#2a2c2e', fascia: '#2a2c2e', awning: 'canopy', awningHex: '#e8e4dc', windows: 'split', door: 'centre' },
  'hayran-61341': { name: 'Hayran', frame: '#4a4036', fascia: false, awning: 'flat', awningHex: '#3f4a32', windows: 'split', door: 'left' },
  // Sheet 10.
  'hinata-72121': { name: 'Hinata', frame: '#2a2420', fascia: false, windows: 'big', door: 'right' },
  'hoi-tin-77906': { name: 'Hoi Tin', frame: '#5a1f1a', fascia: false, awning: 'tiled', awningHex: '#b8602a', windows: 'panes', door: 'centre', sign: 'lamp' },
  'hummus-bistro-d-a-73434': { name: "Hummus d'A", frame: '#3a3634', fascia: '#8a6a3a', windows: 'split', door: 'left' },
  'hunkar-restaurant-16023': { name: 'Hunkar', frame: '#2a2c2e', fascia: '#2a2c2e', awning: 'canopy', awningHex: '#3a3d40', windows: 'split', door: 'centre', terrace: true, plants: true },
  'ibericus-amsterdam-79660': { name: 'Ibericus', frame: '#a0602a', fascia: '#1f1f1f', windows: 'panes', door: 'left' },
  'il-delfino-blu-36816': null,
  'il-primo-68332': { name: 'Il Primo', frame: '#e8e6e0', fascia: '#2a2c2e', windows: 'split', door: 'centre' },
  'il-sogno-08857': null,
  'il-tramezzino-68426': { name: 'Il Tramezzino', frame: '#4a2a1c', fascia: '#4a2a1c', windows: 'big', door: 'right' },
  'impero-romano-52924': { name: 'Impero Romano', frame: '#2a2420', fascia: '#3a2a22', windows: 'panes', door: 'centre', terrace: true },
  'incanto-79461': null,
  'indrapura-78846': { name: 'Indrapura', frame: '#1f1f1f', fascia: '#1f4d3a', windows: 'panes', door: 'centre', transom: true, sign: 'round', signHex: '#c9a227' },
  'insieme-71619': { name: 'Insieme', frame: '#e8e6e0', fascia: '#3a3d40', windows: 'panes', door: 'left', plants: true },
  'instock-amsterdam-69762': null,
  'isshin-59354': { name: 'Isshin', frame: '#2a2420', fascia: false, windows: 'big', door: 'left', sign: 'square', signHex: RED },
  'italia-oggi-71755': { name: 'Italia Oggi', frame: '#1f1f1f', fascia: false, windows: 'arched', door: 'left', plants: true },
  // Sheet 11.
  'jen-s-bing-81194': { name: "Jen's Bing", frame: '#e8e2d4', fascia: false, awning: 'flat', awningHex: '#b8b4aa', windows: 'big', door: 'right', plants: true },
  'jinso-07340': { name: 'Jinso', frame: '#2a2c2e', fascia: false, windows: 'split', door: 'centre', terrace: true, heightM: 4.4 },
  'joselito-tapas-79619': { name: 'Joselito', frame: '#1f2a24', fascia: false, windows: 'panes', door: 'centre' },
  'jun-93249': { name: 'Jun', frame: '#6b1f1a', fascia: '#6b1f1a', windows: 'panes', door: 'centre', plants: true },
  'kaagman-kortekaas-69080': null,
  'kafe-kontrast-36508': { name: 'Kontrast', frame: '#1f1f1f', fascia: '#1f1f1f', windows: 'big', door: 'centre', terrace: true },
  'kamasutra-78550': { name: 'Kamasutra', frame: '#e8e6e0', fascia: false, windows: 'arched', door: 'left', sign: 'round', signHex: RED },
  'kathmandu-kitchen-15728': { name: 'Intisari', frame: '#e8e6e0', fascia: false, windows: 'big', door: 'centre' },
  'kebaphan-69641': null,
  'kebec-corner-13694': null,
  'kerkzicht-29775': { name: 'Kerkzicht', frame: '#2a2420', fascia: false, windows: 'panes', door: 'centre', shutters: '#1f5a32', terrace: true },
  'kilimanjaro-37317': { name: 'Kilimanjaro', frame: '#e8e6e0', fascia: '#e3c020', windows: 'big', door: 'right' },
  'kim-s-so-18480': { name: "Kim's So", frame: '#2a2c2e', fascia: '#2a2c2e', windows: 'split', door: 'centre' },
  'klein-breda-78942': { name: 'Klein Breda', frame: '#1f2a2a', fascia: false, windows: 'panes', door: 'right', terrace: true },
  'koeah-75819': { name: 'Koeah', frame: '#3a3634', fascia: false, windows: 'split', door: 'centre', plants: true },
  'kokohili-01213': { name: 'Kokohili', frame: '#e8e6e0', fascia: '#2a2c2e', awning: 'flat', awningHex: '#9a2a3a', windows: 'split', door: 'centre' },
  // Sheet 12.
  'kreeftenbar-12628': null,
  'kruabuppha-87294': { name: 'Kruabuppha', frame: '#e8e6e0', fascia: '#2a2c2e', windows: 'big', door: 'left' },
  'kyo-82963': { name: 'Kyo', frame: '#6b1f22', fascia: false, windows: 'panes', transom: true, door: 'centre' },
  'la-brasa-67816': { name: 'La Brasa', frame: '#2a2c2e', fascia: false, windows: 'arched', door: 'right', plants: true },
  'la-bruschetta-87323': null,
  'la-cacerola-71888': { name: 'La Cacerola', frame: '#1f1f1f', fascia: false, windows: 'panes', door: 'left', plants: true },
  'la-cantina-79571': null,
  'la-fucina-81789': { name: 'La Fucina', frame: '#2a2c2e', fascia: '#2a2c2e', windows: 'split', door: 'right', terrace: true },
  'la-maschera-68857': { name: 'La Maschera', frame: '#2a2a28', fascia: false, windows: 'big', door: 'right' },
  'la-oliva-pintxos-y-vinos-72953': { name: 'La Oliva', frame: '#e8e2d4', fascia: false, windows: 'split', door: 'centre', sign: 'square', signHex: '#1f5a32' },
  'la-paella-78816': { name: 'La Paella', frame: '#2a2420', fascia: false, windows: 'split', door: 'left' },
  'la-perla-72878': { name: 'La Perla', frame: '#3d4652', fascia: false, awning: 'flat', awningHex: '#8a8070', windows: 'split', door: 'right', plants: true },
  'la-piazza-65128': { name: 'La Piazza', frame: '#2a2420', fascia: '#3a2a22', letters: '#c8282a', windows: 'big', door: 'left', heightM: 4.4 },
  'la-polpetta-31526': { name: 'La Polpetta', frame: '#2a2c2e', fascia: '#2a2c2e', windows: 'split', door: 'centre', plants: true },
  'la-reinita-empanadas-73572': { name: 'La Reinita', frame: '#2a2a28', fascia: false, awning: 'flat', awningHex: '#1f4d3a', windows: 'big', door: 'left' },
  'la-roma-81243': null,
  // Sheet 13.
  'la-ruelle-54949': null,
  'ladybird-fried-chicken-54143': { name: 'Ladybird', frame: '#7a2a1c', fascia: false, awning: 'flat', awningHex: '#e8e6e0', windows: 'big', door: 'right', terrace: true },
  'le-4-stagioni-57247': { name: 'Le 4 Stagioni', frame: '#3a3d40', fascia: false, windows: 'split', door: 'centre', terrace: true },
  'le-sud-76570': { name: 'Le Sud', frame: '#2a2a28', fascia: false, windows: 'big', door: 'left' },
  'lemoene-33308': null,
  'leonardo-s-ravioli-bar-59331': { name: "Leonardo's", frame: '#2a2a2c', fascia: '#2a2a2c', windows: 'big', door: 'right' },
  'les-zazous-79884': null,
  'leziz-71219': { name: 'Leziz', frame: '#2a2c2e', fascia: '#2a2c2e', windows: 'split', door: 'centre', plants: true },
  'little-chinatown-asian-cuisine-19312': null,
  'little-saigon-68107': { name: 'Little Saigon', frame: '#1f1f1f', fascia: '#e8e6e0', letters: '#2a2a2c', windows: 'big', door: 'centre', heightM: 4.2 },
  'lloyd-hotel-18149': null,
  'lokaal-van-de-stad-40908': { name: 'Lokaal van de Stad', frame: '#2a2420', fascia: false, awning: 'flat', awningHex: '#3a3634', windows: 'split', door: 'centre', terrace: true, plants: true },
  'lombardo-s-77099': { name: "Lombardo's", frame: '#2a2c2e', fascia: false, awning: 'flat', awningHex: '#1f1f1f', windows: 'panes', door: 'right' },
  'long-pura-70087': null,
  'loulou-pizzabar-57281': { name: 'Loulou', frame: '#2a2420', fascia: false, windows: 'arched', door: 'centre', plants: true },
  'lucca-due-80345': { name: 'Lucca Due', frame: '#5a1a14', fascia: '#5a1a14', windows: 'panes', transom: true, door: 'left', sign: 'lamp' },
  // Sheet 14.
  'lucius-75671': { name: 'Lucius', frame: '#1f2a2a', fascia: false, awning: 'flat', awningHex: '#1f2a2a', windows: 'panes', door: 'centre' },
  'lucky-house-73005': { name: 'Lucky House', frame: '#e8e6e0', fascia: false, windows: 'panes', door: 'left' },
  'luna-73311': { name: 'Luna', frame: '#6b1f22', fascia: '#3a2a22', windows: 'panes', door: 'right' },
  'lupe-72083': { name: 'Lupe', frame: '#2a2c2e', fascia: '#2a2c2e', windows: 'split', door: 'centre', terrace: true },
  'made-s-warung-26789': { name: "Made's Warung", frame: '#9a5a22', fascia: '#3a2a22', windows: 'panes', transom: true, door: 'right', plants: true },
  'maenaam-thai-75826': { name: 'Maenaam', frame: '#1f1f1f', fascia: false, windows: 'panes', door: 'centre', shutters: '#b8282a' },
  'makachi-64043': { name: 'Mercer', frame: '#e8e6e0', fascia: false, awning: 'flat', awningHex: '#2a2a2c', windows: 'big', door: 'centre' },
  'mama-makan-43487': { name: 'Mama Makan', frame: '#e3d8a0', fascia: false, windows: 'split', door: 'centre', heightM: 4.2 },
  'mamas-tapas-63129': { name: 'Viswinkel Tol', frame: WHITE, fascia: '#c8282a', awning: 'flat', awningHex: '#c8282a', windows: 'big', door: 'left' },
  'mangia-pizza-centrum-75482': { name: 'Mangia', frame: '#3a3a3a', fascia: false, windows: 'big', door: 'right', terrace: true },
  'mangiancora-65866': { name: 'Mangiancora', frame: '#2f4a40', fascia: false, windows: 'split', door: 'centre', sign: 'square', signHex: RED },
  'maris-piper-brasserie-36608': { name: 'Maris Piper', frame: '#1f1f1f', fascia: false, awning: 'canopy', awningHex: '#3a3d40', windows: 'panes', door: 'centre' },
  'marmaris-grill-pizza-73393': null,
  'maydanoz-56807': { name: 'Maydanoz', frame: '#2a2c2e', fascia: '#2a2c2e', letters: '#5fa58a', awning: 'striped', awningHex: '#3a3a3a', windows: 'big', door: 'left' },
  'mchi-42337': null,
  'meghna-78969': { name: 'Meghna', frame: '#3a1a1a', fascia: false, windows: 'panes', door: 'right' },
  // Sheet 15.
  'men-impossible-69882': { name: 'Men Impossible', frame: '#2a2420', fascia: false, windows: 'panes', door: 'left' },
  'merza-45331': null,
  'mesken-56710': { name: 'Mesken', frame: '#2a2420', fascia: '#7a1f2b', windows: 'split', door: 'centre', terrace: true },
  'middl-eat-67960': { name: "Middl'Eat", frame: '#e8e2d4', fascia: '#1f4d3a', windows: 'split', door: 'right' },
  'miko-s-28387': null,
  'mima-09184': { name: 'Mima', frame: '#3a3d40', fascia: false, windows: 'split', door: 'centre', heightM: 4.6 },
  'mirchi-63270': { name: 'Mirchi', frame: '#e8e6e0', fascia: '#2a2c2e', windows: 'big', door: 'right' },
  'miri-mary-83742': { name: 'Miri Mary', frame: '#2a3a5a', fascia: '#8a8a88', windows: 'split', door: 'centre' },
  'moak-pancakes-19677': { name: 'Moak', frame: '#e8e6e0', fascia: '#2a4a8a', windows: 'big', door: 'left' },
  'moche-67178': { name: 'Moche', frame: '#5a3a22', fascia: false, windows: 'arched', door: 'left' },
  'mogu-amsterdam-89620': { name: 'Loving Hut', frame: '#e8e2d4', fascia: '#e8e2d4', letters: '#3a7a3a', windows: 'big', door: 'right', plants: true },
  'momo-tibet-57116': { name: 'Momo Tibet', frame: '#c9a227', fascia: '#c8282a', windows: 'split', door: 'right' },
  'mont-blanc-66374': { name: 'Mont Blanc', frame: '#e8e2d4', fascia: false, windows: 'panes', door: 'right' },
  'moon-68473': null,
  'moshik-06274': { name: 'Moshik', frame: '#5a5048', fascia: false, windows: 'big', door: 'centre', heightM: 4.4 },
  'mount-everest-05308': { name: 'Mount Everest', frame: '#e8e6e0', fascia: '#c86a2a', windows: 'big', door: 'left' },
  // Sheet 16.
  'mr-gyoza-61236': { name: 'Mr Gyoza', frame: '#e8e2d4', fascia: false, windows: 'big', door: 'left' },
  'mr-sushi-54293': null,
  'muang-thai-66837': { name: 'Muang Thai', frame: '#d8ccb0', fascia: false, windows: 'split', door: 'none' },
  'mudavim-58188': null,
  'my-surinaamse-broodjes-36700': { name: 'Surinaamse', frame: '#e8e6e0', fascia: '#2f7a3a', windows: 'big', door: 'right', plants: true },
  'mythos-69645': { name: 'Mythos', frame: WHITE, fascia: '#2a4a8a', windows: 'panes', door: 'centre', sign: 'round', signHex: '#2a4a8a' },
  'naa-thai-63810': { name: 'Naa Thai', frame: '#2a2420', fascia: false, awning: 'flat', awningHex: '#b8282a', windows: 'big', door: 'left' },
  'nap-amsterdam-83408': null,
  'nara-nara-81960': { name: 'Nara Nara', frame: '#8fc8b0', fascia: false, awning: 'striped', awningHex: '#1f1f1f', windows: 'big', door: 'centre', heightM: 4.2 },
  'nefis-etli-ekmek-59658': { name: 'Nefis', frame: '#e8e6e0', fascia: false, awning: 'canopy', awningHex: '#9a1f2a', windows: 'big', door: 'right', terrace: true },
  'nikotin-19058': { name: 'Nikotin', frame: '#1f1f1f', fascia: false, windows: 'panes', door: 'centre', terrace: true, heightM: 4.2 },
  'nk-thai-noodles-68178': { name: 'Thai Corner', frame: '#e8e6e0', fascia: '#e8e6e0', windows: 'big', door: 'right', plants: true },
  'nnea-pizza-66802': { name: 'NNea', frame: '#1f3a8a', fascia: '#1f3a8a', windows: 'big', door: 'right' },
  'no-man-s-art-gallery-94050': { name: "No Man's Art", frame: '#e8e6e0', fascia: false, awning: 'flat', awningHex: '#c8282a', windows: 'panes', door: 'centre' },
  'noemi-37240': null,
  'nom-nom-vietnamese-foodshop-73355': null,
  // Sheet 17.
  'nonna-06423': { name: 'Nonna', frame: '#1f2a3a', fascia: '#1f2a3a', windows: 'split', door: 'centre' },
  'northeast-kitchen-67017': { name: 'Northeast Kitchen', frame: '#2a2c2e', fascia: false, awning: 'striped', awningHex: '#2a3a5a', awningHex2: '#d8d4ca', windows: 'split', door: 'centre' },
  'nyonya-78393': { name: 'Coffeeshop', frame: '#1f1f1f', fascia: '#1f1f1f', windows: 'big', door: 'right' },
  'o-bistro-68625': null,
  'o-mai-vietnamees-restaurant-78850': { name: "O'Mai", frame: '#e8e6e0', fascia: false, windows: 'big', door: 'centre' },
  'o-sole-mio-68570': { name: "O Sole Mio", frame: '#e8e6e0', fascia: '#1f3a6a', windows: 'big', door: 'right', transom: true },
  'obalade-suya-55235': { name: 'Obalade', frame: '#3a2a22', fascia: false, awning: 'flat', awningHex: '#3a2a22', windows: 'split', door: 'centre', plants: true },
  'oceania-40557': { name: 'Oceania', frame: '#1f2a24', fascia: '#3a2420', awning: 'flat', awningHex: '#2a2c2e', windows: 'split', door: 'centre', plants: true },
  'ode-aan-de-amstel-40353': { name: 'Ode aan de Amstel', frame: '#8a8478', fascia: false, windows: 'split', door: 'none' },
  'olijfje-65616': null,
  'omahe-72216': { name: 'Omahe', frame: '#e8e6e0', fascia: false, awning: 'flat', awningHex: '#e8e6e0', windows: 'big', door: 'left' },
  'omg-burger-79311': { name: 'OMG!', frame: '#e8e6e0', fascia: '#e8e6e0', letters: '#2f7a3a', windows: 'split', door: 'centre', terrace: true, plants: true },
  'ons-dorpje-21431': null,
  'oresti-s-taverna-62627': { name: "Oresti's", frame: '#e8e2d4', fascia: '#7a1f2b', windows: 'arched', door: 'centre', terrace: true, plants: true },
  'oriental-city-78751': { name: 'Oriental City', frame: '#e8e6e0', fascia: '#3a3d40', windows: 'split', door: 'left', sign: 'round', signHex: '#e3a020' },
  'osteria-bella-ciao-73586': null,
  // Sheet 18.
  'otaru-91498': { name: 'Otaru', frame: '#e8e2d4', fascia: '#e8e2d4', windows: 'panes', door: 'centre', shutters: '#8a6a4a' },
  'otemba-61722': { name: 'Otemba', frame: '#2a2420', fascia: false, awning: 'flat', awningHex: '#1f1f1f', windows: 'split', door: 'centre', terrace: true },
  'otemba-ramen-36441': { name: 'Otemba Ramen', frame: '#e8e6e0', fascia: false, windows: 'arched', door: 'left' },
  'pad-thai-72000': { name: 'Pad Thai', frame: '#e8e2d4', fascia: '#1f4d3a', windows: 'big', door: 'right' },
  'paik-s-noodle-75231': null,
  'palladio-70190': { name: 'Palladio', frame: '#2a2a28', fascia: false, awning: 'flat', awningHex: '#2a2a28', windows: 'panes', door: 'centre', sign: 'lamp' },
  'paloma-blanca-60566': { name: 'Coffee Roastery', frame: '#2a2c2e', fascia: false, awning: 'flat', awningHex: '#2a2c2e', windows: 'split', door: 'centre', plants: true },
  'pancakes-amsterdam-aan-t-ij-77894': null,
  'pannenkoekerij-gansi-87577': null,
  'papa-ali-mix-grill-82440': { name: 'Papa Ali', frame: WHITE, fascia: '#c8282a', windows: 'big', door: 'left', terrace: true },
  'pasta-e-pizza-62433': { name: 'Pasta e Pizza', frame: '#9ad8b0', fascia: '#1f4d3a', windows: 'split', door: 'right' },
  'pasta-paradijs-52857': { name: 'Pasta Paradijs', frame: '#2a2a2c', fascia: '#e8e6e0', letters: '#c8282a', windows: 'big', door: 'left' },
  'pastai-60962': { name: 'Pastai', frame: '#1f3a3a', fascia: false, windows: 'big', door: 'left' },
  'pastini-72218': { name: 'Pastini', frame: '#e8e6e0', fascia: '#3a3d40', windows: 'panes', door: 'right', transom: true },
  'pata-negra-71777': { name: 'Pata Negra', frame: '#4a3a1c', fascia: false, windows: 'split', door: 'centre', terrace: true },
  'pepenero-64223': { name: 'Pepenero', frame: '#e8e2d4', fascia: false, awning: 'flat', awningHex: '#2a2a2c', windows: 'arched', door: 'right', sign: 'lamp', plants: true },
  // Sheet 19.
  'pepenero-cucina-pizza-99914': null,
  'peperoncino-84094': { name: 'Peperoncino', frame: '#e8e6e0', fascia: false, awning: 'flat', awningHex: '#b8282a', windows: 'big', door: 'left', terrace: true },
  'perla-di-roma-48686': null,
  'petit-caron-73912': { name: 'Petit Caron', frame: '#e8e6e0', fascia: '#1f1f1f', awning: 'flat', awningHex: '#b8282a', windows: 'big', door: 'right', terrace: true },
  'pho-viet-76172': { name: 'Pho Viet', frame: '#8a3b12', fascia: false, windows: 'big', transom: true, door: 'right' },
  'pica-pica-90102': null,
  'picchino-53915': { name: 'Picchino', frame: '#1f1f1f', fascia: false, windows: 'big', door: 'right' },
  'pide-dunyas-78723': { name: 'Pide Dunyas', frame: '#2a2c2e', fascia: '#e8e6e0', letters: '#c8282a', windows: 'big', door: 'left' },
  'piet-de-leeuw-80082': { name: 'Piet de Leeuw', frame: '#1f1f1f', fascia: false, windows: 'panes', door: 'centre', sign: 'lamp' },
  'pizza-project-64561': null,
  'pizza-project-bar-69760': { name: 'De Nieuwe Vaart', frame: '#3a3d40', fascia: false, awning: 'flat', awningHex: '#a89a6a', windows: 'split', door: 'centre', terrace: true },
  'pizza-taxi-da-paolo-seba-66100': { name: 'Da Paolo', frame: '#e8e2d4', fascia: '#e8e2d4', windows: 'big', transom: true, door: 'left' },
  'pizzeria-steakhouse-ijburg-80574': { name: 'Steakhouse IJburg', frame: '#2a2c2e', fascia: '#2a2c2e', windows: 'big', door: 'centre' },
  'plato-loco-19305': { name: 'Plato Loco', frame: '#3a3d40', fascia: false, windows: 'big', door: 'none' },
  'proper-indofood-75795': { name: 'Proper Indofood', frame: '#2a2a2c', fascia: false, windows: 'panes', door: 'centre', sign: 'lamp' },
  'rainbowls-35465': { name: 'Rainbowls', frame: '#2a2a2c', fascia: false, awning: 'flat', awningHex: '#1f1f1f', windows: 'big', door: 'left', plants: true },
  // Sheet 20.
  'ramen-city-37023': null,
  'ramen-ism-78019': { name: 'Ramen-ism', frame: '#e8e2d4', fascia: false, windows: 'panes', transom: true, door: 'right' },
  'rangla-punjab-61813': { name: 'Rangla Punjab', frame: '#e8e6e0', fascia: '#3a2a5a', windows: 'big', door: 'right' },
  'rasoi-74500': { name: 'Rasoi', frame: '#e8e2d4', fascia: false, awning: 'flat', awningHex: '#d8d4ca', windows: 'big', door: 'right' },
  'reijnders-68746': { name: 'Reijnders', frame: '#4a2414', fascia: '#3a1a10', letters: '#c8282a', windows: 'panes', transom: true, door: 'centre', terrace: true },
  'renato-s-osteria-32916': { name: "Renato's", frame: '#2a4a8a', fascia: false, windows: 'panes', door: 'centre', plants: true },
  'restaurant-212-71575': { name: '212', frame: '#2a2420', fascia: false, windows: 'split', door: 'left', heightM: 4.4 },
  'restaurant-asian-fantasy-14927': null,
  'restaurant-ja-36832': { name: 'Ja', frame: '#e8e2d4', fascia: false, windows: 'arched', door: 'none', plants: true },
  'restaurant-klaproos-35403': { name: 'Uku', frame: '#2f6f7a', fascia: false, windows: 'big', door: 'centre', heightM: 4.4 },
  'restaurant-lastage-82260': { name: 'Lastage', frame: '#2a2a2c', fascia: false, windows: 'panes', transom: true, door: 'right', plants: true },
  'restaurant-sallora-51279': null,
  'restaurant-shiva-79404': { name: 'Shiva', frame: '#1f1f1f', fascia: '#1f1f1f', windows: 'panes', transom: true, door: 'left' },
  'ricardo-s-63107': { name: 'Rongsen', frame: '#e8e6e0', fascia: '#2a3a5a', windows: 'split', door: 'centre' },
  'rijnbar-80338': { name: 'Rijnbar', frame: '#2a2420', fascia: false, windows: 'big', door: 'left', sign: 'round', signHex: '#2f7a3a' },
  'rijsel-36544': null,
  // Sheet 21.
  'ristorante-papa-carlo-82585': { name: 'Papa Carlo', frame: '#3a2a22', fascia: false, awning: 'flat', awningHex: '#3a2a22', windows: 'panes', door: 'centre' },
  'ristorante-pizzeria-monte-verde-65953': { name: 'Monte Verde', frame: '#4a2414', fascia: '#1f4d3a', windows: 'panes', door: 'centre', transom: true },
  'ron-gastrobar-32011': { name: 'Ron Gastrobar', frame: '#e8e6e0', fascia: false, awning: 'canopy', awningHex: '#e8e6e0', windows: 'split', door: 'centre', terrace: true, plants: true },
  'roopram-roti-55550': { name: 'Roopram', frame: '#e8e6e0', fascia: false, windows: 'panes', door: 'centre' },
  'rossi-sandwiches-31005': { name: 'Rossi', frame: '#e8e6e0', fascia: false, windows: 'split', door: 'left' },
  'roum-cafe-61185': { name: 'Roum', frame: '#e8e2d4', fascia: false, awning: 'flat', awningHex: '#1f1f1f', windows: 'big', door: 'right', terrace: true },
  'royal-fook-long-42162': { name: 'Royal Fook Long', frame: '#3a3d40', fascia: '#9a1f22', windows: 'split', door: 'centre' },
  'royal98-53823': { name: 'Royal98', frame: '#1f1f1f', fascia: false, windows: 'big', door: 'left' },
  'royalvis-traiteur-18311': { name: 'Royal Med', frame: '#3a3d40', fascia: '#2a3a5a', windows: 'big', door: 'centre', rollers: '#2a3a6a' },
  'rue-la-bastille-77670': null,
  'rufus-restaurant-57012': { name: 'Rufus', frame: '#1f1f1f', fascia: '#1f1f1f', windows: 'big', door: 'right', terrace: true },
  'sab-s-deli-36070': { name: "Sab's", frame: '#3a2a22', fascia: false, awning: 'flat', awningHex: '#1f4d3a', windows: 'split', door: 'centre', terrace: true, plants: true },
  'sababa-58581': { name: 'Sababa', frame: '#e8e2d4', fascia: '#c8282a', windows: 'split', door: 'left' },
  'saeed-s-curry-house-54207': { name: "Saeed's", frame: '#5a1a14', fascia: false, awning: 'striped', awningHex: '#c8282a', windows: 'big', door: 'right' },
  'sagardi-72053': null,
  'sahan-92837': { name: 'Sahan', frame: '#2a2c2e', fascia: '#e8e6e0', letters: '#2a2c2e', awning: 'canopy', awningHex: '#3a3d40', windows: 'split', door: 'centre', terrace: true, plants: true },
  // Sheet 22.
  'salento-latino-78584': { name: 'Salento Latino', frame: '#3a3d40', fascia: false, awning: 'flat', awningHex: '#b8282a', windows: 'split', door: 'centre' },
  'salvatorica-74729': { name: 'Salvatorica', frame: '#2a2c2e', fascia: false, windows: 'split', door: 'centre' },
  'sama-sebo-65990': { name: 'Sama Sebo', frame: '#e8e2d4', fascia: '#3a2a22', windows: 'panes', door: 'right' },
  'samba-kitchen-59252': { name: 'Samba Kitchen', frame: '#e8e6e0', fascia: '#e8e6e0', windows: 'big', door: 'left', terrace: true },
  'sapporo-ramen-sora-35936': null,
  'scheltema-67522': null,
  'schiller-78854': { name: 'Schiller', frame: '#e3dcc8', fascia: '#3a3d40', windows: 'split', door: 'centre', terrace: true, heightM: 4.2 },
  'seafood-bistro-78815': { name: 'Seafood Bistro', frame: '#e8e6e0', fascia: false, windows: 'big', door: 'left', sign: 'square', signHex: '#e3c020' },
  'seasons-restaurant-75049': { name: 'Seasons', frame: '#e8e2d4', fascia: false, windows: 'big', door: 'right', transom: true },
  'semai-52074': { name: 'Semai', frame: '#e8e6e0', fascia: '#3a3d40', windows: 'split', door: 'centre' },
  'semhar-74838': { name: 'Semhar', frame: '#7a1f1a', fascia: '#7a1f1a', letters: '#e3c020', windows: 'split', door: 'right' },
  'senayan-73612': { name: 'Senayan', frame: '#e8e2d4', fascia: '#2a2c2e', windows: 'split', door: 'centre' },
  'seth-takeout-76929': { name: 'Seth', frame: '#e8e6e0', fascia: false, windows: 'big', door: 'right' },
  'sham-87688': { name: 'Sham', frame: '#1f1f1f', fascia: '#1f1f1f', letters: '#c9a227', windows: 'arched', door: 'centre', terrace: true },
  'sham-maza-80856': { name: 'Sham Maza', frame: '#2a2a28', fascia: '#2a2a28', windows: 'big', door: 'centre' },
  'sherpa-39376': { name: 'Sherpa', frame: '#2a2c2e', fascia: '#2a2c2e', windows: 'big', door: 'right', terrace: true },
  // Sheet 23.
  'shiki-79220': null,
  'sichuan-food-68478': { name: 'Sichuan Food', frame: '#2a2420', fascia: false, awning: 'flat', awningHex: '#c9a227', windows: 'big', door: 'centre', terrace: true },
  'silk-road-kebab-house-80959': { name: 'Silk Road', frame: '#2a2c2e', fascia: '#2a2c2e', windows: 'big', door: 'centre' },
  'sinne-35937': { name: 'Sinne', frame: '#2a2c2e', fascia: false, awning: 'flat', awningHex: '#3a3d40', windows: 'big', door: 'left' },
  't-vliegertje-36397': { name: "'t Vliegertje", frame: '#1f1f1f', fascia: '#1f2a3a', windows: 'split', door: 'right', terrace: true },
  'vermeer-82718': { name: 'Vermeer', frame: '#8a8a88', fascia: false, windows: 'split', door: 'none' },
  'vinkeles-74123': null,
};
