import { planTiles } from './buildingTileSource.js';
import { tileKey } from './slippyTiles.js';

type PublicFeature={layer:'waterdeel'|'overbruggingsdeel'|'begroeidterreindeel'|'wegdeel'|'ondersteunendwegdeel'|'scheiding_lijn';feature:any};
type PublicTile={version:4;key:string;features:PublicFeature[]};
type TileMeta={key:string;url:string;sha256:string;contentSha256:string;bytes:number;water:number;bridges:number;green:number;footpaths:number;cycleways:number;boundaries:number;sourceVertices:number;publishedVertices:number};
type PublicIndex={version:4;zoom:number;releaseId:string;areaId:string;sourceContextSha256:string;geometrySource:'bgt-display-simplified';simplificationToleranceM:number;boundaryHeightM:number;boundaryHeightSource:'illustrative-display-prior';bridgeDepthM:number;bridgeDepthSource:'illustrative-display-prior';renderPolicy:'water-greenery-active-mobility-quay-v5-bridge-understructure';origin:{lng:number;lat:number};water:number;bridges:number;green:number;footpaths:number;cycleways:number;boundaries:number;sourceVertices:number;publishedVertices:number;tileList:string[];tiles:TileMeta[]};
const {THREE}=window.CanalRecallThree;
const sha256=async(bytes:ArrayBuffer)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');
export const STUDY_PUBLIC_REALM_MIN_ZOOM=15.25;
async function decode(bytes:ArrayBuffer):Promise<PublicTile>{const view=new Uint8Array(bytes);if(view[0]!==0x1f||view[1]!==0x8b)return JSON.parse(new TextDecoder().decode(view));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text());}
const open=(ring:number[][])=>ring.length>1&&ring[0][0]===ring.at(-1)?.[0]&&ring[0][1]===ring.at(-1)?.[1]?ring.slice(0,-1):ring;
type IndexedBatch={positions:number[];indices:number[]};
function appendPolygon(rings:number[][][],height:number,batch:IndexedBatch){if(!rings.length)return;const opened=rings.map(open);if(opened.some(ring=>ring.length<3||ring.some(point=>point.length<2||!point.slice(0,2).every(Number.isFinite)||Math.abs(point[0])>2000||Math.abs(point[1])>2000)))throw Error('Invalid public-realm polygon');const contour=opened[0].map(([x,z])=>new THREE.Vector2(x,-z)),holes=opened.slice(1).map(ring=>ring.map(([x,z])=>new THREE.Vector2(x,-z))),faces=THREE.ShapeUtils.triangulateShape(contour,holes),vertices=opened.flat(),base=batch.positions.length/3;for(const [x,z]of vertices)batch.positions.push(x,-z,height);for(const face of faces)for(const index of face)batch.indices.push(base+index);}
function polygons(feature:any){const geometry=feature?.geometry;if(!geometry||!['Polygon','MultiPolygon'].includes(geometry.type))throw Error('Invalid public-realm geometry');return geometry.type==='Polygon'?[geometry.coordinates]:geometry.coordinates;}
function lines(feature:any){const geometry=feature?.geometry;if(!geometry||!['LineString','MultiLineString'].includes(geometry.type))throw Error('Invalid public-realm line geometry');return geometry.type==='LineString'?[geometry.coordinates]:geometry.coordinates;}
const vertexCount=(features:PublicFeature[])=>features.reduce((sum,item)=>sum+item.feature.geometry.coordinates.flat(Infinity).length/2,0);
function appendBoundary(line:number[][],height:number,batch:IndexedBatch,baseHeight=.025){if(line.length<2||line.some(point=>point.length<2||!point.slice(0,2).every(Number.isFinite))||![height,baseHeight].every(Number.isFinite)||height<=baseHeight)throw Error('Invalid public-realm boundary');for(let i=1;i<line.length;i++){const a=line[i-1],b=line[i],base=batch.positions.length/3;batch.positions.push(a[0],-a[1],baseHeight,b[0],-b[1],baseHeight,b[0],-b[1],height,a[0],-a[1],height);batch.indices.push(base,base+1,base+2,base,base+2,base+3);}}

export class StudyPublicRealm{
  enabled=true;ready=false;debugWater=0;debugBridges=0;debugBridgeMeshes=0;debugGreen=0;debugFootpaths=0;debugCycleways=0;debugBoundaries=0;debugResident=0;debugMeshes=0;debugGeometryBytes=0;private scene=new THREE.Scene();private layer:any;private index:PublicIndex|null=null;private metas=new Map<string,TileMeta>();private resources=new Map<string,any[]>();private controllers=new Map<string,AbortController>();private queue:string[]=[];private inFlight=0;
  constructor(private map:any,private maplibregl:any,private areaId=''){this.layer=this.makeLayer();this.scene.add(new THREE.HemisphereLight(0xffffff,0x496168,2.1));const sun=new THREE.DirectionalLight(0xfff1d8,1.8);sun.position.set(-2,-1,4);this.scene.add(sun);if(!map.getLayer(this.layer.id))map.addLayer(this.layer,map.getLayer('road_area_pattern')?'road_area_pattern':undefined);}
  get debugRenderable(){return this.enabled&&this.ready&&this.map.getZoom()>=STUDY_PUBLIC_REALM_MIN_ZOOM;}
  async load(pointerUrl:string){const response=await fetch(pointerUrl,{cache:'no-store'});if(!response.ok)throw Error('Study public-realm pointer unavailable');const pointer=await response.json(),value=pointer?.studyPublicRealm as PublicIndex;if(pointer?.version!==1||!pointer.releaseId||value?.version!==4||value.releaseId!==pointer.releaseId||value.areaId!==pointer.areaId||value.sourceContextSha256!==pointer.context?.sha256||value.geometrySource!=='bgt-display-simplified'||value.simplificationToleranceM!==.08||value.boundaryHeightM!==.55||value.boundaryHeightSource!=='illustrative-display-prior'||value.bridgeDepthM!==.55||value.bridgeDepthSource!=='illustrative-display-prior'||value.renderPolicy!=='water-greenery-active-mobility-quay-v5-bridge-understructure'||value.zoom!==16||!Array.isArray(value.tiles)||!Array.isArray(value.tileList)||value.tiles.length!==value.tileList.length||![value.origin?.lng,value.origin?.lat,value.water,value.bridges,value.green,value.footpaths,value.cycleways,value.boundaries,value.sourceVertices,value.publishedVertices].every(Number.isFinite)||value.publishedVertices>value.sourceVertices)throw Error('Study public-realm release binding mismatch');this.index=value;this.metas=new Map(value.tiles.map(tile=>[tile.key,tile]));const sourceVertices=value.tiles.reduce((sum,tile)=>sum+tile.sourceVertices,0),publishedVertices=value.tiles.reduce((sum,tile)=>sum+tile.publishedVertices,0);if(this.metas.size!==value.tiles.length||sourceVertices!==value.sourceVertices||publishedVertices!==value.publishedVertices||value.tiles.some(tile=>!value.tileList.includes(tile.key)||!/^[a-f0-9]{64}$/.test(tile.sha256)||!/^[a-f0-9]{64}$/.test(tile.contentSha256)||![tile.bytes,tile.water,tile.bridges,tile.green,tile.footpaths,tile.cycleways,tile.boundaries,tile.sourceVertices,tile.publishedVertices].every(Number.isFinite)||tile.publishedVertices>tile.sourceVertices))throw Error('Invalid study public-realm index');this.debugWater=value.water;this.debugBridges=value.bridges;this.debugGreen=value.green;this.debugFootpaths=value.footpaths;this.debugCycleways=value.cycleways;this.debugBoundaries=value.boundaries;this.layer.origin=value.origin;this.ready=true;this.map.on('moveend',()=>this.update());this.update();this.map.triggerRepaint();}
  setEnabled(value:boolean){this.enabled=!!value;if(this.enabled)this.update();else this.clearResources();this.map.triggerRepaint();}
  dispose(){this.clearResources();this.ready=false;}
  private clearResources(){for(const controller of this.controllers.values())controller.abort();for(const meshes of this.resources.values())this.disposeMeshes(meshes);this.controllers.clear();this.resources.clear();this.queue=[];this.refreshStats();}
  private update(){if(!this.enabled||!this.ready||!this.index)return;if(this.map.getZoom()<STUDY_PUBLIC_REALM_MIN_ZOOM){this.clearResources();return;}const b=this.map.getBounds(),plan=planTiles({west:b.getWest(),south:b.getSouth(),east:b.getEast(),north:b.getNorth()},this.resources.keys(),{zoom:this.index.zoom,margin:1,budget:12}),wanted=new Set(plan.wanted);for(const key of plan.evict){const meshes=this.resources.get(key);if(meshes){this.disposeMeshes(meshes);this.resources.delete(key);}}for(const[key,controller]of this.controllers)if(!wanted.has(key)){controller.abort();this.controllers.delete(key);}this.queue=plan.load.map(tileKey).filter(key=>this.metas.has(key)&&!this.resources.has(key)&&!this.controllers.has(key));this.refreshStats();this.pump();}
  private pump(){while(this.inFlight<2&&this.queue.length){const key=this.queue.shift();if(key)void this.fetchTile(key);}}
  private async fetchTile(key:string){const meta=this.metas.get(key);if(!meta)return;const controller=new AbortController();this.controllers.set(key,controller);this.inFlight++;try{const response=await fetch(meta.url,{signal:controller.signal});if(!response.ok)throw Error('Study public-realm tile unavailable');const bytes=await response.arrayBuffer();if(await sha256(bytes)!==meta.contentSha256)throw Error('Study public-realm content hash mismatch');const tile=await decode(bytes);if(tile.version!==4||tile.key!==key||!Array.isArray(tile.features))throw Error('Invalid study public-realm tile');const count=(predicate:(item:PublicFeature)=>boolean)=>tile.features.filter(predicate).length;if(vertexCount(tile.features)!==meta.publishedVertices||count(item=>item.layer==='waterdeel')!==meta.water||count(item=>item.layer==='overbruggingsdeel')!==meta.bridges||count(item=>item.layer==='begroeidterreindeel')!==meta.green||count(item=>/voetpad/.test(item.feature.kind))!==meta.footpaths||count(item=>item.feature.kind==='fietspad')!==meta.cycleways||count(item=>item.layer==='scheiding_lijn')!==meta.boundaries)throw Error('Invalid study public-realm tile');const meshes=this.createMeshes(tile.features);if(!controller.signal.aborted){this.resources.set(key,meshes);for(const mesh of meshes)this.scene.add(mesh);}}catch(error){if((error as Error).name!=='AbortError')console.warn(`Study public-realm tile ${key} unavailable.`,error);}finally{this.controllers.delete(key);this.inFlight--;this.refreshStats();this.pump();this.map.triggerRepaint();}}
  private createMeshes(features:PublicFeature[]){const batches=new Map<string,IndexedBatch>(),batch=(kind:string)=>{const value=batches.get(kind)??{positions:[],indices:[]};batches.set(kind,value);return value;},add=(kind:string,polygon:number[][][],height:number)=>appendPolygon(polygon,height,batch(kind));for(const item of features){if(!['waterdeel','overbruggingsdeel','begroeidterreindeel','wegdeel','ondersteunendwegdeel','scheiding_lijn'].includes(item.layer))throw Error('Invalid public-realm layer');if(item.layer==='scheiding_lijn'){for(const line of lines(item.feature))appendBoundary(line,.55,batch('boundary'));continue;}for(const polygon of polygons(item.feature)){if(item.layer==='waterdeel')add('water',polygon,.025);else if(item.layer==='overbruggingsdeel'){for(const ring of polygon)appendBoundary(ring,.015,batch('bridge'),-.55);}else if(item.layer==='begroeidterreindeel')add('green',polygon,.018);else if(/voetpad/.test(item.feature.kind))add('footpath',polygon,.035);else if(item.feature.kind==='fietspad')add('cycleway',polygon,.04);}}const styles:any={water:{color:'#7c9fb0',emissive:'#476979',emissiveIntensity:.28,roughness:.34,metalness:.03,clearcoat:.65,clearcoatRoughness:.24,transparent:true,opacity:.38,depthWrite:false},bridge:{color:'#6f6558',roughness:.96},green:{color:'#7f9b65',roughness:1},footpath:{color:'#cbbfa8',roughness:.98},cycleway:{color:'#9d6f5d',roughness:.95},boundary:{color:'#817a6b',roughness:1}};const meshes:any[]=[];for(const[kind,value]of batches){if(!value.indices.length)continue;const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(value.positions,3));geometry.setIndex(value.indices);geometry.computeVertexNormals();geometry.computeBoundingSphere();const material=kind==='water'?new THREE.MeshPhysicalMaterial({...styles[kind],side:THREE.DoubleSide}):new THREE.MeshStandardMaterial({...styles[kind],side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1}),mesh=new THREE.Mesh(geometry,material);mesh.name=`city-appearance-public-${kind}`;mesh.frustumCulled=false;meshes.push(mesh);}return meshes;}
  private disposeMeshes(meshes:any[]){for(const mesh of meshes){this.scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}}
  private refreshStats(){const meshes=[...this.resources.values()].flat(),geometryBytes=(geometry:any)=>Object.values(geometry.attributes??{}).reduce((sum:number,attribute:any)=>sum+(attribute.array?.byteLength||0),0)+(geometry.index?.array?.byteLength||0);this.debugResident=this.resources.size;this.debugMeshes=meshes.length;this.debugBridgeMeshes=meshes.filter(mesh=>mesh.name==='city-appearance-public-bridge').length;this.debugGeometryBytes=meshes.reduce((sum,mesh)=>sum+geometryBytes(mesh.geometry),0);}
  private makeLayer(){const owner=this;let camera:any,renderer:any,suffix=this.areaId?`-${this.areaId.replace(/[^a-z0-9-]/gi,'-')}`:'';const layer:any={id:`city-appearance-bgt-public-realm${suffix}`,type:'custom',renderingMode:'3d',origin:null,onAdd(_map:any,gl:any){camera=new THREE.Camera();renderer=new THREE.WebGLRenderer({canvas:owner.map.getCanvas(),context:gl,antialias:true});renderer.autoClear=false;},render(_gl:any,args:any){const origin=layer.origin;if(!owner.debugRenderable||!origin)return;const coordinate=owner.maplibregl.MercatorCoordinate.fromLngLat([origin.lng,origin.lat],0),scale=coordinate.meterInMercatorCoordinateUnits(),transform=new THREE.Matrix4().makeTranslation(coordinate.x,coordinate.y,coordinate.z).scale(new THREE.Vector3(scale,-scale,scale));camera.projectionMatrix.fromArray(args.defaultProjectionData.mainMatrix).multiply(transform);renderer.resetState();renderer.render(owner.scene,camera);}};return layer;}
}

declare global{interface Window{CanalRecallThree:any;CanalRecallStudyPublicRealm?:{StudyPublicRealm:typeof StudyPublicRealm}}}
window.CanalRecallStudyPublicRealm={StudyPublicRealm};
