import { planTiles } from './buildingTileSource.js';
import { tileKey } from './slippyTiles.js';
import { facadeBatchOpacity } from './cityAppearanceFacadeLod.js';
type FacadeBatch={kind:string;colour:string;triangles:number[]};type FacadeTile={version:1;key:string;batches:FacadeBatch[]};type TileMeta={key:string;url:string;sha256:string;contentSha256:string;bytes:number;triangles:number};type FacadeIndex={version:1;zoom:number;releaseId:string;areaId:string;sourceBlockSha256:string;styleSource:'procedural-prior-not-measured';geometrySource:'3dbag-lod22-wall-surfaces';openingStyle:'era-rhythm-recessed-sash-entrance-v3';reliefOffsetM:number;origin:{lng:number;lat:number};windows:number;doors:number;trims:number;tileList:string[];tiles:TileMeta[]};
const {THREE}=window.CanalRecallThree;const sha256=async(bytes:ArrayBuffer)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');async function decode(bytes:ArrayBuffer):Promise<FacadeTile>{const view=new Uint8Array(bytes);if(view[0]!==0x1f||view[1]!==0x8b)return JSON.parse(new TextDecoder().decode(view));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text());}
export const STUDY_FACADE_MIN_ZOOM=16.5;
export class StudyFacades{
  enabled=true;ready=false;debugWindows=0;debugDoors=0;debugTrims=0;debugTriangles=0;debugResident=0;debugGeometryBytes=0;debugVisibleMeshes=0;private scene:any;private layer:any;private index:FacadeIndex|null=null;private metas=new Map<string,TileMeta>();private resources=new Map<string,any[]>();private controllers=new Map<string,AbortController>();private queue:string[]=[];private inFlight=0;
  constructor(private map:any,private maplibregl:any,private areaId=''){this.scene=new THREE.Scene();this.scene.add(new THREE.HemisphereLight(0xffffff,0x596166,2.2));this.layer=this.makeLayer();if(!map.getLayer(this.layer.id))map.addLayer(this.layer);}
  get debugRenderable(){return this.enabled&&this.ready&&this.map.getZoom()>=STUDY_FACADE_MIN_ZOOM;}
  async load(pointerUrl:string):Promise<void>{const response=await fetch(pointerUrl,{cache:'no-store'});if(!response.ok)throw Error('Study facade pointer unavailable');const pointer=await response.json(),value=pointer?.studyFacades as FacadeIndex;if(pointer?.version!==1||!pointer.releaseId||value?.version!==1||value.releaseId!==pointer.releaseId||value.areaId!==pointer.areaId||value.sourceBlockSha256!==pointer.sourceHashes?.block||value.styleSource!=='procedural-prior-not-measured'||value.geometrySource!=='3dbag-lod22-wall-surfaces'||value.openingStyle!=='era-rhythm-recessed-sash-entrance-v3'||value.reliefOffsetM!==.18||value.zoom!==16||!Array.isArray(value.tiles)||!Array.isArray(value.tileList)||value.tiles.length!==value.tileList.length||![value.origin?.lng,value.origin?.lat,value.windows,value.doors,value.trims].every(Number.isFinite))throw Error('Study facade release binding mismatch');this.index=value;this.metas=new Map(value.tiles.map(tile=>[tile.key,tile]));if(this.metas.size!==value.tiles.length||value.tiles.some(tile=>!value.tileList.includes(tile.key)||!/^[a-f0-9]{64}$/.test(tile.sha256)||!/^[a-f0-9]{64}$/.test(tile.contentSha256)))throw Error('Invalid study facade tile index');this.debugWindows=value.windows;this.debugDoors=value.doors;this.debugTrims=value.trims;this.layer.origin=value.origin;this.ready=true;this.map.on('moveend',()=>this.update());this.update();this.map.triggerRepaint();}
  setEnabled(value:boolean){this.enabled=!!value;if(this.enabled)this.update();else this.clearResources();this.map.triggerRepaint();}dispose(){this.clearResources();this.ready=false;}
  private clearResources(){for(const controller of this.controllers.values())controller.abort();for(const meshes of this.resources.values())this.disposeMeshes(meshes);this.controllers.clear();this.resources.clear();this.queue=[];this.debugVisibleMeshes=0;this.refreshStats();}
  private update(){if(!this.enabled||!this.ready||!this.index)return;if(this.map.getZoom()<STUDY_FACADE_MIN_ZOOM){this.clearResources();return;}const b=this.map.getBounds(),plan=planTiles({west:b.getWest(),south:b.getSouth(),east:b.getEast(),north:b.getNorth()},this.resources.keys(),{zoom:this.index.zoom,margin:1,budget:12}),wanted=new Set(plan.wanted);for(const key of plan.evict){const meshes=this.resources.get(key);if(meshes){this.disposeMeshes(meshes);this.resources.delete(key);}}for(const[key,controller]of this.controllers)if(!wanted.has(key)){controller.abort();this.controllers.delete(key);}this.queue=plan.load.map(tileKey).filter(key=>this.metas.has(key)&&!this.resources.has(key)&&!this.controllers.has(key));this.refreshStats();this.pump();}
  private pump(){while(this.inFlight<2&&this.queue.length){const key=this.queue.shift();if(key)void this.fetchTile(key);}}
  private async fetchTile(key:string){const meta=this.metas.get(key);if(!meta)return;const controller=new AbortController();this.controllers.set(key,controller);this.inFlight++;try{const response=await fetch(meta.url,{signal:controller.signal});if(!response.ok)throw Error('Study facade tile unavailable');const bytes=await response.arrayBuffer();if(await sha256(bytes)!==meta.contentSha256)throw Error('Study facade tile content hash mismatch');const tile=await decode(bytes);if(tile.version!==1||tile.key!==key||!Array.isArray(tile.batches))throw Error('Invalid study facade tile');const meshes=this.createMeshes(tile.batches);if(!controller.signal.aborted){this.resources.set(key,meshes);for(const mesh of meshes)this.scene.add(mesh);}}catch(error){if((error as Error).name!=='AbortError')console.warn(`Study facade tile ${key} unavailable.`,error);}finally{this.controllers.delete(key);this.inFlight--;this.refreshStats();this.pump();this.map.triggerRepaint();}}
  private createMeshes(batches:FacadeBatch[]){const meshes=[];for(const batch of batches){if(!/^#[a-f0-9]{6}$/i.test(batch.colour)||!Array.isArray(batch.triangles)||batch.triangles.length%9||batch.triangles.some((number,index)=>!Number.isFinite(number)||(index%3===2?(number<-.8||number>100):Math.abs(number)>2000)))throw Error('Invalid study facade batch');const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(batch.triangles,3));const glass=batch.kind.startsWith('windowGlass')||batch.kind==='shopGlass';if(glass)geometry.computeVertexNormals();geometry.computeBoundingSphere();const material=glass?new THREE.MeshStandardMaterial({color:batch.colour,roughness:.34,metalness:.08,side:THREE.DoubleSide}):new THREE.MeshBasicMaterial({color:batch.colour,side:THREE.DoubleSide}),mesh=new THREE.Mesh(geometry,material);mesh.frustumCulled=false;mesh.renderOrder=4;mesh.userData.triangles=batch.triangles.length/9;mesh.userData.facadeBatchKind=batch.kind;meshes.push(mesh);}return meshes;}
  private disposeMeshes(meshes:any[]){for(const mesh of meshes){this.scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}}private refreshStats(){const meshes=[...this.resources.values()].flat(),geometryBytes=(geometry:any)=>Object.values(geometry.attributes??{}).reduce((sum:number,attribute:any)=>sum+(attribute.array?.byteLength||0),0)+(geometry.index?.array?.byteLength||0);this.debugResident=this.resources.size;this.debugTriangles=meshes.reduce((sum,mesh)=>sum+(mesh.userData.triangles||0),0);this.debugGeometryBytes=meshes.reduce((sum,mesh)=>sum+geometryBytes(mesh.geometry),0);}
  private makeLayer(){const owner=this;let camera:any,renderer:any,suffix=this.areaId?`-${this.areaId.replace(/[^a-z0-9-]/gi,'-')}`:'';const layer:any={id:`city-appearance-contextual-facades${suffix}`,type:'custom',renderingMode:'3d',origin:null,onAdd(_map:any,gl:any){camera=new THREE.Camera();renderer=new THREE.WebGLRenderer({canvas:owner.map.getCanvas(),context:gl,antialias:true});renderer.autoClear=false;},render(_gl:any,args:any){const origin=layer.origin;if(!owner.debugRenderable||!origin)return;const zoom=owner.map.getZoom(),meshes=[...owner.resources.values()].flat();for(const mesh of meshes){const opacity=facadeBatchOpacity(mesh.userData.facadeBatchKind,zoom);mesh.visible=opacity>0;if(mesh.material.opacity!==opacity){mesh.material.opacity=opacity;mesh.material.transparent=opacity<1;mesh.material.depthWrite=opacity===1;mesh.material.needsUpdate=true;}}owner.debugVisibleMeshes=meshes.filter(mesh=>mesh.visible).length;if(!owner.debugVisibleMeshes)return;const coordinate=owner.maplibregl.MercatorCoordinate.fromLngLat([origin.lng,origin.lat],0),scale=coordinate.meterInMercatorCoordinateUnits(),transform=new THREE.Matrix4().makeTranslation(coordinate.x,coordinate.y,coordinate.z).scale(new THREE.Vector3(scale,-scale,scale));camera.projectionMatrix.fromArray(args.defaultProjectionData.mainMatrix).multiply(transform);renderer.resetState();renderer.render(owner.scene,camera);}};return layer;}
}
declare global{interface Window{CanalRecallThree:any;CanalRecallStudyFacades?:{StudyFacades:typeof StudyFacades}}}window.CanalRecallStudyFacades={StudyFacades};
