import { planTiles } from './buildingTileSource.js';
import { tileKey } from './slippyTiles.js';

type RoofPoint=[number,number,number];
type RoofBuilding={id:string;colour:string;surfaces:RoofPoint[][][]};
type RoofTile={version:1;key:string;buildings:RoofBuilding[]};
type TileMeta={key:string;url:string;sha256:string;contentSha256:string;bytes:number;buildings:number;surfaces:number};
type RoofIndex={version:2;zoom:number;releaseId:string;areaId:string;sourceBlockSha256:string;geometrySource:'3dbag-lod22-roof-surfaces';selectionPolicy:'per-source-surface-compatible-v2';delivery:'owner-tiles-v1';origin:{lng:number;lat:number};candidateSlantedBuildings:number;withheldSlantedBuildings:number;buildings:number;surfaces:number;tileList:string[];tiles:TileMeta[]};

const {THREE}=window.CanalRecallThree;
const sha256=async(bytes:ArrayBuffer)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');
const openRing=(ring:RoofPoint[])=>ring.length>1&&ring[0].every((value,index)=>value===ring.at(-1)?.[index])?ring.slice(0,-1):ring;
export const STUDY_ROOF_MIN_ZOOM=15.25;
async function decode(bytes:ArrayBuffer):Promise<RoofTile>{const view=new Uint8Array(bytes);if(view[0]!==0x1f||view[1]!==0x8b)return JSON.parse(new TextDecoder().decode(view));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text());}

export class StudyRoofs{
  enabled=true;ready=false;debugBuildings=0;debugSurfaces=0;debugResident=0;debugMeshes=0;debugGeometryBytes=0;private scene=new THREE.Scene();private layer:any;private index:RoofIndex|null=null;private metas=new Map<string,TileMeta>();private resources=new Map<string,any>();private controllers=new Map<string,AbortController>();private queue:string[]=[];private inFlight=0;
  constructor(private map:any,private maplibregl:any,private areaId=''){this.layer=this.makeLayer();this.scene.add(new THREE.HemisphereLight(0xffffff,0x6d665e,2.1));const sun=new THREE.DirectionalLight(0xfff1d8,2.2);sun.position.set(-1,-2,3);this.scene.add(sun);if(!map.getLayer(this.layer.id))map.addLayer(this.layer);}
  get debugRenderable(){return this.enabled&&this.ready&&this.map.getZoom()>=STUDY_ROOF_MIN_ZOOM;}
  async load(pointerUrl:string):Promise<void>{
    const response=await fetch(pointerUrl,{cache:'no-store'});if(!response.ok)throw Error('Study roof pointer unavailable');const pointer=await response.json(),value=pointer?.studyRoofs as RoofIndex;if(pointer?.version!==1||!pointer.releaseId||value?.version!==2||value.releaseId!==pointer.releaseId||value.areaId!==pointer.areaId||value.sourceBlockSha256!==pointer.sourceHashes?.block||value.geometrySource!=='3dbag-lod22-roof-surfaces'||value.selectionPolicy!=='per-source-surface-compatible-v2'||value.delivery!=='owner-tiles-v1'||value.zoom!==16||!Array.isArray(value.tiles)||!Array.isArray(value.tileList)||value.tiles.length!==value.tileList.length||![value.origin?.lng,value.origin?.lat,value.candidateSlantedBuildings,value.withheldSlantedBuildings,value.buildings,value.surfaces].every(Number.isFinite)||value.candidateSlantedBuildings-value.buildings!==value.withheldSlantedBuildings)throw Error('Study roof release binding mismatch');
    this.index=value;this.metas=new Map(value.tiles.map(tile=>[tile.key,tile]));if(this.metas.size!==value.tiles.length||value.tiles.some(tile=>!value.tileList.includes(tile.key)||!/^[a-f0-9]{64}$/.test(tile.sha256)||!/^[a-f0-9]{64}$/.test(tile.contentSha256)||!Number.isFinite(tile.buildings)||!Number.isFinite(tile.surfaces)))throw Error('Invalid study roof tile index');this.debugBuildings=value.buildings;this.debugSurfaces=value.surfaces;this.layer.origin=value.origin;this.ready=true;this.map.on('moveend',()=>this.update());this.update();this.map.triggerRepaint();
  }
  setEnabled(value:boolean){this.enabled=!!value;if(this.enabled)this.update();else this.clearResources();this.map.triggerRepaint();}
  dispose(){this.clearResources();this.ready=false;}
  private clearResources(){for(const controller of this.controllers.values())controller.abort();for(const resource of this.resources.values())this.disposeMesh(resource);this.controllers.clear();this.resources.clear();this.queue=[];this.refreshStats();}
  private update(){if(!this.enabled||!this.ready||!this.index)return;if(this.map.getZoom()<STUDY_ROOF_MIN_ZOOM){this.clearResources();return;}const b=this.map.getBounds(),plan=planTiles({west:b.getWest(),south:b.getSouth(),east:b.getEast(),north:b.getNorth()},this.resources.keys(),{zoom:this.index.zoom,margin:1,budget:12}),wanted=new Set(plan.wanted);for(const key of plan.evict){const resource=this.resources.get(key);if(resource){this.disposeMesh(resource);this.resources.delete(key);}}for(const[key,controller]of this.controllers)if(!wanted.has(key)){controller.abort();this.controllers.delete(key);}this.queue=plan.load.map(tileKey).filter(key=>this.metas.has(key)&&!this.resources.has(key)&&!this.controllers.has(key));this.refreshStats();this.pump();}
  private pump(){while(this.inFlight<2&&this.queue.length){const key=this.queue.shift();if(key)void this.fetchTile(key);}}
  private async fetchTile(key:string){const meta=this.metas.get(key);if(!meta)return;const controller=new AbortController();this.controllers.set(key,controller);this.inFlight++;try{const response=await fetch(meta.url,{signal:controller.signal});if(!response.ok)throw Error('Study roof tile unavailable');const bytes=await response.arrayBuffer();if(await sha256(bytes)!==meta.contentSha256)throw Error('Study roof tile content hash mismatch');const tile=await decode(bytes);if(tile.version!==1||tile.key!==key||!Array.isArray(tile.buildings)||tile.buildings.length!==meta.buildings||tile.buildings.reduce((sum,building)=>sum+building.surfaces.length,0)!==meta.surfaces)throw Error('Invalid study roof tile');const mesh=this.createMesh(tile.buildings);if(!controller.signal.aborted){this.resources.set(key,mesh);this.scene.add(mesh);}}catch(error){if((error as Error).name!=='AbortError')console.warn(`Study roof tile ${key} unavailable.`,error);}finally{this.controllers.delete(key);this.inFlight--;this.refreshStats();this.pump();this.map.triggerRepaint();}}
  private createMesh(buildings:RoofBuilding[]){const positions:number[]=[],colours:number[]=[],indices:number[]=[];for(const building of buildings){if(!/^NL\.IMBAG\.Pand\.\d+$/.test(building.id)||!/^#[a-f0-9]{6}$/i.test(building.colour)||!Array.isArray(building.surfaces))throw Error('Invalid study roof building');const colour=new THREE.Color(building.colour);for(const polygon of building.surfaces){if(!Array.isArray(polygon)||!polygon.length)continue;const rings=polygon.map(openRing);if(rings.some(ring=>ring.length<3||ring.some(point=>point.length!==3||!point.every(Number.isFinite)||Math.abs(point[0])>2000||Math.abs(point[1])>2000||point[2]<-2||point[2]>100)))throw Error('Invalid study roof surface');const contour=rings[0].map(([east,north])=>new THREE.Vector2(east,north)),holes=rings.slice(1).map(ring=>ring.map(([east,north])=>new THREE.Vector2(east,north))),faces=THREE.ShapeUtils.triangulateShape(contour,holes),vertices=rings.flat(),offset=positions.length/3;for(const [east,north,up]of vertices){positions.push(east,north,up+.04);colours.push(colour.r,colour.g,colour.b);}for(const face of faces)indices.push(offset+face[0],offset+face[1],offset+face[2]);}}
    const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colours,3));geometry.setIndex(indices);geometry.computeVertexNormals();geometry.computeBoundingSphere();const material=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.88,metalness:0,side:THREE.DoubleSide}),mesh=new THREE.Mesh(geometry,material);mesh.frustumCulled=false;mesh.userData.geometryBytes=(geometry.getAttribute('position')?.array?.byteLength||0)+(geometry.getAttribute('normal')?.array?.byteLength||0)+(geometry.getAttribute('color')?.array?.byteLength||0)+(geometry.index?.array?.byteLength||0);return mesh;
  }
  private disposeMesh(mesh:any){this.scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}
  private refreshStats(){this.debugResident=this.resources.size;this.debugMeshes=this.resources.size;this.debugGeometryBytes=[...this.resources.values()].reduce((sum,mesh)=>sum+(mesh.userData.geometryBytes||0),0);}
  private makeLayer(){const owner=this;let camera:any,renderer:any,suffix=this.areaId?`-${this.areaId.replace(/[^a-z0-9-]/gi,'-')}`:'';const layer:any={id:`city-appearance-source-roofs${suffix}`,type:'custom',renderingMode:'3d',origin:null,onAdd(_map:any,gl:any){camera=new THREE.Camera();renderer=new THREE.WebGLRenderer({canvas:owner.map.getCanvas(),context:gl,antialias:true});renderer.autoClear=false;},render(_gl:any,args:any){const origin=layer.origin;if(!owner.debugRenderable||!origin)return;const coordinate=owner.maplibregl.MercatorCoordinate.fromLngLat([origin.lng,origin.lat],0),scale=coordinate.meterInMercatorCoordinateUnits(),transform=new THREE.Matrix4().makeTranslation(coordinate.x,coordinate.y,coordinate.z).scale(new THREE.Vector3(scale,-scale,scale));camera.projectionMatrix.fromArray(args.defaultProjectionData.mainMatrix).multiply(transform);renderer.resetState();renderer.render(owner.scene,camera);}};return layer;}
}

declare global{interface Window{CanalRecallThree:any;CanalRecallStudyRoofs?:{StudyRoofs:typeof StudyRoofs}}}
window.CanalRecallStudyRoofs={StudyRoofs};
