import { planTiles } from './buildingTileSource.js';
import { tileKey } from './slippyTiles.js';
// @ts-expect-error Shared inventory typology is a browser JS module.
import { treeTypology, TREE_TYPOLOGY_VERSION } from '../../public/canal-drive/da-costa-block/tree-typology.js';

type TreeTile={version:1;key:string;trees:any[]};
type TileMeta={key:string;url:string;sha256:string;contentSha256:string;bytes:number;trees:number};
type TreeIndex={version:1;zoom:number;releaseId:string;areaId:string;sourceContextSha256:string;positionSource:'municipal-tree-inventory';typology:string;trunkGeometry:'tapered-z-cylinder-v2';origin:{lng:number;lat:number};trees:number;tileList:string[];tiles:TileMeta[]};
const {THREE}=window.CanalRecallThree;
const sha256=async(bytes:ArrayBuffer)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');
export const STUDY_TREE_MIN_ZOOM=15.5;
async function decode(bytes:ArrayBuffer):Promise<TreeTile>{const view=new Uint8Array(bytes);if(view[0]!==0x1f||view[1]!==0x8b)return JSON.parse(new TextDecoder().decode(view));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text());}

export class StudyTrees{
  enabled=true;ready=false;debugTrees=0;debugResident=0;debugMeshes=0;debugGeometryBytes=0;debugTrunkAxis='none';private scene=new THREE.Scene();private layer:any;private index:TreeIndex|null=null;private metas=new Map<string,TileMeta>();private resources=new Map<string,any[]>();private controllers=new Map<string,AbortController>();private queue:string[]=[];private inFlight=0;
  constructor(private map:any,private maplibregl:any,private areaId=''){this.layer=this.makeLayer();this.scene.add(new THREE.HemisphereLight(0xffffff,0x526048,2.15));const sun=new THREE.DirectionalLight(0xfff0d5,1.7);sun.position.set(-2,-1,4);this.scene.add(sun);if(!map.getLayer(this.layer.id))map.addLayer(this.layer);}
  get debugRenderable(){return this.enabled&&this.ready&&this.map.getZoom()>=STUDY_TREE_MIN_ZOOM;}
  async load(pointerUrl:string){const response=await fetch(pointerUrl,{cache:'no-store'});if(!response.ok)throw Error('Study tree pointer unavailable');const pointer=await response.json(),value=pointer?.studyTrees as TreeIndex;if(pointer?.version!==1||!pointer.releaseId||value?.version!==1||value.releaseId!==pointer.releaseId||value.areaId!==pointer.areaId||value.sourceContextSha256!==pointer.context?.sha256||value.positionSource!=='municipal-tree-inventory'||value.typology!==TREE_TYPOLOGY_VERSION||value.trunkGeometry!=='tapered-z-cylinder-v2'||value.zoom!==16||!Array.isArray(value.tiles)||!Array.isArray(value.tileList)||value.tiles.length!==value.tileList.length||![value.origin?.lng,value.origin?.lat,value.trees].every(Number.isFinite))throw Error('Study tree release binding mismatch');this.index=value;this.metas=new Map(value.tiles.map(tile=>[tile.key,tile]));if(this.metas.size!==value.tiles.length||value.tiles.some(tile=>!value.tileList.includes(tile.key)||!/^[a-f0-9]{64}$/.test(tile.sha256)||!/^[a-f0-9]{64}$/.test(tile.contentSha256)))throw Error('Invalid study tree tile index');this.debugTrees=value.trees;this.layer.origin=value.origin;this.ready=true;this.map.on('moveend',()=>this.update());this.update();this.map.triggerRepaint();}
  setEnabled(value:boolean){this.enabled=!!value;if(this.enabled)this.update();else this.clearResources();this.map.triggerRepaint();}
  dispose(){this.clearResources();this.ready=false;}
  private clearResources(){for(const controller of this.controllers.values())controller.abort();for(const meshes of this.resources.values())this.disposeMeshes(meshes);this.controllers.clear();this.resources.clear();this.queue=[];this.refreshStats();}
  private update(){if(!this.enabled||!this.ready||!this.index)return;if(this.map.getZoom()<STUDY_TREE_MIN_ZOOM){this.clearResources();return;}const b=this.map.getBounds(),plan=planTiles({west:b.getWest(),south:b.getSouth(),east:b.getEast(),north:b.getNorth()},this.resources.keys(),{zoom:this.index.zoom,margin:1,budget:12}),wanted=new Set(plan.wanted);for(const key of plan.evict){const meshes=this.resources.get(key);if(meshes){this.disposeMeshes(meshes);this.resources.delete(key);}}for(const[key,controller]of this.controllers)if(!wanted.has(key)){controller.abort();this.controllers.delete(key);}this.queue=plan.load.map(tileKey).filter(key=>this.metas.has(key)&&!this.resources.has(key)&&!this.controllers.has(key));this.refreshStats();this.pump();}
  private pump(){while(this.inFlight<2&&this.queue.length){const key=this.queue.shift();if(key)void this.fetchTile(key);}}
  private async fetchTile(key:string){const meta=this.metas.get(key);if(!meta)return;const controller=new AbortController();this.controllers.set(key,controller);this.inFlight++;try{const response=await fetch(meta.url,{signal:controller.signal});if(!response.ok)throw Error('Study tree tile unavailable');const bytes=await response.arrayBuffer();if(await sha256(bytes)!==meta.contentSha256)throw Error('Study tree tile content hash mismatch');const tile=await decode(bytes);if(tile.version!==1||tile.key!==key||!Array.isArray(tile.trees)||tile.trees.length!==meta.trees)throw Error('Invalid study tree tile');const meshes=this.createMeshes(tile.trees);if(!controller.signal.aborted){this.resources.set(key,meshes);for(const mesh of meshes)this.scene.add(mesh);}}catch(error){if((error as Error).name!=='AbortError')console.warn(`Study tree tile ${key} unavailable.`,error);}finally{this.controllers.delete(key);this.inFlight--;this.refreshStats();this.pump();this.map.triggerRepaint();}}
  private createMeshes(trees:any[]){const trunks:any[]=[],crowns:any[][]=[[],[],[]];for(const tree of trees){const t=treeTypology(tree);if(!t)continue;if(!Array.isArray(t.position)||!t.position.every(Number.isFinite)||!Number.isFinite(t.height)||t.height<=0||t.height>60)throw Error('Invalid study tree');trunks.push({position:[t.position[0],-t.position[1],t.trunkHeight/2+.1],scale:[t.trunkWidth*2,t.trunkWidth*2,t.trunkHeight]});for(const lobe of t.lobes)crowns[lobe.tone].push({position:[t.position[0]+lobe.offset[0],-(t.position[1]+lobe.offset[2]),lobe.offset[1]+.1],scale:[lobe.scale[0],lobe.scale[2],lobe.scale[1]]});}const meshes:any[]=[],dummy=new THREE.Object3D(),add=(items:any[],geometry:any,colour:string)=>{if(!items.length){geometry.dispose();return;}const material=new THREE.MeshStandardMaterial({color:colour,roughness:.93}),mesh=new THREE.InstancedMesh(geometry,material,items.length);items.forEach((item,index)=>{dummy.position.set(...item.position);dummy.scale.set(...item.scale);dummy.updateMatrix();mesh.setMatrixAt(index,dummy.matrix);});mesh.instanceMatrix.needsUpdate=true;mesh.frustumCulled=false;mesh.userData.instances=items.length;meshes.push(mesh);};const trunkGeometry=new THREE.CylinderGeometry(.22,.28,1,7);trunkGeometry.rotateX(Math.PI/2);trunkGeometry.computeBoundingBox();const size=new THREE.Vector3();trunkGeometry.boundingBox.getSize(size);this.debugTrunkAxis=size.z>size.x&&size.z>size.y?'z':'invalid';add(trunks,trunkGeometry,'#665741');for(let i=0;i<3;i++)add(crowns[i],new THREE.IcosahedronGeometry(1,1),['#78945a','#8da767','#667f4c'][i]);return meshes;}
  private disposeMeshes(meshes:any[]){for(const mesh of meshes){this.scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();mesh.dispose?.();}}
  private refreshStats(){const meshes=[...this.resources.values()].flat(),geometryBytes=(geometry:any)=>Object.values(geometry.attributes??{}).reduce((sum:number,attribute:any)=>sum+(attribute.array?.byteLength||0),0)+(geometry.index?.array?.byteLength||0);this.debugResident=this.resources.size;this.debugMeshes=meshes.length;this.debugGeometryBytes=meshes.reduce((sum,mesh)=>sum+geometryBytes(mesh.geometry)+(mesh.instanceMatrix?.array?.byteLength||0),0);}
  private makeLayer(){const owner=this;let camera:any,renderer:any,suffix=this.areaId?`-${this.areaId.replace(/[^a-z0-9-]/gi,'-')}`:'';const layer:any={id:`city-appearance-inventory-trees${suffix}`,type:'custom',renderingMode:'3d',origin:null,onAdd(_map:any,gl:any){camera=new THREE.Camera();renderer=new THREE.WebGLRenderer({canvas:owner.map.getCanvas(),context:gl,antialias:true});renderer.autoClear=false;},render(_gl:any,args:any){const origin=layer.origin;if(!owner.debugRenderable||!origin)return;const coordinate=owner.maplibregl.MercatorCoordinate.fromLngLat([origin.lng,origin.lat],0),scale=coordinate.meterInMercatorCoordinateUnits(),transform=new THREE.Matrix4().makeTranslation(coordinate.x,coordinate.y,coordinate.z).scale(new THREE.Vector3(scale,-scale,scale));camera.projectionMatrix.fromArray(args.defaultProjectionData.mainMatrix).multiply(transform);renderer.resetState();renderer.render(owner.scene,camera);}};return layer;}
}

declare global{interface Window{CanalRecallThree:any;CanalRecallStudyTrees?:{StudyTrees:typeof StudyTrees}}}
window.CanalRecallStudyTrees={StudyTrees};
