/** Publish an immutable geometry-only release from a completed area pipeline.
 * No appearance evidence, inference, review mutation, or acquisition occurs.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { gzipSync } from 'node:zlib';
import { loadAreaConfig } from '../da-costa-block/area-config.mjs';
import { compileBlockAppearance, sha256 } from './compile-block-tiles.js';
import { selectPanoramaAudit } from './select-panorama-audit.mjs';
import { surfaceMatches } from '../../public/canal-drive/da-costa-block/evidence.js';
import { compileContextTiles } from '../../src/canalRecall/cityAppearanceContextTiles.js';
import { compileAreaRoute } from '../../src/canalRecall/cityAppearanceRoute.js';
import { contextualBuildingPalette } from '../../src/canalRecall/cityAppearancePalette.js';
import { contextualFacadePatches, FACADE_PATCH_COLOURS } from '../../src/canalRecall/cityAppearanceFacadeRecipes.js';
import { PUBLIC_REALM_SIMPLIFICATION_TOLERANCE_M, publicRealmVertexCount, simplifyPublicRealmFeature } from '../../src/canalRecall/cityAppearancePublicRealm.js';
import { selectCompatibleSourceRoof, SOURCE_ROOF_SELECTION_POLICY } from '../../src/canalRecall/cityAppearanceRoofs.js';
import { lngLatToRd, rdToLngLat } from '../../src/canalRecall/facade/rdNew.js';

const flag=(name:string)=>process.argv.find(value=>value.startsWith(`--${name}=`))?.slice(name.length+3);
const encode=(value:unknown)=>Buffer.from(JSON.stringify(value));
async function completeRun(areaId:string){
  const root=path.resolve('.cache/city-appearance/areas',areaId,'runs'),runs=[] as any[];
  for(const name of await fs.readdir(root)){if(!/^[a-f0-9]{64}$/.test(name))continue;try{const state=JSON.parse(await fs.readFile(path.join(root,name,'pipeline.json'),'utf8'));if(['compile','inventory','tiles','context-tiles'].every(id=>state.jobs?.[id]?.status==='complete'))runs.push({name,state,completedAt:Math.max(...Object.values(state.jobs).map((job:any)=>Date.parse(job.completedAt)||0))});}catch(error:any){if(error.code!=='ENOENT')throw error;}}
  if(!runs.length)throw Error('No complete area pipeline run with context tiles');runs.sort((a,b)=>a.completedAt-b.completedAt||a.name.localeCompare(b.name));return runs.at(-1);
}
async function writeImmutable(file:string,bytes:Buffer){await fs.mkdir(path.dirname(file),{recursive:true});try{await fs.writeFile(file,bytes,{flag:'wx'});}catch(error:any){if(error.code!=='EEXIST'||sha256(await fs.readFile(file))!==sha256(bytes))throw error;}}
async function routingResults(auditRoot:string){
  const root=path.join(auditRoot,'routing-inputs'),candidates=[] as any[];
  for(const name of await fs.readdir(root)){if(!/^[a-f0-9]{64}$/.test(name))continue;try{const file=path.join(root,name,'machine-routing/results.json'),bytes=await fs.readFile(file),value=JSON.parse(bytes.toString());candidates.push({file,bytes,value});}catch(error:any){if(error.code!=='ENOENT')throw error;}}
  if(!candidates.length)throw Error('No completed compact routing experiment');
  candidates.sort((a,b)=>a.value.inputSetHash.localeCompare(b.value.inputSetHash));return candidates.at(-1);
}

export async function publishAreaGeometryDemo(){
  const areaFile=path.resolve(flag('area-config')??'scripts/city-appearance/areas/da-costa-tranche-400m-v1.json'),area=await loadAreaConfig([`--area-config=${areaFile}`]);
  const evidenceAreaFile=path.resolve(flag('evidence-area-config')??areaFile),evidenceArea=await loadAreaConfig([`--area-config=${evidenceAreaFile}`]);
  const run=await completeRun(area.id),blockPath=run.state.jobs.compile.output.blockPath,blockBytes=await fs.readFile(blockPath),block=JSON.parse(blockBytes.toString());
  if(block.areaConfigHash!==area.configHash)throw Error('Compiled block does not match area config');
  const selected=await selectPanoramaAudit(evidenceArea,{cap:24}),auditManifestPath=path.join(selected.destination,'evidence/manifest.json'),auditPath=path.join(selected.destination,'agent-visual-audit.json');
  const [auditManifestBytes,auditBytes,routing]=await Promise.all([fs.readFile(auditManifestPath),fs.readFile(auditPath),routingResults(selected.destination)]),auditManifest=JSON.parse(auditManifestBytes.toString()),audit=JSON.parse(auditBytes.toString());
  const assessments=new Map(audit.assessments.map((item:any)=>[item.id,item]));
  const proposals=new Map(routing.value.results.filter((item:any)=>item.status==='ok').map((item:any)=>[item.id,item.proposal]));
  const records=auditManifest.records.map((record:any)=>{const assessment:any=assessments.get(record.id),proposal:any=proposals.get(record.id),building=block.buildings.find((item:any)=>item.id===record.buildingId);if(!assessment||!building)throw Error(`Missing source audit/building: ${record.id}`);return {...record,
    renderBuildingId:record.buildingId,evidenceKey:sha256(encode({selectionHash:selected.report.selectionHash,derivationKey:record.derivationKey,assessment})),
    renderSurfaceIndices:surfaceMatches(building,record),agentSourceAudit:assessment,machineRoutingProposal:proposal??null,
    effectiveProposal:{family:proposal?.family??'unknown',wallMaterial:proposal?.wallMaterial??'unknown',wallColour:proposal?.wallColour??'unknown',wholeUsable:proposal?.upperUsable??'unknown',groundUsable:proposal?.groundUsable??(assessment.disposition==='usable'?'yes':'partial'),shopfront:['storefront','mixed'].includes(proposal?.groundType)?'yes':proposal?.groundType==='residential'?'no':'unknown',awning:'unknown',roofShape:'unknown',facadeTop:'unknown'},
    appearancePublication:proposal?'quarantined-machine-preview':'withheld-source-audit-only'};});
  const streetsPath=path.resolve('public/data/extracts/amsterdam/streets-routing.json'),streetsBytes=await fs.readFile(streetsPath),guidedRoute=compileAreaRoute(JSON.parse(streetsBytes.toString()),area.bbox,lngLatToRd(area.origin));
  const compilerFiles=[new URL('./publish-area-geometry-demo.ts',import.meta.url),new URL('./compile-block-tiles.ts',import.meta.url),new URL('./select-panorama-audit.mjs',import.meta.url),new URL('../../src/canalRecall/cityAppearanceTiles.ts',import.meta.url),new URL('../../src/canalRecall/cityAppearanceContextTiles.ts',import.meta.url),new URL('../../src/canalRecall/cityAppearanceRoute.ts',import.meta.url),new URL('../../src/canalRecall/cityAppearancePalette.ts',import.meta.url),new URL('../../src/canalRecall/cityAppearanceFacadeRecipes.ts',import.meta.url),new URL('../../src/canalRecall/cityAppearanceFacadeLod.ts',import.meta.url),new URL('../../src/canalRecall/cityAppearancePublicRealm.ts',import.meta.url),new URL('../../src/canalRecall/cityAppearanceRoofs.ts',import.meta.url),new URL('../../src/canalRecall/studyRoofsBrowser.ts',import.meta.url),new URL('../../src/canalRecall/studyFacadesBrowser.ts',import.meta.url),new URL('../../src/canalRecall/studyTreesBrowser.ts',import.meta.url),new URL('../../src/canalRecall/studyPublicRealmBrowser.ts',import.meta.url),new URL('../../public/canal-drive/da-costa-block/tree-typology.js',import.meta.url),new URL('../../public/canal-drive/da-costa-block/evidence.js',import.meta.url),new URL('../../public/canal-drive/da-costa-block/wall-intervals.js',import.meta.url),new URL('../../public/canal-drive/da-costa-block/face-containment.js',import.meta.url)];
  const compiled=compileBlockAppearance(block,{records},{zoom:16,halo:1}),compilerHash=sha256(encode(await Promise.all(compilerFiles.map(async file=>sha256(await fs.readFile(file))))));
  const sourceHashes={block:sha256(blockBytes),auditManifest:sha256(auditManifestBytes),agentVisualAudit:sha256(auditBytes),machineRouting:sha256(routing.bytes),streetsRouting:sha256(streetsBytes)};
  const releaseId=sha256(encode({version:1,areaConfigHash:area.configHash,evidenceAreaConfigHash:evidenceArea.configHash,runHash:run.name,sourceHashes,compilerHash}));
  const outputRoot=path.resolve(flag('out')??'public/data/city-expansion'),publicBase=flag('public-base')??'/data/city-expansion',base=`${publicBase}/releases/${releaseId}`;
  if(!/^\/[a-zA-Z0-9/_-]+$/.test(publicBase))throw Error('Invalid public base');
  const releaseRoot=path.join(outputRoot,'releases',releaseId),contextTiles=compileContextTiles(block,16);
  const context={...block,buildings:[],anchors:[],references:[],layers:Object.fromEntries(Object.keys(block.layers??{}).map(key=>[key,[]])),trees:[],guidedRoute,
    streamedContext:{zoom:contextTiles.zoom,features:contextTiles.buildings,sourceLayerCounts:Object.fromEntries(Object.entries(block.layers??{}).map(([key,value]:any)=>[key,value.length])),trees:block.trees?.length??0}};
  const routePoi=(point:[number,number],id:string,name:string)=>{const [lng,lat]=rdToLngLat({x:block.origin.x+point[0],y:block.origin.y-point[1]});return{id,name,lat,lng};},firstStreet=guidedRoute.legs.find(leg=>leg.streetName)?.streetName??'Da Costa study start',lastStreet=[...guidedRoute.legs].reverse().find(leg=>leg.streetName)?.streetName??'Da Costa study finish';
  const sourceRoofs=new Map(block.buildings.map((building:any)=>[building.id,selectCompatibleSourceRoof(building)]).filter((entry:any)=>entry[1])),slantedRoofCandidates=block.buildings.filter((building:any)=>building.roofType==='slanted').length;
  const ownerRevisions=new Map(compiled.tiles.flatMap(tile=>tile.owners.map(owner=>[owner.id,owner.geometryRevision]))),contextBytes=encode(context),maplibreAppearance={version:1,releaseId,areaId:area.id,sourceBlockSha256:sourceHashes.block,styleSource:'procedural-prior-not-measured',studyRoute:{id:'da-costa-appearance-study',distanceM:guidedRoute.distanceM,source:'guided-route-source-graph',from:routePoi(guidedRoute.points[0],'da-costa-study-start',firstStreet),to:routePoi(guidedRoute.points.at(-1)!,'da-costa-study-finish',lastStreet)},buildings:block.buildings.map((building:any)=>{const palette=contextualBuildingPalette(building.id,building.year),geometryRevision=ownerRevisions.get(building.id),roof=sourceRoofs.get(building.id);if(!geometryRevision)throw Error(`Missing geometry revision for MapLibre appearance: ${building.id}`);return{id:building.id.startsWith('NL.IMBAG.Pand.')?building.id:`NL.IMBAG.Pand.${building.id}`,sourceId:building.id,geometryRevision,constructionYear:Number.isFinite(building.year)?building.year:null,sideColour:palette.wall,roofColour:palette.roof,groundColour:palette.ground,groundFloorHeightM:Number.isFinite(building.year)&&building.year<1925?3.6:3.2,roofShape:roof?'source-slanted':building.roofType==='horizontal'||building.roofType==='multiple horizontal'?'flat':null,roofEavesHeightM:null,roofGeometrySource:roof?'3dbag-lod22-roof-surfaces':null};})},maplibreBytes=encode(maplibreAppearance);
  const [originLng,originLat]=rdToLngLat(block.origin),owners=compiled.tiles.flatMap(tile=>tile.owners),windowIds=new Set<string>(),doorIds=new Set<string>(),trimIds=new Set<string>(),artifacts=new Map<string,Buffer>([['context.json',contextBytes],['maplibre-appearance.json',maplibreBytes]]),roofTiles=[] as any[];let roofBuildingCount=0,roofSurfaceCount=0;
  for(const tile of compiled.tiles){const buildings=tile.owners.flatMap((owner:any)=>{const building=owner.geometry.building,roof:any=sourceRoofs.get(building.id);if(!roof)return[];const palette=contextualBuildingPalette(building.id,building.year);return[{id:building.id.startsWith('NL.IMBAG.Pand.')?building.id:`NL.IMBAG.Pand.${building.id}`,colour:palette.roof,surfaces:roof.surfaces}];});if(!buildings.length)continue;const payload={version:1,key:tile.key,buildings},payloadBytes=encode(payload),relative=`study-roofs/${tile.key}.json.gz`,bytes=gzipSync(payloadBytes);artifacts.set(relative,bytes);const surfaces=buildings.reduce((sum:number,building:any)=>sum+building.surfaces.length,0);roofBuildingCount+=buildings.length;roofSurfaceCount+=surfaces;roofTiles.push({key:tile.key,url:`${base}/${relative}`,bytes:bytes.length,encoding:'gzip',sha256:sha256(bytes),contentSha256:sha256(payloadBytes),buildings:buildings.length,surfaces});}
  const studyRoofs={version:2,zoom:compiled.zoom,releaseId,areaId:area.id,sourceBlockSha256:sourceHashes.block,geometrySource:'3dbag-lod22-roof-surfaces',selectionPolicy:SOURCE_ROOF_SELECTION_POLICY,delivery:'owner-tiles-v1',origin:{lng:originLng,lat:originLat},candidateSlantedBuildings:slantedRoofCandidates,withheldSlantedBuildings:slantedRoofCandidates-roofBuildingCount,buildings:roofBuildingCount,surfaces:roofSurfaceCount,tileList:roofTiles.map(tile=>tile.key),tiles:roofTiles,compressedBytes:roofTiles.reduce((sum,tile)=>sum+tile.bytes,0)};
  const facadeTiles=[] as any[];
  for(const tile of compiled.tiles){
    const batches=new Map<string,number[]>();
    for(const owner of tile.owners){const ground=Number(owner.geometry.building.groundNAP),center=owner.geometry.building.center;if(!Number.isFinite(ground)||!owner.geometry.building.surfaces?.length||!Array.isArray(center))continue;owner.geometry.building.surfaces.forEach((surface:any,index:number)=>{for(const patch of contextualFacadePatches(owner,surface,index,owners)){const batch=batches.get(patch.colour)??[];for(let offset=0;offset<patch.triangles.length;offset+=3){const east=patch.triangles[offset],south=patch.triangles[offset+2],dx=east-center[0],dz=south-center[1],length=Math.hypot(dx,dz)||1;batch.push(...[east+dx/length*.18,-(south+dz/length*.18),patch.triangles[offset+1]-ground].map(value=>Math.round(value*1000)/1000));}batches.set(patch.colour,batch);if(patch.featureKind==='contextual-window-prior')windowIds.add(patch.featureId);if(patch.featureKind==='contextual-door-prior')doorIds.add(patch.featureId);if(patch.featureKind==='contextual-trim-prior')trimIds.add(patch.featureId);}});}
    if(!batches.size)continue;
    const payload={version:1,key:tile.key,batches:[...batches].map(([kind,triangles])=>({kind,colour:FACADE_PATCH_COLOURS[kind as keyof typeof FACADE_PATCH_COLOURS],triangles}))},payloadBytes=encode(payload),relative=`study-facades/${tile.key}.json.gz`,bytes=gzipSync(payloadBytes);artifacts.set(relative,bytes);facadeTiles.push({key:tile.key,url:`${base}/${relative}`,bytes:bytes.length,encoding:'gzip',sha256:sha256(bytes),contentSha256:sha256(payloadBytes),triangles:payload.batches.reduce((sum,batch)=>sum+batch.triangles.length/9,0)});
  }
  const studyFacades={version:1,zoom:compiled.zoom,releaseId,areaId:area.id,sourceBlockSha256:sourceHashes.block,styleSource:'procedural-prior-not-measured',geometrySource:'3dbag-lod22-wall-surfaces',openingStyle:'era-rhythm-recessed-sash-entrance-v3',reliefOffsetM:.18,origin:{lng:originLng,lat:originLat},windows:windowIds.size,doors:doorIds.size,trims:trimIds.size,tileList:facadeTiles.map(tile=>tile.key),tiles:facadeTiles};
  const treeTiles=[] as any[];let treeCount=0;
  for(const tile of contextTiles.tiles){const trees=tile.owners.filter((owner:any)=>owner.geometry.kind==='tree').map((owner:any)=>owner.geometry.tree);if(!trees.length)continue;const payload={version:1,key:tile.key,trees},payloadBytes=encode(payload),relative=`study-trees/${tile.key}.json.gz`,bytes=gzipSync(payloadBytes);artifacts.set(relative,bytes);treeCount+=trees.length;treeTiles.push({key:tile.key,url:`${base}/${relative}`,bytes:bytes.length,encoding:'gzip',sha256:sha256(bytes),contentSha256:sha256(payloadBytes),trees:trees.length});}
  const studyTrees={version:1,zoom:contextTiles.zoom,releaseId,areaId:area.id,sourceContextSha256:sha256(contextBytes),positionSource:'municipal-tree-inventory',typology:'inventory-crown-priors/v1',trunkGeometry:'tapered-z-cylinder-v2',origin:{lng:originLng,lat:originLat},trees:treeCount,tileList:treeTiles.map(tile=>tile.key),tiles:treeTiles};
  const publicRealmTiles=[] as any[];let waterCount=0,bridgeCount=0,greenCount=0,footpathCount=0,cyclewayCount=0,boundaryCount=0,sourceVertexCount=0,publishedVertexCount=0;
  const publicRealmFeature=(owner:any)=>{const layer=owner.geometry.layer,feature=owner.geometry.feature,kind=feature?.kind;if(['waterdeel','overbruggingsdeel','begroeidterreindeel'].includes(layer))return true;if(layer==='scheiding_lijn')return['kademuur','walbescherming'].includes(kind);return['wegdeel','ondersteunendwegdeel'].includes(layer)&&(/voetpad/.test(kind)||kind==='fietspad');};
  for(const tile of contextTiles.tiles){const sourceFeatures=tile.owners.filter(publicRealmFeature).map((owner:any)=>({layer:owner.geometry.layer,feature:owner.geometry.feature})),features=sourceFeatures.map((item:any)=>({...item,feature:simplifyPublicRealmFeature(item.feature)}));if(!features.length)continue;const count=(predicate:(item:any)=>boolean)=>features.filter(predicate).length,water=count(item=>item.layer==='waterdeel'),bridges=count(item=>item.layer==='overbruggingsdeel'),green=count(item=>item.layer==='begroeidterreindeel'),footpaths=count(item=>/voetpad/.test(item.feature.kind)),cycleways=count(item=>item.feature.kind==='fietspad'),boundaries=count(item=>item.layer==='scheiding_lijn'),sourceVertices=sourceFeatures.reduce((sum,item)=>sum+publicRealmVertexCount(item.feature),0),publishedVertices=features.reduce((sum,item)=>sum+publicRealmVertexCount(item.feature),0),payload={version:4,key:tile.key,features},payloadBytes=encode(payload),relative=`study-public-realm/${tile.key}.json.gz`,bytes=gzipSync(payloadBytes);artifacts.set(relative,bytes);waterCount+=water;bridgeCount+=bridges;greenCount+=green;footpathCount+=footpaths;cyclewayCount+=cycleways;boundaryCount+=boundaries;sourceVertexCount+=sourceVertices;publishedVertexCount+=publishedVertices;publicRealmTiles.push({key:tile.key,url:`${base}/${relative}`,bytes:bytes.length,encoding:'gzip',sha256:sha256(bytes),contentSha256:sha256(payloadBytes),water,bridges,green,footpaths,cycleways,boundaries,sourceVertices,publishedVertices});}
  const studyPublicRealm={version:4,zoom:contextTiles.zoom,releaseId,areaId:area.id,sourceContextSha256:sha256(contextBytes),geometrySource:'bgt-display-simplified',simplificationToleranceM:PUBLIC_REALM_SIMPLIFICATION_TOLERANCE_M,boundaryHeightM:.55,boundaryHeightSource:'illustrative-display-prior',bridgeDepthM:.55,bridgeDepthSource:'illustrative-display-prior',renderPolicy:'water-greenery-active-mobility-quay-v5-bridge-understructure',origin:{lng:originLng,lat:originLat},water:waterCount,bridges:bridgeCount,green:greenCount,footpaths:footpathCount,cycleways:cyclewayCount,boundaries:boundaryCount,sourceVertices:sourceVertexCount,publishedVertices:publishedVertexCount,tileList:publicRealmTiles.map(tile=>tile.key),tiles:publicRealmTiles};
  const tiles=[] as any[];for(const tile of compiled.tiles){const relative=`tiles/${tile.key}.json.gz`,payloadBytes=encode(tile),bytes=gzipSync(payloadBytes);artifacts.set(relative,bytes);tiles.push({key:tile.key,url:`${base}/${relative}`,bytes:bytes.length,encoding:'gzip',sha256:sha256(bytes),contentSha256:sha256(payloadBytes),owners:tile.owners.length,haloReferences:tile.halo.length});}
  const contextTileList=[] as any[];for(const tile of contextTiles.tiles){const relative=`context-tiles/${tile.key}.json.gz`,payloadBytes=encode(tile),bytes=gzipSync(payloadBytes);artifacts.set(relative,bytes);contextTileList.push({key:tile.key,url:`${base}/${relative}`,bytes:bytes.length,encoding:'gzip',sha256:sha256(bytes),contentSha256:sha256(payloadBytes),owners:tile.owners.length,haloReferences:tile.halo.length});}
  const manifest={version:1,zoom:compiled.zoom,releaseId,publication:'experimental-city-demo',areaId:area.id,areaConfigHash:area.configHash,evidenceAreaId:evidenceArea.id,evidenceAreaConfigHash:evidenceArea.configHash,runHash:run.name,
    pipeline:{jobs:Object.fromEntries(['compile','inventory','tiles','context-tiles'].map(id=>[id,{inputKey:run.state.jobs[id].inputKey,outputKey:run.state.jobs[id].outputKey,completedAt:run.state.jobs[id].completedAt}]))},
    sourceHashes,compilerHash,reviewed:0,accepted:0,buildings:compiled.buildings,observations:compiled.observations,
    context:{url:`${base}/context.json`,sha256:sha256(contextBytes)},maplibreAppearance:{url:`${base}/maplibre-appearance.json`,sha256:sha256(maplibreBytes),buildings:maplibreAppearance.buildings.length,styleSource:maplibreAppearance.styleSource},studyRoofs,studyFacades:{...studyFacades,compressedBytes:facadeTiles.reduce((sum,tile)=>sum+tile.bytes,0),triangles:facadeTiles.reduce((sum,tile)=>sum+tile.triangles,0)},studyTrees:{...studyTrees,compressedBytes:treeTiles.reduce((sum,tile)=>sum+tile.bytes,0)},studyPublicRealm:{...studyPublicRealm,compressedBytes:publicRealmTiles.reduce((sum,tile)=>sum+tile.bytes,0)},contextTiles:{version:1,zoom:contextTiles.zoom,tileList:contextTiles.tiles.map(tile=>tile.key),tiles:contextTileList},tileList:tiles.map(tile=>tile.key),tiles,
    sourceAudit:{selectionHash:selected.report.selectionHash,frontages:audit.summary.frontages,usable:audit.summary.usable,partial:audit.summary.partial,usableFacadeLengthM:audit.summary.usableFacadeLengthM},
    machinePreview:{inputSetHash:routing.value.inputSetHash,model:routing.value.model,frontages:proposals.size,observedUsd:routing.value.results.reduce((sum:number,item:any)=>sum+(item.usage?.cost??0),0),status:'quarantined-not-canonical'},
    appearanceCoverage:{geometryBuildings:compiled.buildings,contextualPriorBuildings:compiled.buildings,auditedFrontages:audit.summary.frontages,machinePreviewFrontages:proposals.size,humanConfirmedFrontages:0},
    policy:'Source geometry plus reversible, provenance-labelled machine preview. No inferred field is canonical or human-reviewed.',downloads:0,paidCalls:0};
  const manifestBytes=encode(manifest);artifacts.set('manifest.json',manifestBytes);
  if(!process.argv.includes('--dry-run')){for(const [relative,bytes]of artifacts)await writeImmutable(path.join(releaseRoot,relative),bytes);await fs.mkdir(outputRoot,{recursive:true});const temporary=path.join(outputRoot,`current-${process.pid}.tmp`);await fs.writeFile(temporary,manifestBytes,{flag:'wx'});await fs.rename(temporary,path.join(outputRoot,'current.json'));}
  return manifest;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href)publishAreaGeometryDemo().then(value=>console.log(JSON.stringify(value,null,2))).catch(error=>{console.error(error.message);process.exitCode=1;});
