/** Resumable, local-only proposal worker for completed material-4000 rectification batches. */
import fs from 'node:fs/promises'; import path from 'node:path'; import crypto from 'node:crypto';
import { execFile } from 'node:child_process'; import { promisify } from 'node:util'; import { pathToFileURL } from 'node:url';
import { runBenchmark } from './benchmark-local-materials.mjs';
const exec=promisify(execFile), hash=(b:Buffer|string)=>crypto.createHash('sha256').update(b).digest('hex');
const flag=(n:string,d?:string)=>process.argv.find(v=>v.startsWith(`--${n}=`))?.slice(n.length+3)??d;
const integer=(n:string,d:number,min:number,max:number)=>{const v=Number(flag(n,String(d)));if(!Number.isInteger(v)||v<min||v>max)throw Error(`${n} must be ${min}–${max}`);return v};
const atomic=async(f:string,v:any)=>{await fs.mkdir(path.dirname(f),{recursive:true});const t=`${f}.${process.pid}.${crypto.randomUUID()}.tmp`;try{await fs.writeFile(t,JSON.stringify(v,null,2));await fs.rename(t,f)}finally{await fs.rm(t,{force:true})}};
const read=async(f:string)=>JSON.parse(await fs.readFile(f,'utf8'));
const diskFree=async()=>Number((await exec('df',['-k','.'])).stdout.trim().split('\n').at(-1)!.trim().split(/\s+/)[3])*1024;
const root='.cache/city-appearance', district='da-costa-jordaan-v1', profile='material-4000';
async function completed(){const dir=path.join(root,'districts',district,'rectification');let names:string[];try{names=await fs.readdir(dir)}catch(e:any){if(e.code==='ENOENT')return [];throw e}const files=names.filter(f=>f.endsWith('-material-4000-batch-100.json')).sort();const out:any[]=[];for(const f of files){const report=await read(path.join(dir,f));for(const b of report.batches??[])if(Number.isInteger(b.rectifiedFrontages)&&b.rectifiedFrontages>0){const manifest=path.join(root,'areas',b.areaId,'panorama-audit',b.selectionHash,'evidence/manifest.json');try{const bytes=await fs.readFile(manifest);out.push({areaId:b.areaId,batchIndex:b.batchIndex,selectionHash:b.selectionHash,manifest,manifestSha256:hash(bytes)})}catch{}}}return out.sort((a,b)=>a.areaId.localeCompare(b.areaId)||a.batchIndex-b.batchIndex)}
async function strips(job:any,dir:string){const manifest=await read(job.manifest), images=path.join(path.dirname(job.manifest),'images');await fs.mkdir(dir,{recursive:true});const rows=[];for(const r of manifest.records){const im=r.images?.full,src=path.join(images,im.file),dst=path.join(dir,`${im.sha256}.jpg`),bytes=await fs.readFile(src);if(hash(bytes)!==im.sha256)throw Error(`source hash mismatch ${src}`);try{await fs.link(src,dst)}catch(e:any){if(e.code!=='EEXIST')throw e}rows.push({file:path.basename(dst),pandId:r.buildingId,address:r.address??null,obliquityDeg:im.obliquity??null,standoffM:im.standoff??null,sourceSha256:im.sha256,sourcePixelsPerMetre:45,renderedPixelsPerMetre:45})}await atomic(path.join(dir,'manifest.json'),{version:1,metadata:{sourceManifest:job.manifest,sourceManifestSha256:job.manifestSha256,localOnly:true},strips:rows});return hash(await fs.readFile(path.join(dir,'manifest.json')))}
async function child(cmd:string,args:string[]){await exec(cmd,args,{cwd:process.cwd(),maxBuffer:8*1024*1024})}
async function execute(job:any,state:any){const key=hash(JSON.stringify({selectionHash:job.selectionHash,manifestSha256:job.manifestSha256,profile,worker:'district-material-review/1'}));const prior=state.jobs[key];if(prior?.status==='complete'&&prior.manifestSha256===job.manifestSha256)return;const base=path.join(root,'district-material-review',job.selectionHash), stripDir=path.join(base,'strips'), seg=path.join(base,'segmentation'), colours=path.join(base,'wall-colours.json');const row=state.jobs[key]={key,areaId:job.areaId,batchIndex:job.batchIndex,selectionHash:job.selectionHash,manifest:job.manifest,manifestSha256:job.manifestSha256,status:'running',startedAt:new Date().toISOString(),attempts:(prior?.attempts??0)+1,outputs:{}};await atomic(state.file,state);try{const stripHash=await strips(job,stripDir);row.outputs.strips={directory:stripDir,manifestSha256:stripHash};const benchmark=await runBenchmark([`--manifest=${job.manifest}`,'--limit=250','--prompt-profile=conservative','--think=false','--image-size=768',`--out=${path.join(root,'local-material-benchmark','district-conservative-768')}`]);row.outputs.benchmark={directory:benchmark.out,experimentHash:benchmark.experimentHash};await child('.cache/roofline-eval/venv/bin/python',['scripts/roofline-eval/segment.py','--method=s1',`--strips=${stripDir}`,`--out=${seg}`,'--long-side=768']);row.outputs.segmentation={directory:seg,provenance:path.join(seg,'s1.provenance.json')};await child(process.execPath,['--import','tsx','scripts/city-appearance/measure-local-wall-colours.ts',`--manifest=${job.manifest}`,`--masks=${path.join(seg,'masks/s1')}`,`--out=${colours}`]);row.outputs.wallColours=colours;row.status='complete';row.completedAt=new Date().toISOString();row.gate='proposals-only: material classifier confidence and colour-pixel reliability are not visual acceptance or publication';await atomic(state.file,state)}catch(e:any){row.status='error';row.error=String(e.message??e);row.completedAt=new Date().toISOString();await atomic(state.file,state);throw e}}
async function main(){const run=process.argv.includes('--run'),watch=process.argv.includes('--watch'),max=integer('max-batches',44,1,10000),hours=integer('max-hours',8,1,72),file=path.join(root,'district-material-review','progress.json');let state:any;try{state=await read(file)}catch{state={version:1,policy:'Local-only proposal artifacts. No game appearance publication or visual acceptance.',jobs:{}}}state.file=file;if(!run){console.log(JSON.stringify({mode:'plan',jobs:(await completed()).length,maxBatches:max,runRequired:true},null,2));return}const deadline=Date.now()+hours*3600e3;let done=0;do{for(const job of await completed()){if(done>=max||Date.now()>deadline)break;if(await diskFree()<4*1024**3)throw Error('disk below 4GiB');try{await execute(job,state);done++}catch(e:any){const k=Object.keys(state.jobs).find(k=>state.jobs[k].selectionHash===job.selectionHash);if((state.jobs[k!]?.attempts??0)>=3)continue;throw e}}if(!watch||done>=max||Date.now()>deadline)break;await new Promise(r=>setTimeout(r,60000))}while(true);delete state.file;await atomic(file,state);console.log(JSON.stringify({mode:'run',processed:done,progress:file},null,2))}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href)main().catch(e=>{console.error(e.stack??e);process.exitCode=1});
